### PR TITLE
In the TRANSFAC parser, don't issue warnings if strict is False

### PR DESCRIPTION
**Pull request by mdehoon**
The parser in Bio.motifs.transfac issues warnings if it detects discrepancies between the file contents and the TRANSFAC format. In practice, discrepancies occur frequently but are rarely harmful. Printing these warnings may prevent more serious warnings from being noticed. The PR introduces an argument "strict" which, if False, prevents the parser from printing these warnings. By default, "strict" is True.

Up for discussion is whether the parser should raise an Exception instead of issuing a warning, if strict is True. This would be more in line with other parsers in Biopython, specifically the parser in Bio.Entrez.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
If both the space issue and key length violation are common, then I understand making this silent by default. There is also the precedent of the PDB parser with a strict mode (it can do warnings and exceptions, I'd have to remind myself exactly how that works with its strict mode).

**Comment by mdehoon** [comment]
By default, the warnings would still be issued.

**Comment by peterjc** [comment]
My preference would be document how to use ``warnings`` to ignore ``BiopythonParserWarning``, perhaps with a context manager, but would bow to practicality of adding a flag if these warnings are very common.

The precedent with Bio.PDB is complicated with both ``PERMISSIVE=False`` but allowing you to silence errors, ``QUIET=False``but  allowing you to silence warnings. Note to follow PEP8 these ought to be lower case.

Using ``strict=...``` also makes sense, and we have precedent in ``Bio/SeqUtils/MeltingTemp.py``.

The Entrez case is different again, ``validate=True``, but makes sense in that context.

I have no strong view here, other than PEP8 lower case argument names.

@Bow was there anything similar in SearchIO which could guide the naming here?

**Comment by mdehoon** [comment]
Lots of files encountered in the wild deviate in some way from the TRANSFAC format, so yes these warnings are common. I am open to other suggestions instead of `strict`. The Entrez case is indeed different; `validate` doesn't seem right in this case.

**Pull request merged**
