### PR TITLE
SAM format parser for Bio.Align

### PR DESCRIPTION
**Pull request by mdehoon**
This PR adds a parser for alignment files in the SAM format to `Bio.Align`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
I want to review this - having written my own parser some years back
including BAM support. The format was (is?) a moving target though.

**Comment by mdehoon** [comment]
@peterjc  Thanks! It would be good if you could review this.

**Comment by mdehoon** [comment]
@peterjc  Any objections?

**Comment by peterjc** [comment]
Sadly I've not been able to look at this - but expect we can combine it with ``Bio/bgzf.py`` and my (pure Python) SAM/BAM code to extend this to BAM as well.

**Comment by mdehoon** [comment]
@peterjc  Thanks. Yes I think it can be combined with `Bio/bgzf.py` in the future.

**Pull request merged**
