### PR TITLE
Apply black to Tests/run_tests.py

### PR DESCRIPTION
**Pull request by martonlanga**
This pull request addresses issue #2552

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by martonlanga** [comment]
Sorry for the incorrect title @peterjc. Also, I ran the tests and there were many import errors for me. Is that normal?

**Comment by peterjc** [comment]
Import errors for optional dependencies like ReportLab should be caught and a short message shown when the relevant tests are skipped. It sounds like something else is happening?

**Comment by martonlanga** [comment]
Oh, I was running `run_tests.py` directly. Using `python setup.py test` worked correctly 👍🏻

**Comment by peterjc** [comment]
Either should work - ``python setup.py test`` from the top level directory, or ``python run_tests.py`` from the ``Tests/`` folder.

Anyway, the continuous integration testing also passed. Thank you!

**Comment by peterjc** [comment]
TravisCI has finished, although GitHub still shows it as pending. Strange. Merging anyway...

**Pull request merged**
