### PR TITLE
This patch will fix the optimizer issue of scipy 1.5.0 when using ML method for dn/ds calculation

### PR DESCRIPTION
**Pull request by zruan**
This pull request addresses issue #...

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks! Can you explicitly agree to the BSD dual licensing?

Is anyone else available to review this on the technical side?

**Comment by zruan** [comment]
I checked all three boxes.

The issue arises due to the third parameter is fixed to 1 during minimization. The 1.5.0 scipy.optimize.minimize seems to be very strict and doesn't allow this to happen. The fix is to define another temporary function without the third parameter. Everything else remains unchanged. I think this is okay.

**Comment by peterjc** [comment]
Cross reference #2993

**Comment by peterjc** [comment]
Applying now since the new SciPy appears to be available on Windows now, and AppVeyor stopped working too. Thank you.

**Pull request merged**
