### PR TITLE
SearchIO HHsuite

### PR DESCRIPTION
**Pull request by bow**
This pull request is the clean, rebased continuation of #1965.

- [ ] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ ] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by bow** [comment]
@linucks This is the rebased changeset continuing from #1965. Please let me know whether you'd like to have your name added also to `CONTRIB.rst`. After the tests pass, I'll update `NEWS.rst` and then accept the changes to `master` :).

**Comment by linucks** [comment]
Hi @bow That's great - thanks for doing that. Sorry for the git issues - it always manages to trip me up one way or another! Please do add my name to CONTRIB.rst. It's great to have been able to contribute code to biopython. Do you have a rough idea of when these changes will make it into a release?

**Comment by bow** [comment]
No worries @linucks. I updated `NEWS.rst` with your contribution :) (didn't realize your name was already in `CONTRIB.rst`, so I left it unchanged).

With regards to release time, I don't know for sure. But for the past few years, we have had releases around spring/summer (around the time of [ISMB](https://www.iscb.org/ismbeccb2019)) and the last release was about 5 months ago. So I would guess it may happen within the next few weeks. Perhaps @peterjc already has a date / week in mind :)?

Anyway, I will merge this branch as soon as the tests pass. Thanks again @linucks :fireworks:!

**Comment by bow** [comment]
Hmm..looks like AppVeyor is failing for some reason unrelated to the code. Is there any way the build can be restarted @peterjc?

**Comment by peterjc** [comment]
Looks like it timed out? Currently the AppVeyor account is setup via our biopython-dev-owner's mailing list address (which we need to think about changing as at some point the OBF is moving mailman hosting any biopython-dev will no longer exist other than as a static archive).

**Comment by bow** [comment]
Hmm..indeed, it looks like something on their side. I was trying to find a way to restart it, but it seems ok now.

Anyway, I am merging this now ~ it's been a long time due :).

**Pull request merged**
