### PR TITLE
Small fix to gc skew

### PR DESCRIPTION
**Pull request by Cashalow**
In reference to issue #1107 I have add a check whether G and C are in same quantity and return 0 if so. And a unittest on a window with no G or C.

### CODE REVIEW

**Comment by peterjc** [comment]
When ``g == c``, the existing code didn't have any problem - it would already return ``0`.

I was expecting you to check if ``g + c == 0`` to avoid a division by zero error?

**Comment by peterjc** [comment]
One of the things we check with TravisCI is Python style, and that is failing:

```
$ flake8 Bio/
Bio/SeqUtils/__init__.py:97:1: W293 blank line contains whitespace
Bio/SeqUtils/__init__.py:99:1: W293 blank line contains whitespace
```

You can install flake8 using ``pip install flake8``.

**Comment by peterjc** [comment]
You'll need to import ``GC_skew`` at the top of ``test_SeqUtils.py`` in order to fix this error:

``
======================================================================
ERROR: test_GC_skew (test_SeqUtils.SeqUtilsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_SeqUtils.py", line 145, in test_GC_skew
    self.assertEqual(GC_skew(seq)[0], 0)
NameError: global name 'GC_skew' is not defined
----------------------------------------------------------------------
```

**Comment by Cashalow** [comment]
Yes indeed sorry I got confused in my branches and I forgot the include in the one I sent.

I'll check the Python styles ASAP.

Regarding my fix, indeed it worked when g == c but I was just thinking that this would save one operation for the cases where G and Cs are present and equal. I could check g + c == 0 instead but I think the count function never returns negative values so my fix should be safe.

**Comment by peterjc** [comment]
Yes, the counts should never be negative.

How about something like this?:

```
    try:
        skew = (g - c) / float(g + c)
    except ZeroDivisionError:
        skew = 0.0
```

**Comment by Cashalow** [comment]
Okay then :) It was also the way this was done for the GC function in the same file, I should have checked it before, sorry.

**Comment by peterjc** [comment]
(The coverage report is a bit odd, but I was tinkering with coverage settings this afternoon)

Other than the docstring this looks good:

```
If the numbers of G and C are equal, returns 0. Fixes the issue when the window is devoid of G/Cs.
```

Something like this?:

```
If a window contains no G or C bases, a skew of zero is used.
```

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by Cashalow** [comment]
Yes I agree to all of this :)

**Comment by peterjc** [comment]
I emailed your GMail account a few days ago: Would you prefer to be acknowledged under your real name, or just as Cashalow?

**Comment by peterjc** [comment]
Thank you - merged as the first pull request for what will be Biopython 1.70.

**Comment by peterjc** [comment]
@sachalau Hi again Sacha. Are you happy to dual licence your contributions under both the Biopython License Agreement AND the BSD 3-Clause License? See #898. Thank you.

**Comment by sachalau** [comment]
yes

Le jeu. 20 sept. 2018 à 16:32, Peter Cock <notifications@github.com> a
écrit :

**Comment by peterjc** [comment]
Thank you - We still need one more author's agreement before we can dual license ``Bio/SeqUtils/__init__.py`` but this is progress.

**Pull request merged**
