### PR TITLE
Dual license Bio/Blast/NCBIXML.py

### PR DESCRIPTION
**Pull request by peterjc**
Original author Bertrand Frottier, named copyright holders, and all
contributors since as tracked with version control have agreed:

 - Bertrand Frottier
   https://mailman.open-bio.org/pipermail/biopython/2019-August/016662.html
 - Brad Chapman (@chapmanb)
   http://mailman.open-bio.org/pipermail/biopython-dev/2013-July/019903.html
 - Carlos Pena (@carlosp420)
   https://github.com/biopython/biopython/issues/898#issuecomment-236925650
 - Christian Brueffer (@cbrueffer)
   https://github.com/biopython/biopython/issues/898#issuecomment-236922857
 - Francesco Gastaldello (@gasta88)
   https://github.com/biopython/biopython/pull/1063
 - Iddo Friedberg (@idoerg)
   https://github.com/biopython/biopython/issues/898#issuecomment-380437378
 - Konstantin Vdovkin (@rtf-const)
   https://github.com/biopython/biopython/pull/1767
 - Lenna Peterson (@lennax)
   https://github.com/biopython/biopython/issues/898#issuecomment-237023021
 - Michiel de Hoon (@mdehoon)
   https://github.com/biopython/biopython/issues/898#issuecomment-237122630
 - @morrme
   https://github.com/biopython/biopython/pull/1172#issuecomment-295430028
 - Nick Negretti (@nimne)
   https://github.com/biopython/biopython/pull/1768#issue-210631196
 - Nick Semenkovich (@semenko)
   https://github.com/biopython/biopython/issues/898#issuecomment-236932677
 - Peter Cock (@peterjc)
   https://github.com/biopython/biopython/issues/898#issue-167420613
 - Sergei Lebedev (@superbobry)
   https://github.com/biopython/biopython/issues/898#issuecomment-237282456
 - Sergio Valqui (@svalqui)
   https://github.com/biopython/biopython/pull/1749
 - Terry Jones (@terrycojones)
   https://github.com/biopython/biopython/issues/898#issuecomment-241048919
 - Travis Wrightsman (@twrightsman)
   https://github.com/biopython/biopython/issues/898#issuecomment-237625470

This pull request addresses issue #1878

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@cbrueffer would you be able to review this, just in case I overlooked a named contributor, e.g. in a commit comment?

**Comment by terrycojones** [comment]
Diff looks good. Thanks!

**Comment by peterjc** [comment]
Does anyone else have time to review the git log here? I've been looking at:

```
$ git log --follow -- Bio/Blast/NCBIXML.py
```

One to query, b8502025878688e95140c6ea20311d33e793ff99, Christof Winter from TU Dresden in 2005, committed via @mdehoon:

> Bug fix by Christof Winter from TU Dresden. Previously, the parser did not return the bit score (hsp.bits).

I'll have the email address he was using as of 2008...

**Comment by mdehoon** [comment]
I guess this is him:
https://www.linkedin.com/in/christof-winter-8202197b/
Best,-Michiel

    On Tuesday, August 27, 2019, 6:01:05 PM GMT+9, Peter Cock <notifications@github.com> wrote:  
 
 
Does anyone else have time to review the git log here? I've been looking at:
$ git log --follow -- Bio/Blast/NCBIXML.py

One to query, b850202, Christof Winter from TU Dresden in 2005, committed via @mdehoon:


Bug fix by Christof Winter from TU Dresden. Previously, the parser did not return the bit score (hsp.bits).


I'll have the email address he was using as of 2008...

**Comment by cbrueffer** [comment]
He's a former collegue of mine, I can provide a private email address off-PR.

**Comment by cbrueffer** [comment]
Actually I'll just prod him, he has a Github account and should be able to just reply to the main PR.

**Comment by peterjc** [comment]
Thank you @winterschlaefer - https://github.com/biopython/biopython/issues/898#issuecomment-525365340 - I'll just update the commit message now.

**Pull request merged**
