### PR TITLE
Added (PRIVATE) to summary line of private docstrings #1466

### PR DESCRIPTION
**Pull request by Amrithasuresh**
@peterjc Please have a look at the changes. Let me know if there are mistake. #1466 

Thank you.

### CODE REVIEW

**Comment by peterjc** [comment]
Thank you. The changes looks fine to me, but we will need your explicit agreement to dual license your contribution under both the Biopython licence or at the user's choice the 3-clause BSD clause license (see #898). This is part of the default pull request message, which you did not use.

I'd also like @etal as ``Bio.Phylo`` owner to OK this.

**Comment by Amrithasuresh** [comment]
@peterjc oh sorry I missed it. Please let me know if I need to send an email or to comment in the issue #898.

Thank you.

**Comment by peterjc** [comment]
Thanks for confirming the licensing is fine. The GenBank changes look good, I'd have applied them now if there were on a separate pull request. I'll give @etal a few more days to comment, and then go ahead as merge this.

**Comment by Amrithasuresh** [comment]
@peterjc from next time onwards I will create new branch and then I will proceed the changes. Thank you!

**Pull request merged**
