### PR TITLE
Fix keys in Bio.SeqUtils.MeltingTemp.DNA_TMM1

### LINKED ISSUE #2280: key err in DNA_TMM1 of Bio.SeqUtils for two NN pairs
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-18.6.0-x86_64-i386-64bit
1.74
```

### Expected behavior

All terminal mismatch pairs in the terminal mismatch table `DNA_TMM1` are included in nearest neighbor tm calculation

### Actual behaviour

I saw two keys with spaces in the terminal mismatch table `DNA_TMM1`: ` GG/CA` and ` CC/GC`. I don't see a trim or anything in `Bio.SeqUtils.Tm_NN` at this step, so I believe these two pairs are being missed during tm calculation and the tm's are a tad low.

`' GG/CA'`
`' CC/GC'`

and the code to calculate the tm with neighbors:

```python
    # Now for terminal mismatches
    left_tmm = tmp_cseq[:2][::-1] + '/' + tmp_seq[:2][::-1]
    if left_tmm in tmm_table:
        delta_h += tmm_table[left_tmm][d_h]
        delta_s += tmm_table[left_tmm][d_s]
        tmp_seq = tmp_seq[1:]
        tmp_cseq = tmp_cseq[1:]
    right_tmm = tmp_seq[-2:] + '/' + tmp_cseq[-2:]
    if right_tmm in tmm_table:
        delta_h += tmm_table[right_tmm][d_h]
        delta_s += tmm_table[right_tmm][d_s]
        tmp_seq = tmp_seq[:-1]
        tmp_cseq = tmp_cseq[:-1]
```

I can do a PR for this -- it's just a two character change. Please let me know.

### Steps to reproduce

```
from Bio.SeqUtils.MeltingTemp import Tm_NN
Tm_NN("AAAAAAGG", c_seq="TTTTTTCA")
```

### PR DESCRIPTION
**Pull request by JJTimmons**
- two keys in Bio.SeqUtils.MeltingTemp.py had spaces that
prevented their lookup during nearest neighbor tm calculation:
"CC/GC" and "GG/CA" (closes #2280)
- added a ".mypy_cache" ignore to .gitignore
which is autogenerated for devs running mypy (related to #2236)
- fixed a small mispelling of directory in .gitignore

This pull request addresses issue #2280 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by JJTimmons** [comment]
I don't have any strong opinions on the last two bullets re: mypy. Can remove if BioPython maintainers prefer PRs to be more issue-scoped

**Comment by MarkusPiotrowski** [comment]
@peterjc are you OK with the changes in `.gitignore`?

**Comment by peterjc** [comment]
If you would like to, please do add yourself to ``CONTRIB.rst`` and ``NEWS.rst`` for the next release. Thanks!

**Comment by JJTimmons** [comment]
Thank you, @MarkusPiotrowski and @peterjc. Re: CONTRIB I feel this catch was too small for that but I _do_ hope to make more substantial contributions in the future. I'll keep an eye on issues page and/or possible additions. Am enjoying using biopython

**Comment by MarkusPiotrowski** [comment]
OK, I'm merging this now. Thank you, @JJTimmons

**Pull request merged**
