### PR TITLE
Update xbbtools

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
Addresses issue #848.
`xbbtools` should now run under Python 2 and Python 3 and without additional dependencies. Although I added some functionality, the main purpose was to make this script running; it has still very limited capabilities.

Solved bugs:

 - Problem with unicode error when running under Python 2
 - Help didn't open

Improvements:

 - Removed dependency from `pmw` library
 - Switched to tkinter's ttk widgets
 - Added single frame translation for all six frames and three frame translation for both directions
 - Added some message windows to make the blast option more self-explaining, added a paragraph to the Help window
 - Used Biopython's `NcbiblastxxxCommandline` instead of `os.sytem()`

Others:

 - Removed some leftover methods
 - Some work on coding style, e.g., removed star imports, made `try...except` clauses more explicit etc.

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good - can you add something to NEWS file about this too (next the paragraph about SeqGui)?

**Comment by MarkusPiotrowski** [comment]
Updated NEWS file.

**Comment by MarkusPiotrowski** [comment]
...and rebased with upstream master.

**Comment by peterjc** [comment]
Cherry-picked as https://github.com/biopython/biopython/commit/ed93c0090e89a32102ed40a5cefd3cd64b1ff705 thank you :)

**Pull request closed without merging**
