### PR TITLE
Add pre-commit config

### PR DESCRIPTION
**Pull request by MartinThoma**
I have seen that you have agreed in #2008 to use the black formatter - nice!

One tool that helped me in another team to keep code quality high is [pre-commit](https://pre-commit.com/). It is a tool every developer can install locally (but doesn't have to). Before a commit is done, it runs the pre-commit hooks defined in `.pre-commit-config.yaml`.

There are some hooks which I would recommend, but might need to be discussed first:

* [isort](https://github.com/timothycrosley/isort): #2828
* check-yaml: #2825 needs to be fixed first
* [pyupgrade](https://github.com/asottile/pyupgrade): I guess I'll run it and make a PR after this one so that you can see the effect -- see #2510
* mypy: Only useful if you add type annotations ... and I think that is mainly useful for Python 3.6+. I'm not sure if this project still wants to support prior versions.

This PR should only be merged after #2552 is done and #2826 is merged.

## How to use pre-commit

```
# Install it locally
$ pip install pre-commit

# Tell pre-commit to run pre-commit hooks for the current repository
# This only needs to be done once
$ pre-commit install

# Tell pre-commit to run all hooks on all files
pre-commit run --all-files
```

## Checkboxes

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by MarkusPiotrowski** [comment]
You have also seen #2580?

**Comment by MartinThoma** [comment]
@MarkusPiotrowski No, I haven't. But it seems as if this is desired :-)

**Comment by peterjc** [comment]
Can you include flake8 here too?

That would let us do the black tests via ``flake8-black`` (as done now on TravisCI) with rules to ignore the lack of black on the tests for now (#2552).

**Comment by peterjc** [comment]
I see we missed applying black to some Python scripts without the ``.py`` extension - can you submit that as a separate pull request which we can merge almost immediately?

(I wonder if our flake8 setup needs to explicitly include those files... or if we should rename them?)

**Comment by MartinThoma** [comment]
@peterjc I've added Flake8, excluded Tests from the black and flake8 checks. I removed the changes from this PR

**Comment by peterjc** [comment]
What do you think @MarkusPiotrowski, @JoaoRodrigues ?

It will need followup work to update the CONTRIBUTING file.

**Comment by peterjc** [comment]
It would also open the way to follow up work replacing the TravisCI/Tox style checks as outlined on #2580 - that should be at least as strict.

**Comment by MarkusPiotrowski** [comment]
I have to admit that I don't understand enough of  `pre-commit` to make a useful contribution here.

I think it would still be nice to have the possibility for a local set-up so that I can prepare my PRs that they hopefully do not fail during submission.

**Comment by peterjc** [comment]
That is exactly the goal - rather than running _just_ flake8 as a git pre-commit hook (our current recommendation which can only check Python files), pre-commit is a framework for running multiple checks (which would include flake8 and other Python checks, but also can do other things like YAML validation).

My goal as outlined on #2580 is to have most of the testing currently only done on TravisCI done locally via the git hook.

i.e. Increase the chance that a PR prepared locally will pass once submitted to GitHub.

**Comment by MarkusPiotrowski** [comment]
OK, my misunderstanding was that `pre-commit` is only for the GitHub side. Sorry, I'll give it a try.

**Comment by JoaoRodrigues** [comment]
Completely 👍 , pre-commit is very nice (and easy to install too). Thanks!

**Comment by JoaoRodrigues** [comment]
Is there something holding this back?

**Comment by peterjc** [comment]
I've not made time to try this myself yet, no objection in principle. Especially since flake8 have deprecated their built in hook.

As long as one core developer has tested it themselves we should probably merge it, and update the CONTRIBUTING.rst file and potentially tutorial accordingly.

**Comment by JoaoRodrigues** [comment]
I'll do it then. Happy to take the plunge and report back.

**Comment by JoaoRodrigues** [comment]
The installation works fine, but it does take a little bit of time to run the first time. Couple of things we need to figure out:

1. Which hooks do we want in the end? Right now this PR enables black, flake8, blacken-docs, and a few JSON, line ending stuff, but there's support for isort (import sorting), mypy, and some others. Personally, I'm in favor of keeping these import sorting stuff out of the equation, same with typing.

2. This might be my inexperience with these style checkers, but why do we need flake8-black and black? 

3. There are a lot of commented-out settings in the `.flake8` config, maybe we could take the opportunity to clean that?

4. On the same note, if I run flake8/black locally it doesn't seem to pick up on the same things that travisCI is picking up on. Where could the difference in set up come from?

**Comment by peterjc** [comment]
1. There is some interest in enforcing sort order and adding type checking, but for now I agree it is simpler to take those commented lines out.

2. We need just one. As a check which would abort if black style is not followed, the hook could run ``black --check`` OR run ``flake8`` using my ``flake8-black`` plugin. What it appears to do is actually run black and edit your code as needed?

3. I'm not sure what you mean, unless it is removing the comments describing the things we are (temporarily or otherwise) ignoring?

4. Black does have a configuration file, but it is rarely used (and Biopython does not attempt to change it). The most likely cause is the flake8 configuration, perhaps interacting with a flake8 bug with how relative paths are handled. See also the work around with duplicated ``per-file-ignores`` settings in our ``.flake8`` file. As long as running the new pre-commit check (regardless of which directory you are in) matches TravisCI, I'm happy.

**Comment by JoaoRodrigues** [comment]
1. 👍 

2. Yeah, I've been using `black --diff` (black check doesn't output errors, just a Pass/Fail note).

3. I mean that there are a lot of good comments we should keep (describing what we ignore and whatnot) but also the lower half of the file seems to be just commented out. We could clean it...

4. OK. I'll check against TravisCI.

**Comment by peterjc** [comment]
Regarding (3), I see what you mean now - does #3017 resolve that?

**Comment by JoaoRodrigues** [comment]
Oh OK, that was dumb of me. Those are explanations of the codes......... 🤦

**Comment by peterjc** [comment]
Not at all, the old layout was a bit misleading - but we've clarified that now in #3017, so thanks for raising it.

**Comment by JoaoRodrigues** [comment]
Thanks! I'll clean a bit the pre-commit config file to keep it as lean as possible and see if I can get the right set of options to reproduce what we have at the moment.

**Comment by MartinThoma** [comment]
Hi folks, I'm currently not quite sure what to do / if I can support. If you want me to adjust something in this PR, just let me know :-)

**Comment by JoaoRodrigues** [comment]
Hi @MartinThoma , first of all, thanks a ton for this PR. I'll be testing/tweaking things in the next few days and try to get it as stable as possible to merge. Would you prefer I write here my changes and you handle the commits yourself or can I push directly to this PR?

**Comment by MartinThoma** [comment]
@JoaoRodrigues You can push directly to this PR, of course :-) I'm happy that I could help a bit and also that you take it over :-)

**Comment by JoaoRodrigues** [comment]
@MartinThoma - I made minimal tweaks to your config file to match the flake8/black dependencies used in our Travis CI pipeline. I also added an argument to `black` (`--check`) so that the pre-commit hook does not modify files in-place.  Finally, I removed the exclusions to the `Tests` folders, so the checks are enforced there as well if those files are being committed and tweaked a bit the extensions for the executables/trailing whitespace/mixed line ending hooks.

I did not add `flake8-black` since we can call black directly, is this OK @peterjc ?

As for testing: I seem to get the same results locally as an open PR (#3210) on Travis. Anyone has better tests?

**Comment by peterjc** [comment]
Note that for pre-commit, running black directly is better. It will be faster than using flake8-black because black has a cache which speeds up subsequent runs (flake8 and the plugin currently do not - see https://github.com/peterjc/flake8-black/issues/26 for more).

Also I dropped ``flake8-black`` on TravisCI - calling black allowed me to split up the checks into parallel tasks which sped up TravisCI. See #3184.

**Comment by MartinThoma** [comment]
@peterjc Should I add the update of CONTRIBUTING.rst in this PR?

**Comment by peterjc** [comment]
It would probably be easier as a new pull request, so I merged this now. You could also be welcome to add your name to the NEWS and CONRIB files too, if you want.

Thank you both!

**Comment by JoaoRodrigues** [comment]
Thank you for the initiative @MartinThoma !! This is great!

**Comment by peterjc** [comment]
In hindsight I should have tested this locally too. I've removed three flake8 plugins we're not (yet) enforcing in #3214, and removed the overly aggressive trailing-whitespace which broke multiple doctests which have meaningful trailing whitespace.

**Pull request merged**
