### PR TITLE
Update IUPAC alphabet for Selenocysteine. 'U' now translates to 'Sec'

### PR DESCRIPTION
**Pull request by jose-mr**
This is according with the comments (line 26) and the provided link: biopython/blob/c60067476b4fe84b43df985cf81140d32f70e319/Bio/Data/IUPACData.py

This pull request addresses issue #...

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

I am happy be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files,
and have added myself to those files as part of this pull request. (*This
acknowledgement is optional. Note we list the names sorted alphabetically.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Tracing the history of that bit of code, it was moved from ``Bio/SeqUtils/__init__.py`` by @bow in 2013:

https://github.com/biopython/biopython/commit/850079440db7394ce71ae09b5ff61ad6c14b26b9

But it was originally added way back in 2002,

https://github.com/biopython/biopython/commit/4a7775ffea1d56f9e9cdf36494ad65f6723c4a99

I'm checking because the old function docstring claimed ``Sel`` was what IUPAC recommended. That appears to have been false.

I even found a publication declaring *"We now recommend both a three-letter and a one-letter symbol to be added to earlier recommended symbols (...), namely Sec and U."*

IUPAC-IUBMB Joint Commission on Biochemical Nomenclature (JCBN) and Nomenclature Committee of IUBMB (NC-IUBMB) (1999). "Newsletter 1999" (reprint, with permission). European Journal of Biochemistry. 264 (2): 607–609. https://doi.org/10.1046%2Fj.1432-1327.1999.news99.x

So, this looks like a minor error in Biopython for the last 15 years! Well spotted, and thank you!

Assuming none of the tests need updating, I'll merge this - but I will tweak the commit comment to include this reference and a little more context.

**Comment by peterjc** [comment]
I checked and BioPerl seems fine, they added this in 2006
https://github.com/bioperl/bioperl-live/commit/3863e80c9f5a9b3ba0f4050b99221f77bbae91a8

**Comment by MarkusPiotrowski** [comment]
@peterjc The correct reference is already in the file! (Line 27)

**Comment by peterjc** [comment]
http://www.chem.qmul.ac.uk/iubmb/newsletter/1999/item3.html vs https://doi.org/10.1046%2Fj.1432-1327.1999.news99.x

Yes, they are both the newsletter, but the latter is journal reprint which is properly archived with a DOI. That's the link I'd trust to last longer.

**Comment by jose-mr** [comment]
Thank you for accepting the change.
Not many people worried about Selenocysteine in the last 15 years, I guess :)

PDB also uses Sec for selecysteine. I noticed the error because I was mapping some PDB residues to Uniprot and using the Biopython dict to do the translation.

**Comment by peterjc** [comment]
Suggested commit message:

```
Squashed commit of pull request #1527, addressing long standing minor
error in Biopython's mapping table which was originally added in 2002.

Quoting the IUPAC-IUBMB committee's 1999 newsletter,

"We now recommend both a three-letter and a one-letter symbol to be added
to earlier recommended symbols (...), namely Sec and U."

See:

http://www.chem.qmul.ac.uk/iubmb/newsletter/1999/item3.html

or,

IUPAC-IUBMB Joint Commission on Biochemical Nomenclature (JCBN) and
Nomenclature Committee of IUBMB (NC-IUBMB) (1999). "Newsletter 1999"
(reprint, with permission).
European Journal of Biochemistry. 264 (2): 607–609.
https://doi.org/10.1046%2Fj.1432-1327.1999.news99.x
```

@jose-mr did you want to be acknowledged? If so, could you update the ``NEWS.rst`` and ``CONTRIB.rst`` files as part of this pull request.

**Comment by jose-mr** [comment]
Thank you, there is no need for that. I will do it if I make a more sizeable contribution in the future.

**Comment by peterjc** [comment]
Thank you - and we'll look forward to further contributions in future.

**Pull request merged**
