### PR TITLE
Simplified math in SeqUtils.IsoelectricPoint

### PR DESCRIPTION
**Pull request by TianyiShi2001**
Simplified math. No need to stick to the 'CR' described by [David L. Tabb](http://fields.scripps.edu/DTASelect/20010710-pI-Algorithm.pdf). 

This improves speed by ~5% without compromising readability. 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Could you clarify why you want to change the equation?

I note the old code seems to match the final equation on page 4 of the linked PDF.

**Comment by MarkusPiotrowski** [comment]
@TianyiShi2001 Can you show with a few examples that the change in the equation does not change the final result? I don't have the time to test this. Or, if it changes the final result, why do you think this is more accurat?

**Comment by TianyiShi2001** [comment]
This change will not alter the result. In addition, it improves speed by 40% on average (ranging from 30%-50%). I will prove these later.

**Comment by MarkusPiotrowski** [comment]
@TianyiShi2001 Sorry, test and doctest passed, meaning the calculation is fine. I missed the point that pK and pH are now reversed in the exponent, so the fraction stays the same.

**Comment by peterjc** [comment]
That's subtle - I missed it too.

**Comment by TianyiShi2001** [comment]
```python
import random
import time
from statistics import mean
from Bio.SeqUtils.ProtParam import ProteinAnalysis
from Bio.SeqUtils.IsoelectricPoint import IsoelectricPoint


class IsoelectricPoint1(IsoelectricPoint):

    def _chargeR(self, pH): # altered method
        positive_charge = 0.0
        for aa, pK in self.pos_pKs.items():
            partial_charge = 1.0 / (10 ** (pH - pK) + 1.0)     # simplified math
            positive_charge += self.charged_aas_content[aa] * partial_charge

        negative_charge = 0.0
        for aa, pK in self.neg_pKs.items():
            partial_charge = 1.0 / (10 ** (pK - pH) + 1.0)     # simplified math
            negative_charge += self.charged_aas_content[aa] * partial_charge

        return positive_charge - negative_charge


if __name__ == "__main__":

    # making a protein sequence as the argument for IsoelectricPoint
    ProteinAnalysisObj = ProteinAnalysis('ACDEFGHIK' * 100)
    sequence, content = ProteinAnalysisObj.sequence, ProteinAnalysisObj.count_amino_acids()

    # speed comparison

    original = []
    improved = []

    for i in range(10):

        t0 = time.time()
        IsoelectricPoint(sequence, content).pi()
        t1 = time.time()
        original.append(t1-t0)

        t0 = time.time()
        IsoelectricPoint1(sequence, content).pi()
        t1 = time.time()
        improved.append(t1-t0)

    print(f'''\
original:
    result:    
    time:      {mean(original)}
simplified math:
    result:    
    time:      {mean(improved)}
    improvement: {(mean(original)-mean(improved))/mean(original)*100}%
        ''')
```

```
original:
    result:    
    time:      5.049705505371094e-05
simplified math:
    result:    
    time:      4.651546478271484e-05
    improvement: 7.884796978281406%
```

There should be a constant improvement of speed by around 5%.

**Comment by MarkusPiotrowski** [comment]
@TianyiShi2001 Since the docstring is referencing the article of David L. Tabb, and the change in the formula is not self explanatory for a non-mathematician like me, can you explain this with a small comment once, e.g., by out-commenting the old calculation and giving a short explanation: 
```python
            # CR = 10 ** (pK - pH)
            # partial_charge = CR / (CR + 1.0)
            # Simplified math, this is the same (but faster):
            partial_charge = 1.0 / (10 ** (pH - pK) + 1.0)
```

**Comment by TianyiShi2001** [comment]
@MarkusPiotrowski Sure! I'll open another PR. Could you also have a look at issue #2646 –– I want to rewrite the `pi()` method and if that's OK I'll put them together in the next PR.

**Pull request closed without merging**
