### PR TITLE
Apply black style to test_Emboss* files, version 19.10b0.

### PR DESCRIPTION
**Pull request by svalqui**
This pull request addresses issue #2552 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

This PR applies black style to test_Emboss files, files listed below; it would be good to review it.
test_Emboss.py
test_EmbossPhylipNew.py
test_EmbossPrimer.py

### CODE REVIEW

**Comment by peterjc** [comment]
Looked good by eye, but:

```
$ flake8
./Tests/test_EmbossPrimer.py:191:52: ISC001 implicitly concatenated string literals on one line
```

**Comment by svalqui** [comment]
Yes, I missed that one, sorry, amended now.

**Comment by peterjc** [comment]
No harm done, but do you have flake8 with the plugins installed? Do you have a pre-commit hook setup? That should have caught this before making the commit to git.

**Comment by svalqui** [comment]
I got the plugins, but I just configured the hook, that should work better.

**Pull request merged**
