### PR TITLE
Pre-commit tools and black update

### PR DESCRIPTION
**Pull request by peterjc**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Some minor housekeeping with the style checking.

### CODE REVIEW

**Comment by peterjc** [comment]
Cross reference https://github.com/PyCQA/pyflakes/issues/804 for E704 false positives

**Comment by JoaoRodrigues** [comment]
Not necessarily related to this PR, but should we have a look at all the linters/rules we use and maybe standardize them? Right now in our CI workflows I see:
- Our CI runs pre-commit
- We have a separate pre-commit.ci service

In the CI workflow, we have:
- flake8
- black
- ruff
- etc.

Could we maybe consider dropping black and flake for ruff alone? Will that make a big difference in style, whereas it might simplify our CI quite a bit?

**Comment by peterjc** [comment]
I've been moving some my own stuff to ruff in favour of flake8 and black, but it doesn't cover everything we're using. Dropping pydocstyle on this PR is a step in that direction, happy to take that further 👍

**Comment by JoaoRodrigues** [comment]
👍 👍 Are there any rules you're following when dropping the linters? Like, run with ruff only, then run the old linters to see if it missed anything?

**Comment by peterjc** [comment]
You have to enable non-default ruff checks, which ought to be fine if we're already using the original it was based on (e.g. flake8-bugbear), but occasionally there are differences.

I'm hoping once ruff adds array formatting we can use it in place off black.

**Comment by peterjc** [comment]
@JoaoRodrigues was that an implicit PR approval?

**Pull request merged**
