### PR TITLE
remove alphabets from consensus sequences in Bio.Align.AlignInfo

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request removes alphabets from consensus sequences in Bio.Align.AlignInfo.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@peterjc  Sorry dude. The agreement was to remove alphabets. If you want to reintroduce them, it will have to be handled separately at a later date.

**Comment by peterjc** [comment]
@mdehoon My understanding as written in#2046 is key part blocking removal is tracking molecule type. Something has to be used there. Thus "remove/replace" in that issue title.

**Comment by mdehoon** [comment]
@peterjc  There will be corner cases when an alphabet is needed, as in the example of writing a Genbank file. There are multiple ways in which that can be addressed. Adding an alphabet to each Seq object is not the only (and definitely not the best solution). For example, you could have an optional argument to SeqIO.write to specify the alphabet when you're writing a GenBank file.

Each corner case will be different and likely needs to be solved in a different way. The purpose of alphabet removal now is to find out where alphabets were actually needed, and then find the appropriate solution for them.

**Comment by mdehoon** [comment]
Thanks

**Pull request merged**
