### PR TITLE
Easy fix: redeclaration of variables as "unsigned int"

### PR DESCRIPTION
**Pull request by OscarMaestre**
All warnings are related to comparation of int's with unsigned int's. To avoid such warnings some variables can be safely redeclared as "unsigned int".

### CODE REVIEW

**Comment by peterjc** [comment]
This looks good but the branch history is a little confused. Do you know how to create a clean new branch from the Biopython master? Or, should I handle that?

Also because your git commits are recorded as authored by ``oscar@example.com`` this means GitHub does not match this to your account. See https://help.github.com/articles/keeping-your-email-address-private/ for how to do this as ``OscarMaestre@users.noreply.github.com``

Again, I could adjust that as part of manually getting your changes from this branch.

**Comment by peterjc** [comment]
I'm happy to manually rebase this and sort out the merge conflicts - but first a formality:

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

**Comment by OscarMaestre** [comment]
Hello,

I agreed to the license change. You can find it in #898

**Comment by peterjc** [comment]
Thanks.

**Comment by peterjc** [comment]
Your name was already added from the UniProt work (#1034):

https://github.com/biopython/biopython/commit/769564699ccd4bcce96eb19dbdf397eab7e434c9

I think everything has been applied to the master, but that I forgot to update this pull request at the time:

https://github.com/biopython/biopython/commit/f1d7d8558d0efb9ca78877b097d0c2bf7a979695
https://github.com/biopython/biopython/commit/1327ece4395bb567a9d7a9451766545e3b079b16
https://github.com/biopython/biopython/commit/7a5d057ec9b22c77cb8845a3254a5ddc70899a15

Thank you!

**Pull request closed without merging**
