### PR TITLE
New restriction analysis library, v2

### PR DESCRIPTION
**Pull request by anntzer**
This supersedes #148.  I created a new branch so that the emboss db doesn't appear in the history (and also to restart from the current master).  Now, importing the library will have the side-effect of dowloading the db.  Note, though, that setup.py may need to be modified so that the db is present before biopython is written to a directory owned by root (probably just an import is enough, but untested).
I also got rid of the custom Seq class, now I just rely on the standard Seq and pass circular as a kwarg.
Finally, I removed the patch for the old restriction library as it doesn't seem to apply cleanly and I have little interest in figuring out why -- but you can still get it from #148 and give it a try.

### CODE REVIEW

**Comment by vincentdavis** [comment]
@peterjc looked through these comments and the #148. It seems the plan is to build a new restriction library and deprecate the old in the future? What are the goals for rewriting?

**Comment by peterjc** [comment]
Multiple: Avoid the legal grey area about the REBASE files by downloading them either at install time or usage. Avoid what where with hindsight poor design choices in current implementation (overly complex implementation with classes for every enzyme which also hampers auto-generated documentation, and use of one-based counting rather than Python counting).

**Comment by mdehoon** [comment]
It would be nice to get this into the next Biopython release.

**Comment by peterjc** [comment]
Replacing the restriction digest module is a worthy goal.

However, I feel Biopython 1.82 is already over due but ready to release - so wouldn't want to delay it any more.

**Comment by peterjc** [comment]
Note sure wny there is a git merge conflict.

Relatively minor things: I'd change this to use PEP8 lower case module names, perhaps ``Bio.digest`` rather than a lower case version of ``Bio.Restriction2``, and apply black. I would also be inclined to move the main class into the ``__init__.py`` file for easier end-user imports. And we can probably import the IUPAC ambiguity codes from ``Bio.Data`` rather then redefining them here.

More importantly, it would need some unit tests - the old module's ought to be a good guide.

**Comment by peterjc** [comment]
Thank you @anntzer - while we have your attention, in case we do eventually use this or something based on it, would you agree to dual licence this code under both the Biopython License Agreement and the 3-clause BSD license - see #898 - thanks!

**Comment by anntzer** [comment]
Yes, I do agree.

**Comment by peterjc** [comment]
Thank you!

**Pull request closed without merging**
