### PR TITLE
Standardising labels in Tutorial LaTeX source

### PR DESCRIPTION
**Pull request by peterjc**
This pull request is partly nice for consistency, but is mainly to help with potential conversion to reStructuredText for replacing hevea/pdflatex with Sphinx for the Tutorial - see #907.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
This has grown to include quite a few minor improvements to the Tutorial - little things noticed while reviewing the Sphinx output via pandoc to RST.

**Comment by peterjc** [comment]
I've applied what I thought we uncontroversial changes directly to the master, and rebased.

**Comment by peterjc** [comment]
TravisCI was failing with a doc8 dependency, fixed in #2181, but this will need another rebase to fix the merge conflict.

**Comment by MarkusPiotrowski** [comment]
Is there a place, where the output of these changes can be inspected?

**Comment by peterjc** [comment]
PDF as of commit 9de7a6f84e6aabb86451d96d579f42c8815e20c5 here:

[Tutorial.pdf](https://github.com/biopython/biopython/files/3428787/Tutorial.pdf)

I don't have hevea installed locally, but could log into a server if you want to see the HTML too.

**Comment by peterjc** [comment]
Thank you both - merging now, ready to build more on this at the BOSC 2019 CoFest tomorrow and on Saturday.

**Pull request merged**
