### PR TITLE
Remove remaining __future__ imports in Test

### PR DESCRIPTION
**Pull request by Dsujan**
This pull request addresses issue #2429 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by Dsujan** [comment]
This is strange `appveyor` says test failed. @peterjc 
```
FAIL: test_distancematrix_kmedoids (test_Cluster.TestCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_Cluster.py", line 1498, in test_distancematrix_kmedoids
    self.assertEqual(clusterid[0], 5)
AssertionError: 0 != 5
======================================================================
FAIL: test_kcluster (test_Cluster.TestCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_Cluster.py", line 314, in test_kcluster
    self.assertEqual(clusterid[i], mapping[correct[i]])
AssertionError: 2 != 1
----------------------------------------------------------------------
Ran 522 tests in 837.133 seconds
FAILED (failures = 1)
Skipping any tests requiring internet access
Python version: 3.7.4 (default, Aug  9 2019, 18:22:51) [MSC v.1915 32 bit (Intel)]
Operating system: nt win32
Command exited with code 1
```

**Comment by peterjc** [comment]
Next time can you start from a new branch from the latest master? It looks like this started from your old branch doing future imports from Bio.

The test_distancematrix_kmedoids test failure is unexpected. It might be a random failure - I have restarted it.

**Comment by Dsujan** [comment]
> Next time can you start from a new branch from the latest master? It looks like this started from your old branch doing future imports from Bio.

Okay. I will keep that in mind.

**Comment by peterjc** [comment]
Yes, it looks like a random failure from the cluster tests. If that keeps happening we may need to review the test (there have been other stochastic failures in tests with random inputs which caused similar problems).

Anyway, squash-and-merged as d5c66e6a3f411511c46784c7d377244791beb0ad - thank you!

**Pull request merged**
