### PR TITLE
Fix issue 704

### PR DESCRIPTION
**Pull request by sticken88**
Hello biopython devs! I hope this could help fixing this issue. Let me know if you accept it!

### CODE REVIEW

**Comment by peterjc** [comment]
The TravisCI failure is not your fault (something broken with PyPy3 and BioSQL).

Also don't worry about QuantifiedCode preferring the ``.format()`` method.

**Comment by sticken88** [comment]
All right then. I guess that my job is over for this issue unless you reject this pull request, right?

**Comment by peterjc** [comment]
Well done for identifying the flaw, this worked:

```
$ python3.5 Tests/test_Tutorial.py 
```

But using ``sys.argv[0]`` in the following failed because ``run_tests.py`` has already changed to the ``Tests/`` directory before calling ``test_Tutorial.py`` so my path assumptions broke:

```
$ python3.5 Tests/run_tests.py test_Tutorial.py 
```

I've fixed this a little differently https://github.com/biopython/biopython/commit/20107c4e006684750ed63c8f5a5b14eec453d113 - but your work helped by identifying the key issue. Would you like to be thanked in the ``NEWS`` and ``CONTRIB`` file for this?

**Comment by sticken88** [comment]
I am glad that my work helped you figuring out what the issue was. Yes, sure, it would be great to be thanked in the NEWS and CONTRIB file!
Hope to contribute even more to biopython!

**Pull request closed without merging**
