### PR TITLE
Add Sequence class to Bio.motifs.mast

### PR DESCRIPTION
**Pull request by victorlin**
This pull request introduces a class `Sequence` to `Bio.motifs.mast`. This allows for an organized way of parsing additional sequence information from the XML.

Previous functionality:

```python
>>> from Bio.motifs import mast
>>> record = mast.read('Tests/motifs/mast.adh.de.oops.html.xml')
>>> type(record.sequences[0])
<type 'str'>
>>> print(record.sequences[0])
ENTA_ECOLI
```

New functionality:

```python
>>> record = mast.read('Tests/motifs/mast.adh.de.oops.html.xml')
>>> type(record.sequences[0])
<class 'Bio.motifs.mast.Sequence'>
>>> print(record.sequences[0])
ENTA_ECOLI
>>> vars(record.sequences[0])
{'combined_pvalue': 9.46e-16,
 'description': '2,3-DIHYDRO-2,3-DIHYDROXYBENZOATE DEHYDROGENASE (EC 1.3.1.28)',
 'diagram': '[1]-[2]-224',
 'evalue': 3.1e-14,
 'length': 248,
 'name': 'ENTA_ECOLI',
 'strand': 'both'}
```

Tests will need to be modified accordingly.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
It is probably the class name ``Sequence``, but I'm not keen on this at all. Can't you use the existing ``SeqRecord`` class if you need an annotated sequence?

**Comment by mdehoon** [comment]
Agree with @peterjc  . I don't think we should add a new Sequence class.

**Comment by victorlin** [comment]
Thanks for the tip - I'm relatively new to this repository and haven't used the `SeqRecord` class. It seems that `SeqRecord` requires the actual sequence to be known but this can't be extracted from the XML (only parts of it are known from motif hits). Using `UnknownSeq` is an option but there doesn't seem to be an attribute for annotations.

**Comment by peterjc** [comment]
You would use the ``SeqRecord`` with the ``seq`` attribute set to an instance of the ``UnknownSeq`` class. However, it may well be that this is still not a good match for the motif information you want to store.

Have you looked to see what other metadata the other motif formats contain which is not captured in the current ``Bio.motifs.*`` approach?

**Comment by victorlin** [comment]
The metadata I would like to add is per sequence, each of which can have multiple motif hits. Here's an entry for one sequence in the XML:

```xml
<sequence db="0" name="FIXR_BRAJA" comment="FIXR PROTEIN" length="278">
    <score strand="both" combined_pvalue="2.35e-12" evalue="7.8e-11"/>
    <seg start="1">
        <data>
MGLDLPNDNLIRGPLPEAHLDRLVDAVNARVDRGEPKVMLLTGASRGIGHATAKLFSEAGWRIISCARQPFDGER
        </data>
        <hit pos="44" idx="1" pvalue="2.6e-11" match="+++++++++++ "/>
    </seg>
    <seg start="151">
        <data>
APILLAQGLFDELRAASGSIVNVTSIAGSRVHPFAGSAYATSKAALASLTRELAHDYAPHGIRVNAIAPGEIRTD
        </data>
        <hit pos="205" idx="0" pvalue="4.1e-08" match="+++++++++++ "/>
    </seg>
</sequence>
```

With the current parser, `"FIXR_BRAJA"` is stored in `Record.sequences` coupled by `"43-[2]-149-[1]-62"`, a string representation of the motif hit locations, under `Record.diagrams["ENTA_ECOLI"]`.

With your approach of `SeqRecord` and `UnknownSeq`, all the attributes in the `<sequence>` and `<score>` tags can be stored under `SeqRecord`. The diagram string can be added to `SeqRecord` as well, though it leaves out the exact sequence values per segment.

**Comment by peterjc** [comment]
I think might be a better fit to ``Bio.SearchIO`` (which already covers things like BLAST and HMMER), although that is blurring the lines between it and ``Bio.motifs`` ? What do you think @bow ?

**Comment by victorlin** [comment]
Closing - not a necessary feature.

**Pull request closed without merging**
