### PR TITLE
Bigbed search

### PR DESCRIPTION
**Pull request by mdehoon**
Add search capability to the bigbed parser in `Bio.Align`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Despite not touching ``Bio\Cluster\cluster.c`` itself, from the timing it looks like merging this PR has broken the master branch CI testing under Windows:

```
...
Generating code
D:\a\biopython\biopython\Bio\Cluster\cluster.c(1495) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com/ 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  link!RaiseException()+0x62
  link!RaiseException()+0x62
  link!InvokeCompilerPass()+0xdf7f1
  link!CloseTypeServerPDB()+0xe97e1
  link!CloseTypeServerPDB()+0x3b101

error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 3765260340
```

Maybe we should try a pull request reverting this to confirm that, and rule out anything like a change to the build environment?

**Comment by mdehoon** [comment]
This is pure python code. I don't see how it can affect the compiler.

**Comment by peterjc** [comment]
Huh. This makes it look more likely to be a build environment change then...

20 August 2022 - https://github.com/biopython/biopython/commit/1ebd1bb919a45908da4db46468a5180203377471 worked post PR #4045 merger

23 August 2022 - https://github.com/biopython/biopython/commit/07026ecbd0282de326c3e6a73109fc608f961b6e failed post PR #4046 merger

**Comment by mdehoon** [comment]
To add to the mystery, at https://github.com/biopython/biopython/runs/7967360664?check_suite_focus=true
compilation runs fine for Python 3.7 and 3.9, but crashes for Python 3.8 and 3.10.

**Comment by peterjc** [comment]
I've opened #4052 specifically for tracking this ``fatal error C1001: Internal compiler error.`` problem.

**Pull request merged**
