### PR TITLE
Improve Travis before_install part for readability.

### PR DESCRIPTION
**Pull request by junaruga**
Hello,

I updated  Travis before_install part in `.travis.yml` for readability.
YAML block style "|" helps us for that.
As Travis is run as "bash -e" mode, I think that we do not have to connect with `&&`.

### CODE REVIEW

**Comment by junaruga** [comment]
Travis: success.
AppVeyor: Failed with "AppVeyor was unable to build non-mergeable pull request"
I found below page.
http://help.appveyor.com/discussions/problems/4830-stuck-on-appveyor-was-unable-to-build-non-mergeable

I just modified only `.travis.yml`.
So, it looks false positive.

**Comment by peterjc** [comment]
I don't think I was persistent enough with exploring the TravisCI multi-line capabilities - I didn't think that was possible.

See also #1305 which would remove this hack once TravisCI supports PyPy directly.

**Comment by junaruga** [comment]
I will sometimes see the multi-line block style in projects.

> See also #1305 which would remove this hack once TravisCI supports PyPy directly.

Ok, it looks the ticket code just need rebase on the latest master branch.
I am fine to do it. It can be an another PR.
I will send the PR doing cherry-pick the ticket's commits.

Feel free to close or merge this PR.

**Comment by peterjc** [comment]
Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by junaruga** [comment]
Yes, I am fine or happy :)
Just do it as you like :)

**Comment by junaruga** [comment]
> Just do it 

Ah sorry my English is bad.. That was mistake for "Please do it".

**Comment by peterjc** [comment]
I understood "Just do it". Your meaning was clear.

If you want to try rebasing and testing #1305, that would be helpful - thank you :)

**Pull request merged**
