### PR TITLE
Convert more f-strings

### PR DESCRIPTION
**Pull request by Caiofcas**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Some progress in #2510

### CODE REVIEW

**Comment by peterjc** [comment]
How are you doing these? If by hand, that makes be very nervous about accidental mistakes.

Also something is triggering ``RecursionError: maximum recursion depth exceeded while calling a Python object`` on the tests.

**Comment by Caiofcas** [comment]
Was doing them by hand, yes, but did somtehing wrong when testing locally, will fix it.

**Comment by peterjc** [comment]
Is there good reason to replace ``str(expression)`` with ``f"{expression}"`` here? From a C programming background this is like a cast, and very clear and explicit. It might be faster too?

**Comment by Caiofcas** [comment]
I had the impression it would be faster since it would avoid a function call, but doing some more research this appears to only be true for simpler types. I think I will close this PR and open some smaller ones to facilitate the review process.

**Comment by peterjc** [comment]
OK - maybe focus on one sub-directory at a time? And I would suggest starting with just running flynt and black (automated so less chance of error) and see how much manual review is needed after that.

Some slightly out of date numbers on https://github.com/biopython/biopython/issues/2510#issuecomment-916793707

**Pull request closed without merging**
