### PR TITLE
SearchIO/hmmer2-text: Deal with line breaks in the end of sequence marker

### PR DESCRIPTION
**Pull request by kblin**
Signed-off-by: Kai Blin <kblin@biosustain.dtu.dk>

This pull request addresses issue #1564

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

I am happy be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files,
and have added myself to those files as part of this pull request. (*This
acknowledgement is optional. Note we list the names sorted alphabetically.*)

### CODE REVIEW

**Comment by kblin** [comment]
As mentioned in the bug report, I don't like the dance in lines 286..288, but couldn't come up with a better way of making sure we're not parsing the `-` end coordinate marker as part of `otherseq`.

**Comment by peterjc** [comment]
Over to you @bow - can you see a cleaner fix, or should we go with this?

**Comment by bow** [comment]
This looks ok ~ sometimes ugly corners just pop up of course, at least I think here it is commented properly. (By the way, I mistakenly added my comments on the [issue page](https://github.com/biopython/biopython/issues/1564) rather than here).

Thanks again @kblin!

**Comment by kblin** [comment]
I just ran across an end marker with a `<\n-*` style break and can confirm that my "fake" version matches. So we should be good for both cases. :)

**Comment by peterjc** [comment]
Great. Are you happy with the fake test, or you do want to replace it with the new real one?

**Pull request merged**
