### PR TITLE
Enforce black on Bio/

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses issue #2008, and assumes #2551 will be merged first.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Rebased now that #2551 is merged, this should pass the automated tests...

**Comment by mdehoon** [comment]
Isn't this a bit too early? From the black website:

> NOTE: This is a beta product

> Black is already successfully used by many projects, small and big. It also sports a decent test suite. However, it is still very new. Things will probably be wonky for a while. This is made explicit by the "Beta" trove classifier, as well as by the "b" in the version number. What this means for you is that until the formatter becomes stable, you should expect some formatting to change in the future. That being said, no drastic stylistic changes are planned, mostly responses to bug reports.

My other concern is how this will impact code development. The biggest problem by far I see in Biopython is antiquated code, both in terms of modules that have not been kept up to date, and code that does not take advantage of modern Python (for example, the Seq object was designed for Python 2.1). Adding more rules will slow us down further.

**Comment by peterjc** [comment]
See discussion on #2008 where I thought we'd covered those issues. This should speed up taking new contributions as it makes complying with style formatting much easier (especially tedious things like trailing white space) - "just run black" will cover the majority. We can look at automating that too on pull requests.

(Black doesn't catch actual code problems like undefined variables, so flake8 or other linting tools still have a role to play).

**Comment by mdehoon** [comment]
@peterjc  Sorry I haven't really followed the style discussion. Would this PR require developers to install additional tools?

**Comment by peterjc** [comment]
It wouldn't force them to, in the same way that we don't force people to install flake8 now.

We already encourage people to install and run ``flake8`` (and a list of plugins) as described in ``CONTRIBUTING.rst``, this essentially adds ``black`` to that list.

This would not stop simple pull requests via the GitHub web interface, e.g. fixing a typo or deleting a comment. Occasionally those kind of edits would break a stylistic rule - but we have that already with the flake8 enforcement.

**Comment by peterjc** [comment]
Just refreshing to include black updates on a few more files edited in the meantime.

**Pull request merged**
