### PR TITLE
Apply black style to test_NCBITextParser.py, version 19.10b0.

### PR DESCRIPTION
**Pull request by svalqui**
This pull request addresses issue #2552 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

This PR applies black style to test_NCBIXMLTextParser.py, more than 1,000 differences. it would good to review it.

### CODE REVIEW

**Comment by peterjc** [comment]
Yikes:

> 10,667 additions, 2,734 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

**Comment by svalqui** [comment]
Yes, I have give it a glance, seems fine; run flake and the test passes, now to look it in detail line by line might be too much for this one.

**Comment by peterjc** [comment]
@mdehoon do you want to comment on this one? Shall we just merge it?

**Comment by mdehoon** [comment]
I didn't know we are still parsing plain-text Blast output.

**Comment by peterjc** [comment]
It's strongly discouraged by us and the NCBI, but still useful. Is that a fair summary @bow?

**Comment by mdehoon** [comment]
It makes us look bad though.

**Comment by peterjc** [comment]
You mean the (non) black formatting (this PR will fix that), or that we still have a plain text parser (e.g. do you want to formally deprecate it with a warning)?

**Comment by mdehoon** [comment]
@peterjc 

> You mean the (non) black formatting (this PR will fix that), or that we still have a plain text parser (e.g. do you want to formally deprecate it with a warning)?

that we still have a plain text parser

>  (e.g. do you want to formally deprecate it with a warning)?

or just remove it. Deprecation takes too long.

**Comment by peterjc** [comment]
Quoting https://github.com/biopython/biopython/blob/master/DEPRECATED.rst

> Bio.Blast.NCBIStandalone
> The three functions for calling the "legacy" NCBI BLAST command line tools blastall, blastpgp and rpsblast were declared obsolete in Biopython Release 1.53, deprecated in Release 1.61, and removed in Release 1.64. Please use the BLAST+ wrappers in Bio.Blast.Applications instead.
>
> The remainder of this module is a parser for the plain text BLAST output, which was declared obsolete in Release 1.54, and deprecated in Release 1.63.
>
> For some time now, both the NCBI and Biopython have encouraged people to parse the XML output instead, however Bio.SearchIO will initially attempt to support plain text BLAST output.
>
> The module was removed in Release 1.72 from the public API. It lives now in maintenance mode in Bio.SearchIO._legacy to preserve existing functionality.

Biopython 1.72 was released June 2018, coming up on two years ago. There is a warning on using "blast-text" in SearchIO, ``BiopythonWarning: Parsing BLAST plain text output file is not a well supported functionality anymore. Consider generating your BLAST output for parsing as XML or tabular format instead.`` although it isn't literally our deprecation warning.

Maybe close enough if @bow wants to remove the plain text parsing now? Or as a compromise switch it to a deprecation warning for one more release, and then drop it?

**Comment by peterjc** [comment]
And as to the black formatting, how about we just disable black on this test file since it will be most likely be removed at some point?

**Comment by svalqui** [comment]
@peterjc , sorry for the delay, time constrained at the moment, I'll close this as there is other changes to the file already and it could get messy, and I'll open a fresh PR for this, disabling the formatting on this file.

**Pull request closed without merging**
