### PR TITLE
Run PyPy workers on Linux only.

### LINKED ISSUE #3674: github actions macOS pypy broken
Compiling a working numpy from source for pypy under macOS is failing (and there are currently no pre-compiled wheels available for pip to use), e.g.

https://github.com/biopython/biopython/runs/3189739916

```
Traceback (most recent call last):
  File "run_tests.py", line 41, in <module>
    import numpy
  File "/Users/runner/hostedtoolcache/PyPy/3.6.12/x64/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

Fixing the environment to build numpy looks non-trivial:

https://foss.heptapod.net/pypy/pypy/-/issues/3268

Can we skip this entry in the test matrix? Just pypy on Linux ought to suffice.

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3674.

### CODE REVIEW

**Comment by peterjc** [comment]
Strange, it still has: ``test_windows (pypy3)`` which fails.

**Comment by peterjc** [comment]
Correction, also still has ``test_macos (pypy3)`` which is failing.

Maybe we need two separate exclude entries here?

**Comment by JoaoRodrigues** [comment]
I think the changes only kick in once we merge the PR. This is running the "old" action workflow no? These CI workflows are a nightmare to debug... I'll test this on my fork.

**Comment by JoaoRodrigues** [comment]
Nevermind, was editing the wrong part of the file...

**Review by peterjc — APPROVED** [review]
Squash and merge?

**Comment by peterjc** [comment]
Looks like the docs build is failing (but was never reached before). There is an argument for doing that at the same time, or even prior to all the rest?

Anyway, progress - thank you!

**Comment by JoaoRodrigues** [comment]
Squash and merge! I am refactoring a little the YAML file to do more caching to speed things up, but I can push it later. Thanks!

**Pull request merged**
