### PR TITLE
split the alignment chapter

### PR DESCRIPTION
**Pull request by mdehoon**
This PR splits the chapter on sequence alignments into 4 chapters:
 - One chapter on the new-style `Alignment` class;
 - One chapter on performing pairwise sequence alignments using `Bio.Align.PairwiseAligner`;
 - One chapter on the old-style `MultipleSeqAlignment` class;
 - One chapter on `Bio.pairwise2`.

In most cases, the contents of the documentation has not yet been updated.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
I don't quite follow the split between ``chapter_align.tex`` and ``chapter_pairwise.tex`` which follows it. As written both appear to be about pairwise alignments using the new code in ``Bio.Align``?

**Comment by mdehoon** [comment]
`chapter_align.tex` (which is not completed yet) will be about the `Alignment` object and the parsers.
`chapter_pairwise.tex` is about the pairwise aligner.

**Comment by peterjc** [comment]
i.e. ``chapter_align.tex`` will cover the objects used for not just pairwise alignments, but multiple sequence alignments too (like in #4366)? Then it makes sense.

Do you think you'd have more of that done soon, or would it be better to do the Biopython 1.82 release before this restructing?

Also, I was hoping to do more work on the LaTeX to RST conversion during the BOSC 2023 CoFest (starting tomorrow). However it is perhaps unlikely that would be ready to merge and go live, so we'll probably have to port any changes to the LaTeX tutorial in the meantime.

**Comment by mdehoon** [comment]
> i.e. chapter_align.tex will cover the objects used for not just pairwise alignments, but multiple sequence alignments too (like in https://github.com/biopython/biopython/pull/4366)? Then it makes sense.

The `Alignment` class is used both for pairwise alignments and multiple sequence alignments.

> Do you think you'd have more of that done soon, or would it be better to do the Biopython 1.82 release before this restructing?

It may not be perfect, but it's easy to write a rudimentary chapter. Also, the current chapter is way too confusing.

**Comment by peterjc** [comment]
OK, then go ahead and merge this now :)

**Review by peterjc — APPROVED** [review]

**Pull request merged**
