### PR TITLE
[WIP] SearchIO Refactoring

### PR DESCRIPTION
**Pull request by bow**
This pull request (work in progress, not ready for merging) was triggered by this: https://landscape.io/github/biopython/biopython/38/modules/Bio/SearchIO/FastaIO.py#L403

While the part of the code works (they are all under testing), it's not so easy to understand and makes future refactoring difficult. This pull request is meant to fix that (and other SearchIO-related issues not related to functionality).

### CODE REVIEW

**Comment by peterjc** [comment]
Is this pull request still live Bow?

**Comment by bow** [comment]
Hey @peterjc,

Ah yes, this has been a while. Yes, this is. I'll mark this with a `[WIP]` and then ping when it's done?

**Comment by peterjc** [comment]
Good plan. Do you want WIP as a GitHub label, or just add it to the issue title?

**Comment by peterjc** [comment]
Bow, is this PR still alive? It will need some updating due to conflicts...

**Comment by bow** [comment]
@peterjc Unfortunately, I have not looked into this for a while. The initial landscape.io report that triggered this is not even available anymore for several years now.

I hope it's reasonable to close this. The changes so far are minor and can be discarded.

**Pull request closed without merging**
