### PR TITLE
SeqRecord format now plain text only

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses issue #2333 now that we have dropped Python 2, and in part #2420 for ``SeqRecord.py``

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
How's this @mdehoon - or do you want to switch to a try/except approach where the binary formats would raise a TypeError?

**Comment by mdehoon** [comment]
> How's this @mdehoon - or do you want to switch to a try/except approach where the binary formats would raise a TypeError?

Yes a try/except approach is the Pythonic way. Ideally we should get rid of SeqIO._BinaryFormats altogether, and let the SeqIO backend tell us if it can handle binary or text by raising a TypeError.

**Comment by peterjc** [comment]
Rebasing for merge conflict...

**Comment by peterjc** [comment]
I'm going to merge this as is (to address the short term goal of removing the Python version check, #2490), but Michiel is right - we can do better and avoid needing ``SeqIO._BinaryFormats`` here.

**Pull request merged**
