### PR TITLE
Apply black style to Bio.Restriction.

### PR DESCRIPTION
**Pull request by svalqui**
This pull request addresses issue #2008 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

The style has changed some lists appearance, making it long but it reads better; should be fine to merge.

### CODE REVIEW

**Comment by MarkusPiotrowski** [comment]
@svalqui `Bio.Restriction_Dictionary` is an autogenerated file. So it does not make sense to change the file itself but the script (`ranacompiler.py` under Scripts) that generates it.

**Comment by svalqui** [comment]
@MarkusPiotrowski , Thank you for that, I missed it; I'll have a think about this one, the lines are too long horizontally as is, after black they are too long vertically, needs a middle ground.

**Comment by peterjc** [comment]
If the black version is too long (and it often is), I would just mark the file a black format off - which needs a tiny change to the autogeneration script.

**Comment by svalqui** [comment]
I have updated ranacompiler.py to switch off black style, and run it to check Restriction_Dictionary.py; seems fine now; however it had been producing long lines already, about 2290 characters long
https://github.com/biopython/biopython/blob/7844bcaa558b7922af3601a5b82173a76bc51c69/Bio/Restriction/Restriction_Dictionary.py#L24354-L24359

That would need some sort of styling, I do not think that is part of this PR, added a TODO note for that.

**Comment by peterjc** [comment]
I would leave the automatically generated file as it was other than adding a _single_ set of black format off/on lines at the top and bottom (not adding them for every enzyme).

**Comment by svalqui** [comment]
There is only one black off and one black on for the entire file, not per each enzyme;  the first after the header, the last after "del _temp\n". ranacompiler.py produces the file fine with a single set of black off/on.

**Comment by peterjc** [comment]
Sorry - you're right. I see you've also updated the REBASE database as part of this - which I would prefer to see as a separate pull request, or at least separate commit. It usually gets a line in the NEWS file too.

**Comment by svalqui** [comment]
I understand now, I have left Restriction_Dictionary the same version as is now, just added the black statement manually.

**Comment by peterjc** [comment]
Thank you!

**Pull request merged**
