### PR TITLE
remove alphabets from Bio.SeqIO.AbiIO

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request removes alphabets from `Bio.SeqIO.AbiIO`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
We've already got ``record.annotations["molecule_type"] = "DNA"`` so this is fine.

**Comment by mdehoon** [comment]
> We've already got record.annotations["molecule_type"] = "DNA" so this is fine.

Actually I am not sure if this line should be in `AbiIO.py`, as this information is not read from the file contents.

**Comment by peterjc** [comment]
I don't follow - the ABI files are the output file of a DNA sequencer, it is always DNA.

**Comment by mdehoon** [comment]
> I don't follow - the ABI files are the output file of a DNA sequencer, it is always DNA.

For this reason, the parser should _not_ store this information. Users can set this information if they want to; they don't need the parser to tell them what the molecule type is. In addition, you don't really know what the molecule type is. Genbank for example may say that the molecule type is RNA although the sequence is given as DNA nucleotides. Same here; to the user, this could be RNA.

The ultimate problem is that the molecule type is poorly defined; it's just an ad-hoc measure to store information that is available in the file. Alphabets suffered from the same problem. If we set the molecule type in cases where this information is not explicitly stored in the file, then alphabets are creeping back in.

As a general guideline, we could say that Biopython should be able to write back a file it has parsed without information loss. Then, for Genbank files, the parser should store the molecule type in the `SeqRecord`. For Abi files, it does not need to do so.

**Pull request merged**
