### PR TITLE
update Bio.PopGen for python3

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request does some cleanup of Bio.PopGen. It also removes `Bio/PopGen/GenePop/Utils.py`, which has been empty for 12 years.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Removing ``Bio/PopGen/GenePop/Utils.py`` makes sense after over 10 years as a stub since affda2f9c955a8fff39a16a6de8b24bb656411ca

**Comment by mdehoon** [comment]
Don't know what Travis is obsessing about.

**Comment by peterjc** [comment]
Sorry -  a glitch on the master when I manually merged #1697, fixed in d5d76303932e71fc9e6827b915c630061a4c25e4

(I would have updated the pull request branch but it may have predated the GitHub option to give project maintainers write access to pull request branches)

A git rebase or merge should fix this.

**Comment by mdehoon** [comment]
Let's first wait and see if @tiagoantao  has any comments or suggestions.

**Comment by mdehoon** [comment]
@tiagoantao  Thanks! Trust me, there is even much more ancient code in Biopython.

**Comment by mdehoon** [comment]
@peterjc  Can I just push squash and merge now, or would that break things?

**Comment by peterjc** [comment]
Let me just rebase it to make sure, should only take a few minutes (plus the Travis/AppVeyor time).

**Pull request merged**
