### PR TITLE
remove "if __name__ == '__main__':" block

### PR DESCRIPTION
**Pull request by Gasta88**
As mentioned in issue #820 ,I've removed the block

### CODE REVIEW

**Comment by peterjc** [comment]
Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS`` and ``CONTRIB`` files?

**Comment by Gasta88** [comment]
Happy with both.

**Comment by peterjc** [comment]
How do you want to be named? ``FGastaldello``?

**Comment by Gasta88** [comment]
Sure, it' fine. (Sorry, I don't get notifications anymore for issues or PRs, I need to check my options)

**Pull request merged**
