### PR TITLE
Deploy API documentation using CircleCI

### PR DESCRIPTION
**Pull request by erik-whiting**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

This work addresses some of the work listed in [3688](https://github.com/biopython/biopython/issues/3688). Specifically, it updates the doc-deployment script mostly with instructions on how to set up docs deployment in GitHub. Note, this work will not yet automate the deployment process, a maintainer will still have to configure the necessary SSH keys in CirlceCI and the Biopython project.

### CODE REVIEW

**Comment by peterjc** [comment]
I've changed the title. Note you will have to agree to the licensing if we are to accept this contribution when it is ready.

**Comment by erik-whiting** [comment]
> I've changed the title. Note you will have to agree to the licensing if we are to accept this contribution when it is ready.

Noted, thank you. I thought this PR was on my own fork, I'm really _**really**_ sorry for all the spam emails. I think I have this almost figured out; I will also clean up the commit history once it's ready to go.

**Comment by erik-whiting** [comment]
Just an update, I finally got this working in my own repositories. I will update and make instructions more clear for biopython deployment but I am stepping into class now.

**Comment by erik-whiting** [comment]
@peterjc this is ready for a serious look. As noted in the main comment, please note that you (or some authorized maintainer with the necessary access) will have to follow the instructions I left in the script

**Comment by peterjc** [comment]
I didn't appreciate https://github.com/erik-whiting/biopython/pull/1 was on your repository, but my comments there apply here. This looks very promising :)

**Comment by erik-whiting** [comment]
@peterjc I applied the request changes, let me know if there's anything else that pops out at you

**Comment by peterjc** [comment]
I'll try to setup the keys following your notes...

**Comment by erik-whiting** [comment]
Cool, let me know if I should update anything or if you need anything from me

**Comment by peterjc** [comment]
Will it work? Fingers crossed...

I had done almost all the SSH keys bits in your instructions previously (so didn't repeat them all).

**Comment by peterjc** [comment]
So close, but should be easy to fix:

```
ERROR: The key you are authenticating with has been marked as read only.
```

https://app.circleci.com/pipelines/github/biopython/biopython/576/workflows/1f03113a-e29a-4a24-9705-942352a6d439/jobs/579

**Comment by peterjc** [comment]
I removed all the old keys, made a new one, and now it works:

https://github.com/biopython/docs/commit/168b440ecb2ff8edf8a59576afd0d6b79e1958e9

Thank you 🥳

**Comment by erik-whiting** [comment]
this was the last problem I experienced in my local repos. it was fixed by adding a user key in it CircleCI project settings (the last paragraph of the instructions before the bash code in the deploy script).

did you do that part? I think it's a specifically-CircleCI requirement for this work.

**Pull request merged**
