### PR TITLE
adds Ahmad ASA values to PDB DSSP

### LINKED ISSUE #3552: Feature request: different DSSP ASA to RSA conversion values
At the moment Bio.PDB.DSSP offers three maximum solvent accessibility tables for converting Absolute and Relative solvent accessibilities (ASA and RSA).

There is another conversion table which is frequently used, for example by the state-of-the-art solvent accessibility predictor NetsurtfP-2.

The table is described in:
Ahmad,S., Gromiha,M. M., and Sarai,A. (2003-02) Real value prediction of solvent accessibility from amino acid sequence. Proteins: Structure, Function, and Bioinformatics, 50, 629–635. https://doi.org/10.1002/prot.340200303

It would be nice to be able to use also the aforementioned table directly from Biopython.
I paste here the values from that paper.

```
RESIDUE_MAX_ACC = {
    # this is the ASA for the residue in an extended Ala-X-Ala trypeptide
    # Values from Ahmad et al. 2003, https://doi.org/10.1002/prot.10328
    "A": 110.2,
    "R": 229.0,
    "N": 146.4,
    "D": 144.1,
    "C": 140.4,
    "Q": 178.6,
    "E": 174.7,
    "G": 78.70,
    "H": 181.9,
    "I": 183.1,
    "L": 164.0,
    "K": 205.7,
    "M": 200.1,
    "F": 200.7,
    "P": 141.9,
    "S": 117.2,
    "T": 138.7,
    "W": 240.5,
    "Y": 213.7,
    "V": 153.7,
}
```

### PR DESCRIPTION
**Pull request by Caiofcas**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3552 . Adds the requested ASA values.

### CODE REVIEW

**Comment by Caiofcas** [comment]
The Appveyor build failed for unrelated reasons, don't know if I should do something about it.

**Comment by JoaoRodrigues** [comment]
Hi @Caiofcas ,

Thanks for the contribution! I had seen that issue and was planning to work on it but you beat me to it.

My idea was to actually decouple the relative solvent accessibility scales from DSSP and make them more broadly available. We now have a native ASA calculation code (Bio.PDB.SASA) and could plug several scales there to normalize the raw values we obtain. Adding to the scales we already have, we should add NACCESS's.

**Comment by JoaoRodrigues** [comment]
For NACCESS values, we can use these standards, which I obtained from author a few years ago to include in freesasa:

https://github.com/mittinatten/freesasa/tree/e68a4ba73b4672c7089836168af2ad96e33a5a4e/scripts/rsa

**Comment by Caiofcas** [comment]
Hi @JoaoRodrigues thanks for the comments! 

I'm not that familiar with PDB, but took this issue because it seemed like an easy addition. Just to make sure I understand your comments, you are saying I should add the NACESS's standard values to the ASA predefined scales? or are you suggesting more of a refactoring of this section? If it's second I'm not really sure how to approach it, since I'm not really confident that I understand the use cases for these modules.

**Comment by Caiofcas** [comment]
@JoaoRodrigues Do you think we can merge this to close #3552 and then open a new enhancement issue for the decoupling of DSSP values?

**Comment by JoaoRodrigues** [comment]
Sorry @Caiofcas, this completely slipped off my mind. Merging the new scale sounds OK for me. I just pushed a new module `Bio/Data/ProteinData.py` a couple of days ago, which I think would be a good place for these scales to live on the long-term.

**Review by JoaoRodrigues — APPROVED** [review]

**Comment by Caiofcas** [comment]
No problems, thanks for the merge

**Pull request merged**
