### PR TITLE
Apply black style to Bio.GenBank.

### PR DESCRIPTION
**Pull request by svalqui**
This pull request addresses issue #2008

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Minor changes, should be fine to merge.

### CODE REVIEW

**Comment by peterjc** [comment]
Can you double check which version of black you are using (and in future state this in your commit messages)?

#2191 already applied black v19.3b0 - most these changes look like fine tuning at the max-line length, and a corner case with square brackets.

**Comment by svalqui** [comment]
I'm using black, version 19.3b0 as well, not sure why has not been picked up on the previous run.

**Comment by peterjc** [comment]
Strange. Perhaps I wasn't using what I thought I was (I did briefly have a confused version as at one point I was testing a branch of black for a potential bug fix).

Anyway, could you update to the latest release? black 19.10b0

**Comment by svalqui** [comment]
Update to black, version 19.10b0, and re-run it on this branch, no changes, nothing to commit.

**Comment by peterjc** [comment]
Thanks - looks like I was using a test branch of black.

**Pull request merged**
