### PR TITLE
Fixes for pydocstyle rule D211 (blank lines)

### PR DESCRIPTION
**Pull request by morrme**
Ref: Issue #1170

### CODE REVIEW

**Comment by peterjc** [comment]
The current TravisCI failure is my fault (I must have rushed this before leaving work today...)

**Comment by morrme** [comment]
@peterjc is it that ";" before `then` ?

**Comment by peterjc** [comment]
Its something annoying about the quotes needed get it working inside of tox, testing now....

**Comment by peterjc** [comment]
Fixed  https://github.com/biopython/biopython/commit/7813b39db8c27dabf17a56297694ce43989e4284- see https://travis-ci.org/biopython/biopython/jobs/223710530

I see you've already updated ``.pydocstyle`` to remove D211 from the ignore list :)

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files? You can add yourself if you like as part of this pull request (note they are sorted alphabetically, and we check this automatically for the contributor listing via TravisCI using the sort command given at the top of the file).

**Comment by morrme** [comment]
great! 
Yes, I made sure to do that step ! :smiley: 
Yes I am happy to dual license all of my contributions. 
I can add myself at the next commit, since this one is all done.

**Comment by peterjc** [comment]
Thanks for agreeing to the licensing. What do you want to use as your name? Your GitHub profile doesn't say.

**Pull request merged**
