### PR TITLE
PSSM search - force uppercase and optimize C code

### PR DESCRIPTION
**Pull request by sefakilic**

### CODE REVIEW

**Comment by mdehoon** [comment]
Why is this better?

**Comment by sefakilic** [comment]
The C `_calculate` handles both uppercase and lowercase explicitly. The Python `_calculate` function, however, first changes the sequence to uppercase and then scores it. This change makes the sequence uppercase first and then calls Python or C `_calculate` function depending on NumPy availability. I think it makes the code cleaner.

In addition, not sure about how the compiler optimizes this but, the switch statement in C _calculate function now has less number of cases to go through before finding the matching one.

**Comment by mdehoon** [comment]
But if the sequence is very long (e.g. a complete chromosome), you will lose time in creating the uppercase sequence, and the memory required may be excessive.

**Comment by peterjc** [comment]
That's a strong point Michiel. How about we replace this comment:

``` python
# TODO - Force uppercase here and optimise switch statement in C
# by assuming upper case?
```

with a note like:

``` python
# NOTE: The C code handles mixed case input as this could be large
# (e.g. contig or chromosome), so requiring it be all upper or lower
# case would impose an overhead to allocate the extra memory.
```

I'd also put this comment in the C code.

What do you think @sefakilic ?

**Comment by sefakilic** [comment]
That sounds good to me.

**Comment by peterjc** [comment]
@sefakilic  Do you want to add a comment in the C code too? Otherwise I'm happy to apply this as a squashed commit.

Are you happy being named in the ``NEWS`` and ``CONTRIB`` files?

**Comment by peterjc** [comment]
Change applied as a squashed commit, thank you @sefakilic 👍 

I'm happy to add you to the `NEWS` and `CONTRIB` files now, or wait if you're planning further larger contributions which would be most welcome.

**Comment by sefakilic** [comment]
Thanks. I don't think this commit deserves any credit. I am planning to do some work on PSSM search to handle ambiguous DNA sequences. I would be glad to be added after submitting that PR.

**Comment by peterjc** [comment]
Great - thanks!

**Comment by peterjc** [comment]
@sefakilic would you agree to dual license your Biopython contributions as discussed on #898 so we can switch to the standard 3-clause BSD license? (Apologies if you already have done so, and I have overlooked this)

**Pull request closed without merging**
