### PR TITLE
Update meme parser (v 4.11.4 support)

### PR DESCRIPTION
**Pull request by aralap**
Fixes the problem parsing the new version of MEME (4.11.4)

### CODE REVIEW

**Comment by aralap** [comment]
Small fix to support parsing of MEME format version 4.11.4.

**Comment by peterjc** [comment]
This looks good to me, although if you could pick a small test case to add to ``Tests/motifs/`` and use in ``Tests/test_motifs.py`` that would make me happier.

@barwil @mdehoon - could you review/comment?

**Comment by peterjc** [comment]
Also, are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

And are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by aralap** [comment]
Added a test file  (#1279) and test (#1281) , and have no problem  with licensing or being thanked.

**Comment by peterjc** [comment]
I've moved the test file and change to use it from #1279 and #1281 into this pull request:

```
$ git cherry-pick e601ca41bc6544b53efb712644c53f8ecb1d7971
$ git cherry-pick e5b46733f54e8d91d937b27d1b0bf2b034a0b737
```

Fingers crossed the TravisCI automated tests will now pass...

**Comment by peterjc** [comment]
Since you've not filed in your GitHub profile, I wanted to check how would you like to be named in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

Note I can work out your name from the email address in the git commits, if you want to be more anonymous, see https://help.github.com/articles/keeping-your-email-address-private/

**Comment by peterjc** [comment]
Hopefully I have just fixed the failing style issues - but there is something wrong with ``meme_v_4_11_4.txt`` vs ``meme_v_4_11_4.out`` (and not just the file name, the content).

**Comment by peterjc** [comment]
Note I rebased the branch to the current master. With hindsight that probably was unhelpful.

**Comment by aralap** [comment]
I would like to be named (or rather have nothing against it).

**Comment by aralap** [comment]
The test file should be meme_v4_11_4.txt, meme_v_4_11_4.out was uploaded by mistake, sorry.

**Comment by peterjc** [comment]
Can you commit the ``meme_v4_11_4.txt`` file to this branch or a new branch please?

**Comment by peterjc** [comment]
Excellent, merged. Thank you.

Note we may need to revisit this next time MEME is updated, but hopefully at that point it will be clearer how this part of the output will be presented in general.

**Pull request merged**
