### PR TITLE
Add parser/writer for BED files to Bio.Align

### PR DESCRIPTION
**Pull request by mdehoon**
This PR adds a parser/writer for BED files to `Bio.Align`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@peterjc  Any objections?

**Comment by peterjc** [comment]
There's a few public API changes in here like ``write_alignment`` --> ``format_alignment``, but I think that is _probably_ OK given the general flux in ``Bio.Align``.

Would it be trivial to preserve the old method name as a deprecated wrapper round the new one?

**Comment by mdehoon** [comment]
> There's a few public API changes in here like `write_alignment` --> `format_alignment`, but I think that is _probably_ OK given the general flux in `Bio.Align`.
> 
> Would it be trivial to preserve the old method name as a deprecated wrapper round the new one?

I don't think it is necessary. The old `write_alignment` method is not in any Biopython release yet.

**Comment by peterjc** [comment]
Oh good - no problems there then :)

**Comment by mdehoon** [comment]
@peterjc  Thanks!

**Pull request merged**
