### PR TITLE
Rm future imports

### PR DESCRIPTION
**Pull request by Dsujan**
This pull request addresses issue #2429 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
The flake8 style checks are failing, quoting the TravisCI output:

```
$ flake8
./Bio/Geo/Record.py:17:1: E303 too many blank lines (3)
./Bio/SwissProt/KeyWList.py:24:1: E303 too many blank lines (3)
./Bio/NMR/xpktools.py:9:1: E303 too many blank lines (3)
./Bio/SeqUtils/CodonUsage.py:10:1: E303 too many blank lines (3)
./Bio/Align/Applications/_Dialign.py:11:1: E303 too many blank lines (3)
./Bio/Align/Applications/_MSAProbs.py:11:1: E303 too many blank lines (3)
./Bio/Align/Applications/_Prank.py:11:1: E303 too many blank lines (3)
./Bio/Align/Applications/_Probcons.py:11:1: E303 too many blank lines (3)
./Bio/PDB/AbstractPropertyMap.py:12:1: E303 too many blank lines (3)
./Bio/SubsMat/__init__.py:115:1: E303 too many blank lines (3)
./Bio/HMM/Utilities.py:16:1: E303 too many blank lines (3)
```

You can run flake8 locally as described in the CONTRIBUTING.rst file, but basically many of the places where you removed an import line need a blank line removed too.

This won't take too long by hand, if there were more I would recommend trying autopep8 which says it has an E303 fixer: https://github.com/hhatto/autopep8

**Comment by Dsujan** [comment]
@peterjc I have fixed the issues now. Please check. 
And thanks for the autopep8 heads up.

**Comment by peterjc** [comment]
Looks good, thank you. You can add yourself to the NEWS file next time if you want?

**Comment by Dsujan** [comment]
I have added myself in the NEWS file.
Thank you for the reminder.

**Pull request merged**
