### PR TITLE
Dual license most of Bio.PDB

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses in part issue #989

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

For dual licensing the remaining Python code under ``Bio/PDB/``, I believe we still need consent from the following (apologies if you have agreed and I've missed it) - agreement to the mailing list, here, or on #989 would be appreciated - thank you:

 - [ ] @andrewguy (sorry, was initially missing the y)
 - [ ] @asford
 - [x] @biojerm (below)
 - [x] @fcaramia https://github.com/biopython/biopython/pull/576#issuecomment-521465740
 - [x] @hectormartinezdev (below)
 - [ ] @kokonech

### CODE REVIEW

**Comment by peterjc** [comment]
I think dual licensing the remaining PDB test file, ``Tests/test_PDB.py``, requires agreement from just @andrewguy

**Comment by hectormartinezdev** [comment]
Hey! Agreed 👍

**Comment by biojerm** [comment]
Hi Peter,

I agree.  I am @biojerm


Jeremy

**Comment by peterjc** [comment]
We would be ready for ``Bio/PDB/PDBList.py`` according to the git authors, but as per the comments in the file we need check with Wiktoria Karwicka: https://github.com/biopython/biopython/pull/943#issuecomment-521603801

**Comment by peterjc** [comment]
@etal @JoaoRodrigues @lennax Are any of you able to look over the dual licensing here vs the git log and any copyright lines, in case I have missed someone? Thanks!

**Comment by andrewguy** [comment]
Hi Peter, I agree. Sorry I missed this initially. 

Thanks,
Andrew

**Comment by peterjc** [comment]
Thanks all, I'm going to apply this now (thanks Eric for the review), and then come back to the extra files we can dual license with the additional recent agreements from Andrew & Alex.

**Pull request merged**
