### PR TITLE
Use Bio.Align.substitution_matrices instead of Bio.SubsMat in TreeConstruction

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request addresses issue #2917 by replacing `Bio.SubsMat` in `Bio/Phylo/TreeConstruction.py` by `Bio.Align.substitution_matrices`.

This could be pushed further by using the same matrices also in `ParsimonyScorer`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Does this change need a small NEWS entry?

**Comment by mdehoon** [comment]
@peterjc  From a user's perspective, very little changes.

**Comment by peterjc** [comment]
OK.

**Comment by mdehoon** [comment]
@lijax , @etal  Any objections?

**Comment by mdehoon** [comment]
Thank you.

**Pull request merged**
