### PR TITLE
Deprecate Bio.LogisticRegression & Bio.kNN modules

### PR DESCRIPTION
**Pull request by peterjc**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Suggested in discussion on #907 since dropping this chapter from the tutorial will make the pandoc conversion from LaTeX to RST slightly easier. This module has been in maintainance mode for over 20 years, and most potential users would be better of trying something more extensive like scikit-learn for machine learning.

### CODE REVIEW

**Comment by peterjc** [comment]
Ah, the chapter also covered ``Bio.kNN`` as well. Perhaps the same argument applies?

**Comment by peterjc** [comment]
The chapter also mentions the following, but with stubs only:

* ``Bio.NaiveBayes``
* ``Bio.MaxEntropy``
* ``Bio.MarkovModel`` and/or ``Bio.HMM.MarkovModel``

**Review by mdehoon — APPROVED** [review]

**Comment by mdehoon** [comment]
> Ah, the chapter also covered Bio.kNN as well. Perhaps the same argument applies?

Yes I think so.

**Comment by peterjc** [comment]
OK, I'll extend this to deprecate ``Bio.kNN`` as well.

**Pull request merged**
