### PR TITLE
map between pairwise alignments

### PR DESCRIPTION
**Pull request by mdehoon**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Add a `map` method to the `PairwiseAlignment` object in `Bo.Align` that maps one alignment to another. Specifically, if `alignment1` is the alignment of query1 to target1, and `alignment2` is the alignment of query2 to target2, where query1 and target2 are the same, then `alignment1.map(alignment2)` returns the pairwise alignment of query2 to target1.

### CODE REVIEW

**Comment by peterjc** [comment]
There's a bunch to fiddly stuff from black - and flake8 seems to have spotted some real issues on top of PEP257 docstring complaints:

```
Bio/Align/__init__.py:1713:55: F821 undefined name 'qEnd'
Bio/Align/__init__.py:1716:50: F821 undefined name 'qEnd'
```

I also see D402 false positives but I though I just fixed them in #3542

**Comment by mdehoon** [comment]
> I don't understand why you might want to be able to discard the sequence though.

In the future, we may want to load the pairwise alignment from a `bed` file. Then we won't know the sequence to begin with. Since we don't have that capability yet, I am using this contrived example instead for now.

**Comment by peterjc** [comment]
I think these on circleci are fixed on the master, but prior to when this branch was started:

```
Bio/SeqFeature.py:1676:1: D402 First line should not be the function's "signature"
Bio/SeqFeature.py:1812:1: D402 First line should not be the function's "signature"
Bio/SeqFeature.py:1930:1: D402 First line should not be the function's "signature"
Bio/SeqFeature.py:1995:1: D402 First line should not be the function's "signature"
Bio/SeqFeature.py:2071:1: D402 First line should not be the function's "signature"
Bio/Phylo/BaseTree.py:465:1: D402 First line should not be the function's "signature"
Bio/GenBank/__init__.py:726:1: D402 First line should not be the function's "signature"
Bio/GenBank/__init__.py:1496:1: D402 First line should not be the function's "signature"
```

If so, a "git rebase origin/master" might be one simple thing to try.

**Comment by peterjc** [comment]
Also black still wants to move things about, including the new ``# noqa: W291`` comments which would need moving up a line to be on the string not the closing bracket.

**Comment by mdehoon** [comment]
@peterjc Should we worry about the CircleCI failure?

**Comment by peterjc** [comment]
My guess is that CircleCI is testing your branch stand alone, not your branch as it would be once merged to the current master (like TravisCI definitely does). There may be a configuration setting there...

I am almost certain that that the CircleCI D402 false positives will be fine once merged, as it working on the master branch (see #3542, something changed in flake8 and/or the plugin about which line docstring violations were reported against, and thus where any ``# noqa`` tag needed to be).

So I think we can go ahead and do a squash-and-merge of this work.

**Comment by mdehoon** [comment]
@peterjc  OK thanks, I'll proceed and merge this then.

**Comment by peterjc** [comment]
Yes, all green from the merged commit 👍

**Pull request merged**
