### PR TITLE
Fix issue #1126

### PR DESCRIPTION
**Pull request by mkorycinski**
Changes required to fix issue #1126 and tests as described in the issue topic.

### CODE REVIEW

**Comment by bow** [comment]
I will close the PR since the changes have been cherry-picked into master (+ I've added some notes in b35abd1). Thanks again for the fix and I hope the parser works fine for you now :).

**Comment by peterjc** [comment]
(Apologies if @bow asked and I missed this)

@mkorycinski Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

**Comment by mkorycinski** [comment]
@peterjc No problem. I am fine with both. ;-)

**Comment by bow** [comment]
Ah, I have not @peterjc ~ thanks for the reminder. I should keep reminding myself we have not fully switched licenses :).

**Comment by peterjc** [comment]
@Bow: No problem - I'll be asking each module owner to try to check all the contributors to that part of Biopython have agreed in order to move this along for the next release. Thanks

@mkorycinski Thank you

**Pull request closed without merging**
