### PR TITLE
Close connections to SQLite files before deleting them

### LINKED ISSUE #4356: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
Recently (11 July 2023) the Windows 64 tests on AppVeyor have stopped working, last good build:

https://ci.appveyor.com/project/biopython/biopython/builds/47519949 - last good build

```
python -c "import sys; print(sys.version)"
3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
```

https://ci.appveyor.com/project/biopython/biopython/builds/47523213 - new failure

```
python -c "import sys; print(sys.version)"
3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
```

This is likely due to the jump from Python 3.10 to 3.11, or perhaps from on of the Python dependencies.

(There were some unrelated failures in between, see 2287f70c0c54b893900442abd861735ac01c35bd for that)

```
======================================================================
ERROR: test_duplicate_id_load (common_BioSQL.DupLoadTest.test_duplicate_id_load)
Make sure can't import records with same ID (in one go).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1011, in tearDown
    destroy_database()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 234, in destroy_database
    os.remove(TESTDB)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpnz4q3g65_BioSQL.db'
======================================================================
ERROR: test_duplicate_load (common_BioSQL.DupLoadTest.test_duplicate_load)
Make sure can't import a single record twice (in one go).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1011, in tearDown
    destroy_database()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 234, in destroy_database
    os.remove(TESTDB)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpveckyte6_BioSQL.db'
======================================================================
ERROR: test_duplicate_load2 (common_BioSQL.DupLoadTest.test_duplicate_load2)
Make sure can't import a single record twice (in steps).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1011, in tearDown
    destroy_database()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 234, in destroy_database
    os.remove(TESTDB)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp5tuc5mu0_BioSQL.db'
======================================================================
ERROR: test_reload (common_BioSQL.InDepthLoadTest.test_reload)
Make sure can't reimport existing records.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1250, in tearDown
    destroy_database()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 234, in destroy_database
    os.remove(TESTDB)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp2gbx7v6e_BioSQL.db'
======================================================================
ERROR: test_bundle_without_target (test_MafIO_index.NewIndexTest.test_bundle_without_target)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpbkl11bxu\\database.sqlite3'
======================================================================
ERROR: test_good_big (test_MafIO_index.NewIndexTest.test_good_big)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp1_7klvpu\\database.sqlite3'
======================================================================
ERROR: test_good_small (test_MafIO_index.NewIndexTest.test_good_small)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpb36xwzlf\\database.sqlite3'
======================================================================
ERROR: test_length_coords_mismatch (test_MafIO_index.NewIndexTest.test_length_coords_mismatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line [759](https://ci.appveyor.com/project/biopython/biopython/builds/47525001/job/42gbx250hgu75xk1#L759), in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpu4n11kx8\\database.sqlite3'
----------------------------------------------------------------------
```

i.e. Two classes of failure, removing a temporarly SQLite database in the BioSQL tests, and removing a temporary MAF index.

I've seen similar issues before on Windows where you cannot delete a file which still has an open handle (which is allowed on macOS and Linux). We are likely missing a couple of explicit file handle closes - something which made a lot of work for us with PyPy given its different GC model.

If this can easily be reproduced on a contributor or developer's Windows machine (i.e. not just using AppVeyor), that would be ideal for debugging this...

### PR DESCRIPTION
**Pull request by peterjc**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Second attempt to close #4356 after #4363 didn't work out.

### CODE REVIEW

**Comment by peterjc** [comment]
That is progress, new output:

```
======================================================================
ERROR: test_reload (common_BioSQL.InDepthLoadTest.test_reload)
Make sure can't reimport existing records.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 1250, in tearDown
    destroy_database()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 234, in destroy_database
    os.remove(TESTDB)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpwu5ym8qf_BioSQL.db'
======================================================================
ERROR: test_bundle_without_target (test_MafIO_index.NewIndexTest.test_bundle_without_target)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpbnmcetpc\\database.sqlite3'
======================================================================
ERROR: test_good_big (test_MafIO_index.NewIndexTest.test_good_big)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp4go7hi96\\database.sqlite3'
======================================================================
ERROR: test_good_small (test_MafIO_index.NewIndexTest.test_good_small)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpfmjws8gv\\database.sqlite3'
======================================================================
ERROR: test_length_coords_mismatch (test_MafIO_index.NewIndexTest.test_length_coords_mismatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp4irkn8oq\\database.sqlite3'
----------------------------------------------------------------------
```

i.e. It solved the three BioSQL errors:

* ERROR: test_duplicate_id_load (common_BioSQL.DupLoadTest.test_duplicate_id_load)
  Make sure can't import records with same ID (in one go).
* ERROR: test_duplicate_load (common_BioSQL.DupLoadTest.test_duplicate_load)
  Make sure can't import a single record twice (in one go).
* ERROR: test_duplicate_load2 (common_BioSQL.DupLoadTest.test_duplicate_load2)
  Make sure can't import a single record twice (in steps).

Sadly not any of the MafIO errors where #4363 made partial progress.

**Comment by peterjc** [comment]
Getting there, just two left now:

```
======================================================================
ERROR: test_good_big (test_MafIO_index.NewIndexTest.test_good_big)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpl2o4bl65\\database.sqlite3'
======================================================================
ERROR: test_good_small (test_MafIO_index.NewIndexTest.test_good_small)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_MafIO_index.py", line 155, in tearDown
    shutil.rmtree(self.tmpdir)
  File "C:\Py\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Py\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp11kkn91r\\database.sqlite3'
----------------------------------------------------------------------
```

**Comment by peterjc** [comment]
Bah, flake8-bugbear B033 - see pull request #4364

**Comment by peterjc** [comment]
Looks like I will need the explicit close method trialled in #4363 as well (to avoid using the private attribute as in this proof of pricniple).

**Comment by peterjc** [comment]
@MarkusPiotrowski I'm happy with this now, took more remote AppVeyor runs that I hoped to debug this but got there :)

**Comment by MarkusPiotrowski** [comment]
Looks good to me. Sorry that I couldn't help, but I'm stuck on Python 3.8 on my computer at the moment.

**Comment by peterjc** [comment]
Thank you. It probably would have been easier if I'd setup Python under Windows locally...

**Pull request merged**
