### PR TITLE
BSD dual license Bio.Phylo

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses in part issue #898.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

@etal your eyes on this for would be welcome in case I've missed a contributor, also for the PAML part @brandoninvergo.

The one file this has not yet dual-licensed is ``Bio/Phylo/PAML/chi2.py`` which is based on the PAML source itself (which as far as I can see has not stated license) with permission of the author. Depending exactly what was agreed, this may be fine - could you check your old emails please Brandon:

https://github.com/biopython/biopython/blob/master/Bio/Phylo/PAML/chi2.py

See also #1610 which is about the licensing of another bit of chi2 code in Biopython...

### CODE REVIEW

**Comment by peterjc** [comment]
Would anyone else like to review this? @carlosp420 , @cbrueffer or @svalqui maybe since you've worked on this code?

**Comment by brandoninvergo** [comment]
Very sorry that I missed this.  I think the dual-licensing of chi2.py shouldn't be a problem.  Here's the relevant snippet of my conversation with Ziheng Yang:


> >  I feel that if I will be basing my code
> > heavily on yours, it would be prudent to ask your permission to do so
> > before writing a line of code. Are you ok with me doing this?
> > 

> Yes.
> 
> > I would
> > include information at the top of the source code indicating that it
> > is based on yours. Is there any other copyright/licensing info you
> > would want me to add?
> 
> No.
>

Anyway I think that, technically, since I translated the language it doesn't fall under his copyright anymore. Algorithms can't be copyrighted (and obviously there's no patent in this case). It's out of politeness that I acknowledge the source of the algorithm, but the actual code in chi2.py is mine.

**Comment by peterjc** [comment]
Thanks @brandoninvergo - with that contextual information, I agree - you are free to relicense your ``chi2.py`` code - I will update that file shortly 👍 

Do you have time to look at the contributors to ``Bio/Phylo/`` or at least ``Bio/Phlyo/PAML/`` to see if I missed anyone?

**Comment by brandoninvergo** [comment]
I've dug into `Bio.Phylo.PAML` and the only borderline non-trivial commit from someone other than me is 81a635501e0b4d10fe30d1d8c7516044e60fb068. The changes to `Bio/Phylo/PAML/_parse_codeml.py` are pretty minor (bugfix), but a decent chunk of code was added to `Tests/test_PAML_codeml.py`.  The copyright header for that file wasn't updated but I'm not sure if it qualifies by the usual standards that you apply.

@alpae isn't mentioned on #898 (unless there are more than two batches of usernames buried in the hidden comments) and so he hasn't explicitly approved.  But before that's necessary, we'll need to decide whether to update the `test_PAML_codeml.py` copyright statement.

**Comment by peterjc** [comment]
That was through - He did agree, link in the dual licensing commit b023e726773d2fbc52fc13799bf02b7954263b0b to the original pull request where he agreed https://github.com/biopython/biopython/pull/1012#issuecomment-263330364

In short, the list on #898 does not attempt to include all the recent contributors who have agreed on their pull requests (there is a prompt in the PR template to streamline this).

Thanks for doing that - anyone like to be the second opinion for the rest of Bio/Phylo/ please?

**Comment by peterjc** [comment]
Also, I'm defaulting to assuming any contribution has copyright (even if not named in the file header) and attempting to get consent. If you think any of the file headers need a couple more names added, it's not a problem to update them.

**Comment by brandoninvergo** [comment]
>He did agree, link in the dual licensing commit b023e72 to the original pull request where he agreed #1012 (comment)
>
>In short, the list on #898 does not attempt to include all the recent contributors who have agreed on their pull requests (there is a prompt in the PR template to streamline this).

Ah ok, that makes sense.  I was just using #898 for quick searches but I didn't think to check the commit sign-offs.  OK, in that case, I think `Bio.Phylo.PAML` is all set.

> Also, I'm defaulting to assuming any contribution has copyright (even if not named in the file header) and attempting to get consent. If you think any of the file headers need a couple more names added, it's not a problem to update them.

That's probably the wisest course, indeed.  I wasn't sure about the cutoff.

> Thanks for doing that - anyone like to be the second opinion for the rest of Bio/Phylo/ please?

I also checked the rest of `Bio.Phylo` just now and that looks good too (but another set of eyes would be good, of course).

**Comment by peterjc** [comment]
I've put the PAML commits into a separate PR, #2368 

Once that's merged I will rebase this PR for the rest of the Bio.Phylo code.

**Comment by svalqui** [comment]
run $ git shortlog --summary --numbered --email -- Bio/Phylo/ 
The only ones I can't find are:
- Jingping Li <jingpingli@gmail.com>
https://github.com/biopython/biopython/commits?author=Jingping

and
- unify <unify@example.org> ; I think this is an special account.

And not sure about contributions prior Github.

**Comment by peterjc** [comment]
Yes, unify was a dummy author for when I was running this automated code formatting tool:
https://github.com/myint/unify

I realise the pull request description does not mention that it did not currently cover ``Bio/Phylo/Applications/*.py`` - but good catch, for ``Bio/Phylo/Applications/_Raxml.py`` my semi-automated checks had spotted this - cross reference https://github.com/biopython/biopython/pull/73

Otherwise I think the ``Bio/Phylo/Applications/*.py`` files are OK - I'll do that in a follow up pull request.

So thank you for checking this 👍

**Pull request merged**
