### PR TITLE
Update README: add GitHub actions badge

### PR DESCRIPTION
**Pull request by vimalkvn**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Thank you.

To my eye, visually ever so slightly different in style? Or am I imagining things. There is probably a https://img.shields.io/ version which would match perfectly if you fancy checking that?

**Comment by vimalkvn** [comment]
Thanks. Yes, It had a darker background colour. I submitted it too quickly!
Replaced it with a shields.io version. Please check. 

I can also add missing logos for the other badges. Can I push those changes to this branch, or should that be a new PR?

**Comment by peterjc** [comment]
That's great ☑️ 

Another PR or updating this one is fine. If you're making changes, could you move the coverage badge *after* the testing ones too?

**Comment by vimalkvn** [comment]
Done.

**Comment by peterjc** [comment]
Thank you 🎉

**Pull request merged**
