### PR TITLE
Bio.SeqUtils.MeltingTemp: Correction of salt-correction methods for Tm_GC

### LINKED ISSUE #3842: formulas in biopython/Bio/SeqUtils/MeltingTemp.py  source code line 736-760 don't correspond to line 795-818
Hello,

I found formulas in the source code line 736-760 are as follows,

1. Tm = 69.3 + 0.41(%GC) - 650/N
   (Marmur & Doty 1962, J Mol Biol 5: 109-118; Chester & Marshak 1993),
   Anal Biochem 209: 284-290)

   **_No salt correction_**

2. Tm = 81.5 + 0.41(%GC) - 675/N - %mismatch
   'QuikChange' formula. Recommended (by the manufacturer) for the
   design of primers for QuikChange mutagenesis.

   **_No salt correction_**

3. Tm = 81.5 + 0.41(%GC) - 675/N + 16.6 x log[Na+]
   (Marmur & Doty 1962, J Mol Biol 5: 109-118; Schildkraut & Lifson
   1965, Biopolymers 3: 195-208)

   **_salt correction method 1_**

4. Tm = 81.5 + 0.41(%GC) - 500/N + 16.6 x log([Na+]/(1.0 + 0.7 x[Na+])) - %mismatch
   (Wetmur 1991, Crit Rev Biochem Mol Biol 126: 227-259). This is the
   standard formula in approximative mode of MELTING 4.3.

   **_salt correction method 2_**

5. Tm = 78 + 0.7(%GC) - 500/N + 16.6 x log([Na+]/(1.0 + 0.7 x [Na+])) - %mismatch
   (Wetmur 1991, Crit Rev Biochem Mol Biol 126: 227-259). For RNA.

   **_salt correction method 2_**

6. Tm = 67 + 0.8(%GC) - 500/N + 16.6 x log([Na+]/(1.0 + 0.7 x [Na+])) - %mismatch
   (Wetmur 1991, Crit Rev Biochem Mol Biol 126: 227-259). For RNA/DNA
   hybrids.

   **_salt correction method 2_**

7. Tm = 81.5 + 0.41(%GC) - 600/N + 16.6 x log[Na+]
   Used by Primer3Plus to calculate the product Tm. Default set.

   **_salt correction method 1_**

8. Tm = 77.1 + 0.41(%GC) - 528/N + 11.7 x log[Na+]
   (von Ahsen et al. 2001, Clin Chem 47: 1956-1961). Recommended 'as a
   tradeoff between accuracy and ease of use'.
   
   **_salt correction method 4_**

While formulas in the source code line 795-818 don't correspond to the above one,

```
        if valueset == 1:
            A, B, C, D = (69.3, 0.41, 650, 1)
            saltcorr = 0
        if valueset == 2:
            A, B, C, D = (81.5, 0.41, 675, 1)
            saltcorr = 0
        if valueset == 3:
            A, B, C, D = (81.5, 0.41, 675, 1)
            saltcorr = 2
        if valueset == 4:
            A, B, C, D = (81.5, 0.41, 500, 1)
            saltcorr = 3
        if valueset == 5:
            A, B, C, D = (78.0, 0.7, 500, 1)
            saltcorr = 3
        if valueset == 6:
            A, B, C, D = (67.0, 0.8, 500, 1)
            saltcorr = 3
        if valueset == 7:
            A, B, C, D = (81.5, 0.41, 600, 1)
            saltcorr = 2
        if valueset == 8:
            A, B, C, D = (77.1, 0.41, 528, 1)
            saltcorr = 4
```

should the `saltcorr` parameters be like this?

```
        if valueset == 1:
            A, B, C, D = (69.3, 0.41, 650, 1)
            saltcorr = 0
        if valueset == 2:
            A, B, C, D = (81.5, 0.41, 675, 1)
            saltcorr = 0
        if valueset == 3:
            A, B, C, D = (81.5, 0.41, 675, 1)
            saltcorr = 1
        if valueset == 4:
            A, B, C, D = (81.5, 0.41, 500, 1)
            saltcorr = 2
        if valueset == 5:
            A, B, C, D = (78.0, 0.7, 500, 1)
            saltcorr = 2
        if valueset == 6:
            A, B, C, D = (67.0, 0.8, 500, 1)
            saltcorr = 2
        if valueset == 7:
            A, B, C, D = (81.5, 0.41, 600, 1)
            saltcorr = 1
        if valueset == 8:
            A, B, C, D = (77.1, 0.41, 528, 1)
            saltcorr = 4
```

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3842
There were some wrong assignments of salt-correction methods to some `valuesets` in `Tm_GC` which have been corrected now.

### CODE REVIEW

**Comment by peterjc** [comment]
Lots of names - did you get several opinions on this to be sure?

**Comment by MarkusPiotrowski** [comment]
@peterjc Which names do you mean? The authors for the different salt-corrections and `valuesets`? At the time of writing the module (9 years ago) I read several papers and reviews and also compared to other Tm resources (e.g. Primer3). 

I think the important thing for this PR is that the documentation (where the formulas are given precisely) fits with the code.

Besides that, I'm quite confident about the references for the salt-correction methods and also about the `valuesets` in `Tm_GC`.

**Comment by peterjc** [comment]
The NEWS.rst file entry gets several names for the next release, and it wasn't clear to me why.

**Comment by peterjc** [comment]
Sorry - I see it now, you just fixed the name sorting.

**Comment by MarkusPiotrowski** [comment]
I just added my name and sorted the others alphabetically.

**Review by peterjc — APPROVED** [review]

**Pull request merged**
