### PR TITLE
deprecating Bio.FSSP

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request addresses deprecates Bio.FSSP, as the FSSP database doesn't seem to exist any more.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by widdowquinn** [comment]
I suppose that while this [FTP site](ftp://ftp.ebi.ac.uk/pub/databases/fssp/) still exists, there's *technically* an FSSP database, but it's clearly not current. I have no objections to deprecation - has anyone seen FSSP used 'in the wild' for a while?

**Comment by peterjc** [comment]
Shall we do a curtesy email to the mailing list, just in case?

**Comment by mdehoon** [comment]
> Shall we do a curtesy email to the mailing list, just in case?

Yes we could, but personally I am trying to keep a low profile on the mailing list.

**Comment by JoaoRodrigues** [comment]
I know this is not a metric, but looking at which articles cited FSSP (or
the last available description paper) it seems like it's pretty much dead.
I'd vote to put a deprecation warning and then let people bring it up if
they are against it.

**Pull request merged**
