### PR TITLE
Dual license Bio.SeqUtils

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses part of issue #898

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Still need to get consent from all the authors of ``Bio/SeqUtils/__init__.py``, originally called ``Bio/sequtils.py`` and created here: https://github.com/biopython/biopython/commit/528479932aabc941c0437094edff27765890fcf4

**Comment by peterjc** [comment]
@chapmanb or @MarkusPiotrowski - would one of you like to review this change, as you've both contributed to most of these files?

**Comment by chapmanb** [comment]
Peter -- thanks for doing this. All looks great by me +1 for merging.

**Comment by MarkusPiotrowski** [comment]
Looks good!

**Comment by peterjc** [comment]
Thank you both, merging...

**Pull request merged**
