### PR TITLE
Introducing Biopython Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Biopython Guru](https://gurubase.io/g/biopython) to Gurubase. Biopython Guru uses the data from this repo and data from the [docs](https://biopython.org/docs/latest/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Biopython Guru", which highlights that Biopython now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Biopython Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by kursataktas** [comment]
Hey everyone, have you had a chance to check this out?

**Comment by rob-miller** [comment]
I've done some playing with it.  For a certain class of queries it does
point in the right direction.  It's like a better (easier, gentler)
starting point than walking through the table of contents of the manual or
tutorial; it didn't provide great answers on some of some of my research
questions but that shouldn't be expected.

For my Biopython code, it is more up to date, accurate and therefore useful
than Chat-GPT 4o.  Overall it seems like a useful thing to have if people
know about it, but it has to be clear that it is only a guide through the
documentation and not a scientific colleague to discuss research questions
with.

I wouldn't do away with it.  How often would it be updated to reflect new
facilities in new Biopython releases?

**Comment by kursataktas** [comment]
Thanks for the review, @rob-miller! I’m glad to hear you like it.

We can allow Biopython maintainers to manage Biopython Guru via a web panel, where you’ll be able to edit or refresh data sources. We’re planning to release it next week. If you’d like, I’d be happy to update this thread once it’s available.

**Comment by kursataktas** [comment]
Hey everyone,

Since I haven’t received any further feedback, I have disabled the Biopython Guru on Gurubase. Please let me know if you think otherwise.

**Pull request closed without merging**
