### PR TITLE
Alignment addition

### PR DESCRIPTION
**Pull request by mdehoon**
Adding addition (`__add__`) to the `Alignment` class.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
This may cause confusion - your addition is column wise, but the existing MSA class addition is row wise.

**Comment by mdehoon** [comment]
The row-wise addition in the MSA class never made much sense to me. It's easy to get wrong alignments that way.
For example:
```
A-BCD
AABCD
```
`+`
```
ABC-D
ABCCD
```
`=`
```
A-BCD
AABCD
ABC-D
ABCCD
```

**Comment by peterjc** [comment]
False alarm, sorry - my memory at fault, quoting the MSA ``__add__`` docstring:

> If you have two multiple sequence alignments (MSAs), there are two ways to think
> about adding them - by row or by column. Using the extend method adds by row.
> Using the addition operator adds by column. For example,

Does it make sense to offer an extend/append method here?

**Comment by mdehoon** [comment]
> Does it make sense to offer an extend/append method here?

How? It will run into the same problem as my example above.

**Comment by peterjc** [comment]
I'm pretty sure I have used row based addition with MSA, but probably less often. I can't currently come up with a compelling usecase either. Let's wait and see if there is user demand.

**Pull request merged**
