### PR TITLE
Adopt the OBF Code of Conduct

### PR DESCRIPTION
**Pull request by peterjc**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

See:
* https://mailman.open-bio.org/pipermail/biopython/2019-November/016730.html
* https://mailman.open-bio.org/pipermail/biopython/2021-May/016869.html
* https://www.open-bio.org/2021/05/12/request-for-comments-on-coc-draft/
* https://github.com/OBF/obf-docs/pull/78
* https://www.open-bio.org/2022/01/27/approved-by-obf-membership-vote/

Note that to match the other Biopython top level text files I have used ``CODE_OF_CONDUCT.rst`` rather than ``CODE_OF_CONDUCT.md`` as suggested by GitHub: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

### CODE REVIEW

**Comment by peterjc** [comment]
Posted to the mailing list too:

https://mailman.open-bio.org/pipermail/biopython/2022-February/016930.html

**Comment by peterjc** [comment]
Cross reference https://github.com/bioperl/bioperl-live/pull/366 for BioPerl

**Comment by JoaoRodrigues** [comment]
Nothing to add to the text itself. My only comment would be that it would be nice to have the actual CoC file on our repository, but I see the advantages of having it centralized in the OBF repo and then linked to (updates, etc).

**Comment by peterjc** [comment]
Yes, having the text directly in the Biopython repository would be nice, but then we need a mechanism to keep it in sync with the central copy. A short human readable file directing readers to the central copy seemed best.

**Comment by peterjc** [comment]
There were no further comments on the mailing list either since https://mailman.open-bio.org/pipermail/biopython/2022-April/016934.html

**Pull request merged**
