### PR TITLE
enable flake8 testing of doctests in Bio, BioSQL; fix tests

### PR DESCRIPTION
**Pull request by rwst**
This pull request addresses issue #1899 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by rwst** [comment]
As I changed doctests fails may occur. If you don't like commenting out some lines then disabling flake8 doctest checks for specific directories is an alternative, as it existed in `BioSQL`.

**Comment by peterjc** [comment]
I see you fixed a few objects being used as default arguments too :)

**Comment by rwst** [comment]
Running tests via `python run_tests.py` results in lot of failures here but this would be a different ticket. As to this ticket, why not run flake8 in the automatic tests now that everything is fixed? I am not familiar with Travis/Appveyor though.

**Comment by peterjc** [comment]
The primary goal of this pull request and #1899 is to check the doctest examples in our docstrings are following our flake8 settings (i.e. PEP8 code style, spaces etc). That seems to be working nicely, thanks to your work.

A secondary goal of doctest examples is to be run as functional tests, which in Biopython we control via a list in ``run_tests.py`` - and historically only some of the ``Bio.PDB`` examples actually worked as real tests. It would be nice to have all of them run as real tests one day.

**Comment by peterjc** [comment]
Merged, thank you!

**Pull request merged**
