### PR TITLE
Simple counts() method for pairwise alignments

### LINKED ISSUE #3538: matches, mismatches and gaps from Bio.Align.PairwiseAlignment
Example use case creating an ``PairwiseAlignment`` instance as per the tutorial:

```pycon
>>> from Bio import Align
>>> aligner = Align.PairwiseAligner()
>>> seq1 = "GAACT"
>>> seq2 = "GAT"
>>> alignments = aligner.align(seq1, seq2)
>>> print(alignments.score)
3.0
>>> alignment = alignments[0]
>>> print(alignment)
GAACT
||--|
GA--T

```

I would like to be able to get easy access to the number of matches, mismatches, and gaps:

```pycon
>>> alignment.matches
3
>>> alignment.mismatches
0
>>> alignment.gaps
2
```

Workaround to get these numbers from the default string representation:

```
>>> middle_line = str(alignment).splitlines()[1]
>>> [middle_line.count(_) for _ in "|.-"]
[3, 0, 2]
```

This can be done more efficiently directly from ``alignment.path`` but that is non-trivial.

### PR DESCRIPTION
**Pull request by peterjc**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3538, while leaving scope for future enhancement.

### CODE REVIEW

**Review by mdehoon — COMMENTED** [review]
Just two suggestions:
- It may be better to return a `namedtuple` instead of a plain tuple, as future versions of this function may return additional numbers (e.g. number of gap opens, number of gap extensions, number of upper-vs-lower matches, etc.). Then users can use the `namedtuple` keywords to ensure that they are getting the number they think they are getting.
- For multiple (> 2) alignments, it is trivial to extend this function to include all pairs, as in
```python
for i, seq1 in alignment:
    for j, seq2 in alignment:
        if i==j: break
        for a, b in zip(seq1, seq2):
           if a == "-" or b == "-":
                gaps += 1
            elif a == b:
                identities += 1
            else:
                mismatches += 1
```

**Comment by peterjc** [comment]
Good idea on using a named tuple, although it is possible a future optional argument might change "identities" into something else like "close matches". Go with the current variable names?

Do you think the counts defined that way would be useful for n>2?

If so, should we exclude double counting - i.e. something equivalent to this:

```python
for i, seq1 in alignment:
    for j, seq2 in alignment:
        # Don't count seq1 vs seq2 and seq2 vs seq1
        if i >= j: break
        for a, b in zip(seq1, seq2):
           if a == "-" or b == "-":
                gaps += 1
            elif a == b:
                identities += 1
            else:
                mismatches += 1
```

**Comment by mdehoon** [comment]
> Good idea on using a named tuple, although it is possible a future optional argument might change "identities" into something else like "close matches". Go with the current variable names?

Yes; `identities` is not ambiguous.

> Do you think the counts defined that way would be useful for n>2?

I have seen this used before in Biopython, though I can't remember now where. In any case, it does not hurt to allow that possibility.

> If so, should we exclude double counting - i.e. something equivalent to this:

I believe that works out to be the same as breaking on `i == j`.

**Review by mdehoon — APPROVED** [review]

**Comment by peterjc** [comment]
Thank you - that looks better than the first iteration.

**Comment by mdehoon** [comment]
There is a bug in my code above:
```python
           if a == "-" or b == "-":
                gaps += 1
```
If both `a` and `b` are `"-"`, it is not a gap.
For example, for this alignment:
```
ACGT
A-GT
A-GT
```
there is no gap in the alignment between the second and third sequence.

**Pull request merged**
