### PR TITLE
Split biosql tests

### PR DESCRIPTION
**Pull request by ctSkennerton**
As discussed in #819, I've split out the `TaxonomyTest` class which requires the internet into a separate file.

### CODE REVIEW

**Comment by peterjc** [comment]
There seems to be too much duplicated code in ``Tests/common_BioSQL_online.py`` from ``Tests/common_BioSQL.py``, but right now I've not actually got this tested locally: It appears at some point my main build-slave stopped running the MySQL and PostgreSQL tests :(

This might be the incentive we need to get them running on TravisCI?

**Comment by peterjc** [comment]
Correction: The BioSQL tests *are* working on TravisCI, e.g. Python 2.7

```
test_BioSQL_MySQLdb ... ok
test_BioSQL_MySQLdb_online ... ok
test_BioSQL_mysql_connector ... ok
test_BioSQL_mysql_connector_online ... ok
test_BioSQL_psycopg2 ... /home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/BioSQL/BioSeqDatabase.py:123: BiopythonWarning: Your BioSQL PostgreSQL schema includes some rules currently required for bioperl-db but which may cause problems loading data using Biopython (see BioSQL Bug 2839). If you do not use BioPerl, please remove these rules. Biopython should cope with the rules present, but with a performance penalty when loading new records.
  "new records.", BiopythonWarning)
ok
test_BioSQL_psycopg2_online ... ok
test_BioSQL_sqlite3 ... ok
test_BioSQL_sqlite3_online ... ok
```

And Python 3.5, where MySQLdb is not available and we'd want to use mysql_connector anyway:

```
test_BioSQL_MySQLdb ... skipping. Install MySQLdb if you want to use mysql with BioSQL 
test_BioSQL_MySQLdb_online ... skipping. Install MySQLdb if you want to use mysql with BioSQL 
test_BioSQL_mysql_connector ... /home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/BioSQL/Loader.py:887: BiopythonWarning: order location operators are not fully supported
  % feature.location_operator, BiopythonWarning)
ok
test_BioSQL_mysql_connector_online ... ok
test_BioSQL_psycopg2 ... /home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/BioSQL/BioSeqDatabase.py:123: BiopythonWarning: Your BioSQL PostgreSQL schema includes some rules currently required for bioperl-db but which may cause problems loading data using Biopython (see BioSQL Bug 2839). If you do not use BioPerl, please remove these rules. Biopython should cope with the rules present, but with a performance penalty when loading new records.
  "new records.", BiopythonWarning)
/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/BioSQL/Loader.py:887: BiopythonWarning: order location operators are not fully supported
  % feature.location_operator, BiopythonWarning)
/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/BioSQL/BioSeqDatabase.py:123: BiopythonWarning: Your BioSQL PostgreSQL schema includes some rules currently required for bioperl-db but which may cause problems loading data using Biopython (see BioSQL Bug 2839). If you do not use BioPerl, please remove these rules. Biopython should cope with the rules present, but with a performance penalty when loading new records.
  "new records.", BiopythonWarning)
ok
test_BioSQL_psycopg2_online ... ok
test_BioSQL_sqlite3 ... /home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/BioSQL/Loader.py:887: BiopythonWarning: order location operators are not fully supported
  % feature.location_operator, BiopythonWarning)
ok
test_BioSQL_sqlite3_online ... ok
```

P.S. It would be nice to silence those warnings for the tests.

So its just the buildbot system which is currently not fully testing BioSQL...

**Comment by ctSkennerton** [comment]
Can you point me to an example of how to silence warnings during the tests? and I'll reduce the duplicated code

**Comment by peterjc** [comment]
Filtering Python warnings is something of a mess due to global rather than local filters. The best way is to wrap the line(s) of code expected to trigger a warning using a context manager (with statement), e.g.

``` python
with warnings.catch_warnings():
    # e.g. data loss
    warnings.simplefilter("ignore", BiopythonWarning)
    c = SeqIO.write(sequences=records, handle=handle, format=format)
```

Or:

``with warnings.catch_warnings():
    warnings.simplefilter('ignore', BiopythonExperimentalWarning)
    from Bio.SearchIO import parse
```

**Comment by ctSkennerton** [comment]
I removed much of the duplicate code however in doing so I also had to move the global variables into their own module as python doesn't seem to allow global variables to be seen across multiple modules. The new module, `BioSQL_settings`, is imported by all of the biosql test code.

**Comment by peterjc** [comment]
The BioSQL test settings are bit a pain - I've been looking at this while trying to get the BioSQL tests to run on one of the 64bit Linux buildbot slave machines.

Note that things like the database username and password could be different on different backends. Having them inside each Python script was fine in the short term, but has a number of drawbacks including:

- I implemented it with horrible global variables
- changing the settings for the local environment is a problem with git tracking
- duplicated MySQL settings for ``test_BioSQL_MySQLdb.py`` and ``test_BioSQL_mysql_connector.py`` (although we're going to deprecate and remove the former)

I have wondered about having a simple DB settings configuration file which the tests read from, possibly with defaults - or simply skip the test if the settings are missing? We'd be able to provide customised settings for each buildbot (see http://testing.open-bio.org/biopython/grid ), and for things like TravisCI.

**Comment by peterjc** [comment]
Part of the idea with my pull request #826 is to make your refactoring for these online tests easier (although it ends up meaning your most recent commits would not be needed). I can pull out the initial changes on top of #826 if you want me to.

**Comment by peterjc** [comment]
I forgot I wanted to include this in Biopython 1.67, but that's not the end of the world.

**Comment by ctSkennerton** [comment]
No matter, something always slips through the cracks 😃

**Comment by peterjc** [comment]
Superseded by #847

**Pull request closed without merging**
