### PR TITLE
Alignment str

### PR DESCRIPTION
**Pull request by mdehoon**
This PR changes the `__str__` method of `Alignment` object to produce human-readable alignments.

For example, instead of
```
   AAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGG
   |||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||
TTTAAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGGTTTTTT

```
which will wrap over several lines in a typical terminal window, it will now return
```
target            0 AAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAA
                  0 |||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--
query           216 AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--

target           60 CGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGG
                 60 ||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||-
query           178 CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG-

target          120 GAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAA
                120 -|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||-
query           139 -AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA-

target          180 ACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGG
                180 -||||--|||--||||--|||--||||--|||--||||--|||--||||--|||--||||
query           101 -CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG

target          240 GGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAAAACGGGGGAAA
                240 --|||--||||--|||--||||--|||--||||--|||--||||--|||--||||--|||
query            62 --AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA--CGGG--AAA

target          300 AACGGGGGAAAAACGGGGGAAAAACGGG 328
                300 --||||--|||--||||--|||--|||| 328
query            24 --CGGG--AAA--CGGG--AAA--CGGG   6

```

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@peterjc  In case you are interested.

**Comment by peterjc** [comment]
I take it the numbers on the middle row are specific to the matched region only?

Also CC @MarkusPiotrowski as this affects pairwise alignments as well as the MSA, right?

**Comment by peterjc** [comment]
I may be missing this in the GitHub diff view, but do any of the docstrings describe the new layout and the coordinate convention used (i.e. it is Python counting, isn't it?).

This also seems worth mentioning in the NEWS file as well.

**Comment by mdehoon** [comment]
> I take it the numbers on the middle row are specific to the matched region only?

Those are just the column numbers of the alignment (i.e. numbered sequentially), which are useful if someone wants to extract a subalignment.

**Comment by mdehoon** [comment]
> Also CC @MarkusPiotrowski as this affects pairwise alignments as well as the MSA, right?

It does not affect `MultipleSeqAlignment` objects, as that is an independent class used by `Bio.AlignIO`.
It does not affect `Bio.pairwise2` output either.

**Comment by peterjc** [comment]
Thanks - good to be clear that the ``MultipleSeqAlignment`` used by ``Bio.AlignIO`` does not change.

It is just ``Bio.Align.Alignment`` (and the deprecated subclass ``Bio.Align.PairwiseAlignment``) changes, and thus the pairwise alignment output display from ``Bio.Align``. I was wondering how it compared to the (legacy) alignment display in ``Bio.pairwise2`` for example, thus wanting @MarkusPiotrowski to comment.

I do think it would help to make the meaning of those numbers a little more explicit in the docstring.

**Comment by peterjc** [comment]
That new docstring helps 👍

**Comment by mdehoon** [comment]
@MarkusPiotrowski  Any objections?

**Pull request merged**
