### PR TITLE
Fix paml yn00 ng86 parsing

### PR DESCRIPTION
**Pull request by brandoninvergo**
This pull request addresses issue #1290.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good - waiting for tests.

P.S. If you want your avatar to show up on these commits, you'd need to tell GitHub about this other email address as an alias.

**Comment by peterjc** [comment]
Style checks - a relatively recent thing known to pick up on regular expressions:

```
flake8 Bio/
Bio/Phylo/PAML/_parse_yn00.py:34:40: W605 invalid escape sequence '\s'
Bio/Phylo/PAML/_parse_yn00.py:34:47: W605 invalid escape sequence '\s'
Bio/Phylo/PAML/_parse_yn00.py:34:52: W605 invalid escape sequence '\d'
Bio/Phylo/PAML/_parse_yn00.py:34:55: W605 invalid escape sequence '\.'
Bio/Phylo/PAML/_parse_yn00.py:34:57: W605 invalid escape sequence '\d'
Bio/Phylo/PAML/_parse_yn00.py:34:64: W605 invalid escape sequence '\s'
Bio/Phylo/PAML/_parse_yn00.py:34:76: W605 invalid escape sequence '\s'
Bio/Phylo/PAML/_parse_yn00.py:34:79: W605 invalid escape sequence '\('
Bio/Phylo/PAML/_parse_yn00.py:39:45: W605 invalid escape sequence '\d'
Bio/Phylo/PAML/_parse_yn00.py:39:48: W605 invalid escape sequence '\.'
Bio/Phylo/PAML/_parse_yn00.py:39:50: W605 invalid escape sequence '\d'
```

See PR #1847 which fixed the existing cases, the same approach should work here.

**Comment by brandoninvergo** [comment]
Ah right. I always do that these days but I guess this code was written before I learned about that.

**Comment by brandoninvergo** [comment]
Sorry, my fault. I accidentally started hacking without merging upstream first. I restarted on a new branch and then cherry picked commits from the dirty branch. I didn't notice the lack of a raw-string marker when doing so.

**Comment by peterjc** [comment]
Easily done, and thankfully no major changes to deal with from the conflict. The style check has passed now.

**Comment by peterjc** [comment]
Thank you!

**Pull request merged**
