### PR TITLE
Build API documentation with Sphinx via TravisCI/Tox [WIP]

### PR DESCRIPTION
**Pull request by peterjc**
This pull request would in part address issue #906, the goal of replacing epydoc for our API documentation.

Note in addition to Sphinx specific changes, there are some code changes in ``Bio.Restriction`` and ``Bio.Graphics.GenomeDiagram`` in order to avoid an exception and include the classes in the public documentation.

Still needs work, e.g. dealing with special methods like ``__init__`` which we probably want to be included by default.

### CODE REVIEW

**Comment by peterjc** [comment]
These options seem to improve the output, an in particular document ``__init__`` explicitly:

```
.. automodule:: Bio.SeqRecord
    :members:
    :undoc-members:
    :show-inheritance:
    :special-members:
    :exclude-members: __dict__,__weakref__
    :member-order: bysource
```

Including ``:inherited-members:`` sadly appears to include everything from the base Python ``object`` class which introduces a lot of noise.

**Comment by peterjc** [comment]
I hinted at this in a comment in the last commit referencing my Sphinx pull request https://github.com/sphinx-doc/sphinx/pull/4076 which adds a new Sphinx ``conf.py`` setting ``autodoc_exclude_members`` which will hopefully be accepted.

Running this with my branch of Sphinx, we can manage the special settings for ``automodule`` without processing the RST files produced by ``sphinx-apidoc`` to include the special methods while excluding a few boring cases like ``__dict__``, ``__weakref__`` and ``__module__``.

**Comment by peterjc** [comment]
TODO: Resolve all the scary Sphinx warnings ``Unexpected section title.``

**Comment by peterjc** [comment]
Cross reference https://github.com/sphinx-doc/sphinx/issues/4170 for the ``__all__`` and ``__version__`` bug.

**Comment by peterjc** [comment]
Note to self: Sphinx, apidoc, and readthedocs

I think we need to run ``sphinx-apidoc`` as part of building our API documentation, regenerating the module-specific ``*.rst`` files fresh (i.e. not storing them in our source code repository).

However, out of the box, readthedocs seems to focus on the running sphinx with the ``conf.py`` file, and assumes all the ``*.rst`` files already exist. There is an open issue on this:

https://github.com/rtfd/readthedocs.org/issues/1139

That issue includes a workaround where they modify ``conf.py`` to invoke building the API ``*.rst`` files, also documented at http://ggeditor.readthedocs.io/en/latest/ApiDoc.html using:

```python
import sys, os

# append the next line to conf.py, should change "backend" to your module name
sys.path.insert(0, os.path.join(os.path.dirname(__file__),'..','backend'))

# ensure the autodoc and napoleon are in the extensions
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon']

def run_apidoc(_):
    from sphinx.apidoc import main
    parentFolder = os.path.join(os.path.dirname(__file__), '..')
    cur_dir = os.path.abspath(os.path.dirname(__file__))
    sys.path.append(parentFolder)
    # change "backend" to your module name
    module = os.path.join(parentFolder,'backend')
    output_path = os.path.join(cur_dir, 'api')
    main(['-e','-f','-o', output_path, module])

def setup(app):
    # overrides for wide tables in RTD theme
    app.add_stylesheet('theme_overrides.css')
    # trigger the run_apidoc
    app.connect('builder-inited', run_apidoc)
```

**Comment by grihabor** [comment]
Why not just build with readthedocs? Does it hit the time limit?

**Comment by peterjc** [comment]
I'm going to remove the ``Bio.Restriction`` changes (since something equivalent has been merged), and rebase this...

**Comment by peterjc** [comment]
Running locally without ``-W`` now getting five TOC warnings:

```
/Users/xxx/repositories/biopython/Doc/api/Bio.Align.Applications.rst: WARNING: document isn't included in any toctree
/Users/xxx/repositories/biopython/Doc/api/Bio.Graphics.GenomeDiagram.rst: WARNING: document isn't included in any toctree
/Users/xx/repositories/biopython/Doc/api/Bio.Phylo.Applications.rst: WARNING: document isn't included in any toctree
/Users/xx/repositories/biopython/Doc/api/Bio.Sequencing.Applications.rst: WARNING: document isn't included in any toctree
/Users/xx/repositories/biopython/Doc/api/Bio.motifs.applications.rst: WARNING: document isn't included in any toctree
```

**Comment by peterjc** [comment]
Given https://github.com/sphinx-doc/sphinx/pull/5215 was merged and is part of Sphinx 1.8.0, updating the branch (and rebasing)...

**Comment by peterjc** [comment]
Closing in favour of #1803 (which clears up the history) now that this seems to be working.

**Pull request closed without merging**
