### PR TITLE
Handle changes in Bio.SeqIO.QualityIO

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses some of the work from @mdehoon in #2649, avoiding anything which changed the test files or their interpretation. I also merged a few of the linked commits.

Assuming the tests are all fine (they were locally), and the revised commits and comments are fine with you, I suggest we rebase-and-merge this?

And then I can rebase #2649, and we can resume discussing the less straightforward changes?

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
I'll try to run a quick benchmark before/after this change, just in case.

**Comment by peterjc** [comment]
So far this week I have been running online BLAST testing in the background instead (see other issue).

**Comment by peterjc** [comment]
Running some simple FASTQ parsing benchmarking now...

**Comment by peterjc** [comment]
Any performance change is at the noise level from testing FASTQ parsing time on my desktop, so merging.

**Comment by mdehoon** [comment]
Thanks!

**Pull request merged**
