### PR TITLE
Remove _is_int_or_long imports and defination.

### PR DESCRIPTION
**Pull request by Dsujan**
This pull request addresses issue #2420 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
It looks like my instructions about how to start from a clean branch didn't work. Sadly git is complicated and there is definitely more than one way to do things (unlike the Python approach to things where there should be one clearly preferred way).

But not to worry, I'll probably just do a squash-and-merge.

**Comment by peterjc** [comment]
Done - thank you!

**Comment by Dsujan** [comment]
I did follow your instructions to sync the fork and start clean but my remote master (fork) always gave *some* commits ahead of biopython:master though it was just just synced. Yes, GIT is complicated!

**Comment by peterjc** [comment]
Ah, looking at https://github.com/Dsujan/biopython/tree/master it has diverged from https://github.com/biopython/biopython/tree/master

The quick and dirty fix: Assuming you have no open pull requests or branches of work, delete your fork on GitHub, and re-fork. Delete your local repository, and re-clone.

The proper fix: Reset https://github.com/Dsujan/biopython/tree/master and your local master branch to match https://github.com/biopython/biopython/tree/master - I have often had to do this myself. There's more than one way to do this (which is confusing if looking for help online), my method:

```
git checkout master
git checkout -b old_master  # just in case we want these changes... and can't delete current branch
git branch -D master # delete the diverged branch
git checkout -t upstream/master # track the upstream master
git push dusjan master --force # rewrite the master on your fork (one of the few cases you ever need force)
```

I am assuming you have your fork as the remote name ``dusjan`` (it might be ``origin``) and the official repository as ``upsteam`` (it might be ``origin``).

**Comment by Dsujan** [comment]
@peterjc  Ahh It worked. Thanks for the help.

**Pull request merged**
