### PR TITLE
 Bio.Phylo.PAML: replaced "if variable is True" for "if variable"

### PR DESCRIPTION
**Pull request by carlosp420**
also:

* fixed typos.
* PEP8 fixes.

### CODE REVIEW

**Comment by peterjc** [comment]
@brandoninvergo any comments? The truth testing looks fine to me.

**Comment by vincentdavis** [comment]
If you where waiting for another pair of eye, I looked through all of the changes, everything is either spelling or PEP8 spacing. Leeks good to me, I think it is ready to merge.

**Comment by peterjc** [comment]
I was hoping to get @brandoninvergo and maybe @etal to comment as they know this part of the code better than me, but extra eyes on this are appreciated - thanks @vincentdavis

**Comment by etal** [comment]
Looks good to me. The only real code change is in the second commit, dropping "is True". I see `branch_freqs_found` is a local variable that only ever takes on the values True or False, so this change is safe.

**Comment by peterjc** [comment]
Thanks all, rebased to the master branch as the commits leading up to https://github.com/biopython/biopython/commit/fcd0803623abb3c7786b7f788a66187d49fca839

**Pull request closed without merging**
