### PR TITLE
Add Medline#get_all_author_affiliations method

### LINKED ISSUE #4303: Incorrect Mapping Issue: Number of Authors vs Number of Affiliations
During my analysis of the API data, I noticed an inconsistency in the mapping for a specific publication. For example, when retrieving the publication with PubMed ID 31015011, the API indicates that there are seven authors associated with the publication. However, the API only provides information for five affiliations.

Upon reviewing the actual paper, it became apparent that the first, third, and fourth authors belong to Department 1, while the remaining authors follow a sequential incrementation for their department affiliations. This inconsistency raises concerns about the accuracy of the current author-affiliation mapping provided by the API.

Is there any other field which would be helpful for mapping ?

### PR DESCRIPTION
**Pull request by erik-whiting**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #4303 (possibly)

This PR just adds a method for returning a mapping of author affiliations from Medline. The new functionality here is that you can see what author is associated with what affiliation, and author's with multiple affiliations are handled gracefully.

This also returns a dictionary instead of an iterable, I did not think the returned data was worth iterating over.

I didn't discuss this solution with anyone so I'm happy to change anything in the PR

### CODE REVIEW

**Comment by erik-whiting** [comment]
I used this publication as an example for the test cases and docstring: https://pubmed.ncbi.nlm.nih.gov/37195739/#full-view-affiliation-2
here's the pubmed format of the publication: https://pubmed.ncbi.nlm.nih.gov/37195739/?format=pubmed

**Comment by peterjc** [comment]
See my comment on #4303, I am not convinced this is the right approach.

**Comment by mdehoon** [comment]
Thank you @erik-whiting .

For the design, I agree with @peterjc ; see my comment in #4303 .

**Comment by peterjc** [comment]
OK, so closing this pull request - but we'd welcome your input in discussing or even implementing the changes to the parser being discussed. Thank you.

**Pull request closed without merging**
