### PR TITLE
Refactor list/dict/set comprehensions and literal syntax (part 2)

### PR DESCRIPTION
**Pull request by chris-rands**
This pull request addresses issue #2085

So far just the `Scripts/` files. I could also add the `Doc/` files but let's see if the TravisCI build fails or not (as it did previously in PR #2087).

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
So one (or both) of the files changed is triggering something:

```
$ flake8
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/.tox/style/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/biopython/biopython/.tox/style/lib/python2.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/travis/build/biopython/biopython/.tox/style/lib/python2.7/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/home/travis/build/biopython/biopython/.tox/style/lib/python2.7/site-packages/flake8/main/application.py", line 382, in _run
    self.run_checks()
  File "/home/travis/build/biopython/biopython/.tox/style/lib/python2.7/site-packages/flake8/main/application.py", line 301, in run_checks
    self.file_checker_manager.run()
  File "/home/travis/build/biopython/biopython/.tox/style/lib/python2.7/site-packages/flake8/checker.py", line 328, in run
    self.run_parallel()
  File "/home/travis/build/biopython/biopython/.tox/style/lib/python2.7/site-packages/flake8/checker.py", line 292, in run_parallel
    for ret in pool_map:
  File "/opt/python/2.7.15/lib/python2.7/multiprocessing/pool.py", line 289, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/python/2.7.15/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
pydocstyle.parser.ParseError: Cannot parse file.
ERROR: InvocationError for command /home/travis/build/biopython/biopython/.tox/style/bin/flake8 (exited with code 1)
```

**Comment by peterjc** [comment]
Maybe try ``Doc/`` on a separate pull request?

**Comment by chris-rands** [comment]
it seems the problematic changes are to `Scripts/Restriction/ranacompiler.py`, unfortunately I still do not understand why

these changes are:

```
            clsbases = tuple([eval(x) for x in bases])
            clsbases = tuple(eval(x) for x in bases)
```

```
                tydct = dict([(k, v) for k, v in tydct.items()
                              if k in commonattr])
                tydct = {k: v for k, v in tydct.items()
                         if k in commonattr}
```

**Comment by peterjc** [comment]
Strange. How about leaving them be for now, enabling the flake8 plugin, and adding the ``#noqq: C4...`` (fill in the full validation code) pragma to those two lines.

We should also get the basis of a test case to report to ``flake8``.

**Comment by chris-rands** [comment]
That sounds good- this is the `flake8` output now on this branch:

```
$ flake8 Scripts/
Scripts/Restriction/ranacompiler.py:408:24: C407 Unnecessary list comprehension - 'tuple' can take a generator.
Scripts/Restriction/ranacompiler.py:435:25: C404 Unnecessary list comprehension - rewrite as a dict comprehension.
```

There are no other `C4` outputs from `flake8` for the whole of the `biopython/` directory.

Would you be able to enable the `flake8` plugin etc. for Biopython? I'm afraid i'm not too familiar with how this stuff is setup

**Comment by peterjc** [comment]
OK, thank you.

**Comment by chris-rands** [comment]
Thanks Peter

**Comment by chris-rands** [comment]
Interesting, not sure if this is relevant, but you might be able to get a more informative traceback by running tox <2.6
https://github.com/tox-dev/tox/issues/823

**Comment by peterjc** [comment]
Looks very much like like https://gitlab.com/pycqa/flake8-docstrings/issues/24 but with the Python 2 vs 3 issue clouding things.

**Comment by chris-rands** [comment]
i remain confused unfortunately, but i like your idea to push ahead with adopting this anyway as in https://github.com/biopython/biopython/pull/2091#issuecomment-497453112

**Pull request merged**
