### PR TITLE
Add PaqCI to Restriction Dictionary

### PR DESCRIPTION
**Pull request by jacobkimmel**
Add `PaqCI` to the `BIo/Restriction/Restriction_Dictionary.py` database for use with `dnachisel`

### CODE REVIEW

**Comment by MarkusPiotrowski** [comment]
May I ask how you updated `Restriction_Dictionary.py`? Using the latest versions of the scripts in `Scripts/Restriction/` or an older version of these scripts? Or just manually? There are so many changes in the new dictionary file.

**Comment by MarkusPiotrowski** [comment]
Also, the failing tests indicate that you probably didn't use the current scripts for updating `Restriction_Dictionary.py`.

**Comment by MarkusPiotrowski** [comment]
Finally, `PaqCI` is already included in the recent version of `Restriction_Dictionary.py`.
??

**Comment by jacobkimmel** [comment]
Sincerest apologies, this was intended as a merge to a branch of my fork,
not master of the parent. Fat fingered the open PR button!

Please feel free to close without further comment.

**Comment by MarkusPiotrowski** [comment]
Fine, thank you. Closing.

**Pull request closed without merging**
