### PR TITLE
Further fixes which should also correct problems introduced in my previo...

### PR DESCRIPTION
**Pull request by biomadeira**
...us PR.

I have further fixed the parser, this time for good I believe. My previous PR https://github.com/biopython/biopython/pull/502 fixed things generally but unfortunately had a bug which although correctly parsing insertion codes would still raise duplicated residues' error because of an incorrect if statement that only looked for sequence identifier. (The bit below)

``` python
if current_residue_id != resseq:
    current_residue_id = resseq
    int_resseq = int(resseq)
    structure_builder.init_residue(resname, hetatm_flag, int_resseq, icode)
```

Now it checks whether there is a different insertion code and initiates a new residue if that is the case. 

``` python
if current_residue_id != resseq:
    current_residue_id = resseq
    current_icode = None
    if current_icode != icode:
        current_icode = icode
    structure_builder.init_residue(resname, hetatm_flag, resseq, icode)
else:
    if current_icode != icode:
        current_icode = icode
        structure_builder.init_residue(resname, hetatm_flag, resseq, icode)
```

This problem was the reason I quite believed there could be actual problems in the mmCIF files as addressed in this issue https://github.com/biopython/biopython/issues/481.

A strong reason to believe the parser works as it should this time is because besides the code passing the tests, I have actually loaded every mmCIF in current state of the PDB without problems whatsoever. 

Kind regards,
Fábio

### CODE REVIEW

**Comment by peterjc** [comment]
Sorry this seems to have been forgotten about - Is this old pull request still relevant? If so, it would need updating...

**Comment by biomadeira** [comment]
@peterjc This has been long ago... I am sure people would have noticed if there were major problems with the mmCIF parser.

**Comment by peterjc** [comment]
OK, thanks.

**Comment by nanand2** [comment]
This is still an issue

**Comment by peterjc** [comment]
@nanand2 it sounds like you have a test case where this breaks (or something similar goes wrong). Please open a new issue with full details.

**Pull request closed without merging**
