### PR TITLE
make sure that all sequence letters are ASCII

### PR DESCRIPTION
**Pull request by mdehoon**
Ensure that all letters in the sequences passed to the pairwise aligner are ASCII.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Slightly related, giving discussion on #3319, should this reject sequences with gap characters already in them?

**Comment by mdehoon** [comment]
It should not. While using gap characters in sequences would be very confusing, internally the alignment is stored in terms of the trace matrix, not by using gap characters. So as far as the calculation is concerned, gap characters are just as valid as any other character.

**Comment by chris-rands** [comment]
@mdehoon how about a warning for gaps then? I see your alignment approach is agnostic to the alphabet, but in practise `'-'` in the input sequences(s) is surely rarely deliberate

**Comment by mdehoon** [comment]
@chris-rands  The default alphabet of a `PairwiseAligner` object consists of the 26 letters of the alphabet only. The user would have to explicitly add `-` to the alphabet to be able to include it in the sequence.

**Pull request merged**
