### PR TITLE
Issue 3466 fix

### PR DESCRIPTION
**Pull request by noamkremen**
- [ X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #...

### CODE REVIEW

**Comment by peterjc** [comment]
See #3466 and #3473

**Comment by peterjc** [comment]
Do you think it is worth adding your test too, or should we close this now that #3473 has been applied?

**Comment by noamk-pagaya** [comment]
> Do you think it is worth adding your test too, or should we close this now that #3473 has been applied?

Mine depends on an internet connection being available to download the kegg file. Given that tests run with --offline, not much value in adding it. 

```
ERROR: test_kgml_parse (test_KGML_parsing_test.KGMLParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_KGML_parsing_test.py", line 14, in setUp
    self.parsed_pathway = KGML_parser.read(kegg_get("ko00680", "kgml"))
  File "C:\projects\biopython\build\lib.win32-3.8\Bio\KEGG\REST.py", line 203, in kegg_get
    resp = _q("get", dbentries, option)
  File "C:\projects\biopython\build\lib.win32-3.8\Bio\KEGG\REST.py", line 44, in _q
    resp = urlopen(URL % (args))
  File "run_tests.py", line 195, in dummy_urlopen
    raise RuntimeError(
RuntimeError: Internal test suite error, attempting to use internet despite --offline setting
```

**Comment by noamkremen** [comment]
> Do you think it is worth adding your test too, or should we close this now that #3473 has been applied?



Mine depends on an internet connection being available to download the kegg file. Given that tests run with --offline, not much value in adding it.

ERROR: test_kgml_parse (test_KGML_parsing_test.KGMLParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_KGML_parsing_test.py", line 14, in setUp
    self.parsed_pathway = KGML_parser.read(kegg_get("ko00680", "kgml"))
  File "C:\projects\biopython\build\lib.win32-3.8\Bio\KEGG\REST.py", line 203, in kegg_get
    resp = _q("get", dbentries, option)
  File "C:\projects\biopython\build\lib.win32-3.8\Bio\KEGG\REST.py", line 44, in _q
    resp = urlopen(URL % (args))
  File "run_tests.py", line 195, in dummy_urlopen
    raise RuntimeError(
RuntimeError: Internal test suite error, attempting to use internet despite --offline setting

**Comment by peterjc** [comment]
OK, thanks.

Note the other PR added an online test to ``Tests/test_KEGG_online.py``

**Pull request closed without merging**
