### PR TITLE
Added a POST option to the esearch util

### PR DESCRIPTION
**Pull request by jotomicron**
I'm not sure this is the best solution, but I think it works as intended.

### CODE REVIEW

**Comment by peterjc** [comment]
Any further thoughts @jotomicron ? I agree with @mdehoon that a general solution would be best.

As I recall, we have the explicit use of post in ``efetch`` when there are over 200 IDs based on an NCBI guideline.

Perhaps we could change the ``_open`` function's ``post`` argument to use ``None`` to mean automatically use post if otherwise the URL would be too long?

```
def _open(cgi, params=None, post=None, ecitmatch=False):
    ...
    if post is None and len(options) > 1000:
        post = True
    ...
```

Or since this is a private function, we could just change it as follows:

```
def _open(cgi, params=None, force_post=False, ecitmatch=False):
    ...
    post = force_post or len(options) > 1000
    ...
```

Also what would be a sensible threshold for automatically using HTTP POST rather than HTTP GET?

**Comment by jotomicron** [comment]
Apologies for the delayed answer. I'm in the process of writing my PhD thesis and haven't found the time to look into this properly.

I like your second option better. This would also be useful with **EPost**, **ESummary** and **ELink**, since NCBI also asks that such requests be made through POST when they have 200+ ids. 

As for the length of the query, the eutils page says, for **ESearch**

> For very long queries (more than several hundred characters long), consider using an HTTP POST call

So maybe we should consider `len(options) > 300000`. However, I do not know whether the HTTP protocol mandates a limit on URLs and the amount that the NCBI servers actually can handle. So maybe 100000 is a safer bet?

**Comment by peterjc** [comment]
I think 1000 which was my initial guess is safer, even literally 300 which is several hundred? I've heard people report problems with firewalls with long URLs (outside of Entrez use, but in general with REST API calls) so using 300000 seems too high.

@jotomicron are you happy to work on this as discussed above and update this branch?

**Comment by jotomicron** [comment]
Oops, I read that as "several hundred thousand" (really, what was I thinking?)

I will update this branch as discussed.

**Comment by jotomicron** [comment]
There's a thorough answer in stackoverflow (http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers seems) that seems to suggest that the de-facto limit is 2000 (they have links to actual research that is 9 years old, though). Shall I keep it at 300 anyway?

**Comment by jotomicron** [comment]
I messed up and created a NEW branch with these changes. But I think I was able to import the changes into this branch, now. Hope everything works and all tests succeed. I wasn't able to run the tests locally (something weird was happening with the doctest module not finding some of the methods defined inside Bio.Entrez).

**Comment by peterjc** [comment]
Why have you removed ``post`` from the ``_open(...)`` arguments? Previously this was used by ``epost(...)`` to always use a post rather than get.

I'm happy with 1000 as the cutoff - we can tweak this if the NCBI ever give more explicit advise.

**Comment by jotomicron** [comment]
As per the guidelines, epost should also respect the same criteria: 200+ UIDs warrant POST; otherwise, use GET (http://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EPost)

**Comment by peterjc** [comment]
Good answer! They have improved the documentation a lot since ``Bio.Entrez`` was started.

**Comment by peterjc** [comment]
@mdehoon Are you happy with this?

**Comment by buhtz** [comment]
I understand the point that you use a different methode (POST) when the url gets to long. But how can I check that? I need for debuging to know exactly what is send to the server.
Normaler I do `print(handle.url)` which doesn't work here.

**Comment by peterjc** [comment]
Interesting question @buhtz. As far as I can tell Python's ``urllib.request.urlopen(...)`` (and the Python 2 equivalent ``urllib2.urlopen(...)``) do not record the POST data in the handle-like return value, which only offers ``.url`` and ``.geturl()`` to get the URL and similar ways to get the status and headers. Sadly HTTP POST queries are by their nature much more troublesome for logging than plain HTTP GET.

This should not stop us updating ``Bio.Entrez`` to use HTTP POST more in line with the NCBI guidelines.

**Comment by mdehoon** [comment]
@peterjc  I'm OK with this.

**Comment by peterjc** [comment]
@jotomicron would you like to be thanked in the ``NEWS`` and ``CONTRIB`` file? If so under what name - we can use jotomicron as an alias if you like although mostly this is by name.

**Comment by jotomicron** [comment]
Sure. You can use "João D Ferreira" if you want, or "Joao D Ferreira" if non-ascii characters do not play well with those files.

**Comment by peterjc** [comment]
Great. The accented "a" hasn't been a problem with the other João, so I've used that: https://github.com/biopython/biopython/commit/e86cb14824feacde3691509979fe588ceb90e84a

**Comment by buhtz** [comment]
Maybe it is a bit to far from the Issue here, but...
When I give Entrez my parameters with `Enterz.esearch(...)` it create an url out of it, right? After that it check if the url is to long and step to the POST methode, right?
I just want to know the URL at the state before you check its length. I need this for debuging. :)

**Comment by peterjc** [comment]
@buhtz It would probably best to file a new issue about ways to extend ``Bio.Entrez`` for low level logging.

Right now the only thing I can think of is a bit of a hack for the GET/POST situation, adding something like ``._original_url`` to the handle (leading underscore to indicate a private attribute not intended for general use) before returning it from the ``Bio.Entrez._open(...)`` function.

**Comment by buhtz** [comment]
Done #678.

**Comment by peterjc** [comment]
@jdferreira would you agree to dual license your Biopython contributions as discussed on #898 so we can switch to the standard 3-clause BSD license? (Apologies if you already have done so, and I have overlooked this)

**Comment by jdferreira** [comment]
> @jdferreira would you agree to dual license your Biopython contributions as discussed on #898 so we can switch to the standard 3-clause BSD license? (Apologies if you already have done so, and I have overlooked this)

Sure. I've done so on the issue you mentioned &ndash; see https://github.com/biopython/biopython/issues/898#issuecomment-527134170

**Pull request merged**
