### PR TITLE
Stricter alphabet checking in codonalign

### PR DESCRIPTION
**Pull request by peterjc**
What do you think @zruan? I'm wondering if this should instead check for the argument being an instance of class CodonAlphabet?

CC @universvm as he's been trying this module recently.

### CODE REVIEW

**Comment by zruan** [comment]
Is `CodonAlphabet` the only alphabet in biopython that is not `SingleLetterAlphabet`? I think a direct checking like `isinstance(codon_alphabet, CodonAlphabet)` is stricker and will avoid ambiguity.

**Comment by peterjc** [comment]
There are some interesting alphabets used in ``test_GAOrganism.py``, and there is the ``ThreeLetterProtein`` - but almost everything else would be based on ``SingleLetterAlphabet``.

OK, let's add a check for ``isinstance(codon_alphabet, CodonAlphabet)`` here instead. Do you want to do this, or should I?

**Comment by zruan** [comment]
Pull request #1180 is made.

**Comment by peterjc** [comment]
Closes in favour of #1180

**Pull request closed without merging**
