### PR TITLE
Allow ABI parser to pick up extended data

### PR DESCRIPTION
**Pull request by erasche**
This commit disables the check that the key be "known". At the expense of users possibly encountering keys that don't have a built-in label, the format is future-proofed against manufacturers adding additional
keys/value pairs to the files, and users not being able to access that data.

The test case diff showcases that we were obscuring data from the users that they might want to access.

This is a follow up to some discussion in https://github.com/biopython/biopython/pull/473 and seemed like the most user-friendly option that wouldn't *necessitate* future PRs to handle manufacturer changes.

### CODE REVIEW

**Comment by erasche** [comment]
@DavidBulger @bow @peterjc @cariaso since all of you commented on #473

**Comment by DavidBulger** [comment]
Looks great to me. Thank you again Eric for all your work on this!

David

**Comment by peterjc** [comment]
Why bother? We already expose the entire dictionary via the ``record.annotations["abif_raw"]`` key? This was added in Biopython 1.65.

**Comment by erasche** [comment]
@peterjc the previous iteration of the ABIF parser required that a key found in a sequence file be listed in `_INSTRUMENT_SPECIFIC_TAGS`. This disables that check, and as seen in https://github.com/erasche/biopython/blob/fad28eb9a05d6b6bb34484778d767f4761585df4/Tests/test_SeqIO_AbiIO.py#L403 (L404-L411) there are several new pieces of information exposed that weren't previously. See https://github.com/biopython/biopython/pull/473#issuecomment-77160817 for further comments.

**Comment by peterjc** [comment]
Ah - thanks for the clarification @erasche, e.g.

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> Bio.__version__
'1.65'
>>> from Bio import SeqIO
>>> record = SeqIO.read("Abi/A6_1-DB3.ab1", "abi")
>>> record.annotations["abif_raw"]['AUDT1']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'AUDT1'
>>> record.annotations["abif_raw"].keys()
['RUND2', 'RUND1', 'DySN1', 'SMPL1', 'GTyp1', 'PCON2', 'RUNT2', 'PBAS2', 'RUNT1', 'MODL1', 'TUBE1']
>>> quit()
```
Not actually that many fields. Versus with your patch,
```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> Bio.__version__
'1.65+'
>>> from Bio import SeqIO
>>> ecord = SeqIO.read("Abi/A6_1-DB3.ab1", "abi")
>>> record = SeqIO.read("Abi/A6_1-DB3.ab1", "abi")
>>> record.annotations["abif_raw"]['AUDT1']
(56, 66, 98, 58, 40, 123, 46, -93, 88, 124, 76, 61, 54, 88, 79, 63, 84, 118, 101, 33, 64, 46, ..., 0)
>>> record.annotations["abif_raw"].keys()
['RMdX1', 'ASPt1', 'ASPt2', 'PCON1', 'DyeN4', 'PCON2', 'DyeN1', 'DyeN3', 'DyeN2', 'APrX1', 'SVER3', 'SVER2', 'SVER1', 'LsrP1', 'RPrV1', 'ARTN1', 'Dye#1', 'LAST1', 'P1AM1', 'RUNT4', 'TUBE1', 'DCHT1', 'P1RL1', 'DySN1', 'RMdV1', 'CTID1', 'DyeW4', 'DyeW2', 'DyeW3', 'DyeW1', 'EVNT4', 'EVNT1', 'AUDT1', 'EVNT3', 'PDMF2', 'DATA11', 'PDMF1', 'BCTS1', 'PXLB1', 'phCH1', 'HCFG3', 'HCFG2', 'HCFG1', 'B1Pt1', 'B1Pt2', 'HCFG4', 'DATA12', 'phQL1', 'LANE1', 'EPVt1', 'Scal1', 'PTYP1', 'RGNm1', 'PLOC2', 'PLOC1', 'P2RL1', 'CTNM1', 'RMdN1', 'FWO_1', 'APXV1', 'DATA9', 'DATA8', 'DATA5', 'DATA4', 'DATA7', 'DATA6', 'DATA1', 'DATA3', 'DATA2', 'SMPL1', 'phAR1', 'MCHN1', 'RUNT2', 'RUNT3', 'RUNT1', 'SMED1', 'MODL1', 'DATA10', 'FTab1', 'phDY1', 'FVoc1', 'APFN2', 'RMXV1', 'InVt1', 'DSam1', 'ASPF1', 'CMNT1', 'Tmpr1', 'phTR1', 'CTOw1', 'Rate1', 'NOIS1', 'Feat1', 'Scan1', 'InSc1', 'RUND4', 'RUND2', 'RUND3', 'RUND1', 'GTyp1', 'NAVG1', 'P2BA1', 'P2AM1', 'SCAN1', 'BufT1', 'APrV1', 'LIMS1', 'LNTD1', 'P1WD1', 'phTR2', 'MODF1', 'RGOw1', 'SPAC2', 'SPAC3', 'SPAC1', 'APrN1', 'PSZE1', 'RunN1', 'SMLt1', 'CpEP1', 'RPrN1', 'AEPt2', 'AEPt1', 'EVNT2', 'User1', 'NLNE1', 'PBAS2', 'PBAS1', 'S/N%1', 'CTTL1']
```

Presumably the percent signs, slashes, and hash characters are not-problematic as keys?

**Comment by erasche** [comment]
@peterjc as far as I can tell they aren't problematic, they're part of the spec and whoever wrote the original parser wrote it such that they're handled properly.

**Comment by peterjc** [comment]
Applied as https://github.com/biopython/biopython/commit/f8fba1052cbda470a296031279547c60d2e894f3 - thank you!

**Pull request closed without merging**
