### PR TITLE
Generalized pairwise aligner and substitution matrices

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request includes two related changes:
- The PairwiseAligner in Bio.Align was extended to allow generalized pairwise alignments in which the sequences being aligned do not need to be strings, but could be lists or tuples of strings (or any object, really), or arrays of integers. Examples in the updated documentation include the alignment of three-letter amino acid sequences, three-nucleotide codons, and integer arrays, but essentially any kind of object can be aligned. To get this to work, the substitution matrix code had to be redone.
- A new module substitution_matrices was added to Bio.Align, which includes an Array class that can be used as a substitution matrix. This is intended as a replacement of Bio.SubsMat, which is currently unmaintained. The key difference between the two modules is that the new Array class is a subclass of a numpy array, while the SubstitutionMatrix class in Bio.SubsMat is a subclass of a Python dictionary. Because the new Array class is a subclass of a numpy array, mathematical operations can be applied to it in the same way as to numpy arrays. As a result, much of the mathematical operations that are implemented in Bio.SubsMat do not need to be implemented for the Array class. A second advantage is that C code that makes use of substitution matrices (Bio.pairwise2 and the pairwise aligner in Bio.Align) can directly access the numerical values stored in the substitution matrices without needing to copy them from the dictionary. I have also included a function to read substitution matrices from text files, in particular those provided by NCBI containing BLOSUM and PAM matrices. Some of those are included in the Biopython distribution for immediate use.

Note that the subclassing code in numpy changed substantially in numpy version 1.13, so I have added this requirement to setup.py.

Please have a look to see if you agree, in particular with regard to the design of the new substitution matrix code. I have included extensive documentation describing the updates to the pairwise aligner and the substitution matrix code.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
The PyPy failures on Travis are due to the numpy version being out of date (numpy version is 1.12.1, while 1.13 is needed). Can these be updated?
The failure on AppVeyor seems not related to this pull request. Any way to get more information on what is causing the crash?

**Comment by peterjc** [comment]
The officially provided TravisCI PyPy2 and Pypy3 versions used to be rather old, but currently they are practically up to date:

```
$ python --version
Python 2.7.13 (8cdda8b8cdb8, Apr 14 2019, 14:06:44)
[PyPy 7.1.1 with GCC 6.2.0 20160901]
```

and:

```
$ python --version
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901]
```

Note still a beta rather than the final release of PyPy3 7.1.1, #2298 should fix that.

Also, we can add an explicit (minimum) version of numpy for the tests here:

https://github.com/biopython/biopython/blob/biopython-174/.travis-tox.ini#L74

**Comment by peterjc** [comment]
The AppVeyor crash is very strange:

```
test_PDB_StructureAlignment ... C:\projects\biopython\build\lib.win32-2.7\Bio\PDB\StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 13298.
  PDBConstructionWarning,
C:\projects\biopython\build\lib.win32-2.7\Bio\PDB\StructureBuilder.py:92Command exited with code -1073741819
```

Line 92 is issuing the warning, which shouldn't crash.

Nothing has changed in ``Bio.PDB`` recently, so either this is something on the Windows test platform (in which case the master will break in the same way), or it is indirectly from your changes?

**Comment by mdehoon** [comment]
The code in this pull request now works with numpy versions older than 1.13.

**Comment by peterjc** [comment]
The AppVeyor problem persists, and seems to be unique to this branch (e.g. the recent TravisCI change for PyPy passed on the master branch on TravisCI and AppVeyor).

The log says it is using  numpy-1.16.5 - which is not so old.

**Comment by mdehoon** [comment]
The AppVeyor crash occurs before any of the new code is tested. However Bio.Align and therefore Bio.Align._aligner is imported, so perhaps a bug there would cause a crash later. I will push a commit that returns from the import routine in Bio.Align._aligner immediately. Most tests will fail then, but the PDB ones should pass.

**Comment by peterjc** [comment]
In hindsight perhaps having the C code directly in ``Bio.Align`` was a mistake - it gets imported even when not needed.

**Comment by mdehoon** [comment]
All tests are passing now, and currently the code does not require a recent version of numpy; older versions will work fine.

I am still wondering if Bio.Align.substitution_matrices is the best location for the new Array class. Array objects are not necessarily substitution matrices; they could be any square 2D array or even a 1D array. Perhaps a Bio.math module would be a better place? Or we can keep Array in Bio.Align.substitution_matrices for now, and decide later if we want to move it to a different module.

**Comment by peterjc** [comment]
Good job on the older NumPy and 32-bit work.

Your thoughts @MarkusPiotrowski - particularly on the module placement?

**Comment by mdehoon** [comment]
@MarkusPiotrowski  Can we proceed and merge this PR?

**Comment by mdehoon** [comment]
If there are no further comments, can I go ahead and merge? We can always change things later.

**Comment by peterjc** [comment]
If you put a ``BiopythonExperimentalWarning`` on the new bits, we'd be much freer to change it later...

Maybe drop Markus an email in case he missed the notification via GitHub?

**Comment by mdehoon** [comment]
@peterjc  I have written to @MarkusPiotrowski  and asked for his suggestions.

I think a `BiopythonExperimentalWarning` would discourage users from trying the new code.

**Comment by MarkusPiotrowski** [comment]
Sorry, I was offline yesterday. Also, this PR is so big that I'm sorry, but I can't find the time to properly review and test it.

Just four things:
1. I don't think that a `BiopythonExperimentalWarning` will discourage users trying the new code. It doesn't mean: 'Things may not work properly', instead it means: 'The details of the implementation may change later'. This gives us the freedom to easily change things afterwards without taking to much care about backward compatibility. There were already 1 or 2 of such changes in `PairwiseAligner`. As you said "We can always change things later"...
2. Now that you are changing the 'pretty print' output function, can you change the mismatch symbol to those that were agreed on two or three versions ago (PR #1352), i.e. a `.` instead of `X`?
3. Issue #2309 reminded me that we don't have substitutions tables for nucleotides. Can you consider adding `nuc4.2` and `nuc4.4` from ftp://ftp.ncbi.nih.gov/blast/matrices? E.g. `nuc4.4` is identical to `EDNAFULL` used by EMBOSS Water or Needle. We could then add these tables also to `SubsMat`.
4. Regarding a placement of the new `Array` class I don't have any preferences or ideas. 
I'm more unhappy about the fact to have to sets of substitutions tables in quite different places. What about `Bio.Data` as home for the new substitution tables? 

When talking about 'a replacement for of Bio.SubsMat' I think that dictionaries are still handy here. E.g. when someone wants to calculate a score of a given alignment it's quite easy with a data structure like a dictionary. Do you supply a function to convert your array structure into a dictionary? Or, the other way round: Can't you convert the existing dictionaries into your array?

**Comment by mdehoon** [comment]
@MarkusPiotrowski   Thank you for your comments. I have added the NUC4.4 substitution table for nucleotides.

**Comment by mdehoon** [comment]
@MarkusPiotrowski  For NUC4.2, I am not sure how the matrix as provided by NCBI (ftp://ftp.ncbi.nih.gov/blast/matrices/NUC.4.2) should be interpreted, as alignments of ambiguous nucleotides to each other are missing:
```
    A   T   G   C  
A   5  -4  -4  -4 
T  -4   5  -4  -4 
G  -4  -4   5  -4 
C  -4  -4  -4   5 
S  -4  -4   1   1 
W   1   1  -4  -4 
R   1  -4   1  -4 
Y  -4   1  -4   1 
K  -4   1   1  -4 
M   1  -4  -4   1 
B  -4  -1  -1  -1 
V  -1  -4  -1  -1 
H  -1  -1  -4  -1 
D  -1  -1  -1  -4 
```

**Comment by mdehoon** [comment]
@MarkusPiotrowski  For pretty printing, I am happy to use a `.` instead of a `X` for a mismatch. As I was using `.` for sequences outside of a (local) alignment, I replaced those with a space ` `. I agree this looks better.

**Comment by mdehoon** [comment]
@MarkusPiotrowski 

> When talking about 'a replacement for of Bio.SubsMat' I think that dictionaries are still handy here. E.g. when someone wants to calculate a score of a given alignment it's quite easy with a data structure like a dictionary. Do you supply a function to convert your array structure into a dictionary? Or, the other way round: Can't you convert the existing dictionaries into your array?

The new substitution matrices can be used both as an array and as a dictionary. For example,
```
>>> from Bio.Align import substitution_matrices
>>> matrix = substitution_matrices.load("NUC.4.4")
>>> print(matrix)
#  
#  This matrix was created by Todd Lowe   12/10/92
#  
#  Uses ambiguous nucleotide codes, probabilities rounded to
#  nearest integer
#  
#  Lowest score = -4, Highest score = 5
#  
     A    T    G    C    S    W    R    Y    K    M    B    V    H    D    N
A  5.0 -4.0 -4.0 -4.0 -4.0  1.0  1.0 -4.0 -4.0  1.0 -4.0 -1.0 -1.0 -1.0 -2.0
T -4.0  5.0 -4.0 -4.0 -4.0  1.0 -4.0  1.0  1.0 -4.0 -1.0 -4.0 -1.0 -1.0 -2.0
G -4.0 -4.0  5.0 -4.0  1.0 -4.0  1.0 -4.0  1.0 -4.0 -1.0 -1.0 -4.0 -1.0 -2.0
C -4.0 -4.0 -4.0  5.0  1.0 -4.0 -4.0  1.0 -4.0  1.0 -1.0 -1.0 -1.0 -4.0 -2.0
S -4.0 -4.0  1.0  1.0 -1.0 -4.0 -2.0 -2.0 -2.0 -2.0 -1.0 -1.0 -3.0 -3.0 -1.0
W  1.0  1.0 -4.0 -4.0 -4.0 -1.0 -2.0 -2.0 -2.0 -2.0 -3.0 -3.0 -1.0 -1.0 -1.0
R  1.0 -4.0  1.0 -4.0 -2.0 -2.0 -1.0 -4.0 -2.0 -2.0 -3.0 -1.0 -3.0 -1.0 -1.0
Y -4.0  1.0 -4.0  1.0 -2.0 -2.0 -4.0 -1.0 -2.0 -2.0 -1.0 -3.0 -1.0 -3.0 -1.0
K -4.0  1.0  1.0 -4.0 -2.0 -2.0 -2.0 -2.0 -1.0 -4.0 -1.0 -3.0 -3.0 -1.0 -1.0
M  1.0 -4.0 -4.0  1.0 -2.0 -2.0 -2.0 -2.0 -4.0 -1.0 -3.0 -1.0 -1.0 -3.0 -1.0
B -4.0 -1.0 -1.0 -1.0 -1.0 -3.0 -3.0 -1.0 -1.0 -3.0 -1.0 -2.0 -2.0 -2.0 -1.0
V -1.0 -4.0 -1.0 -1.0 -1.0 -3.0 -1.0 -3.0 -3.0 -1.0 -2.0 -1.0 -2.0 -2.0 -1.0
H -1.0 -1.0 -4.0 -1.0 -3.0 -1.0 -3.0 -1.0 -3.0 -1.0 -2.0 -2.0 -1.0 -2.0 -1.0
D -1.0 -1.0 -1.0 -4.0 -3.0 -1.0 -1.0 -3.0 -1.0 -3.0 -2.0 -2.0 -2.0 -1.0 -1.0
N -2.0 -2.0 -2.0 -2.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0

>>> matrix['A','T']
-4.0
>>> matrix['A',5]  # 'W'
1.0
>>> matrix[3,5]  # 'C','W'
-4.0
>>> matrix['A',:]
Array([ 5., -4., -4., -4., -4.,  1.,  1., -4., -4.,  1., -4., -1., -1.,
       -1., -2.],
         alphabet='ATGCSWRYKMBVHDN')
>>> matrix.keys()
(('A', 'A'), ('T', 'A'), ('G', 'A'), ('C', 'A'), ('S', 'A'), ('W', 'A'), ('R', 'A'), ('Y', 'A'), ('K', 'A'), ('M', 'A'), ('B', 'A'), ('V', 'A'), ('H', 'A'), ('D', 'A'), ('N', 'A'), ('A', 'T'), ('T', 'T'), ('G', 'T'), ('C', 'T'), ('S', 'T'), ('W', 'T'), ('R', 'T'), ('Y', 'T'), ('K', 'T'), ('M', 'T'), ('B', 'T'), ('V', 'T'), ('H', 'T'), ('D', 'T'), ('N', 'T'), ('A', 'G'), ('T', 'G'), ('G', 'G'), ('C', 'G'), ('S', 'G'), ('W', 'G'), ('R', 'G'), ('Y', 'G'), ('K', 'G'), ('M', 'G'), ('B', 'G'), ('V', 'G'), ('H', 'G'), ('D', 'G'), ('N', 'G'), ('A', 'C'), ('T', 'C'), ('G', 'C'), ('C', 'C'), ('S', 'C'), ('W', 'C'), ('R', 'C'), ('Y', 'C'), ('K', 'C'), ('M', 'C'), ('B', 'C'), ('V', 'C'), ('H', 'C'), ('D', 'C'), ('N', 'C'), ('A', 'S'), ('T', 'S'), ('G', 'S'), ('C', 'S'), ('S', 'S'), ('W', 'S'), ('R', 'S'), ('Y', 'S'), ('K', 'S'), ('M', 'S'), ('B', 'S'), ('V', 'S'), ('H', 'S'), ('D', 'S'), ('N', 'S'), ('A', 'W'), ('T', 'W'), ('G', 'W'), ('C', 'W'), ('S', 'W'), ('W', 'W'), ('R', 'W'), ('Y', 'W'), ('K', 'W'), ('M', 'W'), ('B', 'W'), ('V', 'W'), ('H', 'W'), ('D', 'W'), ('N', 'W'), ('A', 'R'), ('T', 'R'), ('G', 'R'), ('C', 'R'), ('S', 'R'), ('W', 'R'), ('R', 'R'), ('Y', 'R'), ('K', 'R'), ('M', 'R'), ('B', 'R'), ('V', 'R'), ('H', 'R'), ('D', 'R'), ('N', 'R'), ('A', 'Y'), ('T', 'Y'), ('G', 'Y'), ('C', 'Y'), ('S', 'Y'), ('W', 'Y'), ('R', 'Y'), ('Y', 'Y'), ('K', 'Y'), ('M', 'Y'), ('B', 'Y'), ('V', 'Y'), ('H', 'Y'), ('D', 'Y'), ('N', 'Y'), ('A', 'K'), ('T', 'K'), ('G', 'K'), ('C', 'K'), ('S', 'K'), ('W', 'K'), ('R', 'K'), ('Y', 'K'), ('K', 'K'), ('M', 'K'), ('B', 'K'), ('V', 'K'), ('H', 'K'), ('D', 'K'), ('N', 'K'), ('A', 'M'), ('T', 'M'), ('G', 'M'), ('C', 'M'), ('S', 'M'), ('W', 'M'), ('R', 'M'), ('Y', 'M'), ('K', 'M'), ('M', 'M'), ('B', 'M'), ('V', 'M'), ('H', 'M'), ('D', 'M'), ('N', 'M'), ('A', 'B'), ('T', 'B'), ('G', 'B'), ('C', 'B'), ('S', 'B'), ('W', 'B'), ('R', 'B'), ('Y', 'B'), ('K', 'B'), ('M', 'B'), ('B', 'B'), ('V', 'B'), ('H', 'B'), ('D', 'B'), ('N', 'B'), ('A', 'V'), ('T', 'V'), ('G', 'V'), ('C', 'V'), ('S', 'V'), ('W', 'V'), ('R', 'V'), ('Y', 'V'), ('K', 'V'), ('M', 'V'), ('B', 'V'), ('V', 'V'), ('H', 'V'), ('D', 'V'), ('N', 'V'), ('A', 'H'), ('T', 'H'), ('G', 'H'), ('C', 'H'), ('S', 'H'), ('W', 'H'), ('R', 'H'), ('Y', 'H'), ('K', 'H'), ('M', 'H'), ('B', 'H'), ('V', 'H'), ('H', 'H'), ('D', 'H'), ('N', 'H'), ('A', 'D'), ('T', 'D'), ('G', 'D'), ('C', 'D'), ('S', 'D'), ('W', 'D'), ('R', 'D'), ('Y', 'D'), ('K', 'D'), ('M', 'D'), ('B', 'D'), ('V', 'D'), ('H', 'D'), ('D', 'D'), ('N', 'D'), ('A', 'N'), ('T', 'N'), ('G', 'N'), ('C', 'N'), ('S', 'N'), ('W', 'N'), ('R', 'N'), ('Y', 'N'), ('K', 'N'), ('M', 'N'), ('B', 'N'), ('V', 'N'), ('H', 'N'), ('D', 'N'), ('N', 'N'))
>>> for key, value in matrix.items():
...     print(key, value)
... 
('A', 'A') 5.0
('A', 'T') -4.0
('A', 'G') -4.0
('A', 'C') -4.0
('A', 'S') -4.0
('A', 'W') 1.0
('A', 'R') 1.0
('A', 'Y') -4.0
('A', 'K') -4.0
('A', 'M') 1.0
('A', 'B') -4.0
('A', 'V') -1.0
('A', 'H') -1.0
('A', 'D') -1.0
('A', 'N') -2.0
('T', 'A') -4.0
('T', 'T') 5.0
... 
```
With the tweak to the `keys()` method that I just uploaded, the new substitution matrices can be used in `Bio.pairwise2` as a drop-in replacement for the old substitution matrices in `Bio.SubsMat`.

**Comment by mdehoon** [comment]
@MarkusPiotrowski   , @peterjc  I have added a `BiopythonExperimentalWarning` to `Bio.Align.substitution_matrices` to point out that this module or parts of the code contained within it may be moved in the future.

**Comment by peterjc** [comment]
Thank you Markus. This needs something in the ``NEWS.rst`` file, but otherwise OK to merge now?

**Comment by MarkusPiotrowski** [comment]
Yes, I think so.

**Comment by peterjc** [comment]
If you are happy with the commit history, rebase-and-merge? Or just squash-and-merge if you prefer?

**Comment by peterjc** [comment]
Bad news, the first wheel for Biopython 1.75 failed its tests - Linux AMD64, Python 2.7, using numpy 1.8.0:

```
...
test_pairwise2 ... ok
test_pairwise2_no_C ... ok
test_pairwise_aligner ... config.sh: line 12:   174 Segmentation fault      (core dumped)
```

https://travis-ci.org/biopython/biopython-wheels/jobs/608204459

This looks like it is related to this pull request?

This could be down to the older NumPy - If so, we can tweak the wheel configuration to build against a newer NumPy.

I'm waiting for the other wheels to finish, which should give more clues (the later Python versions have to use newer NumPy installations).

**Comment by peterjc** [comment]
From a Windows wheel test, 32-bit Python 3.7 with numpy 1.14.5

https://ci.appveyor.com/project/biopython/biopython-wheels/builds/28658869/job/50o4ccdkc04uak3v

```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython-wheels\Tests\test_Tutorial.py", line 260, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 1 Tutorial doctests failed: test_chapter_align_line_02819
----------------------------------------------------------------------
Ran 204 tests in 174.417 seconds
FAILED (failures = 1)
```

**Comment by mdehoon** [comment]
@peterjc  

> Bad news, the first wheel for Biopython 1.75 failed its tests - Linux AMD64, Python 2.7, using numpy 1.8.0:

This is Python 2.7.6, release on November 10, 2013, so six years ago. I cannot even compile numpy with this version of Python. Can we upgrade to a more recent version of Python 2.7?

**Comment by mdehoon** [comment]
> From a Windows wheel test, 32-bit Python 3.7 with numpy 1.14.5
...
Update: Perhaps the fourth block on the doctest with floating point output?

I was not able to replicate this bug on Windows with 32-bit Python 3.7 and numpy 1.14.5. The floating point values on line 2856 are actually text strings. Is there any way to get the actual error that occurred?

**Comment by peterjc** [comment]
The Linux Python 2.6 issues are specific to the default unicode width (the build explicitly using unicode width 16 works):
https://travis-ci.org/biopython/biopython-wheels/builds/608487856

As to the Windows doctest, it is line 2856 onwards (including three continued blocks). My guess was the last part of that test as it has floating point numbers in the text output, but that's actually the start of the ``BLOSUM62`` data file I think?

https://github.com/biopython/biopython/blob/biopython-175/Doc/Tutorial/chapter_align.tex#L2850

Sadly the only way I can see to reproduce this (without access to some Windows virtual machines to try it by hand) is to hack the Windows build script to run ``python test_Tutorial.py`` directly - very tedious, but worth a try.

**Comment by peterjc** [comment]
Trying the doctest debug here:

https://github.com/biopython/biopython-wheels/tree/debug_win_align
https://ci.appveyor.com/project/biopython/biopython-wheels/builds/28680713

**Comment by peterjc** [comment]
Looks like ``OverflowError: number of optimal alignments is larger than 2147483647`` (and then the rest of that doctest naturally fails too).

**Comment by peterjc** [comment]
But also a path assumption I was making in the test setup:

```
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\projects\\biopython-wheels\\for_testing\\Doc\\../Bio/Align/substitution_matrices/data'
```

**Comment by mdehoon** [comment]
@peterjc  Thanks
> Looks like OverflowError: number of optimal alignments is larger than 2147483647 (and then the rest of that doctest naturally fails too).

This is then caused by the difference between 32-bits and 64-bits systems. I suggest we just remove this block from the doctest. I can make a pull request. Or is it easier for you to fix this directly?

> But also a path assumption I was making in the test setup:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\projects\\biopython-wheels\\for_testing\\Doc\\../Bio/Align/substitution_matrices/data'

Can you fix this one? The path looks correct.

**Comment by mdehoon** [comment]
> The Linux Python 2.6 issues are specific to the default unicode width (the build explicitly using unicode width 16 works):
https://travis-ci.org/biopython/biopython-wheels/builds/608487856

Python 2.7.15 with unicode width 32 also works.

**Comment by peterjc** [comment]
The path fails because the test only had Tests/ and Doc/ available - wanted to avoid any chance of importing via local Bio/ folder. Will tweak the wheel builder’s appveyor.yml later (away from computer right now).

**Comment by peterjc** [comment]
I agree that disabling the overflow test is pragmatic - a pull request on the main repository sounds good.

**Pull request merged**
