### PR TITLE
Updated sqlite3 schema to include foreign keys

### PR DESCRIPTION
**Pull request by ctSkennerton**
Fix for biopython/biopython#741 by changing the database schema
for sqlite3 to use foreign keys. A new test has been added in that
explicitly tests to make sure associated data with a bioentry is
removed.

To accommodate the use of foreign keys the connection to an sqlite
database must set the PRAGMA, which is now done automatically when
opening the database.

The sqlite schema for testing has been updated to be identical to
the version in biosql/biosql#3 that is a pull request for the main
biosql repository

### CODE REVIEW

**Comment by peterjc** [comment]
@chapmanb how does this look? I guess the foreign key pragma didn't exist back in Dec 2009 (six years, wow) otherwise you'd have used it in https://github.com/biopython/biopython/commit/a9a100c6dd461dc566fc8425ea4511416e249a40

**Comment by chapmanb** [comment]
Connor -- brilliant, thanks much for bringing this up to date. Looks great to me. +1

**Comment by ctSkennerton** [comment]
Foreign keys have now been added to the main Biosql repo

**Comment by peterjc** [comment]
Can you update this branch (and force push it) to match the accepted version from the BioSQL repository? i.e. With Hilmar's white space changes.

**Comment by ctSkennerton** [comment]
I've copied the version from the biosql repo and updated this branch to match that file

**Comment by peterjc** [comment]
The TravisCI failure from pypy3 is not from your changes (I've seen it on another unrelated pull request too), but if you can see what is wrong that would be useful...

**Comment by peterjc** [comment]
Applied as squashed commit https://github.com/biopython/biopython/commit/9f7eed8a1f068185ed8266161bec4d687b854822 - thank you Conner!

Thanks also Brad for reviewing the changes.

**Pull request closed without merging**
