### PR TITLE
Improve parsing and error checking and reporting for TRANSFAC motifs.

### PR DESCRIPTION
**Pull request by ghuls**
Improve parsing and error checking and reporting for TRANSFAC motifs:
  - Add help messages for asserts.
  - allow parsing of TRANSFAC matrices, which use something else
    than 2 spaces as whitespace separator
    (raise BiopythonParserWarning)
  - Check if each line contains a key of 2 characters, else assert
  - Use line.split(None, 1) to split each line in two fields on
    whitespace to allow parsing of TRANSFAC matrices, which use
    something else than 2 spaces as whitespace separator between
    key and value.
  - Allow parsing slightly wrong TRANSFAC matrix lines:
     - Allow numbers of only 1 character as start of a matrix line
       instead of only numbers of 2 digits
       (raise BiopythonParserWarning).
     - Allow parsing of TRANSFAC matrix if it starts with "00"
       instead of "01" (raise BiopythonParserWarning).
     - Check if a matrix line contains values for each nucleotide.
     - Allow a number of only 1 character, instead of zero prefixed

### CODE REVIEW

**Comment by ghuls** [comment]
This pull request replaces the following pull requests:
  - Allow parsing of TRANSFAC files that have only one space as separator between field and value: https://github.com/biopython/biopython/issues/549
  - Allow parsing of TRANSFAC matrices where the first matrix line starts with 00 instead of 01 (or not): https://github.com/biopython/biopython/issues/550

**Comment by peterjc** [comment]
TravisCI failures:

```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Tutorial.py", line 225, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 1 Tutorial doctests failed: test_chapter_motifs_line_00028
======================================================================
FAIL: test_transfac_parser (test_motifs.TestTransfac)
Test if Bio.motifs can parse TRANSFAC files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_motifs.py", line 1530, in test_transfac_parser
    record = motifs.parse(handle, 'TRANSFAC')
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/motifs/__init__.py", line 84, in parse
    record = transfac.read(handle)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/motifs/transfac.py", line 150, in read
    line)
AssertionError: A TRANSFAC matrix line should have a value for each nucleotide (A, C, G and T): "01      1      2      2      0      S"
----------------------------------------------------------------------
```

I would focus on ``Tests/test_motifs.py`` first, and that may indirectly solve the ``Tests/test_Tutorial.py`` failure. If you need to debug the Tutorial doctest, try:

```
cd Tests
python test_Tutorial.py
```

That should tell you more than just ``test_chapter_motifs_line_00028`` which means the doctest starting at line 28 of the file ``Doc/Tutorial/chapter_motifs.tex``:

https://github.com/biopython/biopython/blob/biopython-168/Doc/Tutorial/chapter_motifs.tex#L28

Note this doctest continues after that - this might benefit from being split up - also from the point of view of someone following the example themselves?

**Comment by ghuls** [comment]
@peterjc The issue is fixed now (Travis succeeds now too).

**Comment by peterjc** [comment]
This looks sensible to me - unless you have any objections @mdehoon and @barwil then I intend to merge it next early week. Thanks!

**Comment by peterjc** [comment]
Thank you @ghuls - rebased to the master 👍

**Pull request merged**
