### PR TITLE
Fixes for pydocstyle rule D405

### PR DESCRIPTION
**Pull request by morrme**
Ref. #1170

### CODE REVIEW

**Comment by peterjc** [comment]
I'm not sure I always agree with what ``pydocstyle`` considers to be a section name, but let's start enforcing this anyway... - thank you!

P.S. Did you decide how you'd like to be thanked in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by morrme** [comment]
No problem! No, I haven't decided. I think it's really nice but I've never really required a public acknowledgement......I'll keep thinking about it as I edit :smile:

**Comment by peterjc** [comment]
I suggest we just list you as ``morrme`` in place of a name, with a link to your GitHub profile in usual in the ``CONTRIB.rst`` file.

**Comment by morrme** [comment]
@peterjc works for me :)

**Comment by peterjc** [comment]
Added you in db074fc7a1fe7e43822e26aa6b2f504fef24cd04 - let us know if you ever want to be listed under a different name. Thanks.

**Pull request merged**
