### PR TITLE
Fixed atom name issue when converting CIF to PDB files

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
Addresses and fixes issue #1081 

I explicitly did not create a new unit test because there are too many variables (different elements, different H namings), and I consider it just an added check to PDBIO that should not change the output for the majority of cases. The patch does pass all tests and was tested in crystal and NMR structures (for Hs).

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
@peterjc @lennax @etal Maybe another pair of eyes should go over this before merging?

**Comment by peterjc** [comment]
I've never worked with CIF files so am unsure of the background to this problem.

**Comment by lennax** [comment]
@JoaoRodrigues Despite the innumerable combinations of atom names, I'd still advocate for at least some very basic unit tests (e.g., doesn't affect hydrogens or single letter atom names). Also, won't this code render an alpha carbon as `_CA` rather than `_CA_`? (underscores to explicitly represent spaces)

**Comment by JoaoRodrigues** [comment]
@lennax You're right, I'll see what I can do to keep tests simple.

>Also, won't this code render an alpha carbon as _CA rather than _CA_? (underscores to explicitly represent spaces)

In `PDBIO` the name is written to a formatted `%-4s` string so the right-side padding is taken care of. Internally though, yes, it is missing that.

**Comment by peterjc** [comment]
Is this good to go once it has a unit test included?

**Comment by JoaoRodrigues** [comment]
@peterjc @lennax Added a unit test that uses `1LCD` (already in the PDB folder), which is a NMR structure (with Hs). I'm reading the CIF file, writing a PDB, re-reading and comparing atom names and elements. If something is off in formatting it should pop either during parsing the PDB file or in assigning elements.

I think it's good to go.

**Comment by peterjc** [comment]
TravisCI is failing due to an external dependency - I saw this yesterday too,

```
curl -L -O ftp://ftp.cmbi.ru.nl/pub/software/dssp/dssp-2.0.4-linux-amd64
```

I'll temporarily comment this out...

**Comment by peterjc** [comment]
@JoaoRodrigues can you try rebasing this branch? That ought to restart TravisCI with 3b03cb4c1e70a1e1ea29729f6ad3765233f6dcd7 to skip the bad dependency URL.

**Comment by JoaoRodrigues** [comment]
@peterjc Done (I think).

**Comment by peterjc** [comment]
Looks good - thank you!

**Pull request merged**
