### PR TITLE
Fix "Avoid mutable default arguments" issue

### PR DESCRIPTION
**Pull request by tiagoantao**
This pull request automatically fixes all occurrences of the following issue:

Issue type: [Avoid mutable default arguments](https://www.quantifiedcode.com/app/issue_class/3P0qV6OB)
Issue details: [https://www.quantifiedcode.com/app/project/gh:biopython:biopython?groups=code_patterns/%3A3P0qV6OB](https://www.quantifiedcode.com/app/project/gh:biopython:biopython?groups=code_patterns/%3A3P0qV6OB)

To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.

Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

### CODE REVIEW

**Comment by peterjc** [comment]
This looks like it would save a lot of manual work - although it doesn't follow PEP8 white spacing which again can be automated. Probably a little bit of feedback to the Qualified Code folk?

**Comment by tiagoantao** [comment]
Will inform them

**Comment by programmdesign** [comment]
Thanks for reporting this. It will be fixed with our next deployment!

**Comment by tiagoantao** [comment]
This was fixed on quantifiedcode, so I will close this one and try again

**Pull request closed without merging**
