### PR TITLE
Remove deprecated stub-module Bio.PDB.Vector

### PR DESCRIPTION
**Pull request by peterjc**
This was left in place following the renaming of the module to Bio.PDB.vectors as a backward compatibility measure.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
There is a case for merging ``test_PDB_vectors.py`` into ``test_PDB.py``, or since that is already rather large, perhaps pulling some vector examples out of that into ``test_PDB_vectors.py`` instead?

**Comment by JoaoRodrigues** [comment]
Will look at this over the weekend. In principle it seems good. I agree that breaking `test_PDB` would be the better solution, I'll see if I can come up with something reasonable to help out.

PS. For some reason, I stopped getting e-mails from these requests from Github so I've been ignoring a few.. Only noticed them now because I logged onto the github home page. Sorry!

**Comment by peterjc** [comment]
Thanks - there's still another legacy test to update before merging this...

**Comment by peterjc** [comment]
I moved some self-contained vector tests (which did not use PDB parsing) into the vector test file.

**Comment by peterjc** [comment]
Conda is having a bad day, a false positive from the AppVeyor tests:

```
coverage xml
cd ..
conda install -c conda-forge codecov
Collecting package metadata: ...working... failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/noarch/repodata.json>
```

**Pull request merged**
