### PR TITLE
Do not replace double spaces when cleaning

### PR DESCRIPTION
**Pull request by chris-rands**
This pull request is related to issue #2270

If all the tests pass then I propose to add a unit test to `Tests/test_SeqRecord.py` to enforce the new behaviour

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good - add that test and I'm happy to merge this.

**Comment by chris-rands** [comment]
Thanks, I added a test

**Comment by peterjc** [comment]
Thank you

**Comment by peterjc** [comment]
Do you want to fix AlignIO's clean too?

**Comment by chris-rands** [comment]
Thanks Peter, can you point me towards the relevant code in `AlignIO`?

**Comment by peterjc** [comment]
https://github.com/biopython/biopython/blob/biopython-174/Bio/AlignIO/Interfaces.py#L117

**Pull request merged**
