### PR TITLE
Replace shlex dependency in mmCIF parsing

### PR DESCRIPTION
**Pull request by jgreener64**
I have seen in some comments on here that the use of `shlex` to split the lines in mmCIF parsing is slow, and I also found an error due to this.

This PR replaces `shlex.split` with a custom function to split lines. On my machine it gives 3-4x speedups in the construction of `MMCIF2Dict`.

Let me know if this is suitable and if any changes are required.

This pull request addresses issue #1357.

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ AND the _BSD 3-Clause License_.

I am happy to be thanked by name in the ``NEWS.rst`` and
``CONTRIB.rst`` files.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

### CODE REVIEW

**Comment by peterjc** [comment]
This looks interesting - paging @lennax @JoaoRodrigues @etal etc for comment as I don't know the mmCIF code myself.

**Comment by lennax** [comment]
I have to admit I haven't looked at an mmCIF file in years so the syntax is not fresh in my mind, but seeing as the other tests pass, I'm okay with it.

**Comment by peterjc** [comment]
Thanks @lennax 

@jgreener64 I like that you've added a functional test for the new split method, but are any of the problem files noted in #1357 small enough to include in Biopython as a direct test case? i.e. 1mom, 1n5m, 1tsl, 1y59, 2a9w, 3b3p or 3dqt

**Comment by jgreener64** [comment]
Thanks @lennax 

The smallest is 1mom, which is 240 KB (3,800 lines). There are 8 other full cif files used in the tests which range from 70 KB to 1.8 MB. Should I include this as a test case?

**Comment by jgreener64** [comment]
For reference, speed changes:

```python
import time
from Bio.PDB.MMCIFParser import MMCIF2Dict

start = time.time()
d = MMCIF2Dict("1ake.cif")
end = time.time()
print(end - start)
```

on my machine gives an average 0.62 s on current master and 0.17 s with this change.

**Comment by JoaoRodrigues** [comment]
The change looks fine to me, as long as it's thoroughly tested. Will it work on a larger scale application on several mmCIFs? If you take a random sample of 50 files from the PDB, will they be parsed correctly?

The speed improvement is great, thanks for writing this!

As for including .cif files in the test case, these are really large files.. Is there maybe a way we can include them zipped and parse them zipped for the test cases? Alternatively, we can write a couple of dummy lines ourselves.

**Comment by jgreener64** [comment]
Thanks @JoaoRodrigues 

Testing on a larger scale is something I am doing now - my strategy is to read in the `MMCIF2Dict`, dump it to json and write it to file. I do this for master and this branch and run `diff` to check any differences. So far the files are identical but I will do a random test on 50 files.

For tests we could just include the section of the cif file with the issue in it (this is what I did in #1349 ).

**Comment by peterjc** [comment]
I agree those files are a bit large to include as is. I think @jgreener64's abstract test should be enough, but if a fragment of the file works that would be great.

I'll delay merging while Joe runs those extra tests with a sample of 50 files.

**Comment by jgreener64** [comment]
I have added a test on a section of 1MOM.cif.

I have confirmed for a random 50 PDB IDs that the dictionary produced by `MMCIF2Dict` on master and this branch are identical.

For reference these are: 3E6T, 4QZX, 1R7F, 4CX8, 5D2C, 3R3S, 1LIO, 5V6S, 4X3F, 1MRW, 1T2Q, 4ICM, 5HI9, 4LL7, 3ITG, 5AQ1, 1CTU, 3DNJ, 2NXB, 3HYR, 5J17, 2GVA, 1BZV, 3UT5, 4QTA, 3NZE, 1C3N, 4V56, 3AL7, 5VHT, 4NGU, 5TI0, 3E5I, 1QN5, 2ZR2, 2P0X, 5VNF, 4W6H, 2J20, 4WH3, 5M1Q, 2GH5, 3AAG, 4YR0, 5DFN, 2OWT, 3HHF, 3M3A, 1LMN, 4ZRE.

**Comment by JoaoRodrigues** [comment]
Then awesome 👍 Great job!

**Comment by peterjc** [comment]
I've asked TravisCI to re-run the test which failed on ``test_GraphicsBitmaps.py`` with the rare stochastic failure ``ZeroDivisionError: float division by zero`` (unrelated to this pull request)

**Comment by peterjc** [comment]
Lovely, thank you all!

**Comment by jgreener64** [comment]
Great thanks.

**Pull request merged**
