### PR TITLE
Updating example source links to github

### PR DESCRIPTION
**Pull request by sbliven**
Switch biopython.org/SRC links to point directly to github, fixing 404 errors. I'm pointing to the master branch.

### CODE REVIEW

**Comment by peterjc** [comment]
Well spotted - I thought we'd fixed all those.

I think it would work better with a link to the direct download?

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by sbliven** [comment]
@peterjc Good call. I'll switch to use the raw URLs.

I'm aware of the License agreement and approve of the dual license. I appreciate the acknowledgment (Spencer Bliven). Hopefully I will contribute something more substantial than documentation patches in the future.

**Comment by sbliven** [comment]
I've changed the URLs for input files to point to raw.githubcontent.com, but I've left files that github pretty-prints (e.g. py, csv, xml) to show the formatted page on github.com. Let me know if raw is preferable for all links, and I can easily change them all.

**Comment by peterjc** [comment]
Thank you :)

**Pull request merged**
