### PR TITLE
Solution to the IPG XML Schema Parsing Issue

### PR DESCRIPTION
**Pull request by danich1**
Greetings,

My name is David Nicholson and I work in the lab of Dr. Ivan Erill. I created a solution to the NotImplementedError, that pops up when biopython tries to parse a IPG report from NCBI. I edited Bio/Entrez/Parser.py and added folder called XSDs which holds xsd files locally.

~David

### CODE REVIEW

**Comment by peterjc** [comment]
Can you look at this pull request @mdehoon?

Can you add an example where this is needed please @danich1?

It will also need functional tests...

**Comment by danich1** [comment]
Example:
>> handle = Entrez.efetch("protein", id = "783730874",rettype="ipg", retmode="xml")
>> records = Entrez.parse(handle)

The first line will fetch an IPG report from ncbi. The report is in schema format which normally would throw an error.

**Comment by mdehoon** [comment]
Looks good to me. This will also allow parsing of other EUtils output that makes use of schemas. I am in favor of accepting this pull request. Thanks David!

**Comment by peterjc** [comment]
Thanks @mdehoon - I'm glad to hear this work will be very useful.

@danich1 - Unfortunately, it needs a bit more polish before we can merge it.

As I mentioned above, this will need a test. e.g. add something like this to ``test_Entrez_online.py``:

```
    def test_fetch_xml_schemas(self):
	handle = Entrez.efetch("protein", id="783730874", rettype="ipg", retmode="xml")
        records = list(Entrez.parse(handle))
        handle.close()
        self.assertEqual(len(records), 1)
        self.assertTrue("'Product" in records[0])
        self.assertTrue("Statistics" in records[0])
        self.assertTrue("RedundantGiList" in records[0])
```

Also please download an example XML file under ``Tests/Entrez/`` and use is in a similar test under ``test_Entrez.py`` (which can be run offline and would be checked by TravisCI automatically).

The good news is it works for Python 2.7,

```
$ python2.7 -c "from Bio import Entrez; print(list(Entrez.parse(Entrez.efetch('protein', id='783730874', rettype='ipg', retmode='xml'))))"
Bio/Entrez/__init__.py:457: UserWarning: ...
[DictElement({u'Product': DictElement({'data': u'methylmalonate-semialdehydedehydrogenase[Rhodococcussp.PML026]'}, attributes={u'accver': u'WP_045840896.1', u'slen': u'513', u'gi': u'797137454'}), u'Statistics': DictElement({}, attributes={u'nuc_count': u'3', u'prot_count': u'2'}), u'RedundantGiList': [DictElement({u'CDSList': [DictElement({}, attributes={u'kingdom': u'UNRESOLVED', u'stop': u'265978', u'taxid': u'1356405', u'start': u'264437', u'strand': u'-', u'org': u'UNRESOLVED', u'accver': u'NZ_KQ031368.1', u'gi': u'797137657'})]}, attributes={u'kingdom': u'UNRESOLVED', u'priority': u'1', u'source': u'RefSeq', u'org': u'UNRESOLVED', u'accver': u'WP_045840896.1', u'taxid': u'1356405', u'gi': u'797137454'}), DictElement({u'CDSList': [DictElement({}, attributes={u'kingdom': u'UNRESOLVED', u'stop': u'265978', u'taxid': u'1356405', u'start': u'264437', u'strand': u'-', u'org': u'UNRESOLVED', u'accver': u'JZIS01000004.1', u'gi': u'783730637'}), DictElement({}, attributes={u'kingdom': u'UNRESOLVED', u'stop': u'265978', u'taxid': u'1356405', u'start': u'264437', u'strand': u'-', u'org': u'UNRESOLVED', u'accver': u'KQ031368.1', u'gi': u'788037324'})]}, attributes={u'kingdom': u'UNRESOLVED', u'priority': u'60', u'source': u'INSDC', u'org': u'UNRESOLVED', u'accver': u'KJV04014.1', u'taxid': u'1356405', u'gi': u'783730874'})]}, attributes={u'kingdom': u'UNRESOLVED', u'org': u'UNRESOLVED', u'accver': u'KJV04014.1', u'taxid': u'1356405', u'gi': u'783730874'})]
```

The bad news, Python 2.6 is broken (probably ElementTree changes?):

```
$ python2.6 -c "from Bio import Entrez; print(list(Entrez.parse(Entrez.efetch('protein', id='783730874', rettype='ipg', retmode='xml'))))"
Bio/Entrez/__init__.py:457: UserWarning:  ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Bio/Entrez/Parser.py", line 264, in parse
    self.parser.Parse(text, False)
  File "Bio/Entrez/Parser.py", line 315, in startElementHandler
    self.parse_xsd(ET.fromstring(handle.read()))
  File "Bio/Entrez/Parser.py", line 412, in parse_xsd
    for element in list(child.iter()):
AttributeError: _ElementInterface instance has no attribute 'iter'
```

And it is also broken on Python 3,

```
$ python3.3 -c "from Bio import Entrez; print(list(Entrez.parse(Entrez.efetch('protein', id='783730874', rettype='ipg', retmode='xml'))))"
./Bio/Entrez/__init__.py:457: UserWarning: ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./Bio/Entrez/Parser.py", line 264, in parse
    self.parser.Parse(text, False)
  File "./Bio/Entrez/Parser.py", line 305, in startElementHandler
    if len(attrs) > 0 and "http" in attrs.keys()[0]:
TypeError: 'dict_keys' object does not support indexing
```

Since ``some_dict.keys()`` is a generator use ``list(some_dict.keys())`` to get code which will work fine on both Python 2 and 3. However, this code looks fragile since the dictionary key order is not fixed - why are you looking at the first key (element zero)?

**Comment by danich1** [comment]
Sorry for the small delay. I'm graduating from undergrad in a few weeks and have had quite a bit of receptions to attend last week. Nevertheless, I believe I managed to fix the issues that was mentioned earlier. I am working on testing everything tonight or tomorrow night.

Regarding the key() error, I was looking at the first element because I was trying to disassociate the header tag with the rest of the content. Since the parser treats schema files as regular xml files, I needed to check the attrs parameter in the StartElementHandler to see if the name of the xsd file was present. 

To give you a better idea what I am talking about here is an example of the header tag.
\<IPGReportSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ncbi.nlm.nih.gov/data_specs/schema/other/seq_report/IPGReportSet.xsd" \>

The attrs variable will be:
{"http://www.w3.org/2001/XMLSchema-instance" : "http://www.ncbi.nlm.nih.gov/data_specs/schema/other/seq_report/IPGReportSet.xsd"}
I check the key of the dictionary to see if this is present and then grab the name of the xsd file.

**Comment by peterjc** [comment]
Can you assume there will only be one entry in the ``attrs`` dictionary?

**Comment by danich1** [comment]
Sorry for the week delay. I'm approaching finals and I now have time to catch up in everything.  I am now available this week to finish everything. For the question before, yes it is safe to assume there will only be one entry in the attrs dictionary. I made appropriate changes and will be uploading my changes tonight.

**Comment by peterjc** [comment]
Thank you David :)

Given @mdehoon's OK earlier, I went ahead and rebased your commits onto the current master with some minor follow up changes. See https://github.com/biopython/biopython/commit/b7815797145817b3e10cbb1b380c9565cb72214c and the preceding commits.

TravisCI didn't test this due to a merge conflict (``test_ecitmatch`` was added to the ``test_Entrez_online.py`` file recently), but TravisCI skips the online tests anyway.

Ideally we would also have an offline test using XSD files. Would you be able to work on that @danich1 - or just suggest another short example which someone else could turn into an offline test?

**Comment by peterjc** [comment]
@danich1 Hi David. Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898. Thank you.

**Pull request closed without merging**
