### PR TITLE
Refactor GHA CI workflow for speed.

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
A first (or n-th) attempt to use cache to make things a little faster. I also added the `concurrency` keyword which runs only one action/workflow per github branch or reference, and a `timeout` of 20 minutes to the tests to prevent hanging.

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
@peterjc I quit :) I have no idea how to fix the PyPy3 issues. Getting some dependencies built takes forever (10+ min) and testing generally speaking is very slow. 

I would maybe move PyPy3 CI to a different yaml file/workflow and try to make it optional (or run only on push or periodically), otherwise our entire CI is slowed down considerably. What do you think?

I got the docs error to go away, but the RST linting is failing (never worked in GHA) because of this error below. Could you take a look?

```

  # Check sort order (bash call work around for pipe character)
  bash -c \' grep "^- " CONTRIB.rst | LC_ALL=C sort -u -c -f \'
  # Check copyright date
  bash -c \' grep "1999-`date +'%Y'`" LICENSE.rst \'
  # Check no __docformat__ lines
  bash -c "if grep --include '*.py' -rn '^__docformat__ ' Bio BioSQL Tests Scripts Doc ; then echo 'Remove __docformat__ line(s), we assume restructuredtext.'; false; fi"
  # Black style check:
  black --check --diff .
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.6/x64/lib
sort: open failed: "'": No such file or directory
grep: -c: line 0: unexpected EOF while looking for matching `''
grep: -c: line 1: syntax error: unexpected end of file
Error: Process completed with exit code 2.
```

**Comment by peterjc** [comment]
Pragmatic answer: Test pypy with as few dependencies as possible, I would suggest just numpy and mysqlclient as per the old TravisCI setup where again, the pypy tests were the slowest.

**Comment by peterjc** [comment]
And yes, #3682 aims to fix the RST / Sphinx API doc testing

**Comment by JoaoRodrigues** [comment]
Will split pypy3 into its own job (seems the simplest) and keep deps to a minimum, like the macos and windows builds.

**Comment by peterjc** [comment]
I don't immediately see why that grep based linting is failing, but you could try dropping the ``bash -c ...`` bit which was a hack on TravisCI?

**Pull request closed without merging**
