### PR TITLE
MMCIFParser ignore '.' header values

### LINKED ISSUE #3195: 682i.cif fails on parse of resolution to structure header
### Setup

I am reporting a problem with Biopython 1.77, Python 3.8.3 (anaconda July 2020) , and CentOS 7 as follows:

```(base) [mothcw@localhost biopython]$ python
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.10
>>> import Bio; print(Bio.__version__)
1.77
```

### Expected behaviour

682i.cif would load, with no halting exception, with the code:

```
from Bio.PDB import MMCIFParser

mmCIF_parser = MMCIFParser(QUIET=True)
structure_cif = mmCIF_parser.get_structure('6g2i','6g2i.cif')
```
### Actual behaviour

Parsing fails with:

Traceback (most recent call last):
  File "./mmcif_fail.py", line 8, in <module>
    structure_cif = mmCIF_parser.get_structure('6g2i','6g2i.cif')
  File "/home/mothcw/anaconda3/lib/python3.8/site-packages/Bio/PDB/MMCIFParser.py", line 63, in get_structure
    self._structure_builder.set_header(self._get_header())
  File "/home/mothcw/anaconda3/lib/python3.8/site-packages/Bio/PDB/MMCIFParser.py", line 112, in _get_header
    self.header["resolution"] = float(self.header["resolution"])
ValueError: could not convert string to float: '.'

### Steps to reproduce

1) Download (and gunzip) 6g2i.cif from rcsb.  It is a 32MB CryoEM structure.
2) Run this code:
```
$ cat mmcif_fail.py
#!/usr/bin/env python

"""Short program to demonstrate that 6g2i.cif fails to load with biopython 1.77"""

# Parse in the small 6g2i.cif file downloaded from rcsb
from Bio.PDB import MMCIFParser
mmCIF_parser = MMCIFParser(QUIET=True)
structure_cif = mmCIF_parser.get_structure('6g2i','6g2i.cif')

print("Resolution is %s"%structure_cif.header['resolution'])
```
Note the failure message.  

### Towards a fix

There are a couple of problems afoot here.

First, line 113 or so of MMCIFParser.py is not considering _em_3d_reconstruction.resolution to find the 5.8A resolution.  I have added that as a 3rd item in the search keys - and it helps.

```
        self._update_header_entry(
            "resolution", ["_refine.ls_d_res_high", "_refine_hist.d_res_high", "_em_3d_reconstruction.resolution"]
        )
```

HOWEVER, in 6g2i.cif itself there is an empty '.' entry for _**refine.ls_d_res_high**.

_refine.ls_abs_structure_Rogers_esd              ?
_refine.ls_d_res_high                            **.**
_refine.ls_d_res_low                             ?

This period to right of d_res_high could be a bug in the file itself - but I am not totally sure of the regular expression for this field defined at RCSB.

For me right now, I have modifed MMCIFParser.py to treat both lone ? and lone period as missing for purpose of filling in the header.  The bug finally went away when I changed line 84 from:

if item != "?":

to

if item != "?" **and item != ".":**

To my eye this is redundant with the _unassigned idea of line 332.  I recommend that, if this is the same kind of thing, that you centralize the notion of unassigned so we are not patching it multiple places.

May I kindly/friendlysuggest that, at minumum, Biopython should be tested against all .cif files available at rcsb/wwwpdb prior to each release?  This is not such a painful thing to do.  I have to contend that these formally curated and deposited files should not trigger runtime exceptions like this.

Idea: Perhaps more importantly for longer term, this could be yet another case where biopython is stuck in a legacy .PDB-oriented worldview.  Perhaps we need to stop initializing 'header' when working with MMCIF.  For MMCIF files, the parsing of the .cif into the dictionary should be the central/main event, and not have a side-effect of initializing a legacy 'header' (that attempts to recreate PDB REMARK entries).  Once the dictionary is parsed, conversion to a Structure for those who want model/chain/residue/atom traversal might be interesting.  But, resolution should come from the parsed in dictionary - and not be set by code trying to replicate the old REMARK RESOLUTION of the PDB.

### LINKED ISSUE #4397: resolution of 5vrf.cif does not get correctly parsed
### Setup

I am reporting a problem with Biopython 1.81, Python 3.9.16, and Ubuntu 18.04.6 as follows:

```python
Python 3.9.16 (main, May 15 2023, 23:46:34) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.9.16 (main, May 15 2023, 23:46:34) 
[GCC 11.2.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.3.0-47-generic-x86_64-with-glibc2.27
>>> import Bio; print(Bio.__version__)
1.81
```

### Expected behaviour
```python
structure = MMCIFParser(QUIET=True).get_structure('5vrf', '5vrf.cif')
print(structure.header['resolution'])
```
Expected output is 4.1, which is recorded in line 6275 in 5vrf.cif ("_em_3d_reconstruction.resolution                  4.1").

### Actual behaviour
Actual output is None. Probably the resolution is masked by line 609 ("_refine.ls_d_res_high                            . "), as [adam-kral](https://github.com/adam-kral) mentioned in https://github.com/biopython/biopython/pull/3229.

### Steps to reproduce

```python
# download 5vrf.cif, and run:
structure = MMCIFParser(QUIET=True).get_structure('5vrf', '5vrf.cif')
print(structure.header['resolution'])
```

### PR DESCRIPTION
**Pull request by rob-miller**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #4397 
Closes #3195 

Change MMCIFParser to ignore '.' values in header lines same as '?'.
Fix exactly as proposed by @ChrisMoth in #3195.

### CODE REVIEW

**Comment by valentynbez** [comment]
Encountered the same issue, would be great if fixed :)

**Comment by peterjc** [comment]
@JoaoRodrigues @lennax @etal @JoaoRodrigues would any of you be able to comment? I'm encouraged by multiple thumbs up and people affected (but have not used these files personally).

**Comment by JoaoRodrigues** [comment]
Looks good to me. Thanks Rob!

A domingo, 12/11/2023, 15:54, Peter Cock ***@***.***>
escreveu:

**Comment by ChrisMoth** [comment]
Thanks so much for keeping this alive through to the fix.

**Comment by peterjc** [comment]
Thanks all, merged!

**Pull request merged**
