### PR TITLE
Fix "Avoid mutable default arguments" issue

### PR DESCRIPTION
**Pull request by tiagoantao**
This pull request automatically fixes all occurrences of the following issue:

Issue type: [Avoid mutable default arguments](https://www.quantifiedcode.com/app/issue_class/3P0qV6OB)
Issue details: [https://www.quantifiedcode.com/app/project/gh:biopython:biopython?groups=code_patterns/%3A3P0qV6OB](https://www.quantifiedcode.com/app/project/gh:biopython:biopython?groups=code_patterns/%3A3P0qV6OB)

To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.

Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

### CODE REVIEW

**Comment by peterjc** [comment]
This is a reprise of #709 with the minor white space issue I flagged address.

**Comment by peterjc** [comment]
The TravisCI failures are in installing dependencies, likely fall out from https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future - which is likely to delay merging this.

In the meantime, since this touches so many modules we ought to have many eyes look at it (and their bits of Biopython).

In a couple of cases I felt simply switching an argument list of values into a tuple of values would be more elegant, e.g. ``Tests/test_SeqIO_features.py`` uses ``out_formats=["gb", "embl", "imgt"]`` which could be instead ``out_formats=("gb", "embl", "imgt")``. See: https://github.com/biopython/biopython/commit/ded3611d8eb260917dd569cf4c44163e89570811

@tiagoantao I ought to look at their interface, but evidently a re-run of CODY (@quantifiedcode-bot) can be requested - even if it can't yet update an existing pull request by updating/rewriting the branch?

**Comment by programmdesign** [comment]
@peterjc: you can re-run Cody as often as you like. The "Fix automatically" button will only disappear, once you fixed the underlying issues.

**Comment by peterjc** [comment]
https://github.com/biopython/biopython/commit/16092f15dbefaba724901fed001de0af2c1d2027 and https://github.com/biopython/biopython/commit/434f7d540437bfb7c9bad2fc1b71b334d3e52f93 fix some more of these by replacing mutable default arguments (here empty lists) with immutable ones (here empty tuples).

**Comment by peterjc** [comment]
I think all the mutable arguments are fixed as of https://github.com/biopython/biopython/commit/f19a4065f32c6244f0391309c917bb7bf55197b9 and the preceding commits this morning and last night. In a few cases I did use the ``None`` default approach used by @quantifiedcode-bot, but in general on reviewing the code I was able to switch to more specific immutable defaults.

The QuantifiedCode report seems happy now, closing - thank you!

**Pull request closed without merging**
