### PR TITLE
Refactoring Bio.Entrez to test internal details

### PR DESCRIPTION
**Pull request by peterjc**
This is based on pull request #684 from @carlosp420 (after I had cherry-picked the simple changes directly to the master, including renaming the old ``test_Entrez.py`` to ``test_Entrez_parser.py`` in order to allow adding this new ``test_Entrez.py`` file).

I believe this captures the important overall changes from #684, except that I have *excluded* the changes to the post logic. i.e. This pull request should have no functional impact.

@carlosp420 does this look OK to you? e.g. did I miss anything?

@mdehoon could you look this over please?

### CODE REVIEW

**Comment by carlosp420** [comment]
Looks good @peterjc

**Comment by peterjc** [comment]
@carlosp420 Any preference on how we write your name con the copyright lines in the source code? We could use the accented character via PEP263 https://www.python.org/dev/peps/pep-0263/ by adding:

```
# -*- coding: utf-8 -*-
```

There is precedent with ``Bio/motifs/applications/_xxmotif.py`` although we've generally avoided this. See also PEP3120 about Python using URF-8 as the default https://www.python.org/dev/peps/pep-3120/ on Python 3 onwards.

**Comment by carlosp420** [comment]
Hi @peterjc. Using "Pena" is fine, besides being simpler and having zero risk for encoding problems.

**Comment by peterjc** [comment]
Great - applied as f525476b0b4e23313d17ffe8e0565a0f5e17ea8b  and dcb71a5651fb5f1c4bc9722de5d385c5dca9ae31 - thank you!

**Pull request closed without merging**
