### PR TITLE
Bio.phenotype module test speedup

### PR DESCRIPTION
**Pull request by mgalardini**
Same as PR #828, but with faster tests (~15 seconds against ~50, on my machine).

I've also fixed a potential bug when writing plates in JSON format

### CODE REVIEW

**Comment by peterjc** [comment]
Given the scipy testing issue, I'm wondering if the ``.fit()`` method be split in two, so that the no-fitting part can be clearly tested separately from the fitting part which requires SciPy?

**Comment by mgalardini** [comment]
Hi Peter,

that wouldn't change much, as the non-scipy part of the function would still be tested in absence of scipy. I'll try to add a separate test file that can be used under scipy. If you like I can also tweak the travis-CI config files so that we test the fit methods in one python version (say, the latest python 3?)

Marco

**Comment by mgalardini** [comment]
Now the fit method gets tested in python 3.5 only, via the new test_phenotype_fit.py file. I've changed the .travis.yml file so that scipy gets installed in that version only.

**Comment by peterjc** [comment]
I'm testing with a rebased version of this branch and getting a failure on Mac OS X or Linux with Python 3. e.g. On Mac,

```
$ python3.5 -c "import numpy; print(numpy.__version__)"
1.9.2
$ python3.5 -c "import scipy; print(scipy.__version__)"
0.17.0
$ python3.5 test_phenotype.py
test_PlateRecord (__main__.TestPhenoMicro)
Test basic functionalities of PlateRecord objects ... ok
test_PlateRecord_errors (__main__.TestPhenoMicro)
Test bad arguments with PlateRecord objects ... ok
test_WellRecord (__main__.TestPhenoMicro)
Test basic functionalities of WellRecord objects ... ERROR
test_phenotype_IO (__main__.TestPhenoMicro)
Test basic functionalities of phenotype IO methods ... ok
test_phenotype_IO_errors (__main__.TestPhenoMicro)
Test bad arguments to phenotype IO methods ... ok

======================================================================
ERROR: test_WellRecord (__main__.TestPhenoMicro)
Test basic functionalities of WellRecord objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_phenotype.py", line 228, in test_WellRecord
    self.assertAlmostEqual(w.area, 20879.5)
  File "/Users/pjcock/lib/python3.5/unittest/case.py", line 858, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

----------------------------------------------------------------------
Ran 5 tests in 20.185s

FAILED (errors=1)
```

Those libraries were slightly out of date, so I did a pip update:

```
$ python3.5 -c "import numpy; print(numpy.__version__)"
1.11.0
$ python3.5 -c "import scipy; print(scipy.__version__)"
0.17.1
$ python3.5 test_phenotype.py
...
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

And on Linux,

```
$ python3.5 -c "import numpy; print(numpy.__version__)"
1.11.0
$ python3.5 -c "import scipy; print(scipy.__version__)"
0.17.0
$ python3.5 test_phenotype.py 
...
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

Also on Python 3.4 on Linux,

```
$ python3.4 -c "import numpy; print(numpy.__version__)"
1.9.2
$ python3.4 -c "import scipy; print(scipy.__version__)"
0.16.0
$ python3.4 test_phenotype.py 
...
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

Interestingly it works with older versions of SciPy that I had installed for Python 2.6 and 2.7 on my Mac and Linux.

I am currently updating a Python 2.7 installation to try to rule out the NumPy and SciPy version being a factor. Comparing ``None`` was something which changed from Python 2 to Python 3, so that may be the cause of this.

I think method ``test_WellRecord`` and the underlying ``.fit()`` function needs to be split up into a non-scipy minimal version, and a separate test when scipy is available - ideally as a separate file ``Tests/test_phenotype_scipy.py`` so we can see explicitly when this is being skipped due to not having scipy.

**Comment by peterjc** [comment]
Progress - this failure is not due to the version of NumPy or SciPy, but is down to the version of Python (specifically it looks like Python 2 vs 3).

These are on the same 64-bit Linux machine (with Python 2.7 and 3.5 installed from source under the home directory):

```
$ python2.7 -c "import numpy; print(numpy.__version__)"
1.11.0
$ python2.7 -c "import scipy; print(scipy.__version__)"
0.17.1
$ python2.7 test_phenotype.py 
test_PlateRecord (__main__.TestPhenoMicro)
Test basic functionalities of PlateRecord objects ... ok
test_PlateRecord_errors (__main__.TestPhenoMicro)
Test bad arguments with PlateRecord objects ... ok
test_WellRecord (__main__.TestPhenoMicro)
Test basic functionalities of WellRecord objects ... /home/xxx/lib/python2.7/site-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
ok
test_phenotype_IO (__main__.TestPhenoMicro)
Test basic functionalities of phenotype IO methods ... ok
test_phenotype_IO_errors (__main__.TestPhenoMicro)
Test bad arguments to phenotype IO methods ... ok

----------------------------------------------------------------------
Ran 5 tests in 19.362s

OK
```

vs:

```
$ python3.5 -c "import numpy; print(numpy.__version__)"
1.11.0
$ python3.5 -c "import scipy; print(scipy.__version__)"
0.17.1
$ python3.5 test_phenotype.py 
test_PlateRecord (__main__.TestPhenoMicro)
Test basic functionalities of PlateRecord objects ... ok
test_PlateRecord_errors (__main__.TestPhenoMicro)
Test bad arguments with PlateRecord objects ... ok
test_WellRecord (__main__.TestPhenoMicro)
Test basic functionalities of WellRecord objects ... ERROR
test_phenotype_IO (__main__.TestPhenoMicro)
Test basic functionalities of phenotype IO methods ... ok
test_phenotype_IO_errors (__main__.TestPhenoMicro)
Test bad arguments to phenotype IO methods ... ok

======================================================================
ERROR: test_WellRecord (__main__.TestPhenoMicro)
Test basic functionalities of WellRecord objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_phenotype.py", line 228, in test_WellRecord
    self.assertAlmostEqual(w.area, 20879.5)
  File "/home/xxx/lib/python3.5/unittest/case.py", line 858, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

----------------------------------------------------------------------
Ran 5 tests in 17.940s

FAILED (errors=1)
```

Can you reproduce this @mgalardini ?

**Comment by peterjc** [comment]
Here's a proposal that changes the ``.fit()`` API to allow explicit use and testing without SciPy: b716cad8f3f1571627bf7189cf1fefe388844b6f

Part of my rebased branch https://github.com/peterjc/biopython/tree/phenomics

**Comment by peterjc** [comment]
Python 3 specific fit test failure solved, it was a non-Python 3 compatible import error, which was unfortunately being hidden with an unnecessary try/except block:

```
         # Parameters that depend on scipy curve_fit
-        from pm_fitting import fit, get_area
-        from pm_fitting import logistic, gompertz, richards
+        from .pm_fitting import fit, get_area
+        from .pm_fitting import logistic, gompertz, richards
```

**Comment by mgalardini** [comment]
Hi Peter,

I know realise that you were testing a non updated version of the phenotype library; if you have a look at the last travisCI from this PR (https://travis-ci.org/biopython/biopython/jobs/134020063) you will see that the test passed on python 3.5 (where the fit method is tested). I also noticed the import bug and fixed it for python 3, as well as to create a new test_phenotype_fit file.

In any case, I'll implement your proposed change to the fit method in this PR, so that all the changes are in place.

Marco

**Comment by peterjc** [comment]
Thanks - I'd missed your most recent commits including the import fix.

**Comment by mgalardini** [comment]
Provided that the tests pass on Travis all the proposed changes have been added. I have left the exception when the fit method fails, as it's certanly more pythonic.

**Comment by peterjc** [comment]
Do you also see this?

```
$ python3.5 test_phenotype_fit.py
test_WellRecord (__main__.TestPhenoMicro)
Test basic functionalities of WellRecord objects ... /Users/pjcock/lib/python3.5/site-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
ok

----------------------------------------------------------------------
Ran 1 test in 0.315s

OK
```

Are you happy with just hiding the optimisation warning in ``test_phenotype_fit.py`` using:

```
$ git diff
diff --git a/Tests/test_phenotype_fit.py b/Tests/test_phenotype_fit.py
index 818a3d4..a010976 100644
--- a/Tests/test_phenotype_fit.py
+++ b/Tests/test_phenotype_fit.py
@@ -12,6 +12,7 @@ except ImportError:
         "Install NumPy if you want to use Bio.phenotype.")
 try:
     import scipy
+    from scipy.optimize import OptimizeWarning
 except ImportError:
     from Bio import MissingExternalDependencyError
     raise MissingExternalDependencyError(
@@ -43,7 +44,9 @@ class TestPhenoMicro(unittest.TestCase):
                                             signals=dict([(times[i], p['measurements']['A10'][i])
                                                           for i in range(len(times))]))
 
-        w.fit()
+        with warnings.catch_warnings():
+            warnings.simplefilter('ignore', OptimizeWarning)
+            w.fit()
         self.assertAlmostEqual(w.area, 20879.5)
         self.assertEqual(w.model, 'gompertz')
         self.assertAlmostEqual(w.lag, 6.0425868725090357, places=5)
```

**Comment by mgalardini** [comment]
Yes, it is a warning that is commonly seen, will apply the fix to the tests (but not in the fit function)

**Comment by peterjc** [comment]
Rebased and applied to master (including fixing the CVS / CSV typo in the NEWS file), see commits leading up to and including 7deb984b915965c324bb522719bb864f4d3ac981

Thank you @mgalardini :)

**Comment by mgalardini** [comment]
Thank you @peterjc, you have been tremendously helpful and patient!

**Pull request closed without merging**
