### PR TITLE
Iqtree

### PR DESCRIPTION
**Pull request by Erundil95**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #... 
Added command-line wrapper for the phylogenomic inference program IQ-Tree

### CODE REVIEW

**Comment by peterjc** [comment]
You've obviously spent a good chunk of time on this, but what was your impression of the current command line wrapper framework - and do you agree with us deprecating and removing it? See #3344 and discussion on #2877

**Comment by Erundil95** [comment]
> You've obviously spent a good chunk of time on this, but what was your impression of the current command line wrapper framework - and do you agree with us deprecating and removing it? See #3344 and discussion on #2877

Yes i did it as part of a school internship program so it was a nice learning experience, I'm afraid I'm not knowledgeable enough to neither agree nor disagree on the removal of the command line wrapper framework but after reading the discussions I can see how it can be very tedious to maintain, I did have quite a bit of problem myself figuring out input values and even found commands that were not listed in the program's documentation

**Comment by peterjc** [comment]
It would be worth emailing or logging an issue with the IQ-Tree about the commands missing in their documentation - they could easily be unaware of the oversight, and that would make things easier for future users.

**Comment by Erundil95** [comment]
Indeed it would, I will do that today

**Comment by peterjc** [comment]
We've now deprecated the wrapper framework as of #3344, so sadly it does not make sense to merge your code. At least your efforts should improve the base documentation of lqtree. Thank you.

**Pull request closed without merging**
