### PR TITLE
adding a MAF parser and writer to Bio.Align

### PR DESCRIPTION
**Pull request by mdehoon**
This PR adds a parser and writer for Multiple Alignment Format (MAF) files to `Bio.Align`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Does this ignore the existing MAF specific indexing code? That works but was done in text mode rather than binary mode which would have been better for random access, and is likely at the root of various Windows specific issues. See e.g.  #1149 and #3640.

**Comment by mdehoon** [comment]
@peterjc 
> Does this ignore the existing MAF specific indexing code?

Yes it does. `bigMaf` is the established format for random access to `maf` files.

**Comment by peterjc** [comment]
Interesting - I wasn't aware of ``bigMaf`` but that sounds like a better solution long term.

**Review by peterjc — APPROVED** [review]
I've only skimmed this, but seems OK for a squash-and-merge

**Pull request merged**
