### PR TITLE
remove python2 import form Bio/

### PR DESCRIPTION
**Pull request by deepaklorkhatri007**
This pull request addresses issue #...

- [X] I hereby agree to dual-license this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
This looks good, can you switch it from draft to ready? Hopefully that will trigger the automated tests to actually run.

**Comment by peterjc** [comment]
You (or perhaps your editor) has removed some trailing white space in ``Tests/test_AlignIO_ClustalIO.py `` which I think will break the tests. That was part of the later commit doing StringIO changes.

I would have preferred you had just done the raise from changes on this pull request, as that alone was a manageable number of files to review.

**Comment by deepaklorkhatri007** [comment]
My bad, what can i do now to fix that?

**Comment by peterjc** [comment]
Are you OK with me editing the branch? GitHub will let me if you ticked the box to allow edits from maintainers when you made the pull request.

**Comment by deepaklorkhatri007** [comment]
yes I am fine that, please let me know where I can help.

**Comment by peterjc** [comment]
Rebased with ``Tests/test_AlignIO_ClustalIO.py`` tweaked to just edit the import line.

**Comment by peterjc** [comment]
Ah, important whitespace edits in ``Doc/Tutorial/chapter_align.tex`` and ``Tests/test_AlignIO_EmbossIO.py`` too...

**Comment by peterjc** [comment]
If you are interested, what I was doing to undo the white space edits was:

```
$ git checkout master Doc/Tutorial/chapter_align.tex # revert to original version
$ emacs Doc/Tutorial/chapter_align.tex # edit just the import line
$ git commit --amend Doc/Tutorial/chapter_align.tex # revise the commit
```

And then doing a forced push to update the pull request (about the only time you ever need to use ``--force`` with ``git push``).

**Comment by deepaklorkhatri007** [comment]
@peterjc thanks for describing the process, I will keep the steps in mind.

**Comment by peterjc** [comment]
White space changes in doctests are tricky since perfect matches are required. It took me a couple of goes to find all the files.

**Comment by peterjc** [comment]
Merged, thank you!

**Comment by deepaklorkhatri007** [comment]
@peterjc tests are failing for master branch on my computer
```
Ran 525 tests in 289.586 seconds

FAILED (failures = 253)
```
I am running the `$ git pull upstream master` command from yesterday but tests are still failing. can I just do my work and send a pull request?

```
From https://github.com/biopython/biopython
 * branch                master     -> FETCH_HEAD
Already up to date.
```

**Comment by peterjc** [comment]
It sounds like you have accidentally made changes to your master branch (which should stay the same as the official upstream/master). Maybe this will help:

```
git fetch upstream # no changes, just updates cache of upstream
git checkout -b local_changes  # put your changes on a named branch
git branch -D master # delete master
git checkout -t upstream/master # take a clean copy of master
```

**Comment by deepaklorkhatri007** [comment]
@peterjc thank you so much for the suggestion I learned something new today, the problem was not in the files it is that I was not running `python setup.py build` before the testing command `python setup.py test` now it seems fine.

**Pull request merged**
