### PR TITLE
Add install instructions for conda

### PR DESCRIPTION
**Pull request by saketkc**

### CODE REVIEW

**Comment by peterjc** [comment]
You need to fix the line wrapping, try to keep to 78 characters for people reading this file at the terminal.

**Comment by peterjc** [comment]
Could you bring this up on the dev mailing list please, as I'd like more input on this potentially controversial change? Can we move towards providing Windows binary wheels for pip install instead?

**Comment by saketkc** [comment]
I am not sure we reached a consensus. Feel free to close it, though I have re-worded it based on comments received on mailing list.

**Comment by peterjc** [comment]
I'm happy to recommend conda on Windows over our installers.

I'm hoping we can do binary wheels for the next release, which will make ``pip install biopython`` a good cross platform choice.

**Pull request closed without merging**
