### PR TITLE
Allow parsing of TRANSFAC files that have only one space as separator…

### PR DESCRIPTION
**Pull request by ghuls**
… between field and value.

Some TRANSFAC files use a TAB instead of 2 or more spaces as separator
between field and value. The old code assumed that the value part
of a line always starts at position 4.

This patch also allows to parse motif matrix lines which do not have
a leading "0" for numbers smaller or equal than 9.
## Example matrix:

NA  ALX1.p2
PO  A   C   G   T
1   79.334802   30.187075   11.671023   39.11148
2   75.758951   39.804695   33.95761    10.783124
3   49.264106   46.809618   10.776781   53.453875
4   1.624345    0.749118    0   157.930917
5   136.373394  4.4525  5.369937    14.108549
6   158.727167  0   0   1.577213
7   1.508366    7.678933    0.690944    150.426137
8   0.695534    11.381705   13.351513   134.875628
9   88.004985   21.998116   16.720946   33.580333
10  47.758261   39.506319   24.613038   48.426762
11  31.136202   60.868109   7.840269    60.4598
12  145.395351  0.962932    10.806892   3.139205
13  0.692268    10.059374   1.564066    147.988672
14  9.51174 7.890105    0   142.902535
15  118.052898  3.531078    27.492738   11.227666
16  14.304979   27.682412   31.513372   86.803617
17  17.672332   66.136874   11.206336   65.288838
18  58.639634   21.05798    18.928821   61.677945
//

### CODE REVIEW

**Comment by peterjc** [comment]
This looks good (not my area of the code though - over to @mdehoon or @barwil for that), but could you turn the example into an actual test case called from ``test_motifs.py`` please?

**Comment by ghuls** [comment]
I added the motif to the unit test.

Another possible TRANSFAC related "fix" if this kind of change is accepted:
**Allow parsing of TRANSFAC matrices where the first matrix line starts with 00 instead of 01 (or not): ** https://github.com/biopython/biopython/issues/550

**Comment by mdehoon** [comment]
@ghuls 
> Some TRANSFAC files use a TAB instead of 2 or more spaces as separator
between field and value. 
Are these official TRANSFAC files? Or TRANSFAC files generated by somebody else?

**Comment by ghuls** [comment]
They are generated by other people.

Examples:

**Regulatory motifs (weight matrices)** Homo Sapiens hg19 on http://swissregulon.unibas.ch/fcgi/sr/downloads has a TAB as separator.

**HOCOMOCOv9_AD_TRANSFAC.txt** on http://autosome.ru/HOCOMOCO/Download.php has matrices that start with 00 instead of 01.

**Comment by mdehoon** [comment]
Then I think it is better to fix those files, rather than changing the parser in Biopython.

**Comment by peterjc** [comment]
As a compromise (assuming the spaces vs tab issue is well defined in the TRANSFAC format), we could tolerate a tab but issue a ``BiopythonParserWarning``? I don't know how analogous this situation is, but with the NCBI GenBank format there are a lot of invalid files produced by other tools where we try to handle some of the abuses (as long as this isn't ambiguous) but give a warning message.

**Comment by mdehoon** [comment]
I think it is too much of a corner case. Just email the SwissRegulon and Hocomoco maintainers and let them know their format is not quite consistent with the TRANSFAC format. Or send them a new file with the formatting issues fixed. Both of SwissRegulon and Hocomoco are made by our Fantom collaborators who in my experience are very helpful.

**Comment by peterjc** [comment]
Thanks @mdehoon - it does sound like improving SwissRegulon and Hocomoco would be best here :)

Are you happy to contact them @ghuls?

**Comment by ghuls** [comment]
@peterjc
I already contacted them before making this pull request.
HOCOMOCO will fix it in the next release (so not in the current v9).

SwissRegulon also promised to fix it.

I still think that I have seen other TRANSFAC-like files that also gave problems.

I think it would still be great if **parse** and **read** in **Bio/motifs/__init__.py** would have an additional argument that would allow to disable strict parsing:
```
parse(handle, format, strict=True)
read(handle, format, strict=True)
```
This would allow to read this slightly wrong TRANSFAC-like (and optionally other formats) files and write fixed versions of the files with the write method.

**Comment by peterjc** [comment]
Have both HOCOMOCO and SwissRegulon fixed their files now? If so can we close this?

Personally I would prefer using warnings over adding a strict mode option. If you want strict mode, Python allows you to upgrade the warnings to exceptions.

**Comment by ghuls** [comment]
SwissRegulon seems to be fixed.

HOCOMOCO is still a problem:

HOCOMOCO v10: http://hocomoco.autosome.ru/final_bundle/HUMAN/mono/HOCOMOCOv10_HUMAN_mono_transfac_format.txt
```
VV	HOCOMOCOv10, SEP 2015
XX
//
AC	M01001
XX
ID	AHR_HUMAN.H10MO.B
XX
NA	AHR_HUMAN
XX
BF	AHR_HUMAN; Species: human, Homo sapiens
XX
P0	A	C	G	T
01	41	18	56	39	d
02	11	12	35	96	K
03	22	44	21	67	h
04	3	1	146	4	G
05	1	150	1	2	C
06	3	1	149	1	G
07	0	3	1	150	T
08	0	0	154	0	G
09	43	67	16	28	h
XX
//
AC	M01002
XX
ID	AIRE_HUMAN.H10MO.C
XX
NA	AIRE_HUMAN
XX
BF	AIRE_HUMAN; Species: human, Homo sapiens
XX
P0	A	C	G	T
01	16	11	5	9	h
02	8	8	6	19	n
03	6	6	8	21	n
04	2	0	36	3	G
05	0	0	33	8	G
06	13	2	1	25	W
07	16	4	1	20	W
08	15	6	6	14	n
09	14	3	6	18	d
10	21	4	6	10	d
11	16	2	3	20	W
12	9	6	3	23	W
13	0	1	36	4	G
14	0	0	40	1	G
15	9	4	10	18	d
16	3	8	8	22	b
17	18	1	7	15	W
18	17	11	4	9	h
XX
//
```

HOCOMOCO v9: http://autosome.ru/HOCOMOCOS/downloads/HOCOMOCOv9_AD_TRANSFAC.txt
```
VV  HOCOMOCO-AD MATRIX TABLE, build9-MAR2012
XX
//
ID  AHR_si
XX
NA  AHR
XX
BF  AHR_HUMAN; Species: human, Homo sapiens.
XX
P0      A      C      G      T
00     41     18     56     39
01     11     12     35     96
02     22     44     21     67
03      3      1    146      4
04      1    150      1      2
05      3      1    149      1
06      0      3      1    150
07      0      0    154      0
08     43     67     16     28
XX
//
ID  AIRE_f2
XX
NA  AIRE
XX
BF  AIRE_HUMAN; Species: human, Homo sapiens.
XX
P0      A      C      G      T
00     16     11      5      9
01      8      8      6     19
02      6      6      8     21
03      2      0     36      3
04      0      0     33      8
05     13      2      1     25
06     16      4      1     20
07     15      6      6     14
08     14      3      6     18
09     21      4      6     10
10     16      2      3     20
11      9      6      3     23
12      0      1     36      4
13      0      0     40      1
14      9      4     10     18
15      3      8      8     22
16     18      1      7     15
17     17     11      4      9
XX
```

**Comment by peterjc** [comment]
@ghuls: It seems worth contacting HOCOMOCO again.

@mdehoon: Would you be OK with parsing these files with a warning?

**Comment by ghuls** [comment]
@peterjc: I contacted them again. I still think it would be useful to allow BioPython parse this files, as this would allow to read this (broken) files and write a fixed version immediately.

**Comment by VorontsovIE** [comment]
Hi all! I'm one of HOCOMOCO-10 maintainers.
We've fixed files so that line header is separated from values by two spaces (columns are still separated by tabs; seems it doesn't matter).
While updated files should work with BioPython (I've asked @ghuls to test them, if they still don't work, we'll fix them again), I want to endorse this pull request.

The main reason is an absence of well documented TRANSFAC format (if I'm wrong, please direct me to it).

Description on MEME site (meme-suite.org/doc/transfac-format.html) doesn't mention any certain separator. Formatted sample on biopython site itself doesn't follow two-space rule (http://biopython.org/DIST/docs/tutorial/Tutorial#htoc216), in HTML there're 6-spaces after 2 letters of header, which makes me think that originally it was a tab character (with 8 spaces per tab editor setting).
So there's no way to construct file formatted appropriately for bioPython use without reading actual library code.

What is much worse, there're no guarantees that other tools which work with TRANSFAC-formatted files use the same parsing assumptions about file format. I'm afraid that this fix will cause errors for other users of HOCOMOCO. So I'm a proponent of the most permissive format until it makes different interpretations possible. What's the reason to check whether there're spaces or tabs? What's the reason to check, whether there're 0-indexed or 1-indexed position numbers, zero-prefixed or not? It just makes format less usable and less portable.

**Comment by peterjc** [comment]
Hi @VorontsovIE - its great to hear you're tweaking the HOCOMOCO files for wider compatibility. I'm very sympathetic to dealing with poorly defined file formats.

Is there an official definition of the TRANSFAC format (even if incomplete)?

@mdehoon unless you object, I would like to merge this pull request at the end of this week. I agree asking the database providers to fix their files for consistency was a good desicision, and that has now happened.

Regarding the HTML rendering of the TRANSFAC example in the tutorial, the LaTeX source uses spaces, but I have not looked over the history to see if that was always the case. A pull request to tweak file ``Doc/Tutorial/chapter_motifs.tex`` would be welcome. Would you like to do that @ghuls?

**Comment by ghuls** [comment]
@peterjc: The extra spaces (more than 2) are only there for P0, PO and matrix lines, to make the matrix right aligned by column.

Here an example for a HOCOMOCO matrix:
```
# First matrix of HOCOMOCO v10:
In [22]: ! grep -A19 -m1 '^AC' HOCOMOCOv10_HUMAN_mono_transfac_format.txt
AC  M01001
XX
ID  AHR_HUMAN.H10MO.B
XX
NA  AHR_HUMAN
XX
BF  AHR_HUMAN; Species: human, Homo sapiens
XX
P0  A	C	G	T
01  41	18	56	39	d
02  11	12	35	96	K
03  22	44	21	67	h
04  3	1	146	4	G
05  1	150	1	2	C
06  3	1	149	1	G
07  0	3	1	150	T
08  0	0	154	0	G
09  43	67	16	28	h
XX
//

# Same matrix after parsing in biopyton and writing it out again.
In [23]: print hocomoco_M01001.format('transfac')
AC  M01001
XX
ID  AHR_HUMAN.H10MO.B
XX
NA  AHR_HUMAN
XX
BF  AHR_HUMAN; Species: human, Homo sapiens
XX
P0      A      C      G      T
01     41     18     56     39      N
02     11     12     35     96      T
03     22     44     21     67      N
04      3      1    146      4      G
05      1    150      1      2      C
06      3      1    149      1      G
07      0      3      1    150      T
08      0      0    154      0      G
09     43     67     16     28      N
XX
//

# Format string used by biopython for matrix lines (applied to the first line of the matrix).
In [24]: '%02.d %6.20g %6.20g %6.20g %6.20g      %s' % (1, 41, 18, 56, 39, 'd')
Out[24]: '01     41     18     56     39      d'

```

**Comment by ghuls** [comment]
@mdehoon 
```python
import warnings
import Bio.motifs

from Bio import BiopythonParserWarning

warnings.simplefilter('always', BiopythonParserWarning)

fh = open('/tmp/HOCOMOCOv9_AD_TRANSFAC.txt', 'r')

m = Bio.motifs.parse(fh, 'transfac')
/home/ghuls/virtualenv/biopython-git/lib/python2.7/site-packages/Bio/motifs/transfac.py:103: BiopythonParserWarning: A TRANSFAC matrix should have 2 spaces between key and value columns: "AC M00000"
  BiopythonParserWarning)
/home/ghuls/virtualenv/biopython-git/lib/python2.7/site-packages/Bio/motifs/transfac.py:103: BiopythonParserWarning: A TRANSFAC matrix should have 2 spaces between key and value columns: "NA AHR"
  BiopythonParserWarning)
/home/ghuls/virtualenv/biopython-git/lib/python2.7/site-packages/Bio/motifs/transfac.py:103: BiopythonParserWarning: A TRANSFAC matrix should have 2 spaces between key and value columns: "BF	AHR_HUMAN; Species: human, Homo sapiens."
  BiopythonParserWarning)
/home/ghuls/virtualenv/biopython-git/lib/python2.7/site-packages/Bio/motifs/transfac.py:138: BiopythonParserWarning: A TRANSFAC matrix should have a 2 digit key at the start ("03"), but this matrix uses "3" instead at line: "3 22     44     21     67".
  BiopythonParserWarning)
/home/ghuls/virtualenv/biopython-git/lib/python2.7/site-packages/Bio/motifs/transfac.py:138: BiopythonParserWarning: A TRANSFAC matrix should have a 2 digit key at the start ("04"), but this matrix uses "4" instead at line: "4 3      1    146      4".
  BiopythonParserWarning)
/home/ghuls/virtualenv/biopython-git/lib/python2.7/site-packages/Bio/motifs/transfac.py:130: BiopythonParserWarning: A TRANSFAC matrix should start with "01", but this file uses "00" instead: "00     16     11      5      9"
  BiopythonParserWarning)
/home/ghuls/virtualenv/biopython-git/lib/python2.7/site-packages/Bio/motifs/transfac.py:138: BiopythonParserWarning: A TRANSFAC matrix should have a 2 digit key at the start ("07"), but this matrix uses "7" instead at line: "7     15      6      6     14".
  BiopythonParserWarning)
```

Here is a new patch which uses BiopythonParserWarnings:
  - uses line.split(None, 1) to split each line in two field on whitespace
  - it checks if each line contains a key of 2 characters, else assert
  - it check if each line has 2 spaces as separator, else BiopythonParserWarning warning
  - for matrix:
      - works if line only as a number of 1 character ( line.split(None, 1) ) ==> BiopythonParserWarning
      - BiopythonParserWarning if matrix starts with "00".
      - BiopythonParserWarning if not at least 2 spaces after starting number
      - assert if number of values is not equal to 4

I noticed that the asserts do not give any info to the user of what the problem might be.
```diff
diff --git a/Bio/motifs/transfac.py b/Bio/motifs/transfac.py
index a6c0473..3b301a8 100644
--- a/Bio/motifs/transfac.py
+++ b/Bio/motifs/transfac.py
@@ -6,7 +6,8 @@
 """Parsing TRANSFAC files
 """
 
-from Bio import motifs
+import warnings
+from Bio import BiopythonParserWarning, motifs
 from Bio.Alphabet import IUPAC
 
 
@@ -90,7 +91,16 @@ def read(handle):
     record = Record()
     for line in handle:
         line = line.strip()
-        key, value = line[:2], line[4:]
+        if not line:
+            continue
+        key_value = line.split(None, 1)
+        key = key_value[0].strip()
+        if len(key_value) == 2:
+            value = key_value[1].strip()
+            if not line.partition('  ')[1]:
+                warnings.warn('A TRANSFAC matrix should have 2 spaces between key and value columns: "{0:s}"'.format(line),
+                              BiopythonParserWarning)
+        assert len(key) == 2
         if key == 'VV':
             record.version = value
         elif key in ('P0', 'PO'):  # Old TRANSFAC files use PO instead of P0
@@ -100,14 +110,33 @@ def read(handle):
             for c in "ACGT":
                 counts[c] = []
             for line in handle:
-                key, value = line[:2], line[4:]
+                line = line.strip()
+                key_value = line.split(None, 1)
+                key = key_value[0].strip()
+                if len(key_value) == 2:
+                    value = key_value[1].strip()
+                    if not line.partition('  ')[1]:
+                        warnings.warn('A TRANSFAC matrix should have 2 spaces between key and value columns: "{0:s}"'.format(line),
+                                      BiopythonParserWarning)
                 try:
                     i = int(key)
                 except ValueError:
                     break
-                length += 1
+                if length == 0 and i == 0:
+                    warnings.warn(
+                        'A TRANSFAC matrix should start with "01", but this file uses "00" instead: "{0:s}"'.format(line),
+                        BiopythonParserWarning)
+                else:
+                    length += 1
                 assert i == length
+                if len(key) == 1:
+                    warnings.warn(
+                        'A TRANSFAC matrix should have a 2 digit key at the start ("{0:02d}"), but this matrix uses "{0:d}" instead at line: "{1:s}".'.format(
+                            i, line),
+                        BiopythonParserWarning)
+                assert len(key_value) == 2
                 values = value.split()
+                assert len(values) == 4
                 for c, v in zip("ACGT", values):
                     counts[c].append(float(v))
         if line == 'XX':
```

**Comment by peterjc** [comment]
@ghuls other than putting this import on two lines, that looks sensible to me:

``` python
from Bio import BiopythonParserWarning, motifs
```

Can you turn it into a pull request?

**Comment by ghuls** [comment]
@mdehoon and @peterjc:  See "Improve parsing and error checking and reporting for TRANSFAC motifs." pull request https://github.com/biopython/biopython/pull/1018

If that one is merged, it would close this issue and https://github.com/biopython/biopython/issues/550

**Comment by peterjc** [comment]
#1018 was merged, so as @ghuls suggested I am closing this now.

**Pull request closed without merging**
