### PR TITLE
Add STANDARD datatype support to Nexus parser

### PR DESCRIPTION
**Pull request by JoeCora**
The Nexus parser within BioPython did not support the STANDARD datatype for the Nexus file format, which holds discrete character information. These changes add support for discrete (STANDARD) character data to the parser but not CONTINUOUS data. A test suite was also included within the Nexus.py file to check for proper parsing of supported Nexus blocks within included test files. A handful of minor cosmetic changes were also made.

### CODE REVIEW

**Comment by etal** [comment]
Thanks for this. I reviewed the code and sprinkled my comments inline. General comments:

- I admit I didn't fully understand all of the changes, so some of my comments may be inane. Sorry if they are. Would you mind quickly describing the major code changes here for us, and if/how they affect existing functionality?
- I see a lot of whitespace changes meant to improve code style/appearance. The changes that don't affect functionality clutter up the diff, making it hard to see where the important bits are and how they interact. Our in-house style guide here at Biopython is Python's [PEP8](https://www.python.org/dev/peps/pep-0008/) and there are some automated tools for detecting and correcting stylistic features like whitespace. Ideally the style changes would be consolidated in a separate commit from the functional code changes to ease reviewing. If that sounds like a pain at this point, given the work you've already done, then I suggest running autopep8 to get things in our preferred style and then squashing the commits together.
- The unit tests and test cases look great.

**Comment by JoeCora** [comment]
I think I addressed all of @etal's concerns and suggestions with the above comments and the latest commit.

There is a pre-existing bug within the core Nexus parser that I described here: https://github.com/biopython/biopython/pull/562#commitcomment-11775048. This should probably be added as a formal, non-urgent bug.

Nothing within this these commits affect existing Nexus parser class functionality.

**Comment by etal** [comment]
Thanks, Joe. I squashed your changes into a single commit, applied some autopep8, and merged it.

Would you like to be added to Biopython's list of contributors for the next release?

**Comment by JoeCora** [comment]
Sure.

- Joe

**Pull request closed without merging**
