### PR TITLE
Fix ladderize (#3780)

### PR DESCRIPTION
**Pull request by anders-was-here**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #...

### CODE REVIEW

**Comment by anders-was-here** [comment]
Not sure why black failed on Tests/test_Nexus.py - too long row maybe?

**Comment by erik-whiting** [comment]
hey @anders-was-here I'm not a maintainer but the pre-commit black fail had me curious and I think I figured it out. It doesn't like line 1046. I'm not exactly sure why, but I played around with it locally and this got rid of the pre-commit failure:
```python
tree_a_val = "((A 6,(B 9,(C 8,C 4))),t2,((E 0,E 7),(F 1,(G 5,G 3))));"
self.assertEqual(t.to_string(ladderize="LEFT"), "tree a_tree = " + tree_a_val)
```
Also, I think you should give that test a doc string (a like after the `def` line that's like `"""This tests some thing"""`)

**Comment by anders-was-here** [comment]
> hey @anders-was-here I'm not a maintainer but the pre-commit black fail had me curious and I think I figured it out. It doesn't like line 1046. I'm not exactly sure why, but I played around with it locally and this got rid of the pre-commit failure:
> 
> ```python
> tree_a_val = "((A 6,(B 9,(C 8,C 4))),t2,((E 0,E 7),(F 1,(G 5,G 3))));"
> self.assertEqual(t.to_string(ladderize="LEFT"), "tree a_tree = " + tree_a_val)
> ```
> 
> Also, I think you should give that test a doc string (a line after the `def` line that's like `"""This tests some thing"""`)

After reading up on pre-commit and black my conclusion is that this was a false positive from the configured black version (black==19.10b0).

The code seems to be OK with the latest black (21.10b0).

**Comment by peterjc** [comment]
Currently pre-commit is configured to use black 21.07b, so that might also have an issue with this line.

**Comment by anders-was-here** [comment]
#3781

**Comment by peterjc** [comment]
Thank you

**Pull request merged**
