### PR TITLE
mmCIF reader always reads in lists

### PR DESCRIPTION
**Pull request by jgreener64**
This pull request addresses issue #1533 and #1884.

I *keep* running into the following gotcha when reading in mmCIF files: single values are read in as a string rather than a list, so when you iterate over them you get characters rather than the desired list items. This leads to cryptic errors such as `ValueError: could not convert string to float: '-'`, see the discussion on the issues above for more. The silent version of the error is even worse as you don't see it messing up your data.

This PR makes everything a list, even if it only contains one item. The advantages are that everything is consistent and that you won't get the above error. The disadvantages are that things with only a single value (e.g. title) will always be in a list, and that it will likely break people's code. The change would need to be communicated clearly for this reason.

Does anybody who uses the mmCIF parser have input here?

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
The proposed behaviour seems appropriate and matches a similar example with the GenBank parser where for feature annotation we consistently use lists even when for some cases one value is only ever expected.

This would need some kind of entry in the ``NEWS.rst`` file (along with ideally including your name too).

**Comment by jgreener64** [comment]
Great, have made those changes.

**Comment by peterjc** [comment]
Oh good, you updated the Tutorial too 👍

**Comment by peterjc** [comment]
Other than @JoaoRodrigues (review requested), are there any other structure folk who might want to comment on this mmCIF reader change - @lennax maybe?

**Comment by StefansM** [comment]
I got pinged by a linked ticket, so I thought I'd offer my 2p.

I unfortunately no longer have the pleasure of working with mmCIF files, but I remember this being a particularly annoying pain point. In the absence of a proper validating grammar (STAR doesn't count) and authors that stick to it (ha ha), I think this is the best that can be done.

Big :+1: for Joe's changes.

**Comment by jgreener64** [comment]
Thanks for the input @StefansM, and hope you are getting on okay!

**Comment by peterjc** [comment]
Hopefully Joao will get to look at this soon (not sure what his travel plans are after BOSC 2019 and the CoFest), but this looks ready to merge 👍

**Comment by peterjc** [comment]
Rebasing and fixing quotes conflict...

**Comment by peterjc** [comment]
Thanks Joe!

**Comment by jgreener64** [comment]
Thanks for the merge Peter.

**Pull request merged**
