### PR TITLE
Fixed a small typo in the Bio.Medline.parse() docstring

### PR DESCRIPTION
**Pull request by andrewbarros**

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks - well spotted. Would you like to be thanked in the ``NEWS`` and ``CONTRIB`` file, or would you prefer to wait until you've made a larger contribution?

**Comment by andrewbarros** [comment]
I feel like one character diffs don't really warrant a thanks. 

I'll wait. 

    --ajb

**Comment by peterjc** [comment]
Thanks, looking forward to future contributions small or large :)

**Comment by peterjc** [comment]
It may not really be necessary for this little fix, but would you agree to dual licence your Biopython contributions under the *Biopython License Agreement* and the *BSD 3-Clause License* as per #898 please?

**Comment by andrewbarros** [comment]
I agree to this request.

**Comment by peterjc** [comment]
Thank you.

**Pull request closed without merging**
