### PR TITLE
Fix parsing of DBLINK field with multiline records

### PR DESCRIPTION
**Pull request by starling13**
This pull request addresses issue #3196

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by starling13** [comment]
Can someone help to understand, what's wrong with tests?

**Comment by peterjc** [comment]
Style checking tool flake8 was complaining:

```
$ flake8
./Bio/GenBank/Scanner.py:1646:48: Q000 Remove bad quotes
./Bio/GenBank/Scanner.py:1648:41: Q000 Remove bad quotes
```

If you run the command line tool black it will fix these, and edit those lines using single quotes to use double quotes instead.

(Note in the meantime we have reworked our flake8 setup and recommended git pre-commit hook to run via the pre-commit tool, the ``CONTRIBUTING.rst`` file has been updated)

**Comment by starling13** [comment]
Can't realize, why codecov reports significant coverage loss with such a simple and local change, covered by unit test.

**Comment by peterjc** [comment]
See #3752 for the unexplained coverage fluctuations.

**Comment by peterjc** [comment]
The CircleCI failure is unexpected, perhaps a configuration default changed on their side...

**Comment by peterjc** [comment]
Nice to see the test case included. The code changes look sensible, @MarkusPiotrowski are you available for a second opinion?

**Pull request merged**
