### PR TITLE
Standardized import numpy as np

### LINKED ISSUE #4238: Standardize on import numpy as np
I think we should follow the numpy documentation and avoid the plain ``import numpy`` form in favour of ``import numpy as np``.

With the current code base:

```
$ cat *.py */*.py */*/*.py | grep "import numpy" | sort | uniq -c
   1         >>> import numpy
   9     import numpy
   3     import numpy as np
   1     import numpy as np  # type: ignore
  17 import numpy
   1 import numpy  # type: ignore
   8 import numpy as np
   1 import numpy as np  # type: ignore
   1 import numpy.linalg
```

This is a fairly simple change with search-and-replace (e.g. using ``sed`` at the command line), suitable for a first-time contributor so marking as such.

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)
Added my name to CONTRIB.rst. Don't know where to add in NEWS.rst.

 Replaced `import numpy` with `import numpy as np`

Closes #4238.

### CODE REVIEW

**Comment by PaarthAgarwal** [comment]
more complicated than I though initially

**Comment by peterjc** [comment]
Lines like this won't work:

```
from np import dot, transpose, sqrt
```

Leave them as they were:

```
from numpy import dot, transpose, sqrt
```

Or possibly use ``import numpy as np`` and then use ``np.dot`` etc but that's more work and more chances of a mistake.

**Comment by mdehoon** [comment]
> Lines like this won't work:
> 
> ```
> from np import dot, transpose, sqrt
> ```
> 
> Leave them as they were:
> 
> ```
> from numpy import dot, transpose, sqrt
> ```
> 
> Or possibly use `import numpy as np` and then use `np.dot` etc but that's more work and more chances of a mistake.

Don't fix what is not broken ;-).

**Comment by pvalle6** [comment]
I would say its best to start with the easier files where only `import numpy as np` before the other modules.

**Comment by pvalle6** [comment]
@PaarthAgarwal Would you accept pull requests into your fork in this PR? I could help out.

**Comment by peterjc** [comment]
This needs merge conflicts to be resolved and other problems solved. Given no activity I'm going to close this. You're welcome to update the branch and reopen it, but perhaps a new branch and new pull request would be better. Thank you.

**Pull request closed without merging**
