### PR TITLE
Add support for passing sets to Entrez.efetch()

### PR DESCRIPTION
**Pull request by austinv11**
I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Accepting a set seems like a bad idea to me in that you have no control over the order the records will be requested in. Does this not matter in your use case? Should we sort the set entries for reproducibility?

Separately, could you add a test for this (maybe modify one of the existing tests using a list to use a set instead)?

Note that TravisCI/AppVeyor are setup to skip the online only tests, so will not be checking your work here.

**Comment by mdehoon** [comment]
I'm OK with this, but we could generalize it further, as in
```python
    try:
         ids = ",".join(ids)
    except TypeError:
         if isinstance(ids, int):
            ids = str(ids)
```

**Comment by austinv11** [comment]
Sorry, I was away.

@peterjc Providing a set implies that the user doesn't care about the order. So I don't think it matters. 

But I will be add the test and @mdehoon's suggestion when I get a chance

**Comment by peterjc** [comment]
I'm happy - over to @mdehoon 

P.S. @austinv11 are you happy to be named in ``NEWS.rst`` for the next release too?

**Comment by austinv11** [comment]
Sure I would be happy to be named in the `NEWS.rst` file.

**Comment by austinv11** [comment]
@mdehoon So do you want me to convert strings to ints and back to strings again to ensure that they are ints?

**Comment by mdehoon** [comment]
@austinv11  No, but in the section
```python
    try:
        ids = variables["id"]
    except KeyError:
        pass
    else:
        try:
            ids = ",".join(ids)
        except TypeError:
            if isinstance(ids, int):
                ids = str(ids)
```
we need an `else` clause, like this:
```python
    try:
        ids = variables["id"]
    except KeyError:
        pass
    else:
        try:
            ids = ",".join(ids)
        except TypeError:
            if isinstance(ids, int):
                ids = str(ids)
            else:
                # raise an exception
```

**Comment by peterjc** [comment]
@mdehoon are you happy so merge this? Does it need anything in the docstring about the lack of any explicit set-order and thus the results order?

**Comment by peterjc** [comment]
I'll rebase this and merge it outside of GitHub (can't update this branch).

**Comment by peterjc** [comment]
Changes applied, thank you!

**Pull request closed without merging**
