### PR TITLE
Speed up SeqIO.parse() for fastq

### PR DESCRIPTION
**Pull request by chris-rands**
If I understand the original implementation correctly, this should be identical functionally but substantially faster.

Original:
```
$ time python3 bench.py biofast-data-v1/M_abscessus_HiSeq.fq 
1.77
5682010	568201000	568201000

real	1m23.955s
user	1m22.737s
sys	0m0.783s
```

This branch:
```
$ time python3 bench.py biofast-data-v1/M_abscessus_HiSeq.fq 
1.77
5682010	568201000	568201000

real	1m2.695s
user	1m5.747s
sys	0m0.876s
```

Benchmark script modified from [biofast](https://github.com/lh3/biofast):
```
$ cat bench.py 
import Bio; print(Bio.__version__)

if __name__ == "__main__":
    from Bio import SeqIO
    import sys, re, gzip
    if len(sys.argv) == 1:
        print("Usage: fqcnt.py <in.fq.gz>")
        sys.exit(0)
    fn = sys.argv[1]
    if re.search(r'\.gz$', fn):
        fp = gzip.open(fn, 'rt')
    else:
        fp = open(fn, 'r')
    n, slen = 0, 0
    for seq in SeqIO.parse(fp, "fastq"):
        n += 1
        slen += len(seq)
    print('{}\t{}\t{}'.format(n, slen, slen))
```

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good - using dictionary comprehensions is a nice stylistic change not available at the time this was written.

I forget now if I ever tried this approach (try/except for validation), perhaps back in the Python 2 era is was slower? That doesn't really matter - this clearly wins on the current Python versions.

**Comment by peterjc** [comment]
#2907 is merged doing the version bump and starting a NEWS entry for the next release.

Do you agree this speedup probably deserves a small mention there?

You can add your name to the contributors to the next release too.

**Comment by chris-rands** [comment]
Thanks Peter, sure, I updated the NEWS. I didn't time this on Py 2, but I think the main reason for the speed-up is because I build smaller dicts and then avoid the O(N) `max()` and `min()` checks

**Comment by peterjc** [comment]
Good job 🥇

**Pull request merged**
