### PR TITLE
Misc docstring and __all__ updates for documentation

### PR DESCRIPTION
**Pull request by peterjc**
These changes are from work on #1388 getting Biopython's docstrings to work nicely with Sphinx and numpydoc.

Most are cosmetic, but the ``__all__`` changes are functional.

Requesting comments from authors/maintainers of changed files including @widdowquinn @bow @zruan @andreas-wilm @cbrueffer @etal @stevemmarshall @MarkusPiotrowski @chapmanb @mdehoon

### CODE REVIEW

**Comment by etal** [comment]
Looks good to me. :+1:

**Comment by peterjc** [comment]
Looks like ``flake8`` is reporting a whole bunch of blank line complaints in the docstrings - I'll have to double check the version I have locally as they changed a few things in the recent release.

**Comment by bow** [comment]
Looks good Peter.  :+1:

**Comment by peterjc** [comment]
Thanks @etal, and @bow - I particularly wanted you to OK the ``__all__`` change in ``Bio.SearchIO`` so that's great.

I'll leave this open a bit longer for wider comment...

**Comment by stevemmarshall** [comment]
Sorry for the late reply... looks good to me..

**Comment by peterjc** [comment]
Thanks Steve

**Pull request merged**
