### PR TITLE
Fix4021: Update swissprot parser to handle new feature qualifiers

### LINKED ISSUE #4021: Biopython 1.79 Fails to parse new Uniprot file in SwissProt text format
There are some new Uniprot records in SwissProt format which biopython fails to parse.

Here's an example of a file which biopython fails to parse (UniProt accession `P00720`):
[P00720.txt](https://github.com/biopython/biopython/files/9257269/P00720.txt)
Note that this file was updated recently on uniprot (03-AUG-2022). 

Here's a previous version of `P00720` (from 26-FEB-2020), which biopython does parse successfully:
[P00720.txt](https://github.com/biopython/biopython/files/9257277/P00720.txt)

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)

3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:33:09)
[Clang 11.1.0 ]
CPython
macOS-10.16-x86_64-i386-64bit
1.79
```

### Expected behaviour

Biopython's `Bio.SwissProt.read()` should correctly parse the file, and return a `Bio.SwissProt.Record`.

### Actual behaviour

Exception is raised when parsing the feature (`FT`) lines:

```python
File ~/mambaforge/envs/proteins/lib/python3.8/site-packages/Bio/SwissProt/__init__.py:257, in read(source)
    255 handle = _open(source)
    256 try:
--> 257     record = _read(handle)
    258     if not record:
    259         raise ValueError("No SwissProt record found")

File ~/mambaforge/envs/proteins/lib/python3.8/site-packages/Bio/SwissProt/__init__.py:371, in _read(handle)
    369     _read_kw(record, value)
    370 elif key == "FT":
--> 371     _read_ft(record, line)
    372 elif key == "SQ":
    373     cols = value.split()

File ~/mambaforge/envs/proteins/lib/python3.8/site-packages/Bio/SwissProt/__init__.py:830, in _read_ft(record, line)
    828 # this line is a continuation of the description of the previous feature
    829 keys = list(feature.qualifiers.keys())
--> 830 key = keys[-1]
    831 description = value.rstrip('"')
    832 old_description = feature.qualifiers[key]

IndexError: list index out of range
```

### Steps to reproduce

Just run the following snippet (adapted from the official biopython documentation).
 
```python
from Bio import ExPASy, SwissProt

accession = "P00720"
handle = ExPASy.get_sprot_raw(accession)
record = SwissProt.read(handle)
```

Or, parse the files attached above, the first (newer one) should fail and the second should succeed.

Another example failing in the same way is with accession `Q72J47`.

### PR DESCRIPTION
**Pull request by fredricj**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #4021

Update the feature line parser in Bio.SwissProt to handle the new ligand qualifiers in Uniprot release 2022_03. This change also allows future qualifiers to work properly without any change

### CODE REVIEW

**Comment by fredricj** [comment]
I have run this patch against all human entries without it producing any exceptions, but I haven’t verified that it parses all entries correctly except for the test cases provided for the module.

**Review by peterjc — APPROVED** [review]
Looks good to me, although I have not directly compared how the UniProt XML version and our parser for that would behave. Could you check that is consistent?

**Comment by Luxxii** [comment]
I can also confirm that this fixes the parsing issue for .txt and .dat files from UniProt. I tested it on the whole SwissProt (568 002 entries), and am currently running it on the trEMBL-entries.

Parsing wise: it looks like it is parsing correctly. At least for the parts i need in those entries.

**Comment by peterjc** [comment]
That's really good news.

Has anyone done a side by side comparison on the same record in the "SwissProt" plain text versus UniProt XML format yet? Hopefully our parsers give something very similar if not the same for these fields...

**Pull request merged**
