### PR TITLE
Begin splitting up test_PDB.py

### PR DESCRIPTION
**Pull request by peterjc**
This pull request begins the task of splitting up ``test_PDB.py`` as it has grown overly large, starting with the new MMCIFDict test work from @Gasta88 - I nearly asked you to do this as part of #1205.

As part of this I noticed and fixed a problem with the ``Bio.PDB.extract`` function and the ``Dice.py`` deprecation.

### CODE REVIEW

**Comment by peterjc** [comment]
P.S. @Gasta88 I've explicitly dual licensed the new file ``test_PDB_MMCIF2Dict.py`` - is this and the copyright header OK with you?

**Comment by peterjc** [comment]
Dealing with the Dice deprecation is more tricky than I realised... if people are using ``Bio.PDB.extract`` perhaps we can't deprecate it?

**Comment by Gasta88** [comment]
I'm happy with both.

We can decide what to do with further `Bio\PDB` module tests in the original issue.

**Comment by peterjc** [comment]
Excellent, thank you. And if you want to work on further splitting ``test_PDB.py`` that would be welcome.

**Comment by Gasta88** [comment]
By splitting `Tests\test_PDB.py` are you referring to future module tests or even take out some tests already present in the file?

**Comment by peterjc** [comment]
Moving some of the existing tests in ``Tests/test_PDB.py`` into their own files, e.g. ``Tests/test_PDB_Vector.py`` would likely be a logical chunk.

**Pull request merged**
