### PR TITLE
GCG MSF support in Bio.AlignIO

### PR DESCRIPTION
**Pull request by peterjc**
This adds support to ``Bio.AlignIO`` for parsing GCG MSF files.

- [X] This work was on behalf of the NMPD, and as copyright holders, they agreed to dual licence this and any previous contributions under both the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Maybe I can improve the test coverage - I should set a good example ;)

**Comment by pbashyal-nmdp** [comment]
Thank you Peter. This has helped us having to use **BioPerl** to convert _IMGT msf_ files to _Stockholm_ before being imported in Biopython.

**Comment by peterjc** [comment]
Almost all the code without tests is error handling for malformed MSF files, and many of the real world examples which trigger the warnings are often too large to include as is...

**Comment by peterjc** [comment]
@pbashyal-nmdp would you prefer this code as is (with the header length heuristics included), or for me to remove the heuristics and raise an exception on length inconsistencies (my preference).

Cross reference:

https://github.com/ANHIG/IMGTHLA/issues/200 - Truncated sequences in MSF files (most recently affecting their release v3.36.0)

https://github.com/ANHIG/IMGTHLA/issues/201 - Wrong alignment length in MSF header (most recently affecting v3.32.0)

As a compromise, we could remove just the wrong MSF header length heuristic, which is the least elegant and most fragile bit of the code in my view.

**Comment by peterjc** [comment]
I have removed the heuristic needed for https://github.com/ANHIG/IMGTHLA/issues/201 which is not needed with IPD-IMGT/HLA database release 3.33.0 onwards.

With these changes, all the recent IPD-IMGT/HLA database MSF files parse perfectly, bar one warning from ``C_gen.msf`` on branch 3360, issue logged as https://github.com/ANHIG/IMGTHLA/issues/200

```
$ for b in 3330 3340 3350 3360 3370 3380; do git checkout --force $b && ./check_all.py; done
Switched to branch '3330'
Your branch is up to date with 'origin/3330'.
Done, 97 parsed
Switched to branch '3340'
Your branch is up to date with 'origin/3340'.
Done, 97 parsed
Switched to branch '3350'
Your branch is up to date with 'origin/3350'.
Done, 97 parsed
Switched to branch '3360'
Your branch is up to date with 'origin/3360'.
C_gen.msf - 13933Kb - One of more alignment sequences were truncated and have been gap padded
Done, 97 parsed
Switched to branch '3370'
Your branch is up to date with 'origin/3370'.
Done, 98 parsed
Switched to branch '3380'
Your branch is up to date with 'origin/3380'.
Done, 101 parsed
```

Test script:

```python
#!/usr/bin/env python

import os
import sys
import warnings

from Bio import BiopythonParserWarning
from Bio import AlignIO

count =0
for f in os.listdir("."):
    if f.endswith(".msf"):
        with warnings.catch_warnings():
            warnings.simplefilter('error', BiopythonParserWarning)
            try:
                align = AlignIO.read(f, "msf")
            except (ValueError, BiopythonParserWarning) as e:
                print("%s - %iKb - %s" % (f, os.stat(f).st_size / 1000, e))
            count += 1

print("Done, %i parsed" % count)
```

This was also used to pick the smallest possible real example files for the two test cases.

**Comment by peterjc** [comment]
The problematic MSF file ``C_gen.msf`` in v3.36.0 has been fixed in https://github.com/ANHIG/IMGTHLA/commit/9926a70c8d463929ee5e38b4b6aa2284ba07da9f

That means versions the IPD-IMGT/HLA database v3.33.0 to v3.38.0 (latest) inclusive MSF files all parse without errors.

**Comment by peterjc** [comment]
Thank you @pbashyal-nmdp and the NMDP, I'm sure other people will find a use for the MSF support too.

**Pull request merged**
