### PR TITLE
Account for the 4-letter KEGG organism codes.

### PR DESCRIPTION
**Pull request by allista**
Otherwise these were getting into the previouse gene record as gene idetifiers.
Example: 
[http://rest.kegg.jp/get/ec:5.4.2.2](http://rest.kegg.jp/get/ec:5.4.2.2)

> BACU: 103004993(PGM1) 103005357(PGM2)

### CODE REVIEW

**Comment by peterjc** [comment]
Does this look fine @mdehoon? Do we need to add a test for this?

**Comment by peterjc** [comment]
@mdehoon or @widdowquinn: does this KEGG change make sense?

@allista: I noticed you have an unrelated Newick commit here, can you give more details about that please? CC @etal.

Regarding the unrelated Mafft command line wrapper change, do you know when this was added to the tool @allista? It is not there on MAFFT v6.71b (2009/12/03), but is there in MAFFT v7.245 (2015/07/22). I'm happy to cherry-pick that right away, provided you are happy to dual license your contributions under both the Biopython License Agreement and the 3-Clause BSD license (see #898). Thanks!

**Comment by allista** [comment]
**MAFFT** [from here](http://mafft.cbrc.jp/alignment/software/changelog.html):

> v6.806, 2010/02/22: Multithreading (linux only)
> v6.884, 2012/04/28: Experimental support for multithreading on Intel Mac, in addition to Linux.
> v7.184 2014/09/21: Experimental support for multithreading on Windows.

And yes, I'm perfectly happy with dual license!

**Newick** -- confidence is stored as a label of an internal node.
But:

> For example, interior nodes can have names in that standard. These names follow the right parenthesis for that interior node, as in this example:
> (B:6.0,(A:5.0,C:3.0,E:4.0)Ancestor1:5.0,D:11.0);

[from here](http://evolution.genetics.washington.edu/phylip/newicktree.html)

**Comment by peterjc** [comment]
Thanks, MAFFT threads addition cherry-picked as f25ca362672f1ae85f8d9770929e3922a9e0c5d7

**Comment by peterjc** [comment]
I've cherry-picked your fix as https://github.com/biopython/biopython/commit/ede2ffd52c18daf78857778683c20990e3db99c6 and updated the unit tests to verify it. Thank you!

Can you open a new issue or pull request about the Newick issue please?

**Pull request closed without merging**
