### PR TITLE
Changed appveyor yaml to use miniforge instead of miniconda, and repl…

### PR DESCRIPTION
**Pull request by flaar94**
Testing

### CODE REVIEW

**Comment by peterjc** [comment]
Why drop 32-bit Windows? Does miniforge not support it?

**Comment by flaar94** [comment]
> Why drop 32-bit Windows? Does miniforge not support it?

It doesn't look like they distribute 32 bit binaries, see https://github.com/biopython/biopython/issues/4788#issuecomment-2298054563 . Here I was just testing to see if the 64 bit version at least ran OK

**Comment by flaar94** [comment]
Oops, did not intend to opened a pull request into the original repo. I was just testing. I'll try to find the automated process that did that

**Comment by peterjc** [comment]
Looks like the failures are unrelated, see e.g. #4797

I suspect numpy 2.1.0, especially for the set_printoptions issues.

**Comment by flaar94** [comment]
OK, that's good. I was wondering. So at least the 64 bit version seems to work. The 32 bit one failed to download because https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Miniforge3-Windows-x86.exe doesn't exist (but https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Miniforge3-Windows-x86_64.exe does)

**Comment by peterjc** [comment]
Looking at https://github.com/conda-forge/miniforge there aren't any 32-bit Windows versions of the deprecated alternative mambaforge either.

Maybe you can try that workaround of installing a 64-bit miniforge, and then using it to create a 32-bit environment by setting ``CONDA_SUBDIR=win-32``?

If it doesn't work, we may have discuss dropping 32-bit Windows support.

**Comment by flaar94** [comment]
Yeah, I'll give it a shot after work today. Regarding the numpy issue, it looks like as part of making `np.printoptions` function as a context manager, they changed `np.set_printoptions` to return a token 
```
@set_module('numpy')
def set_printoptions(precision=None, threshold=None, edgeitems=None,
                     linewidth=None, suppress=None, nanstr=None,
                     infstr=None, formatter=None, sign=None, floatmode=None,
                     *, legacy=None, override_repr=None):
    ...
    new_opt = _make_options_dict(precision, threshold, edgeitems, linewidth,
                                 suppress, nanstr, infstr, sign, formatter,
                                 floatmode, legacy)
    # formatter and override_repr are always reset
    new_opt['formatter'] = formatter
    new_opt['override_repr'] = override_repr

    updated_opt = format_options.get() | new_opt
    updated_opt.update(new_opt)

    if updated_opt['legacy'] == 113:
        updated_opt['sign'] = '-'

    token = format_options.set(updated_opt)
    return token
```

**Pull request closed without merging**
