### PR TITLE
Restore author list to Tutorial, fix up the bibliography

### PR DESCRIPTION
**Pull request by peterjc**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

CC @idoerg

### CODE REVIEW

**Comment by peterjc** [comment]
I've worked out why the [Kent2002] and [Matys2003] entries show with extra indentation: https://biopython.org/docs/dev/Tutorial/chapter_bibliography.html

They start with an initial dot space. Now how to fix this...

**Comment by peterjc** [comment]
@mdehoon your eyes on this might be helpful, particularly is the current capitalisation of "de Hoon" OK?

(Under LaTeX all the bibliography keys were lower case but not user facing; now they are user facing and I picked ``deHoon2004`` rather than ``DeHoon2004``)

**Comment by peterjc** [comment]
Good news: PDF output is looking much better now, although I'd like the title page to look nicer. This includes the author list.

Bad news: There is no equivalent title page in the HTML output.

So, by inserting the author list explicitly (currently above the Tutorial table of contents), it appears once in the HTML and twice in the PDF. And we have to keep the two in sync. That will have to do in the short term.

**Comment by mdehoon** [comment]
> @mdehoon your eyes on this might be helpful, particularly is the current capitalisation of "de Hoon" OK?
> 
> (Under LaTeX all the bibliography keys were lower case but not user facing; now they are user facing and I picked `deHoon2004` rather than `DeHoon2004`)

Thanks @peterjc , this always confuses everybody.
In Dutch, capitalization depends on the grammatical context. Specifically, the letter appearing first in the name should be capitalized. So it is "Mr. Van Gogh" but "Mr. Vincent van Gogh".
Then I guess "DeHoon2004" makes more sense, but either way is fine.

**Pull request merged**
