### PR TITLE
Fix broken merge in Biopython 1.76 contributors

### PR DESCRIPTION
**Pull request by peterjc**
See GitHub issue #3028 with the explanation.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Would anyone like to review this? First it restores the 1.76 list to that of the tagged release:

https://github.com/biopython/biopython/blob/biopython-176/NEWS.rst

Second it adds the extra names later added to 1.76 to 1.77 instead (based on the timing of those contributions I believe none applied to 1.78).

**Comment by morrme** [comment]
Your change looks good but: Is there a reason `Bio.Restriction` doesn't share the same styling as the other components of the package?

**Comment by peterjc** [comment]
Added some more backticks for `Bio.Restriction` - or did you mean something different @morrme ?

**Comment by morrme** [comment]
That's exactly what I meant! 
LGTM

**Pull request merged**
