### PR TITLE
added test for Nexus/Tree module

### PR DESCRIPTION
**Pull request by Gasta88**
This pull request addresses issue #1288 

This is for `Bio.Nexus.Tree` module.

### CODE REVIEW

**Comment by peterjc** [comment]
What do you think @etal ?

**Comment by Gasta88** [comment]
Small side note: I tried to test `merge_with_support` and `consensus` methods, but failed on my attempts.

I was successful in python 2.x, but line 832 in `Bio.Nexus.Tree` has a `key` function using `lambda` and two arguments.
```python
consensus_ids.sort(lambda x, y: len(consensus.node(x).data.taxon) - len(consensus.node(y).data.taxon))
```
 According to the docs, even in 2.x it should get only one argument but it seems more flexible that python 3.x.

Every attempts in python 3.x failed, therefore I'm more than happy to hear any suggestions.

**Comment by peterjc** [comment]
This line assumes Python 2 sorting with a ``cmp=...`` argument:

https://github.com/biopython/biopython/blob/biopython-170/Bio/Nexus/Trees.py#L832

```python
consensus_ids.sort(lambda x, y: len(consensus.node(x).data.taxon) - len(consensus.node(y).data.taxon))
```

Likely fix:

```python
consensus_ids.sort(key = lambda x: len(consensus.node(x).data.taxon))
```

**Comment by etal** [comment]
Looks good to me (once cmp vs. key is sorted out). Great to see better tests for this sub-package.

**Comment by Gasta88** [comment]
Thanks @peterjc , I've used the your suggestion before but the test seems to succeed some times and fail others. I'll try few more attempts and expand further the testing coverage.

If I had to edit `Bio.Nexus.Tree`, would it be preferable to propose a separate PR before moving forward with this one, or collect everything in here?

**Comment by peterjc** [comment]
Hard to say - if the test work is linked to a fix in ``Bio.Nexus.Tree`` then one pull request seems logical.

**Pull request merged**
