### PR TITLE
Fix motif weblogo for Python3, closes #475.

### LINKED ISSUE #475: Py3 compatibility problem of Bio.motifs.Motif.weblogo
Biopython version:

    python3 -c 'import Bio; print(Bio.__version__)'
    1.65

Error when calling ```m.weblogo("motif.png")```:
    
    TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

Relative code: https://github.com/biopython/biopython/blob/master/Bio/Motif/_Motif.py#L663

Thank you guys.

### PR DESCRIPTION
**Pull request by anntzer**
Includes test.

### CODE REVIEW

**Comment by peterjc** [comment]
I don't immediately see why, but TravisCI says this breaks under Python 2.6 which we still support.

**Comment by anntzer** [comment]
The errors look weird and seem unrelated to the patch.  Any chance you can run the test suite locally?

**Comment by peterjc** [comment]
@barwil Can you look at this please? Note there is something strange on Python 2.6 according to the TravisCI tests (which I did re-run and the failure looks the same).

**Comment by anntzer** [comment]
Fixed now.

**Comment by peterjc** [comment]
Thanks for fixing the Python 2.6 incompatibility. This looks good except I realise we ought to move the new test so that it respects the ``run_tests.py --offline`` switch (see the chapter in our tutorial). I'll do that now...

**Comment by peterjc** [comment]
See https://github.com/biopython/biopython/commit/98ad63d20def54cfb5bec636066964bb446d3f1d and preceding commits. Thanks!

**Pull request closed without merging**
