### PR TITLE
Use XML parsing for MEME output files

### PR DESCRIPTION
**Pull request by victorlin**
Similar to #2082, this pull request re-implements the current functionality of Bio/motifs/meme.py using the `xml` module to parse the XML output instead of the plain-text output from MEME. It also includes updated test files from MEME source.

- Functional parity with `.txt` parser which is to be deprecated (#1988).
- Left TODO's where additional information can be extracted from the XML.
- Test cases 2, 3, 4: updated using http://meme-suite.org/meme-software/5.0.5/meme-5.0.5.tar.gz.
- Test cases 1, 4, 4_11_4, RNA: removed due to inability to reproduce.

---

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by victorlin** [comment]
A few concerns:

1. Currently, the value extracted by `Instance.sequence_name` is actually labeled as `sequence_id` in the XML. I've used that value for now to retain original functionality, but it might make more sense to create an additional attribute for `sequence_id` which `sequence_name` can then be derived from.
3. Should we keep the `.txt` and `.html` files alongside the `.xml`? I've also kept it for the MAST files but they are not actually used for testing purposes.
4. The removed test cases were MEME output files generated from files not in this repository. Aside from the official MEME test files, should we include other sample files that can then be used to generate more test files?
5. Should the copyright header be updated?

**Comment by mdehoon** [comment]
> 
    Currently, the value extracted by Instance.sequence_name is actually labeled as sequence_id in the XML. I've used that value for now to retain original functionality, but it might make more sense to create an additional attribute for sequence_id which sequence_name can then be derived from.

I would suggest to follow the XML as closely as possible and use `sequence_id` instead of `sequence_name`.

>     Should we keep the .txt and .html files alongside the .xml? I've also kept it for the MAST files but they are not actually used for testing purposes.

We should remove them.

>    The removed test cases were MEME output files generated from files not in this repository. Aside from the official MEME test files, should we include other sample files that can then be used to generate more test files?

To me this is optional.

>    Should the copyright header be updated?
Probably yes.

The documentation for the MEME parser still needs to be updated - could you do this? It would be great if you could also include some documentation for the MAST parser.

**Comment by victorlin** [comment]
Will update the documentation. Looks like it's just the file `Doc/Tutorial/chapter_motifs.tex`, which lacks documentation for the MAST parser anyways.

Also, how should the copyright header be updated?

**Comment by peterjc** [comment]
Add a line like this under the existing copyright line(s):

```python
# Revisions copyright 2019 by Victor Lin
```

**Comment by littleblackfish** [comment]
Hello, is there anything I can do to help push this through?

**Comment by victorlin** [comment]
@littleblackfish I just pushed a fix for the merge conflict. I think the one remaining task is to update/add documentation for MEME/MAST parsers in `Doc/Tutorial/chapter_motifs.tex`. That could be done as a separate PR if this one is approved by @mdehoon. I don't have a complete biological background for putting that documentation together, so it would be great if you are able to do that. I can help with the technical details.

**Pull request merged**
