### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by Oli4**
Just a typo in a comment... By the way my first contribution on GitHub

### CODE REVIEW

**Comment by peterjc** [comment]
Thank you! Would you like to be added to the NEWS and CONTRIB files now, or are you planning future contributions?

**Comment by Oli4** [comment]
What does it mean to be added to the NEWS and CONTRIB files? 
At the moment I try to manage a large set of transcriptomes (~2000) with python. I want to be able to search in subsets of this data, selected by taxon or any meta information given for the transcriptomes. Furthermore I plan to organize the output of multiple searches. Either by procuding a metafile for each found sequence or by annotating SeqRecords. I want to be able to tell which sequence was found with which query and I need to mark sequences as duplicates or contaminations to remove them from all further analysis. 
Please let me know if something sounds super stupid or there is already an easy solution to my problem.

**Comment by peterjc** [comment]
I meant adding your name to https://github.com/biopython/biopython/blob/master/NEWS and https://github.com/biopython/biopython/blob/master/CONTRIB as a contributor to Biopython.

(I'm not sure what to suggest for your other question - you could ask on our mailing list perhaps?)

**Comment by Oli4** [comment]
Yeah you can add me to the lists. I did not planed to be mentioned somewhere because of such a small contribution. Nevertheless I would like to improve my python, maybe by contributing to biopython. Is there a to do list? SearchIO does not support the output of nhmmer. I thougt about working on this.

**Comment by peterjc** [comment]
Talk to @bow on #579 about nhmmer in SearchIO. Otherwise there are loads of open issues you could look at, also you might have useful comments on some of the open pull requests. See also http://biopython.org/wiki/Active_projects and the website issues https://github.com/biopython/biopython.github.io/issues

Do you want to be listed in the contributors file as just Oli4 (with GItHub URL)?

**Comment by Oli4** [comment]
You can list me as Olivier Morelle. 

Thank you for your kind reply, I'll check out the given resources.

**Comment by peterjc** [comment]
Hi Oliver. Could you comment on issue #898 if you agree to dual license your Biopython contributions under both the "Biopython License Agreement" and the "BSD 3-Clause License". Many thanks, Peter.

**Comment by peterjc** [comment]
Thank you: https://github.com/biopython/biopython/issues/898#issuecomment-380739098

**Pull request merged**
