### PR TITLE
Dedented writing of "END" statement to correct for multi-model PDB files

### PR DESCRIPTION
**Pull request by JoaoRodrigues**

### CODE REVIEW

**Comment by cbrueffer** [comment]
Could you add a test for this to ensure this kind of error doesn't creep in again?

**Comment by JoaoRodrigues** [comment]
@cbrueffer Added. Actually found a small typo in the same test file. Thanks.

**Comment by peterjc** [comment]
Looks good - just waiting for TravisCI to finish.

You can add yourself to the ``NEWS`` file for the next release if you like, or I can do that as part of the merge.

**Comment by peterjc** [comment]
Rebased and applied to master (squashed into two commits), see commits leading up to https://github.com/biopython/biopython/commit/b46ad2ba0bbc86ced99c3b2ae319894474896bbf - thanks!

**Pull request closed without merging**
