### PR TITLE
Topology in GenBank LOCUS and EMBL ID lines

### PR DESCRIPTION
**Pull request by peterjc**
Work in progress, replaces #812 from @kblin to address #363.

Still need to address if and how to store this in BioSQL... https://github.com/biosql/biosql/issues/5

### CODE REVIEW

**Comment by peterjc** [comment]
Also the EMBL parser needs to record the topology as done for the GenBank parser

**Comment by peterjc** [comment]
@kblin what do you think? I don't think I ever got a clear answer from BioPerl/BioSQL on how the topology ought to be stored (I've added some links on https://github.com/biosql/biosql/issues/5 to old email discussions), and the BioPerl optional approach was described as a hack - so perhaps we don't need to force ourselves to match that?

**Comment by kblin** [comment]
Looks good to me.

**Comment by peterjc** [comment]
Great, merged - thank you.

I'm happy to revisit the BioSQL side of things if we can some feedback on https://github.com/biosql/biosql/issues/5 before the next Biopython release.

**Pull request merged**
