### PR TITLE
Added keyword to specify msms executable on class instantiation

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
This pull request closes issue #2983.

Tested on Win10 with MSMS 2.6.1:

```python
import pathlib
from Bio.PDB import PDBParser, ResidueDepth

parser = PDBParser(QUIET=1)
struct = parser.get_structure('x', 'Tests/PDB/2XHE.pdb')

msms = '...'  # path to your executable

rd = ResidueDepth(s, msms_exec=msms)
```

Does not break compatibility with existing code/function calls.

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Do you think using the clearer "msms_exec" is better than the existing choice of "MSMS" in upper case?

**Comment by JoaoRodrigues** [comment]
Hi @peterjc, I do yes. The reason why I didn't change the argument in the other function was to avoid breaking old code. Would you prefer keeping MSMS?

**Comment by peterjc** [comment]
I'm torn - up to you.

**Comment by JoaoRodrigues** [comment]
In an ideal world, we'd change MSMS to msms_exec everywhere with some deprecation warnings. The lower case argument name is more 'pythonic' I think it's fine like this. We should anyway revisit all these third-party application wrappers and try to standardize them like we did for all the sequence alignments tools. Then we can look at this again.

**Comment by peterjc** [comment]
See also #2877 but this example is more complicated than just running a tool, it parses the output too.

**Pull request merged**
