### PR TITLE
Update chapter_advanced.tex

### PR DESCRIPTION
**Pull request by pragyabansal02**
This pull request addresses issue #...

- [ ] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ ] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Was the a reason for this change? I tend to deal more with organism names than people's names in Biopython...

**Comment by peterjc** [comment]
@pragyabansal02 We still need you to agree to the licensing

**Comment by mdehoon** [comment]
I made a mistake here, I thought the PR was switching from person name to organism name. Shall I revert?

**Comment by peterjc** [comment]
Reverting may be best, but let's give @pragyabansal02 a chance to explain first?

**Comment by pragyabansal02** [comment]
Oh! Sry, my mistake. I haven't read the whole code properly. Yeah, you can revert it back!

**Pull request merged**
