### PR TITLE
Fixed a bug in calculating the height of clades when building a UPGMA tree

### PR DESCRIPTION
**Pull request by SHZ66**
This pull request addresses the issue that the UPGMA constructor yields a tree with wrong branch lengths. In some cases, it may even yield a tree with unequal distances from tips to the root, which violates the constant-rate assumption.

The problem is that `DistanceTreeConstructor._height_of()` returns the wrong clade height. The recursion doesn't work as intended. Please verify the changes. Here is an example that will reproduce the bug:

```
from matplotlib.pyplot import *
from Bio import Phylo
from Bio.Phylo.TreeConstruction import _DistanceMatrix
from scipy.spatial.distance import squareform, pdist
from numpy import *

n = 20
X = 10*random.random((n, 2))

A = squareform(pdist(X))

B = []
for i, row in enumerate(A):
    B.append([int(i) for i in row[:i+1]])

names = [str(i) for i in range(n)]

# UPGMA
dm = _DistanceMatrix(names, B)
constructor = Phylo.TreeConstruction.DistanceTreeConstructor()
tree = constructor.upgma(dm)

Phylo.draw(tree)
```
In this example, 20 points (2D) are randomly generated and their pairwise distances evaluated. The original implementation produces a tree that violates the constant-rate assumption:
figure1
After the fix, the branch lengths are evaluated correctly:
figure2

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Can you add a test for this (ideally self contained with a tree constructed in code, or reusing one of the test files already in Biopython as the input)?

I will leave the code change review to @etal etc, stylistically this seems cleaner but I don't understand what the meaning of the change is without taking more time to study it.

**Comment by SHZ66** [comment]
> Can you add a test for this (ideally self contained with a tree constructed in code, or reusing one of the test files already in Biopython as the input)?
> 
> I will leave the code change review to @etal etc, stylistically this seems cleaner but I don't understand what the meaning of the change is without taking more time to study it.

Yes, sure I will figure out a test data that can reproduce the error. But if you look at the original implementation of the `_height_of` function, the recursion is obviously not going to work:
```
    def _height_of(self, clade):
        """Calculate clade height -- the longest path to any terminal (PRIVATE)."""
        height = 0
        if clade.is_terminal():
            height = clade.branch_length
        else:
            height = height + max(self._height_of(c) for c in clade.clades)

        return height
```
Without adding the branch lengths of inner clades somewhere and reset `height=0` in every function call, `max(self._height_of(c) for c in clade.clades)` will simply look for the branch length of some terminal clade of the descendants of `c` and the branch lengths will not accumulate.

**Comment by etal** [comment]
Yes, this fix makes sense to me. My original implementation was not well tested, but this one looks good. Thanks!

**Comment by ramti** [comment]
Hi, any update?

**Review by etal — APPROVED** [review]

**Comment by etal** [comment]
I think we're waiting on a unit test before merging this. The test could be:
1. Set the random seed to a fixed value, e.g. 1
2. Create a distance matrix and build the UPGMA tree (as in the code above)
3. Check that the depths of all terminal nodes are all approximately equal (`[depth for node, depth in tree.depths() if node.is_terminal()]`)

**Comment by fabianegli** [comment]
Not sure - What is the best way to contribute code to this PR?

**Comment by jlumpe** [comment]
Anyone still working on this?

**Comment by WCutePy** [comment]
Hi,

I happened to stumble upon this bug as well using the most recent version of BioPython 1.84 at this time.
@etal  are there currently any plans to resolve merging these changes?

**Comment by etal** [comment]
I found and merged another PR #3951 which includes this PR's commits plus a unit test. So, this fix should be in the main branch now. Apologies for the delay, and thanks for your contributions.

**Pull request closed without merging**
