### PR TITLE
moved self-test from Bio/PDB/Polypeptide.py

### PR DESCRIPTION
**Pull request by Gasta88**
As refer in issue #820, I've moved the self-test from `Bio/PDB/Polypeptide.py` to `Tests/test_PDB.py`

### CODE REVIEW

**Comment by peterjc** [comment]
It looks like you've been caught out by changes to the master branch which added new tests for vectors and ``ResidueDepthTests`` - can you refresh this?

**Comment by Gasta88** [comment]
After I perform the refresh of my master, does GitHub pick up the change automatically or do I have to manually commit something?

**Comment by Gasta88** [comment]
closing PR since it's not synced with Biopython:master.

**Comment by peterjc** [comment]
If you want to continue using the same pull request, you would need to update the same branch. Typically this means doing something like ``git push Gasta88 Gasta88-patch-6 --force``.

However, as using ``--force`` is generally a bad idea as it can delete changes, until you are comfortable with git making a new branch and pull request is safer.

**Pull request closed without merging**
