### PR TITLE
Remove REBASE FTP download script

### PR DESCRIPTION
**Pull request by peterjc**
I've not had any joy with ``rebase_update.py`` so am proposing removing it (although it is a shame to loose the ability to more automated the REBASE updates which as discussed ought to be part of our release process). Did it work for you Markus?

```
$ python rebase_update.py

 Please wait, trying to connect to Rebase

copying ftp://ftp.neb.com/pub/rebase/emboss_e.906
to /Users/xxx/repositories/biopython/Scripts/Restriction/emboss_e.906
copying ftp://ftp.neb.com/pub/rebase/emboss_s.906
to /Users/xxx/repositories/biopython/Scripts/Restriction/emboss_s.906
<urlopen error ftp error error_reply('200 Switching to Binary mode.',)>
This error is probably due to a non-solved ftp bug in recent Python versions. Please download the emboss files manually from http://rebase.neb.com/rebase/rebase.f37.html and then run ranacompiler.py. Find more details in the Restriction manual.
```

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Force pushed to fix accidental change to the hash-bang line.

Cross reference #2091, as I have a hunch that removing the local import of the update code *might* solve the pydocstyle problem which is somehow triggered by the ``ranacompiler.py`` script.

**Comment by peterjc** [comment]
This does not seem to help with that flake8 + pydocstring + flake-comprehensions issue,
https://travis-ci.org/peterjc/biopython/jobs/540763009

**Comment by MarkusPiotrowski** [comment]
It works for me under Python 2.7 (didn't test on Python 3.x).
Have you seen the following lines:
https://github.com/biopython/biopython/blob/b920c5ccf1efc4b3f2ad948867b1ed7a98d9630b/Scripts/Restriction/rebase_update.py#L71-L74

Have you tried to remove this line?

Actually, I would prefer to fix the problem (even it it would be a Python3-only solution) than just to drop the script.

**Comment by peterjc** [comment]
Confirmed, worked for me too, macOS Python 2.7.

Removing the ``urlcleanup()`` call did not help with Python 3.6.0 nor Python 3.7.0rc1 (macOS), nor Python 3.7.2 (Linux).

Also noting that ``urllib.request.FancyURLopener`` is deprecated since Python 3.3

So, it looks like deleting it is a little premature, rather it needs updating for Python 3.

**Pull request closed without merging**
