### PR TITLE
Dual license BSD dual license Bio.KDTreemodule

### PR DESCRIPTION
**Pull request by Amrithasuresh**
Original author Michiel de Hoon and contributors since as
tracked with version control have all agree:

-- Michiel de Hoon (@mdehoon)
   [#2374 (comment)](https://github.com/biopython/biopython/issues/2374#issuecomment-566825939)
-- Christian Brueffer (@cbrueffer)
   [#898 (comment)](https://github.com/biopython/biopython/issues/898#issuecomment-236922857)
-- She Zhang (@SHZ66)
   [#1617 (comment)](https://github.com/biopython/biopython/pull/1617#issue-182351202)

This pull request addresses issue #2374 

- [X ] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Replacement for pull request #2419 

Looks good except the commit comment seems strange - e.g. double asterisks and repeated links? Did you edit this via the GitHub website perhaps?

**Comment by Amrithasuresh** [comment]
> Looks good except the commit comment seems strange - e.g. double asterisks and repeated links? Did you edit this via the GitHub website perhaps?

I copied the old pull request message and added in the commit message. I forgot to edit the double asterisks in the comment message. I noticed after created pull request. I edited manually in the pull request title only. Should I fix again?

Don't need to add the license agreement comment links in the git commit message? It seems I messed up this thread. Also one test fails `.travis-tox.ini`.

**Comment by peterjc** [comment]
You can see the raw commit comment at the command line with git, or by adding ``.patch`` to the end of a commit URL in GitHub:

```
From 85aa21c3ebe0d70c220d6dca7ab15fbb948a73c6 Mon Sep 17 00:00:00 2001
From: Amrithasuresh <sureshcbt@gmail.com>
Date: Sat, 21 Dec 2019 12:30:11 -0500
Subject: [PATCH] Dual license BSD dual license Bio.KDTreemodule Original
 author Michiel de Hoon and contributors since as tracked with version control
 have all agree:

-- Michiel de Hoon (@mdehoon)
   [#2374 (comment)](https://github.com/biopython/biopython/issues/2374#issuecomment-566825939)
-- Christian Brueffer (@cbrueffer)
   [#898 (comment)](https://github.com/biopython/biopython/issues/898#issuecomment-236922857)
-- She Zhang (@SHZ66)
   [#1617 (comment)](https://github.com/biopython/biopython/pull/1617#issue-182351202)
---
 Bio/KDTree/KDTreemodule.c | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/Bio/KDTree/KDTreemodule.c b/Bio/KDTree/KDTreemodule.c
index 0d6a34a6ab..6e361bb827 100644
--- a/Bio/KDTree/KDTreemodule.c
+++ b/Bio/KDTree/KDTreemodule.c
@@ -1,3 +1,11 @@
+/* Copyright 2008-2018 by Michiel de Hoon.  All rights reserved.
+ *
+ * This file is part of the Biopython distribution and governed by your
+ * choice of the "Biopython License Agreement" or the "BSD 3-Clause License".
+ * Please see the LICENSE file that should have been included as part of this
+ * package.
+ */
+
 #include <Python.h>
 #include "KDTree.h"
 ```

The commit message is written using markdown, rather than plain text.

I'll just turn this into a squash-and-merge and edit that now...

**Comment by peterjc** [comment]
Done, thank you. Unfortunately I spotted the repetition of 'dual license' in the commit title too late.

**Pull request merged**
