### PR TITLE
deprecating Bio.SubsMat

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request deprecates `Bio.SubsMat`, which currently is not being maintained, with `Bio.Align.substitution_matrices` as a replacement.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Looked like a stochastic failure in BioSQL, rerunning AppVeyor

**Comment by mdehoon** [comment]
@peterjc  Thanks! Can this be merged then?

**Comment by peterjc** [comment]
The re-run passed, so yes.

**Comment by mdehoon** [comment]
@peterjc 
> Is it worth cutting the old content from the tutorial now,

We could just remove the whole Chapter 22 ("Advanced") from the tutorial.

> or are you maybe going to rework it with the replacement module?

That is pretty much done already, in section 20.4.2 of the tutorial. It can be cleaned up a bit more once we merge `PairwiseAlignment` and `MultipleSeqAlignment`.

**Pull request merged**
