### PR TITLE
small fix to deal with new date format in prosite

### PR DESCRIPTION
**Pull request by francoiscoste**
Following Issue "Format change in prosite.dat" #1130, here is a proposition of simple fix handling both versions.

### CODE REVIEW

**Comment by peterjc** [comment]
The TravisCI checks are all working, which is good. I'm not sure why the QuantifiedCode check is failing, but that ought to be fine. CodeCov is noting that we don't have any tests which use the new code

 Can you suggest a suitable (small) example file we can include in the test suite?

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by francoiscoste** [comment]
Here is an except of the new prosite.dat to test the reader:
[prosite2017-tail-head.zip](https://github.com/biopython/biopython/files/893659/prosite2017-tail-head.zip)
I am happy with the licences and being thanked :-)
Best,
François

**Comment by peterjc** [comment]
I just accidentally solved the same thing while fixing an ExPASy bug - see #1215. You've included some additional useful notes about the timing of the change and the more details dates so I'll combine this...

**Comment by peterjc** [comment]
@francoiscoste are you happy with the combined fix on #1215? Thanks!

**Comment by peterjc** [comment]
Closed via #1215.

**Pull request closed without merging**
