### PR TITLE
Catch import errors during run_tests.py doctest

### PR DESCRIPTION
**Pull request by peterjc**
This addresses recent AppVeyor failures apparently linked to the inclusion of ``Bio.Graphics.KGML_vis`` in the doctests run by ``run_tests.py`` since #1900, and the version of ``pillow`` installed under AppVeyor 64bit Windows Python 2.7, see: https://github.com/biopython/biopython/pull/1906#issuecomment-457516404

I could also "fix" this by explicitly installing ``pillow==4.2`` which might be worth doing as well? See e.g.
https://ci.appveyor.com/project/peterjc/biopython/builds/21865494

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@rwst does this look sensible to see, cross reference #1906

**Comment by peterjc** [comment]
Recent Python 2.7 style check which passed,

```
style installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,chardet==3.0.4,configparser==3.5.0,doc8==0.8.0,docutils==0.14,enum34==1.1.6,flake8==3.6.0,flake8-blind-except==0.1.1,flake8-docstrings==1.3.0,flake8-polyfill==1.0.2,flake8-rst-docstrings==0.0.8,mccabe==0.6.1,pbr==5.1.1,pycodestyle==2.4.0,pydocstyle==3.0.0,pyflakes==2.0.0,restructuredtext-lint==1.2.2,six==1.12.0,snowballstemmer==1.2.1,stevedore==1.30.0
style run-test-pre: PYTHONHASHSEED='2153723868'
style runtests: commands[0] | flake8 --max-line-length 82 setup.py
style runtests: commands[1] | flake8 BioSQL/
style runtests: commands[2] | flake8 Scripts/
...
```

This Python 2.7 style check failed (seemingly not picking up the ``BioSQL/.flake8`` settings:

```
style installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,chardet==3.0.4,configparser==3.5.2,doc8==0.8.0,docutils==0.14,enum34==1.1.6,flake8==3.6.0,flake8-blind-except==0.1.1,flake8-docstrings==1.3.0,flake8-polyfill==1.0.2,flake8-rst-docstrings==0.0.8,mccabe==0.6.1,pbr==5.1.1,pycodestyle==2.4.0,pydocstyle==3.0.0,pyflakes==2.0.0,restructuredtext-lint==1.2.2,six==1.12.0,snowballstemmer==1.2.1,stevedore==1.30.0
style run-test-pre: PYTHONHASHSEED='1759935216'
style runtests: commands[0] | flake8 --max-line-length 82 setup.py
style runtests: commands[1] | flake8 BioSQL/
BioSQL/DBUtils.py:144:80: E501 line too long (83 > 79 characters)
BioSQL/BioSeqDatabase.py:152:80: E501 line too long (85 > 79 characters)
...
```

Looks like ``configparser==3.5.0`` to ``configparser==3.5.2`` was to blame, and indeed:

https://github.com/jaraco/configparser/issues/27

Going to re-run the TravisCI instance and it will hopefully pickup the just fixed ``configparser==3.5.3`` release

**Comment by rwst** [comment]
> @rwst does this look sensible to see, cross reference #1906

I see no problems.

**Comment by peterjc** [comment]
@rwst thanks - merged.

You should be able to remove the import check for ``Bio.Graphics.KGML_vis`` on #1906 now.

**Pull request merged**
