### PR TITLE
Black on Bio.codonalign

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses in part issue #2008.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@zruan would you be able to look at this formatting change to ``Bio.codonalign``?

**Comment by peterjc** [comment]
Updated using black 19.10b, and fixing a few more line breaks by hand.

**Comment by zruan** [comment]
Hi Peter,

These changes look fine to me. I'm wondering why the first check is unsuccessful.

Thanks,
Zheng

**Comment by peterjc** [comment]
Thank you!

Codecov checks how much of the code in the diff was covered by unit tests - ideally this would be 75% but we don't insist on it. If we could change how this appeared on GitHub, I would.

**Pull request merged**
