### PR TITLE
Add "megablast" program into "NCBIWWW" module

### PR DESCRIPTION
**Pull request by yangwu91**
Revised NCBIWWW module:
- Add "megablast":
Megablast is intended to compare closely related sequences. It is much
faster than traditional blastn and recommended to use.
- Revise "filter" parameter:
"Filer" parameter now has different options.

### CODE REVIEW

**Comment by peterjc** [comment]
Could you find any NCBI documentation for this (in which case are there any URLs we should add to the help and/or source code), or was it deduced by testing?

Can you include a test for these changes in ``test_NCBI_qblast.py``? Note TravisCI does not currently run the online tests.

**Comment by yangwu91** [comment]
Sure. I am on it.

**Comment by peterjc** [comment]
Hi @yangwu91 - could you find any official NCBI documentation?

Even without documentation, if you can add test in ``test_NCBI_qblast.py`` I think we should merge this.

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by yangwu91** [comment]
Hi @peterjc 
I have re-folked the master branch and updated `NCBIWWW.py` as as well as `test_NCBI_qblast.py`.
#1150

**Comment by yangwu91** [comment]
I hereby give my explicit permission to switch to the BSD 3-clause license. And I am willing to be listed on the `NEWS.rst` and `CONTRIB.rst` files.

**Comment by yangwu91** [comment]
I hereby give my explicit permission to dual licence my contributions under both the Biopython License Agreement AND the BSD 3-Clause License. 
And I am willing to be listed on the `NEWS.rst` and `CONTRIB.rst` files.

**Pull request closed without merging**
