### PR TITLE
Unify quotes - prefer double quotes

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses part of the changes which ``black`` would include, see #2008. See discussion there.

These changes were made using https://github.com/myint/unify but I have deliberately set the author to a dummy values of ``unify <unify@example.org>`` to avoid inflating my commit count.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
I think https://github.com/biopython/biopython/issues/2008#issuecomment-516362887 can be taken as an approval from @MarkusPiotrowski on standardising on double quotes.

**Comment by MarkusPiotrowski** [comment]
Yes, please do it.

**Comment by peterjc** [comment]
@mdehoon do you want to veto this quote style change, or are you OK with the changes?

**Comment by peterjc** [comment]
I note there is now a merge conflict - I can quite easily redo this and resolve that, if there is agreement on the principle of the changes.

**Comment by mdehoon** [comment]
> @mdehoon do you want to veto this quote style change, or are you OK with the changes?

I am fine either way.

**Comment by peterjc** [comment]
Rebasing...

**Comment by peterjc** [comment]
Thank you all

**Pull request merged**
