### PR TITLE
Rebase update

### PR DESCRIPTION
**Pull request by Andrey-Raspopov**
This pull request addresses issue #2101 

This is a skeleton of another take on this task, using FTPlib instead of deprecated url.request mechanisms. Any feedback is appreciated.

- [ X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Will this conflict with #2130?

**Comment by MarkusPiotrowski** [comment]
@Andrey-Raspopov I have the same error under Python 2 and Python 3 on two different Windows computers. A quik Google search let suggest that the error is related to setting of system variables dealing with proxies. 

While I don't object in general using `ftplib` and having `rebase_update` less drastically changed as I did in PR #2130, I'd prefer to keep most oft these simplifications (e.g. removing `RanaConfig.py`) and then build upon that.

@peterjc Yes, this will conflict #2130.

**Comment by peterjc** [comment]
So unless @Andrey-Raspopov can improve this, we should go with #2130 instead?

**Comment by MarkusPiotrowski** [comment]
@peterjc If you can confirm that #2130 is working for you, I'd suggest going with #2130 for now. Then, if @Andrey-Raspopov is willing to do that, he can try to change the updated `rebase_update.py`, e.g. using `ftplib` (I used `urllib`'s `urlretrieve`, which is deprecated but nicely working...)

**Comment by Andrey-Raspopov** [comment]
Sorry, was out of reach last two weeks. I've checked out #2130 and it is more simple and robust in my opinion, so I think we should go with it.

**Pull request closed without merging**
