### PR TITLE
fixes issue #697

### PR DESCRIPTION
**Pull request by vincentdavis**

### CODE REVIEW

**Comment by vincentdavis** [comment]
Sorry about adding 2b8592a and f7ec831 to this pull request, I was going to make a seperate pull request for those.

**Comment by peterjc** [comment]
I may pull out some of these commits directly as a cherry-pick...

**Comment by vincentdavis** [comment]
Have you cherry picked what you want? Can this be closed?

**Comment by peterjc** [comment]
I think so - see also #707. If I missed anything please comment here or just start a new pull request if that's easier. Thanks!

**Pull request closed without merging**
