### PR TITLE
Added read() to Bio.KEGG.Enzyme

### LINKED ISSUE #593: Define Bio.KEGG.Enzyme.read(...) function
Following the pattern used in ``Bio.SeqIO`` and elsewhere, the iterator ``Bio.KEGG.Enzyme.parse(...)`` should have a matching ``Bio.KEGG.Enzyme.read(...)`` for when you expect exactly one record.

Would be nice to use in the example covered in #592.

### PR DESCRIPTION
**Pull request by arosenfeld**
Resolves #593.

### CODE REVIEW

**Comment by peterjc** [comment]
Looks fine to me - any comments @mdehoon?

@arosenfeld - can you see where the KEGG examples in the Tutorial could make use of the new ``read(...)`` function as discussed on #592 and #593

**Comment by mdehoon** [comment]
The Travis build 7faf416 failed; can we check this first? Otherwise it looks fine to me.

**Comment by peterjc** [comment]
The initial TravisCI failure was fixed with https://github.com/arosenfeld/biopython/commit/26f4ba75b2d4da637ef2a8cbb3646ecfbc300e5b - I'll cherry-pick this to the master branch now...

**Comment by arosenfeld** [comment]
@peterjc: Sure, I'll add it to the tutorial.

**Comment by peterjc** [comment]
Changes applied to the master branch as a squashed commit https://github.com/biopython/biopython/commit/c71acee682825be3a0ce1ec074ab19f2223b5e36 - you can make a new pull request for the tutorial changes (or update this branch if you prefer). Thanks Aaron.

**Comment by peterjc** [comment]
@arosenfeld would you agree to dual license your Biopython contributions as discussed on #898 so we can switch to the standard 3-clause BSD license? (Apologies if you already have done so, and I have overlooked this)

**Comment by arosenfeld** [comment]
@peterjc Yep.  I give permission to dual license my contributions or fully license it under the standard BSD 3-clause license.

**Pull request closed without merging**
