### PR TITLE
Follow conda best practise and set strict channel_priority

### PR DESCRIPTION
**Pull request by peterjc**
Known to reduce conflict conda dependency clashes which happen occasionally otherwise (saw that last night on a branch).

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
OK, same error as last night:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
  - pip -> python[version='>=3.7,<3.8.0a0']
If python is on the left-most side of the chain, that's the version you've asked for.
```

This change is probably worth applying anyway... but something is up with a pip requirement demanding Pyhton 3.7 (which breaks on our Python 2 target).

**Comment by peterjc** [comment]
Both the conda-forge and default channels have pip for Ptyhon 2.7, not changed in the three weeks:

https://anaconda.org/conda-forge/pip/files - currently v19.11
https://anaconda.org/anaconda/pip/files - currently v0.9.3

**Comment by MarkusPiotrowski** [comment]
Can this problem be related to the recent update of conda to version 4.7.5? (https://github.com/conda/conda/blob/master/CHANGELOG.md). E.g.

> Bug fixes
> 
> - restore tests being run on win-32 appveyor (#8801)

**Comment by MarkusPiotrowski** [comment]
Same error message in this (closed) recent issue:
https://github.com/conda/conda/issues/8848#issuecomment-506985236

**Comment by peterjc** [comment]
Hmm. Looking at https://repo.continuum.io/miniconda/ would suggest the latest version we would get right now is conda 4.6.14

Looking at https://github.com/conda/conda/issues/8848#issuecomment-506985236 maybe we need to add ``python=2.7`` to the ``conda install`` line (but dynamic, need something like ``$PY_MAJOR_VER`` here but that is just ``2`` or ``3``)?

**Comment by peterjc** [comment]
We were not doing anything with channels, so my original idea (strict channel mode) is likely irelevant. Including conda-forge didn't seem to help (change reverted).

**Comment by nimne** [comment]
The failure seems related to the conda update. Passing builds didn't have this `conda                                       4.6.14-py27_0 --> 4.7.5-py27_0`.

Commenting out `conda update conda` [lets the test start](https://ci.appveyor.com/project/nimne/biopython/build/job/m1tu6324g3c8jxlk) (although it's taking a while, I don't know if it'll pass), but I don't think that's a good solution anyway.

This seems related to the issue that @MarkusPiotrowski linked above. From my understanding of the issue, some other package (not pip directly) might be causing this?

Another weird thing: [In a recent passing build](https://ci.appveyor.com/project/biopython/biopython/builds/25523807/job/p7t647c3f3s5s2ht), the test that has the environment set `PY_MAJOR_VER=2, PYTHON_ARCH=x86` is reporting the following 
```python
python -c "import sys; print(sys.version)"
3.7.3 (default, Apr 24 2019, 13:20:13) [MSC v.1915 32 bit (Intel)]
```

There are also a ton of `py37_0`'s showing up in the version strings. Somehow python is being upgraded from 2.7 to 3.7, although the Miniconda.exe download is the correct size for the 2.7 version. Clearly something strange is happening - I'll keep looking.

**Comment by MarkusPiotrowski** [comment]
Looking more into this log it really seems that the last passing Python 2.7 [appveyor build](https://ci.appveyor.com/project/biopython/biopython/builds/25523807/job/p7t647c3f3s5s2ht) is indeed a Python 3.7 build. Look at the name of the build folder (`build\lib.win32-3.7`) and also the compiler used for the C extensions is VS 14.0 (while for Python 2.7 it should be VS 9.0).

**Comment by MarkusPiotrowski** [comment]
It has to do with the mysql-connector story. Last appveyor python 2.7 build that was indeed 2.7:
https://ci.appveyor.com/project/biopython/biopython/builds/25147415/job/wt4dj4ynf5ut706w

The next one was a 3.7 build:
https://ci.appveyor.com/project/biopython/biopython/builds/25148076/job/cngiwgikrft7ft35

**Comment by MarkusPiotrowski** [comment]
Is there no conda Python 2.7 `mysql-connector-python` ver 8.0.13 package for Windows?
https://anaconda.org/anaconda/mysql-connector-python/files?version=8.0.13
So, pinning to 8.0.13 forces an upgrade to Python 3.7?

**Comment by peterjc** [comment]
I think that explains things - so simple "fix" is to drop ``mysql-connector-python`` on win32 Python 2.7?

**Comment by MarkusPiotrowski** [comment]
I think I'm coming close to find the original problem. Before we pinned `mysql-connector` to version 8.0.13 it was using version 2.0.4 for Python 2 (and 8.0.13 for Python 3)! This was received from the "free" channel which IIRC is not longer available since one of the recent conda updates. However, this version should still be available from the standard anaconda channel. So:
```
- conda install setuptools numpy psycopg2 matplotlib networkx reportlab scipy coverage pillow==5.4.1
- if "%PY_MAJOR_VER%"=="2" conda install unittest2 mysql-connector-python==2.0.4
- if "%PY_MAJOR_VER%"=="3" conda install mysql-connector-python==8.0.13
```
may work. I will test this over on #2157.

**Comment by MarkusPiotrowski** [comment]
So this setup is working:
```
  - conda install setuptools numpy psycopg2 matplotlib networkx reportlab scipy coverage pillow==5.4.1
  - if "%PY_MAJOR_VER%"=="3" conda install mysql-connector-python==8.0.13
# Restore "free" channel in conda 4.7.5
  - conda config --set restore_free_channel true
  - if "%PY_MAJOR_VER%"=="2" conda install mysql-connector-python==2.0.4
  - python setup.py build
```
Some issues:
1. I had to remove the installation of `unittest2` for Python 2 since the download was always hanging in appveyor. However, it doesn't seem to harm anything...
2. Now, that the correct Python 2 environment is set up, there are failures with a recent commit (#2151), see also #2157

**Comment by peterjc** [comment]
Thank you for following this though to an explanation, your solution seems sensible. Closing in favour of your branch, although I think we could/should apply ``--set channel_priority strict`` as well?

**Pull request closed without merging**
