### PR TITLE
Update rebase_update and simplify Restriction ecosystem slightly

### LINKED ISSUE #2101: Update rebase_update.py for Python 3
See discussion on #2098, it would be good to update ``Scripts/Restriction/rebase_update.py`` to work on Python 3. This script still works on Python 2.7 as is used as part of updating ``Bio.Restriction`` to the latest version of the enzymes in the REBASE database.

(See also #972 for background, and and also the work on #268 to replace ``Bio.Restriction`` entirely)

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
This pull request addresses issue #2101.

`rebase_update.py` was simplified into a more script-like module which now runs under Python 2 and Python 3.

In addition, `RanaConfig.py`, which contained two different sets of constants for `ranacompiler.py` (in `Scripts/`) and `PrintFormat.py` (in `Bio/Restriction/`), was removed and the contained data moved to the respective modules. 

This will close #2101.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Should we mention the removal of ``RanaConfig.py`` in the ``DEPRECATED.rst`` file? I assume its nature as an internal configuration means we don't need to worry about a deprecation cycle.

**Comment by MarkusPiotrowski** [comment]
Is `DEPRECATED.rst` sorted by date? So I add a paragraph directly below `Jython` (and above `Bio.Alphabet`)?

**Comment by peterjc** [comment]
It is roughly in reverse chronological order (after the top level ones about Python platforms), so yes.

**Comment by MarkusPiotrowski** [comment]
@peterjc Can you test `rebase_update`? E.g. running `ranacompiler.py` should automatically invoke `rebase_update` and then write the new `Restriction_Dictionary.py` (together with a copy of the old file).

**Comment by peterjc** [comment]
Oh good - you've already merged this. I was just about to look at this as part of #2192, I will get to test the update now 👍

**Comment by peterjc** [comment]
Sadly it seems the FTP site is timing out right now for me, but the HTTP works:

http://rebase.neb.com/rebase/link_emboss_e
http://rebase.neb.com/rebase/link_emboss_r
http://rebase.neb.com/rebase/link_emboss_s

**Pull request merged**
