### PR TITLE
Update test_GenomeDiagram.py

### PR DESCRIPTION
**Pull request by Gasta88**
As refereed in issue #1096 and #1095, the self-test has been removed from `Bio/Graphics/GenomeDiagram/_FeatureSet.py` and a code base example has been added for `Tests/test_GenomeDiagram.py`.

### CODE REVIEW

**Comment by peterjc** [comment]
TravisCI is failing under Python 2.7 due to this:

```
======================================================================
ERROR: test_circular_genome_diagram_NC_005213_pdf (test_GenomeDiagram.DiagramTest)
Construct and draw PDF using NC_005213 genome.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_GenomeDiagram.py", line 19614, in test_circular_genome_diagram_NC_005213_pdf
    handle = io.StringIO(NC_005213_text)
TypeError: initial_value must be unicode or None, not str
----------------------------------------------------------------------
```

This is due to a change from Python 2 and 3 about how ``io.StringIO`` works. What you should use here is ``from Bio._py3k import StringIO`` which will take care of it. Outside of Biopython, the library ``six`` has similar mechanisms for writing code which will work under both Python 2 and 3.

**Comment by peterjc** [comment]
I've not actually viewed the changes to ``Tests/test_GenomeDiagram.py`` because GitHub says there are too many for the webview. I'd have to check at the command line. This is odd, perhaps something nasty has happened with Windows vs Unix new lines?

**Comment by Gasta88** [comment]
Thanks for the StringIO head up.  

I've no idea why the file is not visible when you open that for editing, but I've copied the text from my IDE (Spyder). It shouldn't cause any problem.

To be sure I've also checked the script in plain Notepad and it's not showing any funny character.

**Comment by peterjc** [comment]
Note sure what GitHub things, but it says for this file:

> 19,817 additions, 1,026 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

**Comment by Gasta88** [comment]
Not very user friendly, but this should avoid using the command line:
https://patch-diff.githubusercontent.com/raw/biopython/biopython/pull/1106.patch

**Comment by peterjc** [comment]
@Gasta88 I believe you are working on Windows. How did you install git, and do you recall an option from the installer about automatically converting the line endings? I'm almost certain part of the large diff is due to a Windows vs Unix end of line change in ``test_GenomeDiagram.py``.

Separately, please do not embed the large  *Nanoarchaeum equitans* NC_005213 GenBank file into the Python test script. It would have been better to have added this as a file under ``Tests/GenBank/NC_005213.gbk`` (so that it could be used in other tests as well), but I would prefer you not include it at all.

I was not clear enough in https://github.com/biopython/biopython/issues/1095#issuecomment-286391312 about this, added comment https://github.com/biopython/biopython/issues/1095#issuecomment-288422263 - my apologies for the confusion.

**Comment by Gasta88** [comment]
No problem, I'll close this PR.

**Comment by peterjc** [comment]
This has reminded me about getting a Windows development machine setup here as a VM (since I don't currently have anyway to test and debug under 64-bit Windows). Thanks.

**Pull request closed without merging**
