### PR TITLE
Hide alphabet in Seq objects' __repr__ [WIP; discussion only]

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses issue #1674.

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Big update to always hide the alphabet (first commit hides only the default alphabet and was the original contents of this pull request).

**Comment by peterjc** [comment]
TODO: ``DBSeq`` in the BioSQL code

**Comment by mdehoon** [comment]
Looks good. I would suggest to remove alphabets also from Doc/Tutorial/chapter_quick_start.tex, and there are a few remaining cases in Doc/Tutorial/chapter_seq_annot.tex and  biopython/Doc/Tutorial/chapter_seqio.tex.

**Comment by peterjc** [comment]
Given comments from @MarkusPiotrowski on #1674, I'm proposing for Biopython 1.72 to only apply the first commit here - just hide the alphabet in the Seq objects' ``__repr__`` when the default is used. See #1687.

**Comment by peterjc** [comment]
This would need rebasing/merging given that #1687 was merged for Biopython 1.72, which hides the default alphabet.

**Comment by peterjc** [comment]
Rebased (merge conflicts were from a couple of style updates, our flake8 settings are now stricter)

**Comment by peterjc** [comment]
This work has been superseded during work on #2046 - we probably could have saved ourselves some work by merging this earlier.

**Pull request closed without merging**
