### PR TITLE
Update README to suggest using pip install

### PR DESCRIPTION
**Pull request by Chris7**
Updated installation instructions to use pip, and provide another set of instructions for Windows users.

### CODE REVIEW

**Comment by peterjc** [comment]
See this thread http://lists.open-bio.org/pipermail/biopython-dev/2015-October/021105.html - not clear yet if we have a consensus, but also the wiki http://biopython.org/wiki/Download and main installation document https://github.com/biopython/biopython/blob/master/Doc/install/Installation.tex will need updating

**Comment by Chris7** [comment]
While we're on readmes, is there any reason you haven't used any markup language to make it easier to navigate?

**Comment by Chris7** [comment]
Linewidths fixed.

**Comment by peterjc** [comment]
The ``README`` is marked up with RST, see the ``README.rst`` symlink in the repository for GitHub's benefit to trigger the formatted view. This symlink file is deliberately not included in the source releases via ``MANIFEST.in``.

**Comment by peterjc** [comment]
Closing - As of  whttps://github.com/biopython/biopython/commit/8a16a61109f40ed353cac3970a9965e3e7505916e do recommend using pip, but as yet do not talk about specific Windows Python packages like Anaconda. You could raise that on the biopython(dev) mailing list to see if this is being widely used?

**Pull request closed without merging**
