### PR TITLE
Fix PDB Entity.copy() for disordered atoms

### PR DESCRIPTION
**Pull request by ghost**
This pull request addresses issue #455

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Implemented fix suggested in comments.

### CODE REVIEW

**Comment by peterjc** [comment]
I've retitled the pull request to something more meaningful. Note we will not consider at this for potential inclusion unless you agree to the licensing terms. i.e. Please read and tick the three boxes from the issue template. Thanks!

**Comment by JoaoRodrigues** [comment]
Will look into it this weekend! Thanks for the patch, this is a long-standing issue.

**Comment by peterjc** [comment]
@Yuval-Shechter Thanks for agreeing to the licensing 👍 

@JoaoRodrigues Thanks for agreeing to look at this

**Comment by peterjc** [comment]
We're agreed that our early 2020 release will be the last Biopython to support Python 2, so if there is an elegant/simple Python 3 only solution that isn't very far away... even doing this conditionally in the short term might be acceptable if a Python 2 solution is judged too much work?

**Comment by JoaoRodrigues** [comment]
That's a good suggestion @ChrisMoth. I implemented a `DisorderedEntity.copy()` method that gets your example to work. I'm testing it in other situations to see if it holds properly.

```
    def copy(self):
        """Returns a shallow copy of the DisorderedEntity, including children"""

        shallow = copy(self)

        shallow.child_list = []
        shallow.child_dict = {}
        shallow.xtra = copy(self.xtra)

        for child in self.disordered_get_list():
            shallow.disordered_add(copy(child))

        shallow.detach_parent()
```

**Comment by JoaoRodrigues** [comment]
Ran into an interesting behavior (ie bug) while checking this and checking #455.
```from Bio import PDB

inputPdb = "mini.pdb"
output  = "out.pdb"

parser = PDB.PDBParser()
struct = parser.get_structure("myStruct", inputPdb)

idMat=( (1,0,0), (0,1,0), (0,0,1) )
trVect=(20.,20.,20.)

s = struct.copy()
s.transform(idMat, trVect)

pdbio = PDB.PDBIO()
pdbio.set_structure(s)

# Print correct, translated coordinates
for atom in pdbio.structure.get_atoms():
    print(atom, atom.coord)

# Prints original, unchanged coordinates
for res in pdbio.structure.get_residues():
    for atom in res.get_unpacked_list():
        print(atom, atom.coord)

with open(output, "w") as fd :
  pdbio.save(fd)
```

The problem seems to come from `Entity.get_list`, which somehow does not let transform operate properly on all children. We could add a transform method to DisorderedEntities as well, to make sure they call `.get_unpacked_list` instead, which leads to the correct behavior.

I'm afraid I might be missing a more obvious fix here. Would anyone else have some time to have a look? @jgreener64 @peterjc ?

**Comment by jgreener64** [comment]
Don't think I'll get a chance to dive into this soon, sorry, but maybe in a week or two!

**Pull request closed without merging**
