### PR TITLE
Note lack of support for minimal MEME format

### PR DESCRIPTION
**Pull request by j-andrews7**
I agree to my contributions being dual licensed under both our original "Biopython License Agreement" and the more widely used "3-Clause BSD License".

Doubt that statement's necessary for a doc change, but whatever.

### CODE REVIEW

**Comment by peterjc** [comment]
How about making the exception message more explicit instead? e.g. Adding ``This can happen with minimal MEME files from XXX which are not supported yet.``

**Comment by j-andrews7** [comment]
@peterjc Probably a much better idea.

**Comment by peterjc** [comment]
Thanks for agreeing to the dual-licensing. Are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by j-andrews7** [comment]
Sure.

**Comment by peterjc** [comment]
Thank you!

**Pull request merged**
