### PR TITLE
replace print-and-compare by unittest for test_AlignIO

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request replaces the print-and-compare test in test_AlignIO by a unit test.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@peterjc  Thanks; done.

**Comment by peterjc** [comment]
Much better 👍 

Can you replace this re-used block:

```python
        self.check_parse1(path, "clustal", 1, 5)
        self.check_parse2(path, "clustal", 1)
        self.check_parse3(path, "clustal", 1)
        self.check_parse4(path, "clustal", 1)
        self.check_parse5(path, "clustal", 1)
        self.check_parse6(path, "clustal", 5)
```

with:

```python
        self.check_parse(path, "clustal", 1, 5)
```

likewise, replace this pattern:

```python
        alignments = self.check_parse1(path, "emboss", 5, 2)
        self.check_parse2(path, "emboss", 5)
        self.check_parse3(path, "emboss", 5)
        self.check_parse4(path, "emboss", 5)
        self.check_parse5(path, "emboss", 5)
        self.check_read_fails(path, "emboss")
```

with:

```python
        alignments = self.check_parse(path, "emboss", 1, 5)
```

where we have:

```python
    def check_parse(self, path, fmt, length, seq_count):
        answer = self.check_parse1(path, fmt, length, seq_count)
        self.check_parse2(path, fmt, length)
        self.check_parse3(path, fmt, length)
        self.check_parse4(path, fmt, length)
        self.check_parse5(path, fmt, length)
        if length == 1:
            self.check_parse6(path, fmt, seq_count)
        else:
            self.check_read_fails(path, fmt)
        return answer
```

Or, maybe merge ``check_parse*N*`` into a single method?

**Comment by mdehoon** [comment]
@peterjc  Such patterns don't work for all formats (for example, nexus would be an exception), and I want to avoid control statements in the test functions.

**Comment by peterjc** [comment]
Hmm. Can we at least combine ``check_parse1`` to ``check_parse5`` and rename ``check_parse6``?:

```python
        self.check_parse1(path, "nexus", 1, 9)
        self.check_parse2(path, "nexus", 1)
        self.check_parse3(path, "nexus", 1)
        self.check_parse4(path, "nexus", 1)
        self.check_parse5(path, "nexus", 1)
```

**Comment by mdehoon** [comment]
@peterjc  What would be the advantage of that?

**Comment by peterjc** [comment]
Why? Less repetition for standard parsing checks which should work on all the formats and files being tests.

I would be happy with ``check_parse1`` to ``check_parse5`` merged into a single method ``check_parsing``, but my main desire is that the ``test_XXX`` stub for each file be as short as possible.

We want it to be as easy as possible to add new test cases, either for a new format, or a pathological test file to improve coverage of an older parser (previously done by adding a tuple to the file list).

**Comment by mdehoon** [comment]
Actually I prefer if the test_XXX functions are as simple as possible; I don't think they should be as short as possible, and code repetition doesn't really bother me for testing code. In contrast, the previous print-and-compare testing code was minimizing code repetition by using control logic, for example:
```python
    if t_count == 1 and t_format not in ["nexus", "emboss", "fasta-m10"]:
        # do some test
```
which made it difficult for me to understand which test are run in each case.

**Comment by peterjc** [comment]
Can you give ``check_parse1`` to ``check_parse6`` more meaningful names then?

**Comment by peterjc** [comment]
I think our remaining differences of opinion here are essentially stylistic - I wouldn't have done it this way, but am OK with you merging this once the tests have passed.

This does put the AlignIO tests on a better framework and I appreciate this improvement - thank you.

**Comment by mdehoon** [comment]
@MarkusPiotrowski  Are you OK with this PR?

**Comment by MarkusPiotrowski** [comment]
I can't add anything useful here, so I'm OK with it.

**Comment by mdehoon** [comment]
Thanks everybody

**Pull request merged**
