### PR TITLE
Raise NotImplementedError when opening bgzf files for append

### PR DESCRIPTION
**Pull request by pkerpedjiev**
This pull request addresses issue https://github.com/biopython/biopython/issues/2142

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good. If you want to, while I wait for the tests to finish, please add yourself to the ``NEWS.rst`` and ``CONTRIB.rst`` files. Thanks!

**Comment by pkerpedjiev** [comment]
Already on there :-) I submitted another PR earlier this year but I forgot what it was. Might have been from my work GitHub account though.

**Comment by peterjc** [comment]
Spotted it now - but this would be an excuse to add you to the Biopython 1.75 credits ;)

**Comment by pkerpedjiev** [comment]
Done.

**Comment by peterjc** [comment]
Thank you!

**Pull request merged**
