### PR TITLE
Bug fixes in Bio/PDB/Vectors.py

### PR DESCRIPTION
**Pull request by bertrand-caron**
Hi,
I came across two bugs in Bio/PDB/Vectors.py that I think you would be interested in getting fixed.

Regards, Bertrand

### CODE REVIEW

**Comment by peterjc** [comment]
@bertrand-caron: Can you add tests for these changes in ``Tests/test_PDB.py``? (There is chapter on the test framework in the main Biopython tutorial).

@etal @lennax @JoaoRodrigues (etc): Can any of you review this? The change to the ``refmat`` method to remove the side effect looks sensible but is it likely anyone is relying on the undocumented behaviour?

**Comment by JoaoRodrigues** [comment]
@pjcock : I will have a look at this a.s.a.p. Seems like a sensible fix,
I'll quickly check if there are any changes in some of my scripts where I
use this.

Peter Cock <notifications@github.com> escreveu no dia qui, 26/03/2015 às
10:30:

**Comment by bertrand-caron** [comment]
@peterjc I'd be glad to do so when I find the time to (not in the next 4 days for sure, I apologise for that ...).

While playing with this Vector module, I actually came upon a much more painful bug that is reproducible with the following snippet:

```
from Vector import Vector, rotmat, m2rotaxis
from numpy import array, dot
#Matrix rotating <Vector 1.00, 0.80, 0.00> onto <Vector -1.00, -0.80, 0.00>:
m = rotmat(Vector([1.00, 0.80, 0.00]), Vector([-1.00, -0.80, 0.00]))
print m2rotaxis(m)
print m
```

The output on my machine is the following:

```
(1.570796326794897, <Vector 0.00, 0.00, 0.00>)
[[-0.2195122  -0.97560976  0.        ]
 [-0.97560976  0.2195122   0.        ]
 [ 0.          0.          1.        ]]
```
The angle of the rotates object is fine (180 degrees), but the vector is not !
Furthermore, the rotation matrix is completely wrong, it should be [[-1,0,0],[0,-1,0],[0,0,1]].

I have just discovered the bug and have not yet looked into solving it, but I thought you should know.
More to come in a couple days as I am off tonight until Monday (Australian time).

**Comment by JoaoRodrigues** [comment]
I was looking at this for a bit but could not find a quick solution.. I'll
have a better look next week.

>

**Comment by peterjc** [comment]
@bertrand-caron @JoaoRodrigues did you ever did deeper into the rotation issue?

Does it make sense to apply the proposed pull request as is?

**Comment by RasmusFonseca** [comment]
@bertrand-caron nothing seems to be wrong with the rotation matrix. If I type
```python
from Bio.PDB.Vector import Vector, rotmat, m2rotaxis
from numpy import array, dot
m = rotmat(Vector([1.00, 0.80, 0.00]), Vector([-1.00, -0.80, 0.00]))
print(Vector([1,0.8,0]).left_multiply(m))
```
I get
```
<Vector -1.00, -0.80, 0.00>
```
.. which is what we asked for. The problem seems to be that `m2rotaxis` doesn't properly check for singularities (i.e. 0 deg and 180 deg rotation. Note that the returned angle (1.570796326794897) is not 180 degs but 90 degs. Based on [this walkthrough](http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToAngle/) I added a couple of if-statements to get the angle right:
```python
def m2rotaxis(m):
    """
    Return angles, axis pair that corresponds to rotation matrix m.
    """
    eps = 1e-5

    #Check for singularities a la http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToAngle/
    if ( abs(m[0,1]-m[1,0]) < eps and 
         abs(m[0,2]-m[2,0]) < eps and 
         abs(m[1,2]-m[2,1]) < eps 
    ):
        #Singularity encountered. Check if its 0 or 180 deg
        if ( abs(m[0,1]+m[1,0]) < eps and 
             abs(m[0,2]+m[2,0]) < eps and 
             abs(m[1,2]+m[2,1]) < eps and
             abs(m[0,0]+m[1,1]+m[2,2]-3) < eps
        ):
            angle = 0
        else:
            #It must be 180 deg
            angle = numpy.pi
    else:
        # Angle always between 0 and pi
        # Sense of rotation is defined by axis orientation
        t = 0.5 * (numpy.trace(m) - 1)
        t = max(-1, t)
        t = min(1, t)
        angle = numpy.arccos(t)

    if angle < 1e-15:
        # Angle is 0
        return 0.0, Vector(1, 0, 0)
    elif angle < numpy.pi:
        # Angle is smaller than pi
        x = m[2, 1] - m[1, 2]
        y = m[0, 2] - m[2, 0]
        z = m[1, 0] - m[0, 1]
        axis = Vector(x, y, z)
        axis.normalize()
        return angle, axis
    else:
        # Angle is pi - special case!
        m00 = m[0, 0]
        m11 = m[1, 1]
        m22 = m[2, 2]
        if m00 > m11 and m00 > m22:
            x = numpy.sqrt(m00 - m11 - m22 + 0.5)
            y = m[0, 1] / (2 * x)
            z = m[0, 2] / (2 * x)
        elif m11 > m00 and m11 > m22:
            y = numpy.sqrt(m11 - m00 - m22 + 0.5)
            x = m[0, 1] / (2 * y)
            z = m[1, 2] / (2 * y)
        else:
            z = numpy.sqrt(m22 - m00 - m11 + 0.5)
            x = m[0, 2] / (2 * z)
            y = m[1, 2] / (2 * z)
        axis = Vector(x, y, z)
        axis.normalize()
        return numpy.pi, axis
```

**Comment by peterjc** [comment]
Ah, matrix singularities are a pain - I know that much from following the NumPy mailing list, but haven't had to deal with that kind of thing for a long time. I have no advice to offer here.

**Comment by JoaoRodrigues** [comment]
@peterjc I can't offer any either, so I asked @RasmusFonseca (lab mate) for his advice :)

@RasmusFonseca if you are sure this fixes (or improves) the module, then go ahead and make a pull request. You also mentioned yesterday (offline) that there were some issues with the code silently changing vectors in some operations, so maybe adding a few `in_place` function options would be good. Thanks!!

**Comment by RasmusFonseca** [comment]
@JoaoRodrigues Ill test it properly and create a pull req within the next couple of days. 

The problem with changing state of the vectors when normalizing is solved by one of @bertrand-caron's [original commits](https://github.com/biopython/biopython/pull/494/commits/528aa1d08cdc4dd07df025c826bba43011ae7482). All his suggestions look completely sensible to me.

**Comment by peterjc** [comment]
Thanks for reviewing this @RasmusFonseca 

@bertrand-caron Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

@JoaoRodrigues It looks like a manual merge is needed, do you want to do that or should I?

**Comment by JoaoRodrigues** [comment]
@peterjc I'll handle that. I'll talk to Rasmus about this too and we can do it together (PR and then merge if it passes tests).

**Comment by bertrand-caron** [comment]
@all Sorry for leaving this one hanging for so long.

@peterjc I am fine with the licensing, and I'd be thrilled to be thanked for such a trivial fix ;)

**Comment by peterjc** [comment]
Applied at the command line (which is why GitHub doesn't see this as merged), thank you all!

**Pull request closed without merging**
