### PR TITLE
emboss parser for `Alignment`

### PR DESCRIPTION
**Pull request by mdehoon**
This PR adds a parser for EMBOSS file formats, generating `Alignment` objects.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
We need a plan here - are you starting to replace ``Bio.AlignIO`` (which makes the old MSA objects based on a collection of ``SeqRecord`` object) with a sister system based on the new alignment?

If so, I would expect a similar high level API with parse/read/write functions.

And an agreed plan on if this is to replace ``Bio.AlignIO`` eventually, or underpin it in the medium term? Presumably we can interconvert the old MSA and the new alignment objects?

**Comment by mdehoon** [comment]
> We need a plan here - are you starting to replace Bio.AlignIO (which makes the old MSA objects based on a collection of SeqRecord object) with a sister system based on the new alignment?

Yes, plus some additional formats that are self-indexed and therefore very fast, but are difficult to parse because they are binary.

> If so, I would expect a similar high level API with parse/read/write functions.

Yes.

> And an agreed plan on if this is to replace Bio.AlignIO eventually, or underpin it in the medium term? 

I think once the parsers are added, plus a few more frills, the new `Alignment` class will be more powerful than the existing `MultipleSeqAlignment` class, and we should start pointing users to it in the documentation. Logically speaking, the `MultipleSeqAlignment` won't be needed any more at that point, though we can keep it around for a while as deprecated code for legacy applications.

> Presumably we can interconvert the old MSA and the new alignment objects?

If somebody wants to spend time to write the conversion code, yes. Personally I don't think it's needed as I assume that `MultipleSeqAlignment` will disappear anyway. Also you will lose some information going from an `Alignment` object to a `MultipleSeqAlignment` object. In a pinch, you could always write out a `MultipleSeqAlignment` object to a Clustal file with `Bio.AlignIO`, and read it back in with the parser in `Bio.Align`.

**Comment by mdehoon** [comment]
This PR has gone fubar; giving up.

**Comment by peterjc** [comment]
It can be painful when you get git branches messed up. Fingers crossed you can sort it out.

**Pull request closed without merging**
