### PR TITLE
Code formatting in readme

### PR DESCRIPTION
**Pull request by jgreener64**
Fix a small formatting bug in the readme.

### CODE REVIEW

**Comment by peterjc** [comment]
Good catch - do you want to be included in the ``NEWS.rst`` and ``CONTRIB.rst`` listing, or wait until you make a larger contribution?

Are you happy to dual licence this and your future contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Thanks!

**Comment by peterjc** [comment]
Also, since you are working on this - there is a missing back-tick around ``pypy`` just below this.

**Comment by peterjc** [comment]
Great. Is the licensing OK, and do you want to be thanked by name?

**Comment by jgreener64** [comment]
Thanks for the response. I am at BOSC Codefest and decided to look at a few Biopython bugs to get to grips with Biopython. So maybe after a few more of them are in I would go on the contrib list.

@peterjc I hear you will be at the Codefest tomorrow so I may grab you to talk about anything I could implement to do with protein structures.

Backtick fixed.

Happy with the license terms.

**Comment by peterjc** [comment]
Excellent plan - thank you!

**Pull request merged**
