### PR TITLE
Fix "failed to understand molecule_type 'dna'"

### PR DESCRIPTION
**Pull request by innovate-invent**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ ] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Fix "failed to understand molecule_type 'dna' introduced by https://github.com/biopython/biopython/pull/2985

### CODE REVIEW

**Review by mdehoon — APPROVED** [review]

**Comment by mdehoon** [comment]
@peterjc  Any objections?

**Comment by peterjc** [comment]
Where are the lower case "DNA" or "RNA" coming from? Should there be a fix there instead (or as well)?

**Comment by mdehoon** [comment]
@innovate-invent   :
@peterjc  makes a good point. It would be good to see which bug this PR fixes.

**Comment by innovate-invent** [comment]
The genome annotation software 'Prokka' is pervasive and generates all sorts of standard non-conformant output.
The files I am passing to biopython are like the following:
```
LOCUS                            2901551 bp    dna     linear   UNK 
ACCESSION   12464
COMMENT     Annotated using prokka-1.8 1.8 from
            http://www.vicbioinformatics.com.
```

**Comment by peterjc** [comment]
Strange - older versions of Prokka gave a LOCUS line with DNA in upper case, as can be seen in multiple bug reports to do with the GenBank output:

https://github.com/tseemann/prokka/issues

Could you file a bug with Prokka?

--

Now, should our GenBank parser (also) automatically fix "dna" to "DNA", "rna" to "RNA"? I don't recall off hand if GenBank uses ssDNA or any mixed case abbreviations, but a blanket application of upper case is probably not always appropriate.

**Comment by innovate-invent** [comment]
I'll look into filing with Prokka, but I need biopython to be able to parse existing data. The proposed code change does not modify the data, it only changes to uppercase during a comparison. The only possible downside is if you ever needed to distinguish `ssDNA` from `SSDNA`. Looking at other parts of the code it appears that it is already changing to uppercase when doing a string comparison.

**Review by peterjc — APPROVED** [review]
Is a squash commit OK, turning this into one commit?

Do you want to add your name to the NEWS and/or CONTRIB file?

**Comment by innovate-invent** [comment]
This is a trivial contribution. Squash it and I need no credit, thank you.

**Comment by mdehoon** [comment]
@innovate-invent  I am just wondering: If the problem is that Biopython cannot parse files generated by Prokka, then why are the changes in this PR only in the writer code of `Bio.SeqIO.InsdcIO`?

**Comment by innovate-invent** [comment]
This is the location of the exception that I am encountering while converting from genbank to embl

**Comment by mdehoon** [comment]
@innovate-invent  Can you show your complete script? There may be an easier solution than modifying Biopython.

**Comment by peterjc** [comment]
My reading is Biopython can parse the GenBank LOCUS line with molecule type "dna" (usually "DNA"), but rejects it when writing GenBank/EMBL.

**Comment by mdehoon** [comment]
Then the solution depends on whether Biopython should consider lower-case "dna" as a valid molecule type. If we stick to the convention of having "DNA" in upper-case, then there is a simple workaround for @innovate-invent 's problem with prokka-generated non-conformant files:

```python
def fix_moltype(records):
    for record in records:
        if record.annotations['molecule_type'] == "dna":
            record.annotations['molecule_type'] = "DNA"
        yield record

records = SeqIO.parse(input_stream, "genbank")
records = fix_moltype(records)
SeqIO.write(records, output_stream, "genbank")
```

**Comment by peterjc** [comment]
Having settled on the molecule type having to be/contain "DNA", "RNA" or "protein" (upper, upper, lower case), I think it is reasonable for the GenBank/EMBL parser to apply this (perhaps with a ``BiopythonParserWarning``).

This should restore the old behaviour with the alphabet objects, prior to moving to the text field molecule type.

**Review by mdehoon — APPROVED** [review]

**Review by peterjc — APPROVED** [review]
I was thinking a warning when parsing a non-standard molecule type in GenBank/EMBL, but this has advantages if the source was elsewhere (e.g. user's script or another input file format)

**Comment by peterjc** [comment]
Applied, thank you 👍

**Pull request merged**
