### PR TITLE
Issue #664 extended Newick parser to handle negative weights

### PR DESCRIPTION
**Pull request by vishnu93**

### CODE REVIEW

**Comment by etal** [comment]
Looks good to me.

**Comment by peterjc** [comment]
Great. @vishnu93 are you happy to be thanked by name in the ``NEWS`` and `` CONTRIB`` file?

Thanks @etal - you can merge this & update the contributors, or should I?

**Comment by etal** [comment]
I'm a little preoccupied at the moment, would you mind doing the merge & update?

**Comment by peterjc** [comment]
I can do the merge then; currently waiting to hear from Vishnu (in case they want to remain semi-anonymous).

**Comment by vishnu93** [comment]
Hi Peter,

It's okay if my name isn't there. (The fix was minor). Looking forward to
making more contributions :)

**Comment by peterjc** [comment]
Thank you Vishnu - We'll look forward to more contributions in future, that's a nice plan :)

**Pull request merged**
