### PR TITLE
updated Bio.SeqIO.InsdcIO for python3

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request updates Bio.SeqIO.InsdcIO

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
I do feel that this code snippet is getting to be so common that it could be a helper function in ``Bio/_utils.py`` or elsewhere.

**Comment by peterjc** [comment]
Also in terms of the commit message, is this actually something linked to Python 3?

Perhaps something along the lines of "Accept handle or filename in InsdcIO" would suffice?

**Comment by mdehoon** [comment]
@peterjc 

> I do feel that this code snippet is getting to be so common that it could be a helper function in Bio/_utils.py or elsewhere.

In my experience, helper functions never quite live up to their expectations, and in the end, we tend to remove them.

**Comment by peterjc** [comment]
In this case the original design of SeqIO avoided the problem with the intent that all the original format specific parsers *only* took handles, and the higher level API SeqIO.parse was a single point to do the handle/filename magic.

I can see your changes make the underlying API slightly more flexible, but don't like the extra repeated boiler plate code.

**Comment by mdehoon** [comment]
> Also in terms of the commit message, is this actually something linked to Python 3?
Perhaps something along the lines of "Accept handle or filename in InsdcIO" would suffice?

Sure we can change it. It is tangentially linked to Python 3, because there is now a clear distinction between binary and text mode, and the `raise Exception .... from None` is needed for Python 3. But I agree that allowing both handles and filenames is the more relevant change.

**Comment by mdehoon** [comment]
> In this case the original design of SeqIO avoided the problem with the intent that all the original format specific parsers only took handles, and the higher level API SeqIO.parse was a single point to do the handle/filename magic.

But then `Bio/SeqIO/__init__.py` needs to keep track of which format is text and which format is binary. Once all of the submodules accept both file names and handles, you won't need `_BinaryFormats` any more.

**Comment by peterjc** [comment]
If I'd started SeqIO in the Python 3 era, the text vs binary issue would have been more prominent, and I might have done things very differently - but at the time on Python 2 the distinction didn't exist.

I was never very bothered by the ``_BinaryFormats`` list - this code repetition troubles me more. We can agree to differ.

**Comment by mdehoon** [comment]
@peterjc 

> I was never very bothered by the _BinaryFormats list - this code repetition troubles me more. 

What you could consider is to define a base class Iterator in `Bio.SeqIO` from which all iterators in the submodules of `Bio.SeqIO` derive. Then file opening and checking can be implemented in the base class, and won't need to be repeated in each of the submodules.

**Comment by peterjc** [comment]
There *are* base classes in ``Bio/SeqIO/Interfaces.py``, but for many of the parsers it was simpler to write a generator function that to actually subclass the iterator.

If they did all subclass ``SequenceIterator`` then it would be a natural single place for this handle code.

**Comment by peterjc** [comment]
Anyway, I'm happy with these changes even if I suspect there will be scope for some later refactoring. Thanks!

**Pull request merged**
