### PR TITLE
Added label_colors argument to Phylo.draw

### PR DESCRIPTION
**Pull request by bamueh**
This makes it possible to individually color the tip labels on a phylogenetic tree when using Phylo.draw().

### CODE REVIEW

**Comment by terrycojones** [comment]
Great!  +1

**Comment by peterjc** [comment]
@etal can you review this?

My only comment is it needs a couple of functional tests, probably in ``test_Phylo_depend.py`` - i.e. at least once with a dict, and once with a call back function.

**Comment by etal** [comment]
The code looks great to me, and I like this new feature. Would @bamueh like to write the unit test?

**Comment by bamueh** [comment]
Yes, I'll do it.

**Comment by terrycojones** [comment]
Does anything else have to happen on this branch?  I'd like to use it for real (not just on a @bamueh branch).  I'm very happy to help if more is needed.

**Comment by peterjc** [comment]
I missed the tests being added last week - they look sensible. OK to merge @etal?

**Comment by etal** [comment]
Yep, tests look good to me.

(I didn't get a github notification about the latest commit either -- seems like we ought to have.)

**Comment by peterjc** [comment]
@bamueh are you happy to be thanked by name in the ``NEWS`` and ``CONTRIB`` files for this?

**Comment by bamueh** [comment]
Yes, I'm happy with that. Thanks!

**Comment by peterjc** [comment]
Thank you all, merged ready for Biopython 1.67

**Pull request merged**
