### PR TITLE
fix blast xml bit-score parsing

### PR DESCRIPTION
**Pull request by rtf-const**
This pull request addresses issue  #2179

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Is bit score working on both old and v2 BLAST XML now? From a quick look the new tests cover the old XML parser.

The doc8 problem on Python 2.7 is unrelated, see https://bugs.launchpad.net/doc8/+bug/1837515

**Comment by peterjc** [comment]
doc8 problem fixed by #2175 2181

**Comment by rtf-const** [comment]
> Is bit score working on both old and v2 BLAST XML now? 

It's working on both now

> From a quick look the new tests cover the old XML parser.

`def _test_xml_2900_tblastn_001(self, filename):`

this method is used for test both xml v1 and v2

**Comment by peterjc** [comment]
Excellent, thank you - merging...

**Pull request merged**
