### PR TITLE
New Blast parser and qblast

### PR DESCRIPTION
**Pull request by mdehoon**
This PR provides a new parser for Blast XML output, and a new qblast function.

The new parser is in `Bio.Blast`; the old parser is in `Bio.Blast.NCBIXML`.

The main differences between the parsers is as follows:
 - The old parser stores information in a `Bio.Blast.NCBIXML.Blast` object. The `'Bio.Blast.NCBIXML.Blast'` class is designed based on the plain-text Blast parser (which has since been removed from Biopython). Attribute names are based on what seemed reasonable given the plain-text Blast output, but is not always transparent given the XML output that it is currently being used for.
Instead, The new parser stores information in a `Bio.Blast.Record` object. This class follows the DTD that describes the XML in terms of attribute names and dictionary key names, class structure, and object types. This makes it easier to find the detailed description of each field in the NCBI Blast documentation.

 - The old parser stores alignment information as-is, for example
```python
>>> from Bio.Blast import NCBIXML
>>> records = NCBIXML.parse(open("xml_2900_blastn_001.xml", 'rb'))
>>> record = next(records)
>>> record.alignments[0].hsps[0].query
'GAATCCTAGAGGCTTGATTGGCCCAGG-CTGCTG'
```
The new parser stores the alignment information as a `Bio.Align.Alignment` object, which can then be used to e.g. print the alignment in a different format:
```python
>>> from Bio import Blast
>>> records = Blast.parse("xml_2900_blastn_001.xml")
>>> for record in records:
...     for hit in record:
...         for alignment in hit:
...             print(alignment)
...             print(format(alignment, "chain"))
...             print(format(alignment, "clustal"))

gi|372099 101449177 GAATCCTAGAGGCTGGACTGGCCCTGGCCTGCTG 101449143
                  0 ||||||||||||||.||.||||||.||-||||||        34
G26684.1        133 GAATCCTAGAGGCTTGATTGGCCCAGG-CTGCTG       166

chain 44.0 gi|372099107|ref|NC_000069.6| 160039680 - 58590503 58590537 G26684.1 285 + 133 166
27	1	0
6


gi|372099107|ref|NC_000069.6|       GAATCCTAGAGGCTGGACTGGCCCTGGCCTGCTG
G26684.1                            GAATCCTAGAGGCTTGATTGGCCCAGG-CTGCTG

...
```

In Python, XML files should be opened in binary mode (as the string encoding is specified in the XML data itself).
However, the current `qblast` function in `Bio.Blast.NCBIWWW` always returns a Python string. This also breaks attempts to download data in a binary format such as `JSON2`, which returns data in a zipped JSON format:
```python
>>> from Bio.Blast import NCBIWWW
>>> from Bio import SeqIO
>>> record = SeqIO.read("m_cold.fasta", "fasta")
>>> result_stream = NCBIWWW.qblast("blastn", "nt", record.seq, format_type="JSON2")
Traceback (most recent call last):
 ...
   results = handle.read().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 10: invalid start byte
```

The new `qblast` function in `Bio.Blast` always returns the search results as `bytes`, so binary data can be retrieved correctly:
```python
>>> from Bio import Blast
>>> result_stream = Blast.qblast("blastn", "nt", record.seq, format_type="JSON2")
>>> data = result_stream.read()
>>> with open("myzipfile.zip", "wb") as out_stream:
...     out_stream.write(data)
... 
13818
>>> import zipfile
>>> myzipfile = zipfile.ZipFile("myzipfile.zip")
>>> myzipfile.namelist()
['NXAVVRHG013.json', 'NXAVVRHG013_1.json']
>>> stream = myzipfile.open('NXAVVRHG013.json')
>>> data = stream.read().decode()
>>> print(data)
{
	"BlastJSON": [
		{"File": "NXAVVRHG013_1.json" }
	]
}
>>> stream = myzipfile.open('NXAVVRHG013_1.json')
>>> data = stream.read().decode()
>>> print(data)
{
  "BlastOutput2": {
    "report": {
      "program": "blastn",
      "version": "BLASTN 2.14.1+",
      "reference": "Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), \"Gapped BLAST and PSI-BLAST: a new generation of protein database search programs\", Nucleic Acids Res. 25:3389-3402.",
      "search_target": {
        "db": "nt"
      },
      "params": {
        "expect": 10,
        "sc_match": 2,
        "sc_mismatch": -3,
        "gap_open": 5,
        "gap_extend": 2,
        "filter": "L;m;"
      },
      "results": {
        "search": {
          "query_id": "Query_45391",
...
```
XML data returned by `qblast` can also be parsed directly:
```python
>>> result_stream = Blast.qblast("blastn", "nt", record.seq, format_type="XML")
>>> records = Blast.parse(result_stream)
>>> records.program
'blastn'
>>> records.version
'BLASTN 2.14.1+'
>>> for record in records:
...     for hit in record:
...         for alignment in hit:
...             print(alignment)
... 
gi|121904       277 ACCGAAAATGGGCAGAGGAGTGAATTATATGGCAATGACACCTGAGCAACTAGCCGCGGC
                  0 ||.|||||||||.||||.|.||||.||..||||.||||.|.||||.|||.|.||||.|||
Query_676        58 ACAGAAAATGGGGAGAGAAATGAAGTACTTGGCCATGAAAACTGATCAATTGGCCGTGGC

gi|121904       337 CAATTTGATCAACTCCGACATCAATGAGCTCAAGATCGTTGTGATGACACTCATTCATGA
                 60 .|||.|||||.|.|||||.|||||||||||.||.||.|.....||||..|||||..||||
Query_676       118 TAATATGATCGATTCCGATATCAATGAGCTTAAAATGGCAACAATGAGGCTCATCAATGA

gi|121904       397 TGCTTCTAGACTCGGCGGCACCTCAGGATTTGGAACTCATTTTCTTAGATGGCTAGCCTC
                120 ||||..||..|||||.--||...|.||-|||||.||||||||.||.|.||||||.||||.
Query_676       178 TGCTAGTATGCTCGGT--CATTACGGG-TTTGGCACTCATTTCCTCAAATGGCTCGCCTG

...
```

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
The ``qblast`` changes seem very sensible. I was thinking ``Bio.Blast`` might be deprecated in favour of ``Bio.SearchIO``.

Given the work here, I find myself wondering if ``Bio.SearchIO`` generally might be reworded to use the new ``Bio.Align`` objects?

**Comment by mdehoon** [comment]
> I was thinking `Bio.Blast` might be deprecated in favour of `Bio.SearchIO`.

The problem with `Bio.SearchIO` is that it uses `Bio.Align.MultipleSeqAlignment` objects, which have limited usability.

> Given the work here, I find myself wondering if `Bio.SearchIO` generally might be reworded to use the new `Bio.Align` objects?

I think so, yes. Currently `Bio.SearchIO` overlaps some of the functionality of `Bio.Align` and `Bio.AlignIO`. But I'd have to look at `Bio.SearchIO` in detail to see which functionality there is not yet covered by the other modules.

**Comment by mdehoon** [comment]
If release 1.82 will come out in the near future, maybe we can leave this PR open for now, merge after 1.82 is out, and then unify `Bio.Align`/`Bio.SearchIO`/`Bio.Blast` before the next release 1.83 comes out.

**Comment by peterjc** [comment]
I like that plan - I am willing to make time to do the release myself in the next month. Cross reference #4312

**Comment by mdehoon** [comment]
Merging this now that 1.82 is out.

**Comment by peterjc** [comment]
This needed a NEWS file entry, but if you have follow up work planned soon that will keep.

**Comment by mdehoon** [comment]
Yes there is more to come.

**Comment by mdehoon** [comment]
NEWS update is in #4564

**Pull request merged**
