### PR TITLE
Fixes with MMTF structure parsing and StructureBuilder

### PR DESCRIPTION
**Pull request by abradle**
1. I _think_ a bug fix in the StructureBuilder for when dealing with microheterogenity.
2. Bug fix in the MMTF structure parser
3. API addition for MMTF to read directly from GZIP

I'm very happy to be told that my bug fix isn't a bug fix - but it allowed MMTF parsing to proceed for the few instances of microheterogenity.

### CODE REVIEW

**Comment by peterjc** [comment]
Can you give some specific files (MMTF and PDB o MMCIF ideally) where this microheterogenity bug happens? It would be good to add a unit test for this.

CC @etal @JoaoRodrigues

**Comment by abradle** [comment]
So I've added example files and a test. The test only failed on MMTF before the bug fix - so it is possibly not a "bug fix". Yeah it would be awesome if someone who understands the codebase could tell me where I've (most likely) gone wrong!

**Comment by JoaoRodrigues** [comment]
I'll have a look later today, could you give one specific example where it
failed (pdb code)?

J

**Comment by abradle** [comment]
1EJG -Thanks!

**Comment by peterjc** [comment]
Could you work out what was going on @JoaoRodrigues?

**Comment by JoaoRodrigues** [comment]
Hi Peter (and Anthony),

Only got time to have a look at this over the weekend, sorry.

I found a problem with our parser but I'm not sure what exactly the
original 'bug' was. There are two types of heterogeneity here: disordered
atoms (occupying multiple positions) and mutated residues (positions 22 and
25). At position 22, there is a Proline and a Serine, but the backbone
nitrogen of the Proline does not have an altloc field. This makes our
PDBParser not parse the Serine, but it does warn about it. Other than that,
all atoms are parsed fine.

What exactly is your problem in MMTF?

2016-10-10 4:31 GMT-07:00 Peter Cock <notifications@github.com>:

**Comment by peterjc** [comment]
@abradle could you answer Joao's query?

**Comment by peterjc** [comment]
@abradle, sorry to nag - could you answer Joao's query?

**Comment by abradle** [comment]
@JoaoRodrigues @peterjc 

Hi Peter and Joao,

I don't fully understand Joao's question. The original problem was that microheterogenity was not parsed correctly by the structure builder. I was just being cautious and wanted Joao to check my code change doesn't break anything fundamental. It's a one line code fix. Before the code fix microheterogenity was parsed incorrectly for MMTF, after it it is parsed correctly. The example files are available.

Let me know what other information you guys need.

**Comment by JoaoRodrigues** [comment]
Hi @abradle 

It's been a while, but from what I remember, my main question was about what you mean by 'microheterogeneity'. As I noted in my answer, there are two types of 'disorder' in the current nomenclature in Bio.PDB: one is 'true' disorder (same atom in multiple places) while another is more of a secondary sequence (which I think is the case in your example file).

If you think your fix fixes things for your parser and the current unit tests go through, I'm good. It does seem like there was a missing return statement in that condition.

**Comment by abradle** [comment]
Awesome. Sounds good to me too.

**Comment by peterjc** [comment]
So you're happy for this to be merged then @JoaoRodrigues?

**Comment by peterjc** [comment]
Prior to merging there are some style checks failing:

```
$ pep8 --ignore E122,E123,E126,E127,E128,E241,E402,E501,E731 Tests/
Tests/test_microhet.py:7:1: E302 expected 2 blank lines, found 1
Tests/test_microhet.py:19:1: E101 indentation contains mixed spaces and tabs
Tests/test_microhet.py:19:1: W191 indentation contains tabs
Tests/test_microhet.py:20:1: E101 indentation contains mixed spaces and tabs
Tests/test_microhet.py:21:58: E231 missing whitespace after ','
Tests/test_microhet.py:27:1: W391 blank line at end of file
```

Also, that inconsistent space/tab indentation is breaking the actual test under Python 3:

```
======================================================================
ERROR: test_microhet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_tests.py", line 419, in runTest
    suite = loader.loadTestsFromName(name)
  File "/opt/python/3.3.5/lib/python3.3/unittest/loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/travis/build/biopython/biopython/Tests/test_microhet.py", line 19
    mmcif_parser = MMCIFParser()
                               ^
TabError: inconsistent use of tabs and spaces in indentation
----------------------------------------------------------------------
```

Please use spaces (four spaces for each level of indentation).

**Comment by peterjc** [comment]
Almost there on the style check,

```
$ flake8 Tests/
Tests/test_microhet.py:11:1: D210 No whitespaces allowed surrounding docstring text
Tests/test_microhet.py:17:1: D210 No whitespaces allowed surrounding docstring text
Tests/test_microhet.py:27:37: W292 no newline at end of file
```

You'd need to first run ``pip install flake8 flake8-docstrings`` to run this check locally.

**Comment by abradle** [comment]
Thanks! That was helpful. All fixed.

Best wishes,

Anthony

**Comment by peterjc** [comment]
Green light on the style, but the tests themselves are failing. The pattern puzzled me initially with failures on Python 2.7, 3.3 and 3.5 but not on all versions of Python, but it matches where the ``mmtf-python`` dependency is installed.

Python 2.7 breaks,

```
======================================================================
ERROR: test_cif (test_microhet.ParseMicrohet)
Parse MMTF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_microhet.py", line 16, in test_cif
    structure = MMTFParser.get_structure("PDB/1EJG.mmtf")
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/PDB/mmtf/__init__.py", line 37, in get_structure
    return get_from_decoded(decoder)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/PDB/mmtf/__init__.py", line 12, in get_from_decoded
    decoder.pass_data_on(structure_decoder)
  File "/home/travis/build/biopython/biopython/.tox/py27-cover/lib/python2.7/site-packages/mmtf/api/mmtf_reader.py", line 173, in pass_data_on
    decoder_utils.add_atomic_information(self, data_setters)
  File "/home/travis/build/biopython/biopython/.tox/py27-cover/lib/python2.7/site-packages/mmtf/utils/decoder_utils.py", line 90, in add_atomic_information
    add_chain_info(data_api, data_setters, chain_index)
  File "/home/travis/build/biopython/biopython/.tox/py27-cover/lib/python2.7/site-packages/mmtf/utils/decoder_utils.py", line 76, in add_chain_info
    add_group(data_api, data_setters, group_ind)
  File "/home/travis/build/biopython/biopython/.tox/py27-cover/lib/python2.7/site-packages/mmtf/utils/decoder_utils.py", line 50, in add_group
    data_api.sec_struct_list[group_index])
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/PDB/mmtf/DefaultParser.py", line 111, in set_group_info
    group_number, insertion_code)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/PDB/StructureBuilder.py", line 155, in init_residue
    % (resname, field, resseq, icode))
PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')
======================================================================
ERROR: test_mmtf (test_microhet.ParseMicrohet)
Parse mmCIF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_microhet.py", line 24, in test_mmtf
    structure = mmcif_parser.get_structure("MICR", "PDB/1EJG.cif")
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/PDB/MMCIFParser.py", line 62, in get_structure
    self._build_structure(structure_id)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/PDB/MMCIFParser.py", line 186, in _build_structure
    structure_builder.init_residue(resname, hetatm_flag, int_resseq, icode)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-2.7/Bio/PDB/StructureBuilder.py", line 155, in init_residue
    % (resname, field, resseq, icode))
PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')
----------------------------------------------------------------------
```

Python 3.3:

```
======================================================================
ERROR: test_cif (test_microhet.ParseMicrohet)
Parse MMTF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_microhet.py", line 16, in test_cif
    structure = MMTFParser.get_structure("PDB/1EJG.mmtf")
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.3/Bio/PDB/mmtf/__init__.py", line 37, in get_structure
    return get_from_decoded(decoder)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.3/Bio/PDB/mmtf/__init__.py", line 12, in get_from_decoded
    decoder.pass_data_on(structure_decoder)
  File "/home/travis/build/biopython/biopython/.tox/py33-cover/lib/python3.3/site-packages/mmtf/api/mmtf_reader.py", line 173, in pass_data_on
    decoder_utils.add_atomic_information(self, data_setters)
  File "/home/travis/build/biopython/biopython/.tox/py33-cover/lib/python3.3/site-packages/mmtf/utils/decoder_utils.py", line 90, in add_atomic_information
    add_chain_info(data_api, data_setters, chain_index)
  File "/home/travis/build/biopython/biopython/.tox/py33-cover/lib/python3.3/site-packages/mmtf/utils/decoder_utils.py", line 76, in add_chain_info
    add_group(data_api, data_setters, group_ind)
  File "/home/travis/build/biopython/biopython/.tox/py33-cover/lib/python3.3/site-packages/mmtf/utils/decoder_utils.py", line 50, in add_group
    data_api.sec_struct_list[group_index])
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.3/Bio/PDB/mmtf/DefaultParser.py", line 111, in set_group_info
    group_number, insertion_code)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.3/Bio/PDB/StructureBuilder.py", line 155, in init_residue
    % (resname, field, resseq, icode))
Bio.PDB.PDBExceptions.PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')
======================================================================
ERROR: test_mmtf (test_microhet.ParseMicrohet)
Parse mmCIF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_microhet.py", line 24, in test_mmtf
    structure = mmcif_parser.get_structure("MICR", "PDB/1EJG.cif")
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.3/Bio/PDB/MMCIFParser.py", line 62, in get_structure
    self._build_structure(structure_id)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.3/Bio/PDB/MMCIFParser.py", line 186, in _build_structure
    structure_builder.init_residue(resname, hetatm_flag, int_resseq, icode)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.3/Bio/PDB/StructureBuilder.py", line 155, in init_residue
    % (resname, field, resseq, icode))
Bio.PDB.PDBExceptions.PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')
----------------------------------------------------------------------
```

Python 3.4 skipped,

```
test_microhet ... skipping. Install mmtf to use Bio.PDB.mmtf (e.g. pip install mmtf-python)
```

Python 3.5 breaks,

```
======================================================================
ERROR: test_cif (test_microhet.ParseMicrohet)
Parse MMTF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_microhet.py", line 16, in test_cif
    structure = MMTFParser.get_structure("PDB/1EJG.mmtf")
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/PDB/mmtf/__init__.py", line 37, in get_structure
    return get_from_decoded(decoder)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/PDB/mmtf/__init__.py", line 12, in get_from_decoded
    decoder.pass_data_on(structure_decoder)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/mmtf/api/mmtf_reader.py", line 173, in pass_data_on
    decoder_utils.add_atomic_information(self, data_setters)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/mmtf/utils/decoder_utils.py", line 90, in add_atomic_information
    add_chain_info(data_api, data_setters, chain_index)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/mmtf/utils/decoder_utils.py", line 76, in add_chain_info
    add_group(data_api, data_setters, group_ind)
  File "/home/travis/build/biopython/biopython/.tox/py35-cover/lib/python3.5/site-packages/mmtf/utils/decoder_utils.py", line 50, in add_group
    data_api.sec_struct_list[group_index])
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/PDB/mmtf/DefaultParser.py", line 111, in set_group_info
    group_number, insertion_code)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/PDB/StructureBuilder.py", line 155, in init_residue
    % (resname, field, resseq, icode))
Bio.PDB.PDBExceptions.PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')
======================================================================
ERROR: test_mmtf (test_microhet.ParseMicrohet)
Parse mmCIF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_microhet.py", line 24, in test_mmtf
    structure = mmcif_parser.get_structure("MICR", "PDB/1EJG.cif")
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/PDB/MMCIFParser.py", line 62, in get_structure
    self._build_structure(structure_id)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/PDB/MMCIFParser.py", line 186, in _build_structure
    structure_builder.init_residue(resname, hetatm_flag, int_resseq, icode)
  File "/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.5/Bio/PDB/StructureBuilder.py", line 155, in init_residue
    % (resname, field, resseq, icode))
Bio.PDB.PDBExceptions.PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')
----------------------------------------------------------------------
```

Python 3.6 skipped,

```
test_microhet ... skipping. Error: Install mmtf to use Bio.PDB.mmtf (e.g. pip install mmtf-python)
```

PyPy skipped,

```
test_microhet ... skipping. Install mmtf to use Bio.PDB.mmtf (e.g. pip install mmtf-python)
```

PyPy3 skipped,

```
test_microhet ... skipping. Error: Install mmtf to use Bio.PDB.mmtf (e.g. pip install mmtf-python)
```

We should ensure ``mmtf-python`` is installed on PyPy or PyPy3 for testing - would you expect it to work (other than the current test failure)?

**Comment by peterjc** [comment]
I just rebased this to the current master (it would be better as a named branch, but never mind).

Testing locally on macOS with PyPy,

```
$ pypy --version
Python 2.7.12 (aff251e54385, Nov 09 2016, 17:25:49)
[PyPy 5.6.0 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)]
$ pypy test_mmtf.py
test_4CUP (__main__.ParseMMTF)
Compare parsing 4CUP.mmtf and 4CUP.cif ... ok
test_1A80 (__main__.SimpleParseMMTF)
Parse 1A8O.mmtf ... ok
test_4ZHL (__main__.SimpleParseMMTF)
Parse 4ZHL.mmtf ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.606s

OK
```

But:

```$ pypy test_microhet.py 
test_cif (__main__.ParseMicrohet)
Parse MMTF file. ... ERROR
test_mmtf (__main__.ParseMicrohet)
Parse mmCIF file. ... ERROR

======================================================================
ERROR: test_cif (__main__.ParseMicrohet)
Parse MMTF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_microhet.py", line 16, in test_cif
    structure = MMTFParser.get_structure("PDB/1EJG.mmtf")
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/Bio/PDB/mmtf/__init__.py", line 39, in get_structure
    return get_from_decoded(decoder)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/Bio/PDB/mmtf/__init__.py", line 12, in get_from_decoded
    decoder.pass_data_on(structure_decoder)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/mmtf/api/mmtf_reader.py", line 173, in pass_data_on
    decoder_utils.add_atomic_information(self, data_setters)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/mmtf/utils/decoder_utils.py", line 90, in add_atomic_information
    add_chain_info(data_api, data_setters, chain_index)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/mmtf/utils/decoder_utils.py", line 76, in add_chain_info
    add_group(data_api, data_setters, group_ind)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/mmtf/utils/decoder_utils.py", line 50, in add_group
    data_api.sec_struct_list[group_index])
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/Bio/PDB/mmtf/DefaultParser.py", line 116, in set_group_info
    group_number, insertion_code)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/Bio/PDB/StructureBuilder.py", line 160, in init_residue
    % (resname, field, resseq, icode))
PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')

======================================================================
ERROR: test_mmtf (__main__.ParseMicrohet)
Parse mmCIF file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_microhet.py", line 24, in test_mmtf
    structure = mmcif_parser.get_structure("MICR", "PDB/1EJG.cif")
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/Bio/PDB/MMCIFParser.py", line 64, in get_structure
    self._build_structure(structure_id)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/Bio/PDB/MMCIFParser.py", line 188, in _build_structure
    structure_builder.init_residue(resname, hetatm_flag, int_resseq, icode)
  File "/Users/pc40583/Downloads/Software/pypy2-v5.6.0-osx64/site-packages/Bio/PDB/StructureBuilder.py", line 160, in init_residue
    % (resname, field, resseq, icode))
PDBConstructionException: Blank altlocs in duplicate residue SER (' ', 22, ' ')

----------------------------------------------------------------------
Ran 2 tests in 0.096s

FAILED (errors=2)
```

i.e. Much the same as the error seen earlier on Linux under TravisCI where mmtf is installed.

**Comment by abradle** [comment]
hi peter,

I've had time to look at this. 

It appears like the error comes from Line 156 in StructureBuilder.py
'''
                    if not self._is_completely_disordered(duplicate_residue):
                        # if this exception is ignored, a residue will be missing
                        self.residue = None
                        raise PDBConstructionException(
                            "Blank altlocs in duplicate residue %s ('%s', %i, '%s')"
                            % (resname, field, resseq, icode))
'''
The logic of that doesn't make sense to me. 

I attach a residue in a valid PDB file (1EJG) that would fail this exception.
It has PRO and SER @ resiude 22 (microheterogenity) and the first one (Proline) does not have alt-locs for all atoms. That also seems fine. But will trigger the exception.

Quite why the above exception exists I don't know.

I would advocate for removing the exception completely - but I don't know the code well enough to see if that would do other bad things.
@peterjc @JoaoRodrigues  thoughts?


ATOM    400  N   PRO A  22       4.915  12.683  -3.102  1.00  1.83           N  
ANISOU  400  N   PRO A  22      220    185    289    -20     -2    -33       N  
ATOM    401  CA APRO A  22       6.042  13.429  -2.601  0.57  1.82           C  
ANISOU  401  CA APRO A  22      339    145    204    -56     75   -144       C  
ATOM    402  C  APRO A  22       6.387  13.122  -1.160  0.57  1.66           C  
ANISOU  402  C  APRO A  22      230    195    204    -82     85   -119       C  
ATOM    403  O  APRO A  22       5.480  13.006  -0.345  0.57  2.09           O  
ANISOU  403  O  APRO A  22      224    322    246    -51     60    -58       O  
ATOM    404  CB APRO A  22       5.655  14.896  -2.744  0.57  2.86           C  
ANISOU  404  CB APRO A  22      591    108    387    -50     -5   -173       C  
ATOM    405  CG APRO A  22       4.661  14.854  -4.058  0.57  2.66           C  
ANISOU  405  CG APRO A  22      420    174    417     69     20    -27       C  
ATOM    406  CD APRO A  22       3.957  13.505  -3.910  0.57  2.27           C  
ANISOU  406  CD APRO A  22      317    174    370     60     -1     -4       C  
ATOM    407  HA APRO A  22       6.915  13.244  -3.241  0.57  1.93           H  
ATOM    408  HB2APRO A  22       5.112  15.266  -1.863  0.57  3.34           H  
ATOM    409  HB3APRO A  22       6.516  15.539  -2.944  0.57  3.34           H  
ATOM    410  HG2APRO A  22       3.919  15.683  -4.043  0.57  3.20           H  
ATOM    411  HG3APRO A  22       5.214  14.903  -5.002  0.57  3.20           H  
ATOM    412  HD2APRO A  22       2.984  13.625  -3.389  0.57  2.69           H  
ATOM    413  HD3APRO A  22       3.752  13.060  -4.903  0.57  2.69           H  
ATOM    414  CA BSER A  22       6.034  13.399  -2.687  0.21  1.55           C  
ATOM    415  CA CSER A  22       6.112  13.653  -2.656  0.22  2.31           C  
ATOM    416  C  BSER A  22       6.367  13.062  -1.223  0.21  2.92           C  
ATOM    417  C  CSER A  22       6.354  13.275  -1.187  0.22  1.92           C  
ATOM    418  O  BSER A  22       5.412  13.050  -0.345  0.21  1.87           O  
ATOM    419  O  CSER A  22       5.636  12.705  -0.270  0.22  1.77           O  
ATOM    420  CB BSER A  22       5.409  14.835  -2.876  0.21  2.60           C  
ATOM    421  CB CSER A  22       5.605  15.097  -2.687  0.22  3.56           C  
ATOM    422  OG BSER A  22       4.760  15.243  -1.635  0.21  2.11           O  
ATOM    423  OG CSER A  22       6.750  15.771  -2.280  0.22  6.38           O  
ATOM    424  HA BSER A  22       6.897  13.240  -3.349  0.21  4.26           H  
ATOM    425  HA CSER A  22       7.013  13.518  -3.271  0.22  4.26           H

**Comment by JoaoRodrigues** [comment]
Hi @abradle ,

Indeed, it seems that the code is expecting residues in the same position (differing in insertion code) to have disordered atoms as well (alternate location fields). This doesn't make much sense to me either. I would remove it and see if it breaks any test, then check what might be going on there.

**Comment by abradle** [comment]
Just running the tests in TravisCI now. Can't run tests locally at the
moment.

**Comment by peterjc** [comment]
Closing this in favour of new pull request #1379

**Pull request closed without merging**
