### PR TITLE
Some KEGG REST queries now return String not Byte in Python3

### PR DESCRIPTION
**Pull request by widdowquinn**
See issue #832.

Python 3 makes a distinction between string types (String and
Byte) that was not made in Python 2. This gave unintuitive results
with print() and SeqIO.read() in Python3. This short fix returns
String rather than Byte handles (as with Bio.Entrez), for all
requests through the KEGG REST API, other than those for image
data, which is still returned as a Byte handle.

### CODE REVIEW

**Comment by peterjc** [comment]
I presume the TravisCI results won't be any help here as we're not using it for the online tests...

**Comment by widdowquinn** [comment]
You're right - I wouldn't have thought they'd be any help.

I tested manually using this notebook: https://github.com/widdowquinn/Notebooks-Bioinformatics/blob/master/Biopython_KGML_intro.ipynb, which gave identical output for me with Python 2 both with and without this change relative to v1.66+, and with Python 3/v1.66+ only after the change.

**Comment by peterjc** [comment]
Can you add something to ``test_KEGG_online.py`` which looks like it hardly parses anything at all right now?

**Comment by widdowquinn** [comment]
The new commit 8c10a24 adds `Bio.SeqIO` parsing to the `aaseq` and `ntseq` tests in `test_KEGG_online.py` - these should fail if a `Byte` handle is returned by `kegg_get()`, and succeed if a `String` handle is returned.

**Comment by peterjc** [comment]
Cherry-picked with minor merge conflict dealt with, and mentioned in the NEWS file - see 24d6ff768748900168bd47cac44a2603a539e466 and the commits preceding it. Thank you!

**Pull request closed without merging**
