### PR TITLE
Fill in missing licence headers in Python files

### PR DESCRIPTION
**Pull request by svalqui**
This pull request addresses issue #1609 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

Files have been updated with the license, this was a bit different better check the license.
biopython/Bio/PDB/parse_pdb_header.py

I left the 2 files below as is, they are better reviewed by a member.
??? - biopython/Bio/PDB/QCPSuperimposer/qcprotmodule.c
??? - biopython/Bio/Cluster/cluster.c

Walking biopython/Tests/
Walking biopython/Bio
Walking biopython/BioSQL/
439 old, 114 new, 0 other, 553 in total

Regards,

### CODE REVIEW

**Comment by peterjc** [comment]
Please undo the changes to these files:

* ``Bio/codonalign/chisq.py`` - see #1610 
* All the dual licensing, i.e. ``Bio/motifs/*`` and ``Bio/Cluster/*`` and ``Bio/KDTree/*`` as I want to do those with a detailed log of the contributors in the git commit message to have an audit trail.

Otherwise this looks good, thank you!

**Comment by svalqui** [comment]
@peterjc , Hi Peter, reverted as requested, All the best.

**Comment by svalqui** [comment]
@peterjc All good, reverted
Bio/PDB/parse_pdb_header.py
Bio/SeqUtils/CodonUsageIndices.py
Bio/SeqUtils/IsoelectricPoint.py
Bio/SeqUtils/ProtParam.py
All the best.

**Comment by peterjc** [comment]
It looks ready to merge - did you want to add your name to the ``NEWS.rst`` and ``CONTRIB.rst`` files?

Note TravisCI is failing right now, but this is not your fault:

```
tox.exception.ConfigError: ConfigError: substitution key 'py27' not found
```

**Comment by peterjc** [comment]
See https://github.com/biopython/biopython/issues/1730 for the TravisCI/Tox problem.

**Comment by peterjc** [comment]
Did you want to be thanked by name? See also #1711 - can we make the template clearer here?

**Comment by svalqui** [comment]
@peterjc , Hi Peter Thank you for the consideration, I think the template #1711 is clear and good, at times when you do a small contribution to a project  writing your name along others who had spent hours doesn't feel right. I intent to continue contributing so I will add my name to the rst files on the next pull request I log.
Cheers,

**Comment by peterjc** [comment]
Thank you - we'll look forward to future contributions 👍

**Pull request merged**
