### PR TITLE
Drop experimental warnings on Bio.phenotype

### PR DESCRIPTION
**Pull request by peterjc**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Both modules have been in place and stable for some time, this is probably overdue.

CC: @mgalardini and @zruan

### CODE REVIEW

**Comment by peterjc** [comment]
I hoped this might also fix the recent release of Sphinx 2.4.0 failing, on the hypothesis it was due to these import time warnings and strict mode.

**Review by mdehoon — CHANGES_REQUESTED** [review]
I don't think `Bio.codonalign` is ready for this.

**Review by mgalardini — APPROVED** [review]

**Comment by peterjc** [comment]
OK, I'll restrict this to just the phenotyping module 👍

**Comment by peterjc** [comment]
(I've rebased this and pushed the change, but it is not yet reflected on the GitHub website)

**Comment by peterjc** [comment]
Ah, I mixed up the repositories. This was not meant to be from the main repo.

**Review by mdehoon — APPROVED** [review]

**Pull request merged**
