### PR TITLE
Use better test alignments for PSL and BED files

### PR DESCRIPTION
**Pull request by mdehoon**
This PR changes the RNA sequences in the PSL and BED tests to enable more extensive testing.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@peterjc  Github automatically adds you as a reviewer whenever there are changes in `Bio.Align`. This PR is a minor change to include better tests.

**Comment by peterjc** [comment]
Shall we change https://github.com/biopython/biopython/blob/master/.github/CODEOWNERS from this:

```
Bio/Align/* @peterjc
Bio/Align/_aligners.c @mdehoon
```

to:

```
Bio/Align/* @mdehoon
```

**Comment by peterjc** [comment]
Cross reference #3863 for updating the code owners file.

**Comment by mdehoon** [comment]
@peterjc  Thanks!

**Pull request merged**
