### PR TITLE
Jaspar doctest update - issue #1902

### PR DESCRIPTION
**Pull request by kaskales**
This pull request addresses issue #1902 , changed the doctest into an RST literal block and updated the example for the JASPAR2018 mysqldump.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
This looks good, but I just applied #1906 which means a minor tweak in ``run_tests.py`` is now needed - it went from a list of doctests to test, to a list to exclude.

**Comment by kaskales** [comment]
I merged with the new r`un_tests.py` file but the AppVeyor build failed and is giving me a `Fallback clouds stack is too big.` error. I'm not sure if this is an error on my end or not.

**Comment by peterjc** [comment]
Merged - thank you!

**Comment by kaskales** [comment]
Thank you!

**Pull request merged**
