### PR TITLE
Delete Tests/Motif for Tests/motifs

### LINKED ISSUE #2057: Duplicate files in Tests/Motif and Tests/motifs
The files in Test/motifs seem to be a copy of those in Test/Motif plus some more. Has the Motif directory been deprecated since renaming Bio.Motif to Bio.motifs?

### PR DESCRIPTION
**Pull request by victorlin**
This pull request addresses issue #2057. The directory Tests/Motif has been abandoned for Tests/motifs since a4bf956.

This closes #2057.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_Tutorial.py", line 260, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 2 Tutorial doctests failed: test_chapter_motifs_line_00028, test_chapter_motifs_line_01455
```

Paths need updating here:

https://github.com/biopython/biopython/blob/biopython-173/Doc/Tutorial/chapter_motifs.tex#L28

and here (exact line number look to have changed slightly since v1.73 which I am linking to here):

https://github.com/biopython/biopython/blob/biopython-173/Doc/Tutorial/chapter_motifs.tex#L1449

```
======================================================================
FAIL: parse (Bio.motifs)
Doctest: Bio.motifs.parse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\doctest.py", line 2224, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.motifs.parse
  File "C:\projects\biopython\build\lib.win32-2.7\Bio\motifs\__init__.py", line 27, in parse
----------------------------------------------------------------------
File "C:\projects\biopython\build\lib.win32-2.7\Bio\motifs\__init__.py", line 47, in Bio.motifs.parse
Failed example:
    with open("Motif/alignace.out") as handle:
        for m in motifs.parse(handle, "AlignAce"):
            print(m.consensus)
Exception raised:
    Traceback (most recent call last):
      File "C:\Py\lib\doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Bio.motifs.parse[1]>", line 1, in <module>
        with open("Motif/alignace.out") as handle:
    IOError: [Errno 2] No such file or directory: 'Motif/alignace.out'
----------------------------------------------------------------------
Ran 491 tests in 814.276 seconds
```

It looks like the path needs fixing in this doctest,

https://github.com/biopython/biopython/blob/biopython-173/Bio/motifs/__init__.py#L46

**Comment by victorlin** [comment]
@peterjc thanks for the tip. Now, running `run_tests.py --offline` yield no errors/failures.

**Comment by MarkusPiotrowski** [comment]
You got the same D400 error as I with an earlier pull request (see PR #2061). Please wait for PR #2061 to be merged

**Comment by peterjc** [comment]
The unrelated flake8 D400 issue has been sorted out.

These changes look good, thank you. If you do want to be thanked by name, just ask and we'll add you to the NEWS.rst and CONTRIB.rst files.

**Comment by victorlin** [comment]
@peterjc thanks for the merge. I've added my name to the listings in #1986 - will wait for that to be merged.

**Pull request merged**
