### PR TITLE
Add support for NCBI BLAST XML v2

### PR DESCRIPTION
**Pull request by rtf-const**
This pull request addresses issue #1839

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
This looks impressive - I see you've split the existing BLAST XML parser into two using subclasses, did that seem easiest?

Does this mean adding support for BLAST XML v2 to ``Bio.SearchIO`` should be really simple to include?

**Comment by rtf-const** [comment]
I do not use subclasses for parsing different XML versions, because parser doesn't know XML version beforehand. Instead actuall version is determined in the process of parsing based on root tag name. Blast XML v1 and v2 are very similar in structure and mainly differ just by tags names. So the process is very simple: start reading XML, look at the name of root node, determine version and then code setups the dictionary that matches XML tag name with the method that process it.

As I can see Bio.SearchIO already uses some constant dictionaries that match tag name with a resulting objects properties. So for adding  xml v2 support in SerachIO we can use different dictionaries depending on XML version.

**Comment by peterjc** [comment]
TravisCI failed on a ReportLab issue, since fixed on the master - see #1995. If you add yourself to the ``NEWS.rst`` file or made any other change that would trigger a rebuild.

@bow are you available to review this work?

**Comment by bow** [comment]
@peterjc I'm less familiar with the internals of `Bio.Blast`, but from what I understand, the changes look ok.

And yes, SearchIO does indeed match XML tag names with object properties, since XML parsing is handled by `xml.etree.ElementTree`. This can be extended to v2 as well.

**Comment by peterjc** [comment]
Rebased to deal with a trivial merge conflict in the NEWS file with the contributor names.

I think this deserves a short ``NEWS.rst`` entry too - although if it is now trivial to add BLAST v2 XML to SearchIO, we could merge this as is, and do that next?

**Comment by bow** [comment]
Sounds like a good idea. It's also nice that @rtf-const already added the test files for v2 ~ which we can use for SearchIO as well :).

**Pull request merged**
