### PR TITLE
Rename Tests\test_MMCIF.py in Tests\test_PDB_MMCIFParser.py

### PR DESCRIPTION
**Pull request by Gasta88**
As decided in PR #1222, I've renamed the file accordingly.

### CODE REVIEW

**Comment by peterjc** [comment]
This looks to be a confused branch history with much of your work on #1222 included. Could you try:

```
git fetch upstream
git rebase upstream/master
git push origin Gasta88-patch-13 --force
```

(Assuming you have the main Biopython repository setup as ``upstream`` and your own fork as ``origin``)

If the rebase fails, just use ``git rebase --abort``

**Comment by Gasta88** [comment]
Are you also assuming that Gasta88-patch-13 is a local branch on my machine? because it is not the case.

I could close this PR and delete the remote branch. Then have the right commit in a new one and create a new PR.

**Comment by peterjc** [comment]
I'll just cherry-pick 331c1d479cbca24dcc7dea96cdf53f2e787616b2 which will solve this in one step...

**Comment by peterjc** [comment]
Cherry-picked as f5126f2965336e978b183cd145d523ba7cfae434 - thanks!

**Pull request closed without merging**
