### PR TITLE
SubsMat.MatrixInfo

### PR DESCRIPTION
**Pull request by biologyguy**
I've added two more matrices to the list (PHAT75/73 and SLIM161, both for transmembrane domains), and a function (mirror_matrix) that will take any of the dictionaries stored in MatrixInfo and return a new dictionary that includes all of the values in both key orders. The reason for the function: 
>\>\>\> blosum62 = MatrixInfo.blosum62
>\>\>\> blosum62[("W","F")]
1
>\>\>\> blosum62[("F","W")]
KeyError 

but:
>\>\>\> blosum62 = MatrixInfo.mirror_matrix(MatrixInfo.blosum62)
>\>\>\> blosum62[("W","F")]
1
>\>\>\> blosum62[("F","W")]
1

### CODE REVIEW

**Comment by biologyguy** [comment]
Just wanted to revive this pull request. I've stripped out any actual new code, and just added a new substitution matrix (PHAT). The expected unit test output has been updated as well. It would be nice to have a transmembrane specific substitution matrix in the official BioPython code base.

As per the previous discussion, there is another matrix, SLIM161, which is useful for those studying transmembrane proteins, but is more complicated because it's non-synonymous. I've removed it from this pull request, because it requires special handling from SeqMat.

**Comment by akhiljobby** [comment]
I am not very versed with these things and was wondering how I could get the PHAT matrix from this [link ](https://github.com/biopython/biopython/pull/283/commits/fada9ffafde639212669bd5b89f5da053bac58e4) in a text or csf format? Thank you.

**Comment by peterjc** [comment]
@akhiljobby This pull request was closed by the author without being merged into the official Biopython repository, so it isn't part of the official Biopython.

You could checkout the final commit, and try running that:
https://github.com/biologyguy/biopython/commit/9ee1df5

(The changes were made on the master branch of the forked repository, and there have been changes on that branch since... we would recommend making a branch for any new feature or bug fix.)

Feedback from someone familiar with and interested in substitution matrices would have been ideal earlier (something I didn't feel qualified to judge without significant time looking at this code). Still, better late than never, this work could be resurrected.

Note at a minimum the tests will need updating (the old print-and-compare tests have since all been converted to the ``unittest`` framework).

**Comment by biologyguy** [comment]
Hi @akhiljobby,
It's been a few years since I looked at this and would need a little while to re-familiarize if resurrection and inclusion in BioPython was the actual goal. If you're just wanting an output of the matrix as text, does this meet your needs?

```
A,A,5.0
A,C,1.0
A,P,3.0
A,S,2.0
A,T,0.0
C,C,7.0
D,A,-5.0
D,C,-7.0
D,D,12.0
D,G,-2.0
D,N,2.0
D,P,-5.0
D,S,-4.0
D,T,-5.0
E,A,-5.0
E,C,-7.0
E,D,6.0
E,E,12.0
E,G,-3.0
E,N,0.0
E,P,-5.0
E,S,-3.0
E,T,-5.0
F,A,-1.0
F,C,0.0
F,D,-5.0
F,E,-5.0
F,F,6.0
F,G,-2.0
F,H,-2.0
F,I,0.0
F,K,-7.0
F,L,1.0
F,M,0.0
F,N,-1.0
F,P,-5.0
F,Q,-2.0
F,R,-7.0
F,S,-2.0
F,T,-2.0
F,V,-1.0
G,A,1.0
G,C,-2.0
G,G,9.0
G,P,-3.0
G,S,1.0
G,T,-1.0
H,A,-3.0
H,C,-7.0
H,D,-1.0
H,E,-1.0
H,G,-4.0
H,H,11.0
H,N,4.0
H,P,-6.0
H,Q,2.0
H,S,-2.0
H,T,-4.0
I,A,0.0
I,C,-3.0
I,D,-5.0
I,E,-5.0
I,G,-2.0
I,H,-5.0
I,I,5.0
I,K,-7.0
I,M,3.0
I,N,-3.0
I,P,-4.0
I,Q,-3.0
I,R,-6.0
I,S,-2.0
I,T,-1.0
K,A,-7.0
K,C,-10.0
K,D,-5.0
K,E,-4.0
K,G,-5.0
K,H,-5.0
K,K,5.0
K,N,-2.0
K,P,-4.0
K,Q,-1.0
K,R,-1.0
K,S,-5.0
K,T,-6.0
L,A,-1.0
L,C,-2.0
L,D,-5.0
L,E,-5.0
L,G,-2.0
L,H,-4.0
L,I,2.0
L,K,-7.0
L,L,4.0
L,M,2.0
L,N,-3.0
L,P,-5.0
L,Q,-3.0
L,R,-6.0
L,S,-2.0
L,T,-1.0
M,A,-1.0
M,C,-2.0
M,D,-5.0
M,E,-5.0
M,G,-1.0
M,H,-4.0
M,K,-6.0
M,M,6.0
M,N,-2.0
M,P,-5.0
M,Q,-1.0
M,R,-6.0
M,S,-2.0
M,T,0.0
N,A,-2.0
N,C,-2.0
N,G,-1.0
N,N,11.0
N,P,-4.0
N,S,1.0
N,T,-1.0
P,C,-8.0
P,P,13.0
P,S,-3.0
P,T,-4.0
Q,A,-3.0
Q,C,-5.0
Q,D,0.0
Q,E,1.0
Q,G,-2.0
Q,N,2.0
Q,P,-3.0
Q,Q,9.0
Q,S,-1.0
Q,T,-3.0
R,A,-6.0
R,C,-8.0
R,D,-7.0
R,E,-6.0
R,G,-5.0
R,H,-4.0
R,N,-3.0
R,P,-7.0
R,Q,-2.0
R,R,9.0
R,S,-6.0
R,T,-6.0
S,C,1.0
S,S,6.0
T,C,-1.0
T,S,1.0
T,T,3.0
V,A,1.0
V,C,-2.0
V,D,-5.0
V,E,-5.0
V,G,-2.0
V,H,-5.0
V,I,3.0
V,K,-8.0
V,L,1.0
V,M,1.0
V,N,-3.0
V,P,-4.0
V,Q,-3.0
V,R,-7.0
V,S,-2.0
V,T,0.0
V,V,4.0
W,A,-4.0
W,C,-4.0
W,D,-7.0
W,E,-7.0
W,F,0.0
W,G,-5.0
W,H,-3.0
W,I,-4.0
W,K,-8.0
W,L,-3.0
W,M,-4.0
W,N,-5.0
W,P,-6.0
W,Q,1.0
W,R,-7.0
W,S,-5.0
W,T,-7.0
W,V,-4.0
W,W,11.0
W,Y,1.0
Y,A,-3.0
Y,C,-1.0
Y,D,-4.0
Y,E,-2.0
Y,F,4.0
Y,G,-3.0
Y,H,3.0
Y,I,-3.0
Y,K,-4.0
Y,L,-2.0
Y,M,-2.0
Y,N,2.0
Y,P,-5.0
Y,Q,0.0
Y,R,-6.0
Y,S,-2.0
Y,T,-3.0
Y,V,-3.0
Y,Y,11.0
```

**Comment by akhiljobby** [comment]
Hi Steve,
Yes, this is sort of what I needed however in a matrix format like blast
format
  A C D E …
A 5.0 1.0 -5.0 -5.0 …
C 1.0 7.0 -7.0 -7.0 …
D -5.0 -7.0 12.0 6.0 …
E -5.0 -7.0 6.0 12.0 …
… … … … … …

Thank you.

Regards,

*AKHIL JOBBY*
Department of Computer Science & Software Engineering
Concordia University.

*1515 St. Catherine St. West, EV11-411*
*Montreal, Quebec, CANADA   H3G 1M8*
Phone: (514) 848 2424 ext. 7211
Cell: (514) 557 6192
Email: a_jobby@encs.concordia.ca

**Comment by biologyguy** [comment]
```python
#!/usr/bin/env python
matrix = {
('W', 'F') :  0.0, ('L', 'R') : -6.0, ('I', 'I') :  5.0, ('Q', 'Q') :  9.0,
('W', 'N') : -5.0, ('V', 'I') :  3.0, ('H', 'T') : -4.0, ('H', 'P') : -6.0,
('W', 'V') : -4.0, ('Q', 'E') :  1.0, ('W', 'R') : -7.0, ('Q', 'A') : -3.0,
('H', 'H') : 11.0, ('H', 'D') : -1.0, ('L', 'N') : -3.0, ('Y', 'M') : -2.0,
('Y', 'I') : -3.0, ('Y', 'E') : -2.0, ('E', 'S') : -3.0, ('Y', 'A') : -3.0,
('Y', 'Y') : 11.0, ('T', 'C') : -1.0, ('E', 'C') : -7.0, ('Y', 'Q') :  0.0,
('E', 'G') : -3.0, ('V', 'A') :  1.0, ('C', 'C') :  7.0, ('M', 'R') : -6.0,
('P', 'T') : -4.0, ('V', 'E') : -5.0, ('P', 'P') : 13.0, ('I', 'T') : -1.0,
('K', 'S') : -5.0, ('R', 'G') : -5.0, ('I', 'P') : -4.0, ('R', 'C') : -8.0,
('A', 'T') :  0.0, ('K', 'K') :  5.0, ('A', 'P') :  3.0, ('V', 'M') :  1.0,
('I', 'D') : -5.0, ('K', 'C') :-10.0, ('K', 'G') : -5.0, ('R', 'S') : -6.0,
('F', 'Q') : -2.0, ('F', 'A') : -1.0, ('V', 'V') :  4.0, ('M', 'N') : -2.0,
('F', 'E') : -5.0, ('D', 'N') :  2.0, ('F', 'I') :  0.0, ('F', 'M') :  0.0,
('M', 'S') : -2.0, ('S', 'S') :  6.0, ('L', 'Q') : -3.0, ('W', 'E') : -7.0,
('W', 'A') : -4.0, ('W', 'M') : -4.0, ('H', 'S') : -2.0, ('W', 'I') : -4.0,
('S', 'C') :  1.0, ('L', 'A') : -1.0, ('L', 'E') : -5.0, ('W', 'Q') :  1.0,
('H', 'G') : -4.0, ('Q', 'N') :  2.0, ('H', 'C') : -7.0, ('L', 'M') :  2.0,
('W', 'Y') :  1.0, ('Y', 'N') :  2.0, ('E', 'P') : -5.0, ('Y', 'F') :  4.0,
('E', 'T') : -5.0, ('A', 'A') :  5.0, ('I', 'N') : -3.0, ('G', 'A') :  1.0,
('Y', 'V') : -3.0, ('E', 'D') :  6.0, ('W', 'H') : -3.0, ('Y', 'R') : -6.0,
('M', 'Q') : -1.0, ('P', 'S') : -3.0, ('R', 'H') : -4.0, ('A', 'C') :  1.0,
('R', 'D') : -7.0, ('K', 'P') : -4.0, ('L', 'D') : -5.0, ('K', 'T') : -6.0,
('V', 'N') : -3.0, ('M', 'A') : -1.0, ('K', 'H') : -5.0, ('V', 'R') : -7.0,
('P', 'C') : -8.0, ('M', 'E') : -5.0, ('A', 'S') :  2.0, ('T', 'T') :  3.0,
('R', 'T') : -6.0, ('I', 'G') : -2.0, ('R', 'P') : -7.0, ('K', 'D') : -5.0,
('I', 'C') : -3.0, ('F', 'R') : -7.0, ('F', 'V') : -1.0, ('L', 'C') : -2.0,
('F', 'F') :  6.0, ('D', 'A') : -5.0, ('F', 'N') : -1.0, ('W', 'D') : -7.0,
('L', 'P') : -5.0, ('Q', 'S') : -1.0, ('N', 'C') : -2.0, ('N', 'G') : -1.0,
('H', 'N') :  4.0, ('W', 'T') : -7.0, ('Q', 'G') : -2.0, ('W', 'P') : -6.0,
('Q', 'C') : -5.0, ('N', 'S') :  1.0, ('L', 'H') : -4.0, ('L', 'L') :  4.0,
('G', 'T') : -1.0, ('M', 'M') :  6.0, ('G', 'P') : -3.0, ('Y', 'K') : -4.0,
('Y', 'G') : -3.0, ('Y', 'C') : -1.0, ('E', 'A') : -5.0, ('E', 'E') : 12.0,
('Y', 'S') : -2.0, ('M', 'P') : -5.0, ('V', 'C') : -2.0, ('M', 'T') :  0.0,
('V', 'G') : -2.0, ('R', 'E') : -6.0, ('V', 'K') : -8.0, ('K', 'Q') : -1.0,
('R', 'A') : -6.0, ('I', 'R') : -6.0, ('N', 'A') : -2.0, ('V', 'S') : -2.0,
('M', 'D') : -5.0, ('M', 'H') : -4.0, ('K', 'A') : -7.0, ('R', 'Q') : -2.0,
('K', 'E') : -4.0, ('F', 'S') : -2.0, ('I', 'K') : -7.0, ('D', 'P') : -5.0,
('D', 'T') : -5.0, ('I', 'M') :  3.0, ('F', 'C') :  0.0, ('W', 'L') : -3.0,
('F', 'G') : -2.0, ('F', 'K') : -7.0, ('F', 'T') : -2.0, ('D', 'D') : 12.0,
('Q', 'T') : -3.0, ('W', 'G') : -5.0, ('Q', 'P') : -3.0, ('W', 'C') : -4.0,
('W', 'K') : -8.0, ('H', 'Q') :  2.0, ('Q', 'D') :  0.0, ('W', 'W') : 11.0,
('V', 'L') :  1.0, ('L', 'G') : -2.0, ('W', 'S') : -5.0, ('L', 'K') : -7.0,
('N', 'P') : -4.0, ('H', 'E') : -1.0, ('N', 'T') : -1.0, ('H', 'A') : -3.0,
('Y', 'L') : -2.0, ('Y', 'H') :  3.0, ('G', 'S') :  1.0, ('Y', 'D') : -4.0,
('V', 'Q') : -3.0, ('L', 'T') : -1.0, ('G', 'G') :  9.0, ('G', 'C') : -2.0,
('E', 'N') :  0.0, ('Y', 'T') : -3.0, ('Y', 'P') : -5.0, ('R', 'N') : -3.0,
('V', 'D') : -5.0, ('K', 'R') : -1.0, ('V', 'H') : -5.0, ('I', 'Q') : -3.0,
('V', 'P') : -4.0, ('M', 'C') : -2.0, ('K', 'N') : -2.0, ('V', 'T') :  0.0,
('M', 'G') : -1.0, ('T', 'S') :  1.0, ('I', 'E') : -5.0, ('M', 'K') : -6.0,
('I', 'A') :  0.0, ('N', 'N') : 11.0, ('R', 'R') :  9.0, ('F', 'P') : -5.0,
('L', 'I') :  2.0, ('I', 'S') : -2.0, ('D', 'S') : -4.0, ('L', 'S') : -2.0,
('I', 'H') : -5.0, ('F', 'D') : -5.0, ('D', 'C') : -7.0, ('F', 'H') : -2.0,
('D', 'G') : -2.0, ('F', 'L') :  1.0
}

chars = [aa[0] for aa in matrix] + [aa[1] for aa in matrix]
chars = sorted(list(set(chars)))

output = " ,%s\n" % ",".join(chars)

for i, aa1 in enumerate(chars):
    output += aa1
    for j, aa2 in enumerate(chars):
        if (aa1, aa2) in matrix:
            output += "," + str(matrix[(aa1, aa2)])
        else:
            output += "," + str(matrix[(aa2, aa1)])
    output += "\n"
print(output)
```

**Comment by akhiljobby** [comment]
Thank you steve. This works!
Regards,

*AKHIL JOBBY*
Department of Computer Science & Software Engineering
Concordia University.

*1515 St. Catherine St. West, EV11-411*
*Montreal, Quebec, CANADA   H3G 1M8*
Phone: (514) 848 2424 ext. 7211
Cell: (514) 557 6192
Email: a_jobby@encs.concordia.ca

**Pull request closed without merging**
