### PR TITLE
removed unnecessary try/except block

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request removes unnecessary try/except block from `test_Seq_objs.py`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Cross reference discussion on #3052

**Comment by peterjc** [comment]
AppVeyor thinks this is a non-mergeable pull request... might need manually rebasing to the (new) master branch? Do you want me to try that?

**Comment by mdehoon** [comment]
@peterjc  Yes please.

**Comment by peterjc** [comment]
I'm confused - at the command line this all seems fine.

No sign of the PR on TravisCI yet either: https://travis-ci.org/github/biopython/biopython/pull_requests

GitHub having a bad day perhaps?

**Comment by mdehoon** [comment]
Done in #3058

**Pull request closed without merging**
