### PR TITLE
Added code to parse h-bond information from DSSP output.

### PR DESCRIPTION
**Pull request by kianho**
Some of my prior work has required the inter-residue hydrogen bond information from DSSP.

My pull request adds the following:
- code to parse the hydrogen bond information (relative indices and energies) from the appropriate columns in the DSSP output.
- A test case in test_PDB.py that checks to see if the relative indices from the hydrogen bond columns of each residue actually point to residues that were successfully parsed by biopython from the same DSSP output.

I have based this contribution from similar code in the prody package (https://github.com/prody/ProDy/blob/master/prody/proteins/dssp.py). It seemed like a trivial (and useful) feature to implement that eliminates the need to re-parse the dssp output just to get new columns from the same output. 

It passes the biopython test suite, including the aforementioned additional test.

I'm open to constructive feedback and discussion.

Thanks.

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
Seems reasonable. @peterjc, any reason why Travis failed? It doesn't seem to be connected to the code, just a random 'hanging' build. The PDB tests passed fine.

**Comment by peterjc** [comment]
Getting three time-outs is suspicious (one could be just bad luck). I have asked TravisCI to re-run them...

**Comment by kianho** [comment]
I took a look at the CI build logs, I will address the errors (they seem easy to fix).

**Comment by peterjc** [comment]
After re-running, we seem to have two timeouts on TravisCI, curiously both on Python 3 after running ``test_SwissProt.py`` which suggests the problem is stalling in ``test_TCoffee_tool.py`` and therefore not related to your changes. Very strange.

I also noticed that there are many warnings shown under Python 3.4 which are successfully silenced under Python 3.3, but again, that is likely a separate issue.

**Comment by kianho** [comment]
That is interesting, because I took a look at my code and I was using python2 idioms that were not compatible with python3 (in short, I was using ```dict.itervalues''' in my test cases, a method which exists in python2 but not 3):

- https://travis-ci.org/biopython/biopython/jobs/47647404#L2699
- https://travis-ci.org/biopython/biopython/jobs/47647405#L2902

I have made the appropriate corrections to my test case code (https://github.com/biopython/biopython/commit/b8e0b698f7210bfd7638bc5e9297906f3449906f).

**Comment by peterjc** [comment]
Well spotted, yes, we use ``.values()`` rather than ``.itervalues()`` in Biopython to work nicely under both Python 2 and Python 3.

**Comment by peterjc** [comment]
There is definitely something wrong with ``test_TCoffee_tool.py`` which is unrelated to your work. I have just disabled this test on TravisCI for now https://travis-ci.org/biopython/biopython/builds/48239754 https://github.com/biopython/biopython/commit/c9cb5d8596f6861b55e534cae9739824b04cba54

**Comment by JoaoRodrigues** [comment]
Bump: @peterjc. The code was fine, IIRC, could we merge this if Travis passes now?

**Comment by peterjc** [comment]
@JoaoRodrigues If the tests pass, then you're happy for this to be merged?

I'm note sure if there's an easy way to get TravisCI to rerun the test after merging to the current master branch... we might have to manually run the tests locally (especially Python 3).

**Comment by JoaoRodrigues** [comment]
I'm not home until Tuesday, I'll check that then. Thanks.

A sex, 3/04/2015, 21:07, Peter Cock <notifications@github.com> escreveu:

**Comment by kianho** [comment]
I made some further amendments to this PR which has triggered a fresh TravisCI re-run.

**Comment by peterjc** [comment]
@JoaoRodrigues the tests pass :)

Other than the trivial ``assertEquals`` to ``assertEqual`` change, are you happy?

(If you want to do the merge, it looks like it would rebase onto master cleanly)

**Comment by JoaoRodrigues** [comment]
@peterjc Fine by me!

**Comment by peterjc** [comment]
@JoaoRodrigues Thanks!

@kianho I will do this now (including the ``assertEquals`` change).

**Comment by peterjc** [comment]
Thank you both - commits rebased and applied to master, see commits leading up to https://github.com/biopython/biopython/commit/66ef7b747a14a34d25af7b20af6330fd45516f6e

**Comment by kianho** [comment]
No problems, it was a pleasure to contribute.
Thanks.

**Comment by peterjc** [comment]
Acknowledged in 66ef7b747a14a34d25af7b20af6330fd45516f6e (was missing # prefix otherwise GitHub would have linked that to this pull request)

**Pull request closed without merging**
