### PR TITLE
Remove executable flag or add shebang

### PR DESCRIPTION
**Pull request by MartinThoma**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by MartinThoma** [comment]
All of the files to which I've added a shebang are marked as executable. I can remove the shebang, but then I would also remove the executable marking. As they didn't have a shebang before, that would likely not break anything.

**Comment by MartinThoma** [comment]
@peterjc `Tests/run_tests.py` is actually not executable :-) 

Should I do the following?

1. Make `Tests/run_tests.py` + add a hashbang
2. Remove the executable flag from the others and remove the shebang

**Comment by peterjc** [comment]
Do you agree @mdehoon / @MarkusPiotrowski / anyone else following general issues?

**Comment by MarkusPiotrowski** [comment]
As Windows user these things don't matter to me. It's just interesting that maybe I or other Windows users have silently converted some py file into executable. If this can happen (shall we test this?) then it wouldn't make sense to remove the executable flag.

**Comment by peterjc** [comment]
If it does happen sometimes accidentally (might be on FAT filesystems or something like that), then automatically testing it makes sense (and the pre-commit hook would do that - we could start running it from the TravisCI/tox style checks).

**Comment by MarkusPiotrowski** [comment]
I'm not sure on what we should aggree:
Adding shebangs to all executables or removing all executable flags and shebangs except `run_tests.py`?

Would `pre-commit*  handle the flag conversion? Or would then I need to fiddle aroung with `chmod`?

**Comment by peterjc** [comment]
Markus is right to ask what the impact would be on developers on Windows. Can you easily install pre-commit and try it?

I would pick one of the following for consistency, probably (a) or (b):

(a) None of ``Tests/*.py`` should have the executable bit, or the hash bang.
(b) Only ``Tests/run_tests.py`` itself is executable with a hash bang, rest of ``Tests/*.py`` non-executable with no hash bang.
(c) Both ``Tests/run_tests.py`` and ``Tests/text_*.py`` files marked as executable with a hash-bang line (things like the ``Tests/common_*.py`` are not).

Right now the pull request does:

(d) Leave the historical mixture (but be internally consistent, executable if and only if there is a hashbang)

**Comment by MartinThoma** [comment]
We could also do the following:

1. Come up with a solution which seems in principle desirable (a, b, or c) and apply it with this PR
2. Remove the check from pre-commit
3. See how the repository looks in a month - if there are executable files again, try to find out why and see if this is a fixable problem.

Please note, though, that one could also see the pre-commit file as a template for the repository. As it is executed on the developers side, it is not enforcing it. People can still just deactivate some of the hooks by removing the line from pre-commit. If we want to enforce it, we need to add the checks to the CI pipeline (Travis).

By the way: [Removing the executable flag on Windows via git](https://stackoverflow.com/a/13593391/562769) - I didn't try it, though.

**Comment by peterjc** [comment]
Good point - we could have the pre-commit configuration active for a month (say), letting keen Biopython developers and contributors start using it, and if there are no issues then start using it from TravisCI and/or AppVeyor.

**Comment by MartinThoma** [comment]
I've just removed the hashbangs where I've added them. Then I noticed that they are in a couple of places where they are not necessary:

```
pairwise2_testCases.py:1:#!/usr/bin/env python
requires_wise.py:1:#!/usr/bin/env python
run_tests.py:1:#!/usr/bin/env python
test_align.py:1:#!/usr/bin/env python
test_BioSQL_mysql_connector_online.py:1:#!/usr/bin/env python
test_BioSQL_mysql_connector.py:1:#!/usr/bin/env python
test_BioSQL_MySQLdb_online.py:1:#!/usr/bin/env python
test_BioSQL_MySQLdb.py:1:#!/usr/bin/env python
test_BioSQL_psycopg2_online.py:1:#!/usr/bin/env python
test_BioSQL_psycopg2.py:1:#!/usr/bin/env python
test_BioSQL_sqlite3_online.py:1:#!/usr/bin/env python
test_BioSQL_sqlite3.py:1:#!/usr/bin/env python
test_Blast_Record.py:1:#!/usr/bin/env python
test_ColorSpiral.py:1:#!/usr/bin/env python
test_EmbossPrimer.py:1:#!/usr/bin/env python
test_GenBank.py:1:#!/usr/bin/env python
test_GenomeDiagram.py:1:#!/usr/bin/env python
test_GraphicsChromosome.py:1:#!/usr/bin/env python
test_GraphicsDistribution.py:1:#!/usr/bin/env python
test_GraphicsGeneral.py:1:#!/usr/bin/env python
test_HMMGeneral.py:1:#!/usr/bin/env python
test_KGML_graphics_online.py:1:#!/usr/bin/env python
test_KGML_graphics.py:1:#!/usr/bin/env python
test_KGML_nographics.py:1:#!/usr/bin/env python
test_Medline.py:1:#!/usr/bin/env python
test_pairwise2_no_C.py:1:#!/usr/bin/env python
test_pairwise2.py:1:#!/usr/bin/env python
test_pairwise_aligner.py:1:#!/usr/bin/env python
test_SwissProt.py:1:#!/usr/bin/env python
test_Uniprot.py:1:#!/usr/bin/env python
```

Should I remove them?

**Comment by peterjc** [comment]
I would be happy with (a) or (b) outlined earlier, i.e. removing the hash-bang from all the ``test_*.py`` files.

Also ``requires_wise.py`` does not need to be executable with a hash-bang.

I personally would keep ``run_tests.py`` and probably ``pairwise2_testCases.py`` as executable.

**Comment by MartinThoma** [comment]
`sed '/#!\/usr\/bin\/env python/d' *.py` did the trick :-)

I think I now implemented (b) :-)

**Comment by MartinThoma** [comment]
> I personally would keep [...] pairwise2_testCases.py as executable

Just curious: Why that? What makes this one special?

**Comment by peterjc** [comment]
Although we can run all the ``test_XXX.py`` files individually with ``python test_XXX.py`` or potentially ``./test_XXX.py``, they are normally run via ``run_tests.py`` (which can take a list of tests as command line arguments and messes about with the python path to try to ensure we're testing the local build and not the system installed Biopython).

Of note, even ``run_tests.py`` does not need to be run directly as it can be called from the parent folder with ``python setup.py test`` - but I think enabling ``./run_tests.py`` is a convience over ``python run_tests.py`` worth having.

Next, ``pairwise2_testCases.py`` is not a test at all, but code to generate test files. It is meaningful to run this directly, albeit not often. While ``requires_wise.py`` gets imported by a couple of the tests, there is no good reason to run it directly  other than testing the logic for finding the command line tool ``wise``.

**Comment by peterjc** [comment]
I've dealt with the trivial merge conflict, assume this passes the automated testing, I think we should squash-and-merge it now.

**Comment by peterjc** [comment]
It didn't make the Biopython 1.77 release, but will be in Biopython 1.78 - thank you!

**Pull request merged**
