### PR TITLE
amend urlopen in Tutorial

### PR DESCRIPTION
**Pull request by Gasta88**
In reference to issue #754, I've edited two chapters where the method `urlopen()` is used in conformation to Python2 (since support for Python3.3 is dropped).

There is one behavior that I don't understand yet (apologies, this is my first time with LaTeX). 
Running `Tests/test_Tutorials.py` in Python 2.7.13 I get the following errors:
```bash
~/Documents/GitHub/biopython/Tests (urlopenTutorial *)$ python test_Tutorial.py 
Running Tutorial doctests...
**********************************************************************
File "test_Tutorial.py", line 238, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00638
Failed example:
    record = Entrez.read(handle)
Expected:
    Traceback (most recent call last):
      ...
    Bio.Entrez.Parser.NotXMLError: Failed to parse the XML data (syntax error: line 1, column 0). Please make sure that the input data are in XML format.
Got:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00638[4]>", line 1, in <module>
        record = Entrez.read(handle)
      File "/home/gasta/.local/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 453, in read
        record = handler.read(handle)
      File "/home/gasta/.local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 243, in read
        raise NotXMLError(e)
    NotXMLError: Failed to parse the XML data (syntax error: line 1, column 0). Please make sure that the input data are in XML format.
**********************************************************************
File "test_Tutorial.py", line 238, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00709
Failed example:
    record = Entrez.read(handle)
Expected:
    Traceback (most recent call last):
      ...
    Bio.Entrez.Parser.ValidationError: Failed to find tag 'DocsumList' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.
Got:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00709[4]>", line 1, in <module>
        record = Entrez.read(handle)
      File "/home/gasta/.local/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 453, in read
        record = handler.read(handle)
      File "/home/gasta/.local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 233, in read
        self.parser.ParseFile(handle)
      File "/home/gasta/.local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 368, in startElementHandler
        raise ValidationError(name)
    ValidationError: Failed to find tag 'DocsumList' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.
**********************************************************************
2 items had failures:
   1 of   5 in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00638
   1 of   5 in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00709
***Test Failed*** 2 failures.
Traceback (most recent call last):
  File "test_Tutorial.py", line 272, in <module>
    raise RuntimeError("%i/%i tests failed" % tests)
RuntimeError: 2/1043 tests failed
```

Which are not involved with any chapter that I've modified.

Instead, if I use Python 3.5.3, everything run smoothly.

### CODE REVIEW

**Comment by peterjc** [comment]
The test failure method names is ``doctest_test_chapter_entrez_line_00638`` and ``doctest_test_chapter_entrez_line_00709`` which mean the doctest in the file ``chapter_entrez.tex`` starting at line 638 and 709. Note it might be further down the file if there are continuations of the doctest.

That seems to mean this is unrelated to your changes, which is odd.

For this it might be simplest to try running the doctest by hand, copy and pasting the examples line by line under both Python 2 and 3.

**Comment by Gasta88** [comment]
After checking better the `Doc/Tutorials` folder, I've noticed that only those two files contains examples of `urllib.openurl`. But these are not tagged with `%doctest` or `%cont-doctest` and the `test_Tutorials.py` script shouldn't pick them up. 
I've notice as well that the syntax `from urllib import urllib` does not work for Python2.

If it is the case to create new doctests for the documentation, then it would be best to find permanent online files that can be used as a reference for both occasions.

Otherwise I suggest to close this issue and focus on the `Entrez` problem.



Otherwise I would close this PR and issue and focus on the `Entrez` error.

**Comment by peterjc** [comment]
Ideally we would make the examples work under both Python 2 and 3, in which case the doctest could be automatically tested. The import is messy though.

See https://github.com/biopython/biopython/commit/56dad1779ab5da91001a27d3bf3c69755daba862 for how to tag the docstests and requiring internet access (to obey the ``run_tests.py --offline`` option).

Second best, make sure they work on Python 3 with a note/comment to warn any Python 2 users.

**Comment by Gasta88** [comment]
The import won't still work if they point to fake files (ex: `someswissprotfile.dat` for the Uniprot chapter) and I have no knowledge of permanent online repositories that can host these type of files. 

Same can be said for the `chapter_cluster.tex`.

Taking as an example `chapter_uniprot.tex`, if we want to make doctests work we must  place more testing files into `Tests/Uniprot` or `Doc/examples`. That said, the doctests might need to be re-written.

**Comment by peterjc** [comment]
We used to use ``www.biopython.org/SRC/Tests/...`` for examples, but that has gone as a downside of moving the website to GitHub pages. Now you can use the GitHub repository download URL for a file, for examples see:

``
$ grep raw.githubusercontent.com Doc/Tutorial/chapter_*.tex
```

**Comment by Gasta88** [comment]
Please ignore the recent commits. 

I'm testing some ideas, therefore I should probably close this PR and open a new one when I have something definitive.

**Comment by peterjc** [comment]
OK, thanks for looking at this.

**Pull request closed without merging**
