### PR TITLE
Declare Bio.Aplhabet obsolete with PendingDeprecationWarning

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses issue #2046

TODO: Follow up with changes to the tutorial to downplay usage of Bio.Aphabet

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by bede** [comment]
Should the following code be triggering this warning?

```python
def consensus_seqrecord(consensus, ref_id):
    return SeqRecord(Seq(consensus), id=ref_id + '_cns')
```

I am not, after all, using Bio.Alphabet explicitly.

**Comment by peterjc** [comment]
Lots of Biopython indirectly imports ``Bio.Alphabet``, so would trigger the ``PendingDeprecationWarning`` - including your example - however that class of warning is silent by default. Something in your code is likely changing the default warning filters?

A next step for us would be to add some (non-silent by default) ``BiopythonDeprecationWarning`` cases, but this is going to be tricky to avoid code like your example triggering it. My current thinking is specific alphabet methods or attributes (like ``.letters`` or ``.gap_char``) could start triggering warnings.

**Comment by bede** [comment]
Thanks Peter. It'll be Pytest that's changing the warning filters. Hardly a major issue – I just wanted to check I wasn't doing something deprecated.

**Comment by peterjc** [comment]
No, your example is the kind of thing which should not need any changes (if we do the deprecation and removal/replacement right). Thanks for checking!

**Comment by zoldello** [comment]
@peterjc What is the alternative to Bio.Alphabet? I see it used on the biopython tutorial page. Do you know a more current tutorial?

**Comment by peterjc** [comment]
Now that Biopython 1.77 is out, we are working on this now. The scale of the job may make some small breaks in backward compatibility almost unavoidable - but hopefully only in rarely used corner cases.

**Comment by zoldello** [comment]
@peterjc  Thanks. Normally, code is deprecated after an alternative is released and not before. I assumed Biopython followed that unwritten rule. Thanks for explaining to me the plan.

**Comment by mdehoon** [comment]
Down with `DeprecationWarning`!

**Pull request merged**
