### PR TITLE
Avoid blind exceptions and enforce this on TravisCI

### PR DESCRIPTION
**Pull request by peterjc**
This pull request 'fixes' a lot of exception handling accross the code base, and expands our TravisCI style checks to include the ``flake8-blind-except`` add-on for ``flake8`` which adds a new error code:

```
B901 blind except: statement
```

https://github.com/elijahandrews/flake8-blind-except

In general I have defaulted to ``except Exception:`` which is still quite generic, but in places I have used ``except ImportError:``, ``except ValueError:`` or ``except KeyError`` where this looked appropriate.

Because it touches lots of files, I'd like extra eyes on this.

CC @lennax (thanks for flagging this on https://github.com/biopython/biopython/pull/1237#discussion_r117775370 during a pull request review)

### CODE REVIEW

**Comment by peterjc** [comment]
Clearly this needs a little more work...

**Comment by peterjc** [comment]
CC @bendmorris, does the ``CDAOError`` exception change here make sense to you? The exception as initially introduced made sense https://github.com/biopython/biopython/commit/5112c91f17da0a459f0adce81a2b77e6c61fd092 but at some point it was switched to only being used for dependency checking.

**Comment by bendmorris** [comment]
Looks right to me. As far as I remember CDAOError was only used to catch issues writing to file via librdf; a later commit removed the librdf dependency and CDAOIO now writes to file directly (https://github.com/biopython/biopython/commit/aa23d59b3ddaf7ee455b42332fc0d979b4805169 and https://github.com/biopython/biopython/commit/3fc47631d6cb0a2212653a8f9e36efe886a14265).

**Comment by peterjc** [comment]
@bendmorris in that case I'm happy with switching to ``MissingPythonDependencyError`` for any import failures in ``Bio/Phylo/CDAOIO.py`` - thanks for checking!

**Comment by peterjc** [comment]
@widdowquinn several of the non-specific try/except blocks were in GenomeDiagram - could you cast your eye over those changes please?

**Comment by peterjc** [comment]
@brandoninvergo some of the non-specific try/except clauses changed here are in your ``Bio.Phylo.PAML`` code, would you mind taking a quick look at the proposed changes here? Thanks!

**Comment by peterjc** [comment]
@zruan could you check the exception change I am proposing in ``Bio/codonalign/codonseq.py`` please? Is ` ``KeyError`` appropriate here?

https://github.com/biopython/biopython/pull/1253/commits/2fb2f41953b5fa757f8cb98f8afcab3a7a4de8b0#diff-8124646a41c73d1fc0e78c1447b483f9

Thanks.

**Comment by widdowquinn** [comment]
The GenomeDiagram changes look fine to me. Boy, but I was even lazier back then when I wrote that code! ;)

**Comment by peterjc** [comment]
Thanks all, merging...

**Comment by peterjc** [comment]
(Codecov complained about the coverage not quite being good enough - its defaults are quite stringent)

**Comment by brandoninvergo** [comment]
The `Bio.Phylo.PAML` changes look fine to me.

**Comment by peterjc** [comment]
Thanks  @brandoninvergo

**Pull request merged**
