### PR TITLE
Add url_base parameter to qblast to enable submissions to BLAST on th…

### PR DESCRIPTION
**Pull request by christiam**
…e cloud

### CODE REVIEW

**Comment by mdehoon** [comment]
Looks good to me. Can you also update the documentation?

**Comment by christiam** [comment]
@mdehoon, 
                  I did update the documentation for the function in question. Could you please point me to what I missed? Thanks in advance!

**Comment by mdehoon** [comment]
@christiam  Sorry, I meant the documentation in Doc/Tutorial/chapter_blast.tex.

**Comment by christiam** [comment]
@mdehoon Thanks, I've expanded the documentation.

**Comment by peterjc** [comment]
Would you be happy to be added to the ``NEWS`` and ``CONTRIB`` files for this work Christiam? Thanks!

**Comment by christiam** [comment]
Yes, that would be fine, thanks.

**Pull request merged**
