### PR TITLE
Apply black style to test_Cluster.py, version 19.10b0.

### PR DESCRIPTION
**Pull request by svalqui**
This pull request addresses issue #2552 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

This PR changes the appearance of some matrices and some list, it seems fine but it would be good to review it.

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good to me, although there are several smaller matrixes (usually of integers) where black has squeezed them into one long line which is less clear. However, adding black format off/on comments would also detract from the flow, so I'd leave it as black put it.

Over to @mdehoon.

**Comment by mdehoon** [comment]
> Looks good to me, although there are several smaller matrixes (usually of integers) where black has squeezed them into one long line which is less clear. 

In these cases, I prefer the original. Clarity is more important than black's opinion.

**Comment by peterjc** [comment]
@svalqui can you force black to cooperate by adding comments after the desired line breaks, or is adding the black format off/on comment line pairs the only option here?

**Comment by svalqui** [comment]
you can use a regex with black, but that is not this case, I'll need to use the fmt on/off here, I need a couple of days an I'll update this.

**Comment by svalqui** [comment]
@mdehoon I have updated it, I tried to keep the overall look, as just keeping them as before made it look a bit uneven. What do you think?

**Comment by peterjc** [comment]
That looks better to me, all the square matrices look good.

**Comment by peterjc** [comment]
And #3070 strikes again, but in triplicate:

```
======================================================================
ERROR: test_transfer (common_BioSQL.InDepthLoadTest)
Make sure can load record into another namespace.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 957, in setUp
    driver=DBDRIVER, user=DBUSER, passwd=DBPASSWD, host=DBHOST, db=TESTDB
  File "C:\projects\biopython\build\lib.win-amd64-3.7\BioSQL\BioSeqDatabase.py", line 110, in open_database
    conn = connect(**kw)
  File "C:\Py\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
======================================================================
ERROR: test_addition (common_BioSQL.SeqInterfaceTest)
Check can add DBSeq objects together.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 440, in setUp
    load_database("GenBank/cor6_6.gb")
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 246, in load_database
    TESTDB = create_database()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 216, in create_database
    _do_db_cleanup()
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 145, in _do_db_cleanup
    driver=DBDRIVER, host=DBHOST, user=DBUSER, passwd=DBPASSWD, db=TESTDB
  File "C:\projects\biopython\build\lib.win-amd64-3.7\BioSQL\BioSeqDatabase.py", line 110, in open_database
    conn = connect(**kw)
  File "C:\Py\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
======================================================================
ERROR: test_seq (common_BioSQL.SeqInterfaceTest)
Make sure Seqs from BioSQL implement the right interface.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\common_BioSQL.py", line 443, in setUp
    driver=DBDRIVER, user=DBUSER, passwd=DBPASSWD, host=DBHOST, db=TESTDB
  File "C:\projects\biopython\build\lib.win-amd64-3.7\BioSQL\BioSeqDatabase.py", line 110, in open_database
    conn = connect(**kw)
  File "C:\Py\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
----------------------------------------------------------------------
Ran 519 tests in 828.684 seconds
FAILED (failures = 1)
```

I will restart AppVeyor.

**Comment by peterjc** [comment]
@mdehoon OK to merge now?

**Comment by peterjc** [comment]
You've addressed the concern about the visual look of the matrices, so I think we can go ahead and merge this now.

**Pull request merged**
