### PR TITLE
remove deprecated module Bio.KDTree

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request removes the deprecated module `Bio.KDTree`.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Isn't this a bit early? It was deprecated in Biopython 1.74, released July 2019 - so we should wait until July 2020: https://biopython.org/wiki/Deprecation_policy

**Comment by mdehoon** [comment]
> Isn't this a bit early? It was deprecated in Biopython 1.74, released July 2019 - so we should wait until July 2020: https://biopython.org/wiki/Deprecation_policy

Time to update the deprecation policy

**Comment by mdehoon** [comment]
> > Isn't this a bit early? It was deprecated in Biopython 1.74, released July 2019 - so we should wait until July 2020: https://biopython.org/wiki/Deprecation_policy
> 
> Time to update the deprecation policy

or at least declare it obsolete

**Comment by JoaoRodrigues** [comment]
I would indeed update the documentation/guidelines just to go with the deprecation warning in the code and let users voice their concerns. I do however, agree that a long period of time (6mo-12mo) is necessary to keep these deprecations from surprising people. Unfortunately, some HPC environments will not follow our release cycle and update their versions of Biopython regularly.

**Comment by mdehoon** [comment]
See also #2872 , which is a duplicate of this PR.

**Pull request closed without merging**
