### PR TITLE
Fixed disordered residue issue #302

### PR DESCRIPTION
**Pull request by fcaramia**

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
@peterjc Just a heads up for this pull, which should fix a long-standing issue on PDB parsing.

**Comment by peterjc** [comment]
@JoaoRodrigues Are you able to review this? If not maybe we have a suitable person at the BOSC 2015 CodeFest in Dublin today who might try? [I'm travelling today]

**Comment by JoaoRodrigues** [comment]
@peterjc I am here :) Reviewed.

**Comment by peterjc** [comment]
Cherry picked as https://github.com/biopython/biopython/commit/a6c8e9bf8f5419c47089a7d4710b10d1ef0f1073 - acknowledgement in https://github.com/biopython/biopython/commit/acbe3a80605b0528cd1acae88002a56aabefd697

Thank you @fcaramia, and @JoaoRodrigues for reviewing this. Apologies for the delay.

**Comment by peterjc** [comment]
@fcaramia Would you agree to dual licence your Biopython contributions under the *Biopython License Agreement* and the *BSD 3-Clause License* as per #898 please?

**Comment by fcaramia** [comment]
I agree. Thanks Peter

**Comment by peterjc** [comment]
Thank you @fcaramia - I think there is just one person to confirm, and we can dual license ``Bio/PDB/StructureBuilder.py`` :)

**Pull request closed without merging**
