### PR TITLE
Apply black to SCOP data and CodonTables

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses in part issue #2008 (applying black).

It is a subset of #2506 avoiding changing the codon tables themselves.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@svalqui do you have time to look over this black pull request?

**Comment by svalqui** [comment]
I usually use
# Turn black code style off
# fmt: off
...
Some code to exclude.
...
# Turn black code style on
# fmt: on

The pair "off" and "on".

on file Bio/Data/CodonTable.py, is only "# fmt: off" as is at the end of the file I do not think that matters.

I looks fine to me, you should merge it.

**Comment by peterjc** [comment]
I wondered about an off/on pair, but in the context just an off seemed fine.

Thank you!

**Comment by peterjc** [comment]
I'm taking Markus' OK on the parent pull request #2506 as an OK...

**Pull request merged**
