### PR TITLE
Remove python 2 branch in setup.py

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses issue #2490 - but I had overlooked it until now.

I wonder if we can drop the entire osx_clang_fix code yet? i.e. -Qunused-arguments special casing on macOS.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
> I wonder if we can drop the entire osx_clang_fix code yet? i.e. -Qunused-arguments special casing on macOS.

Probably we can remove it.
Currently I am getting
```
/usr/bin/python-config --cflags
-iwithsysroot /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -iwithsysroot /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE
```
Also, this code is almost six years old. Something must have changed since then.

**Comment by MarkusPiotrowski** [comment]
There's another Python 2/3 workaround in this file which may be addressed:

https://github.com/biopython/biopython/blob/130ce5f2738e4ff8702619653e5481a9379bbf40/setup.py#L336-L346

**Comment by peterjc** [comment]
True, as long as ``python2 setup.py`` runs and gives the clean error about needing Python 3 we can clean up a few more bits.

**Comment by peterjc** [comment]
On the C flags issue, I current get the following on macOS:

``$ /usr/bin/python-config --cflags``
``-iwithsysroot /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -iwithsysroot /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE
``

**Comment by peterjc** [comment]
I went further and removed the no unused dependency checking code (we no longer even need NumPy at compile time).

**Pull request merged**
