### PR TITLE
Make make not complain about lack of _build dir when run locally

### PR DESCRIPTION
**Pull request by ExplodingCabbage**
This pull request addresses issue #2281 

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

---

In the end I decided to use `.gitkeep` files instead of adding the `mkdir` command to the Makefile, contrary to @peterjc's suggestion in #2281, because:

* I wasn't sure that running that command for *every* Make operation made sense, but since they're all deferred to Sphinx, I can't easily make it run only on build.
* I wasn't sure how to cleanly get the right path in the makefile to pass to the command; if I just copy it verbatim, then the paths are relative to the current working directory and so wrong if you run make from within the `api` folder.

I think this solution is also fine, @peterjc?

### CODE REVIEW

**Comment by peterjc** [comment]
Hmm, not immediately obvious why this breaks from the log:

```
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 1
make: Leaving directory '/home/travis/build/biopython/biopython/Doc/api'
ERROR: InvocationError for command /usr/bin/make -C Doc/api/ html (exited with code 2)
```

However, it looks likely to be down to ``Doc/api/_static/`` not existing?

**Comment by ExplodingCabbage** [comment]
D'oh, sorry. You're right, I screwed up. Will fix tonight.

**Comment by peterjc** [comment]
That's what automated testing is for - we're all human.

**Comment by ExplodingCabbage** [comment]
Fix force-pushed.

**Pull request merged**
