### PR TITLE
Update docs with working testing instructions

### PR DESCRIPTION
**Pull request by npars**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

- PR #3912 introduced changes that broke the existing testing instructions
- Update testing instructions to work with latest test scripts
- Test instructions now work with setup.py script as well as through the Intellij test runner

### CODE REVIEW

**Comment by peterjc** [comment]
Good point, this needs fixing. I recall some pip changes about in-place builds, which may or may not be relevant here...

**Comment by npars** [comment]
@peterjc do you have a link available? I found [this thread](https://discuss.python.org/t/the-difference-between-python-setup-py-build-ext-i-and-pip-install-e/3716/11) where it's mentioned that `build_ext -i` isn't available through pip yet. Not sure if anything has changed since then or if there's another way to get local tests working without needing to install every time.

**Comment by peterjc** [comment]
I was hoping you knew - I'm familiar with ``pip install -e .`` but apparently that maps to ``python setup.py develop``?

**Comment by npars** [comment]
I can give that a shot and see if it allows the tests to resolve the compiled modules correctly

**Comment by npars** [comment]
@peterjc Local tests are working with `pip install -e .` command. It creates the `*.so` libraries in place in the source tree. Updated the instructions accordingly.

**Comment by peterjc** [comment]
Any second opinions about suggesting ``pip install -e .`` prior to running our tests? I've not sat down to review the latest Python packaging documentation on this area...

e.g. @mdehoon or @JoaoRodrigues

**Comment by npars** [comment]
Any update on this @peterjc / @mdehoon  / @JoaoRodrigues ?

**Comment by peterjc** [comment]
Would the sudo install version now be redundant?

**Comment by JoaoRodrigues** [comment]
This look good to me! Completely forgot about the testing instructions, thanks for catching this @npars !

**Comment by JoaoRodrigues** [comment]
>Would the sudo install version now be redundant?
Yes.

**Comment by peterjc** [comment]
Revisiting following #4140.

@etal Doing ``pip install .`` would touch the default Python's files, and if that is the system Python that would need admin rights (i.e. sudo).

**Comment by peterjc** [comment]
This is the current suggestion on the PR:

```
pip install -e .
python setup.py test
sudo python setup.py install
```

@idoerg's suggestion on #4140 is:

```
python setup.py build
sudo python setup.py install
cd Tests
python run_tests.py
```

Note with setups like conda being more common, it less likely nowadays that ``sudo`` would be needed anymore, as you wouldn't need to touch the system Python. Personally for example, I am using:

```
pip install -e .
python setup.py test
```

**Comment by npars** [comment]
My opinion is to just merge this as is since it will get the instructions working. If someone has a better approach than the instructions can be updated again in a follow up PR.

**Comment by idoerg** [comment]
Does pip install from the latest source?

The reason I wanted to install from source in the first place was because
1.79 cannot parse Unipprot-Swissprot anymore (new FT record format). I did
not open an issue on that because 1.80 fixed the problem. I think it's
important to be able to install from source due to lags like that between
releases.

--

**Comment by peterjc** [comment]
Certainly if we had merged this months ago, we'd have saved Iddo some pain.

The current diversity of Python installations (and ``sudo`` or not) probably makes a one-size-fits-all set of install instructions harder than it was 20 years ago.

**Comment by peterjc** [comment]
``pip install .`` (with an optional ``-e`` for developer mode) means install the source code in the current directory ``.``, which in this case is a copy via git of the latest code.

**Pull request merged**
