### PR TITLE
Update NEWS.rst

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
The changes in NEWS.rst of the last pull request (regarding pairwise2) went into version 1.71 (the release for which this PR was intendet). Moved this changes to the current version.

### CODE REVIEW

**Comment by peterjc** [comment]
Minor, but breaking TravisCI:

```
NEWS.rst:38: D001 Line too long
```

Cross reference #1505

**Comment by MarkusPiotrowski** [comment]
Hi @peterjc , should I revert the pairwise2 commit to update NEWS.rst (and rebase) there or can we do this simple change here? Sorry for the noise, wasn't aware of the 80 char limit in NEWS.rst. I thought it is simple enough to do this little change here online. I have learned my lesson..

**Comment by peterjc** [comment]
You did this on a pull request, so no harm done. Doing it on the master branch directly would be a bit more trouble (and I have been guilty of this in the past - usually one word typo fixes seem safe, not not always!) as it can break other people's pull request tests.

You can fix the line length here (#1972), using the online editor or otherwise. And in this case, I would lean to squash-and-merge since the commit history wouldn't be worth keeping.

(I may have misunderstood, but #1505 is merged, there is no changing that.)

**Comment by MarkusPiotrowski** [comment]
From here both the patch branch and the PR are checked by appveyor and travis-ci. Closing here and making pull request from my respository.

**Pull request closed without merging**
