### PR TITLE
Modify the calculation method of Nsite and Ssite in NG86

### PR DESCRIPTION
**Pull request by JuseTiZ**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

If `k` represents the transition/transversion rate ratio, it seems that `k` may have been positioned incorrectly. If my understanding is incorrect, please feel free to correct it and close this pull request. Thank you!

### CODE REVIEW

**Comment by peterjc** [comment]
What do you think @zruan ?

**Comment by mdehoon** [comment]
attn: @zruan

**Comment by mdehoon** [comment]
@JuseTiZ  Would you have a reference showing that the transition/transversion rate ratio should be used?

**Comment by mdehoon** [comment]
Note that the same code appears in the newer `Bio.Align.analysis` module.

**Comment by JuseTiZ** [comment]
> @JuseTiZ Would you have a reference showing that the transition/transversion rate ratio should be used?

@mdehoon 

I consulted Ziheng Yang's 'Computational Molecular Evolution.' Specifically, in the second chapter, titled 'Models of amino acid and codon substitution,' under the section 'Estimation of synonymous and nonsynonymous substitution rates,' there is relevant information on this topic.




It's indicated that sites with higher mutation rates should have higher Ssite and Nsite values. This is important to maintain a balance in their contribution to the overall calculations of dN and dS.

I will add the same code in `Bio.Align.analysis` to this PR. However, I am still not sure if this is correct.

**Comment by zruan** [comment]
This seems to be a bug in which the `w` (transition/transversion ratio) is not correctly placed.

@JuseTiZ can you please confirm that after the changes, the `codonalign.codonseq._count_site_NG86(['TTT'], codon_table, k=2)` reports the same number as shown in the table?

**Comment by JuseTiZ** [comment]
> This seems to be a bug in which the `w` (transition/transversion ratio) is not correctly placed.
> 
> @JuseTiZ can you please confirm that after the changes, the `codonalign.codonseq._count_site_NG86(['TTT'], codon_table, k=2)` reports the same number as shown in the table?

@zruan Below is a demonstration, where `_count_site_NG86_modified` is a function I modified according to the method in the PR (that is, changing the position of k).

```
from Bio.codonalign import codonseq
from Bio.Data import CodonTable

codon_table = CodonTable.generic_by_id[1]
ssite, nsite = codonseq._count_site_NG86(['TTT'], codon_table, k=1)
ssite2, nsite2 = codonseq._count_site_NG86(['TTT'], codon_table, k=2)

print(f'Before modification:\nFor k=1 ssite {ssite:.2f} nsite {nsite:.2f}.\n'
      f'For k=2 ssite {ssite2:.2f} nsite {nsite2:.2f}.')

ssite, nsite = codonseq._count_site_NG86_modified(['TTT'], codon_table, k=1)
ssite2, nsite2 = codonseq._count_site_NG86_modified(['TTT'], codon_table, k=2)

print(f'After modification:\nFor k=1 ssite {ssite:.2f} nsite {nsite:.2f}.\n'
      f'For k=2 ssite {ssite2:.2f} nsite {nsite2:.2f}.')
```

The output of this demonstration is as follows:

```
Before modification:
For k=1 ssite 0.33 nsite 2.67.
For k=2 ssite 0.20 nsite 2.80.
After modification:
For k=1 ssite 0.33 nsite 2.67.
For k=2 ssite 0.50 nsite 2.50.
```

**Comment by zruan** [comment]
It looks like after the modification, the output of the function matches with what are shown in the table.

```
For k=1 ssite 0.33 (1/3) nsite 2.67 (8/3).
For k=2 ssite 0.50 (1/2) nsite 2.50 (5/2).
```

**Comment by mdehoon** [comment]
@zruan  Should we accept this PR then?

**Comment by zruan** [comment]
@mdehoon Yes, we should. Maybe we should update the numbers in unittest as well?

**Review by mdehoon — APPROVED** [review]

**Comment by mdehoon** [comment]
@zruan  The unit tests seem fine as is, as all tests passed.

**Comment by mdehoon** [comment]
Thank you.

**Pull request merged**
