### PR TITLE
Customizability features added to Phylo.draw

### PR DESCRIPTION
**Pull request by nmsutton**
Features added based on https://redmine.open-bio.org/issues/3336.  Users now have the ability to input key word arguments representing pyplot options into plots they create to customize the plots.  Also, an option is added to the plotting code that allows clade lines to be created with matplotlib's linecollection objects enabling plot line customization.  Thanks to Lee at github.com/waterimp for his assistance including kwargs processing techniques and feedback on other code.

Co-authored-by: Lee Bush github@waterimp.com

### CODE REVIEW

**Comment by peterjc** [comment]
@nmsutton you credited Lee Bush with co-authorship, but I see now we missed adding him to the ``CONTRIB`` file and ``NEWS`` for Biopython 1.62 beta. If he is happy, we can do that retrospectively, plus I'd like his explicit permission to dual license his contribution on #898. Is that email address listed above the best contact? Thanks!

**Comment by nmsutton** [comment]
@peterjc Sure, that is the last contact info I have for him, that is nice of you to add him as you described.  Please use that email address and send the requests to him, if you are unable to reach him tell me and I’ll see what else we can do.

**Comment by nmsutton** [comment]
@peterjc Based on efforts to contact Lee Bush and emails with biopython contributors, I hereby state that I will be listed as the contributor to this commit without Lee as another contributor, I thank Lee for his code tips but the amount of work I did on the commit justifies this action.  A response from Lee about the licensing change is not required.

**Comment by peterjc** [comment]
Thanks @nmsutton, let's leave it at that unless Lee gets in touch.

**Pull request closed without merging**
