### PR TITLE
Remove assert statement that have side effects

### LINKED ISSUE #4796: `assert` statements performed non-idempotent operations
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

```
3.12.1 (main, Aug  8 2024, 18:45:38) [GCC 9.4.0]
CPython
Linux-6.5.0-1022-azure-x86_64-with-glibc2.31
1.84
```

### Expected behaviour

No output

### Actual behaviour

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./.venv/lib/python3.12/site-packages/pymsaviz/__init__.py", line 6, in <module>
    from pymsaviz.msaviz import MsaViz
  File "./.venv/lib/python3.12/site-packages/pymsaviz/msaviz.py", line 16, in <module>
    from Bio.Phylo.TreeConstruction import DistanceCalculator, DistanceTreeConstructor
  File "./.venv/lib/python3.12/site-packages/Bio/Phylo/TreeConstruction.py", line 364, in <module>
    class DistanceCalculator:
  File "./.venv/lib/python3.12/site-packages/Bio/Phylo/TreeConstruction.py", line 465, in DistanceCalculator
    matrix = substitution_matrices.load(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/Bio/Align/substitution_matrices/__init__.py", line 518, in load
    matrix = read(path)
             ^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/Bio/Align/substitution_matrices/__init__.py", line 494, in read
    matrix[letter1, letter2] = float(word)
                               ^^^^^^^^^^^
ValueError: could not convert string to float: 'A'
```

### Steps to reproduce

python -O -c "import pymsaviz"

### PR DESCRIPTION
**Pull request by CNSeniorious000**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #4796

### CODE REVIEW

**Comment by peterjc** [comment]
It looks like the new numpy 2.1.0 release is breaking a few doctests (at least on Windows under AppVeyor), unrelated to this PR.

**Comment by flaar94** [comment]
The convention for _ in python is as use as an unused variable (see for example: https://docs.python.org/3.10/reference/lexical_analysis.html#reserved-classes-of-identifiers), along with a couple other special uses. I wonder if it's better to use a different variable name?

**Comment by CNSeniorious000** [comment]
That variable's only usage is in the next line. But it is an assertion statement, which should always be true in production environments, and is ignored with `python -O ...`. So I personally think it is actually an _unused variable_.

**Comment by flaar94** [comment]
Well, my thought is that the purpose of the convention is the readability of the code, and it is being used in an equality statement, so it's being used in the sense that someone reading the code has to see the underscore, then track back to where it's defined to try to figure out what it is (even if it's in the previous line). But that's just me. I'm no expert on python style :)

**Comment by peterjc** [comment]
I think its fine as the assert with ``_`` is the next line.

A possibly better fix would have been to throw an explicit error, e.g. RuntimeError, if the equality check failed. In that case I'd have given the variable a name.

**Pull request merged**
