### PR TITLE
Test genbank unittest

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request replaces the print-and-compare test in test_GenBank.py by a unittest.
Note that there is also a test_GenBank_unittest.py; perhaps we should combine the two into one.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
The new file is rather large, so much so that GitHub won't show the diff, or even the file itself:

> (Sorry about that, but we can’t show files that are this big right now.)

The shear length is also a concern for maintenance - I've not looked at it at the command line yet, but is there no obvious repetitive stuff that could be culled? We don't need to check every attribute of every test file.

**Comment by mdehoon** [comment]
@peterjc  The file size was mainly coming from the fact that the full sequence was used. In the revised version, truncated sequences (first 54 and last 3 characters) are being tested only. File size is now 256 kB.

**Comment by peterjc** [comment]
There are a lot of uses of ``warnings.simplefilter("ignore", BiopythonParserWarning)``, was this automatic and some are redundant, or are they all actually used?

**Comment by peterjc** [comment]
It looks like just five of the warning filters are actually needed:

```
test_File ... ok
test_GenBank ... /home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.7/Bio/GenBank/Scanner.py:1143: BiopythonParserWarning: Premature end of file in sequence data
  BiopythonParserWarning)
/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.7/Bio/GenBank/Scanner.py:1160: BiopythonParserWarning: Invalid indentation for sequence line
  BiopythonParserWarning)
/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.7/Bio/GenBank/Scanner.py:1425: BiopythonParserWarning: Attempting to parse malformed locus line:
'LOCUS       AB070938          6497 bp    DNA     linear   BCT 11-OCT-2001\n'
Found locus 'AB070938' size '6497' residue_type 'DNA'
Some fields may be wrong.
  BiopythonParserWarning)
/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.7/Bio/GenBank/Scanner.py:184: BiopythonParserWarning: line too short to contain a feature: '     misc_feature'
  BiopythonParserWarning)
/home/travis/build/biopython/biopython/build/lib.linux-x86_64-3.7/Bio/GenBank/__init__.py:1096: BiopythonParserWarning: Dropping bond qualifier in feature location
  warnings.warn("Dropping bond qualifier in feature location", BiopythonParserWarning)
ok
test_GenBank_unittest ... ok
```

**Comment by mdehoon** [comment]
One warning remains:

`~/biopython/Tests
$ python run_tests.py test_GenBank
Python version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Operating system: posix darwin
/Users/mdehoon/biopython/Bio/__init__.py:128: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a setup.py file in an unexpected directory: /Users/mdehoon/biopython.
  format(_parent_dir), BiopythonWarning)
`

which should not happen, but is a separate bug.

**Pull request merged**
