### PR TITLE
Docstring fixes for D204

### PR DESCRIPTION
**Pull request by morrme**
Ref. #1170

whew.

### CODE REVIEW

**Comment by morrme** [comment]
Oh no...I combined the branches again 😢

**Comment by peterjc** [comment]
The good news is it rebased automatically at the command line. There is lots of trailing white space, but that ought to be easy to fix automatically...

**Comment by peterjc** [comment]
I'm about to push this to the master having merged it locally & fixed the whitespace, just running tests...

**Comment by peterjc** [comment]
Committed as 80988e819a8948b968da212dca61abd8f129934e thank you :)

**Comment by morrme** [comment]
@peterjc sorry about that. i was working on the whitespace fixes locally, but glad it is sorted!

**Pull request closed without merging**
