### PR TITLE
Bio.Emboss - black and triple quote indentation

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses in part issues #2008 and #2369.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Given I removed the ten-year old command line argument aliases, need to update the doctests which were still using them. Sigh.

**Comment by peterjc** [comment]
Doctests caught my first mistake, removed a still current command line parameter (as part of removing the 10 year old pre-EMBOSS 6.1.0 aliases).

**Comment by peterjc** [comment]
@svalqui could you comment/review this pull request?

**Comment by svalqui** [comment]
This is fine, the obsolete options are gone. you should merge it.

**Comment by svalqui** [comment]
black, version 19.03b? I have updated to 19.10b0 ; I hope there is no much difference.

**Comment by peterjc** [comment]
Black 19.10b0 added a new dependency which is problematic as the author only provides wheels for Windows, and on the machine I was working on I didn't have the build dependencies available. So I used the previous release, black 19.03b which is almost the same in output. I understand the next release of black will drop this new dependency.

**Comment by peterjc** [comment]
Merged, thank you for looking at this.

**Pull request merged**
