### PR TITLE
Update remote BLAST timings (less frequent)

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses issue #1682, although rather than relaxing our historic limits this does the opposite and is now stricter.

I hereby agree to dual licence this and any previous contributions under both the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

### CODE REVIEW

**Comment by peterjc** [comment]
Not sure who is best to review this, maybe @chapmanb or @mdehoon?

**Comment by chapmanb** [comment]
Peter -- looks good to me. If you wanted to make it even simpler you could do a 20 second query (for quick results, based on #1682) then fall back to polling every minute. That complies with NCBI's request, makes the code simpler, and might help some with responsiveness. I'm sure the initial 2 minutes was arbitrary. Either way is cool and thanks for tackling this.

**Comment by peterjc** [comment]
Interesting idea Brad, yes, starting with a 20s wait might overall be faster than an optimistic 10s gap which might rarely succeed first time, thus always taking at least 70s.

**Comment by peterjc** [comment]
The automated tests broke, this was a mistake on the master, already fixed.

**Pull request merged**
