### PR TITLE
GitHub Actions: Explicitly install wheel for API docs

### PR DESCRIPTION
**Pull request by peterjc**
This may fix the installation of mysql-connector-python-rf

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Follow up to #3580 etc.

### CODE REVIEW

**Comment by peterjc** [comment]
The GitHub Actions tests seem to have stalled on Linux PyPy... so has not yet got to the docs check.

**Comment by JoaoRodrigues** [comment]
See my last comment on #3681. Docs go through fine now (with this change indeed), pypy is stalling a lot.. i tried different versions of pypy, nothing helps.

**Comment by peterjc** [comment]
So we should merge this PR to fix the doc building test?

**Comment by JoaoRodrigues** [comment]
Yes. I'll merge it as it does fix the `docs` step. We can look at the other failures later! Thanks, I should have split my changes in multiple PRs..

**Pull request merged**
