### PR TITLE
Only division needs to be in try block

### PR DESCRIPTION
**Pull request by anderspitman**

### CODE REVIEW

**Comment by peterjc** [comment]
Looks sensible - thanks. Do you want to be added to the ``NEWS``/``CONTIB`` file - or would you prefer to wait until you've made a more substantial contribution?

**Comment by anderspitman** [comment]
Probably no need for that, thanks!

**Comment by peterjc** [comment]
@anderspitman Hello again Anders. Are you happy to dual licence your contributions under both the Biopython License Agreement AND the BSD 3-Clause License? See #898. Thank you.

**Comment by anderspitman** [comment]
@peterjc yep no problem. I'm pretty sure I'm already listed in batch 2

**Comment by peterjc** [comment]
Thank you - apologies, I missed your earlier explicit agreement in that long thread - https://github.com/biopython/biopython/issues/898#issuecomment-236999538

**Pull request merged**
