### PR TITLE
Fixed typos in docstrings and docs

### PR DESCRIPTION
**Pull request by carlosp420**
I used this library https://github.com/erichurkman/misspellings to find common misspellings in the code.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
The files in ` Bio/Entrez/DTDs` were downloaded from NCBI. They should not be changed by us.

**Comment by mdehoon** [comment]
Test files generated by programs should also not be changed.

**Comment by peterjc** [comment]
Thank you - do let us know if you want to be named in the next release.

Is this spell checker something we might run automatically, or are there still lots of false positives requiring human review?

**Comment by carlosp420** [comment]
no need to be named in the next release. Maybe after I make a meatier contribution. The tool has to be run manually and it has many false positives and negatives. It even splits variable names and applies detection to each part of the variable name. So it needs human intervention to decide what to fix.

**Comment by peterjc** [comment]
Sounds like this is better run by hand every so often then. Thanks!

**Pull request merged**
