### PR TITLE
Dual license Bio.HHM

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses in part issue #898 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by chapmanb** [comment]
Thanks for doing this, happy to have it merged over. Out of interest, is it possible to assign the copyright to the Biopython community rather than me? Or leave out copyright entirely?

**Comment by peterjc** [comment]
Thanks Brad - do you want to press the big green rebase-and-merge button?

We could discuss if the OBF could hold some/all of the Biopython code copyright (possibly via a fiscal sponsor, currently SPI), but all the projects where I've seen this done require a formal contributor agreement with signature prior to accepting any contributions. It may be more trouble than it's worth?

**Comment by chapmanb** [comment]
Peter;
Sorry didn't want to create extra work, I was just thinking that not having copyright could be more future proof. Path of least resistance is definitely good with me. Thanks again for doing this.

**Comment by peterjc** [comment]
Cheers.

Having a group held copyright may not be as complicated as a fear, but I am not a lawyer ;)

**Pull request merged**
