### PR TITLE
implement print_full_mat, print_mat, and __str__ as a single format method

### PR DESCRIPTION
**Pull request by mdehoon**
Implement the functionality of the three functions print_full_mat, pr…int_mat, and __str__ in a single format method, and deprecate print_full_mat and print_mat.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
Original code was written in November 2000 by Iddo Friedberg, but I didn't see him in the list of potential reviewers.

**Comment by mdehoon** [comment]
@peterjc  Thanks for reviewing. What was the cosmetic point? I didn't find it.

**Comment by peterjc** [comment]
Sorry, maybe I didn't click submit - the minor comment was on the tutorial, suggest changing:

```python
format(self,fmt="%4d",topfmt="%4s",alphabet=None,full=False)
```

to:

```python
format(self, fmt="%4d", topfmt="%4s", alphabet=None, full=False)
```

i.e. Add PEP8 spaces.

**Comment by mdehoon** [comment]
I received a reply from Iddo Friedberg, who wrote this module 20 years ago. He's OK with us modifying Bio.SubsMat as we see fit, and suggested that somebody takes over as code owner of this module.

**Pull request merged**
