### PR TITLE
Support residue insertion codes in SeqIO.PdbIO

### PR DESCRIPTION
**Pull request by mukhyala**
https://github.com/biopython/biopython/issues/2211

This pull request addresses issue #2211 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Can you find a tiny PDB file for a test? Or make a synthetic test in code?

**Comment by peterjc** [comment]
Maybe @lennax, @JoaoRodrigues or @jgreener64 could take a quick look?

**Comment by jgreener64** [comment]
I think the changed line was intended to do two things, as indicated by lines 65 and 70:
- Find gaps to fill with Xs, e.g. skipping from residue 10 to 20.
- Find out-of-order residues and warn about them (then ignore them), e.g. skipping from residue 20 to 10.

The change will make the code work with insertion codes but means that the second point above is ignored. Perhaps changing it to `if rnumbers[i + 1] != rnum + 1 and rnumbers[i + 1] != rnum:` instead would be better. In this case insertion codes are allowed but out-of-order residues are still found.

**Comment by mukhyala** [comment]
Agreed, this will support both out of order residues and insertion codes. I committed the change.

**Comment by jgreener64** [comment]
Thanks, in that case this looks good to me.

**Comment by peterjc** [comment]
Do you want to add yourself to the ``NEWS.rst`` file too?

**Comment by mukhyala** [comment]
Thanks, I wasn't sure if this change meets the criteria for adding to release NEWS.

**Comment by peterjc** [comment]
Absolutely - you could say it was only one line of code in the main library, but it is a bug fix with tests etc.

**Pull request merged**
