### PR TITLE
Use XML parsing for MAST output files

### PR DESCRIPTION
**Pull request by victorlin**
This pull request re-implements the current functionality of Bio/motifs/mast.py using the `xml` module to parse the XML output instead of the plain-text output from MAST. It also includes updated test files from MEME source.

Notable differences:

- Input to `read()` should be a valid XML stream instead of formatted text stream.
- New `alphabet_name_map` global variable: used for mapping alphabet names to respective Bio.Alphabet class. It seems that Bio.Alphabet was deprecated for letters in #2066, but I'm unsure which letters to use in replacement. @mdehoon ?
- Functionality of `__read_section_i()` and `__read_section_ii()` condensed into  `__read_sequences()`: there are no "sections" in the XML file. Also removed `__read_section_iii()` as it had no extracting functionality.
- New function `__make_diagram()` used to generate diagram string found in text files.
- New attribute `Record.strand_handling` required for creation of diagram string.

Suggested improvements for the future:

- Read more metadata (left TODOs where additional information could be extracted).
- New Sequence class with sequence-specific attributes (e.g. diagram, description, evalue, length, combined_pvalue). This would eliminate the redundancy of `Record.sequences` and `Record.diagrams`.

ref  #1988, #1980 

Related: http://web.mit.edu/meme/current/bin/mast_xml_to_txt

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@victorlin  I would suggest to store `alphabet_str` as is, so "Protein" or "DNA":
```python
record.alphabet = xml_tree.find('alphabet').get('name')
```

**Comment by peterjc** [comment]
Regarding the alphabets in motifs, see also the changes @mdehoon made in #2066 - that might help understand what is needed. Are you happy to rebase your branch to take in these changes, or do a merge, or will you need help?

**Comment by victorlin** [comment]
@peterjc @mdehoon thank you for the pointers. I should be able to resolve the merge conflicts and update this pull request accordingly.

**Comment by peterjc** [comment]
If I am reading this correctly, the ``Bio.motifs`` parser for ``"mast"`` format used to take plain text, and with this change will require XML instead.

Would it be better to keep the plain text parser as ``"mast"``, and add the new XML parser as ``"mast-xml"`` (or similar) in the top level API? That way it won't break things for people using the older format (e.g. pipelines using older version of MAST, or for comparisons of old vs new MAST behaviour).

**Comment by mdehoon** [comment]
@peterjc  Which version of Mast does the plain-text parser support?

**Comment by peterjc** [comment]
According to the test files:

```
MAST version 3.0 (Release date: 2004/08/18 09:07:01)
```

**Comment by victorlin** [comment]
I think we had this discussion in #1988.

In summary, the MAST program (latest 5.0.5) currently outputs 3 different files: `.txt`, `.xml`, and `.html`.
The XML output was introduced in version 4.4.0 (April 23, 2010).

If we want to retain both parsers, maybe having a parameter would be better:

```python
from Bio.motifs import mast

mast.parse(open('mast.txt'))
mast.parse(open('mast.xml'), format='xml')
```

but different format names for Bio.motifs.parse/read:

```python
from Bio import motifs

motifs.parse(open('mast.txt'), 'mast')
motifs.parse(open('mast.xml'), 'mast-xml')

motifs.read(open('mast.txt'), 'mast')
motifs.read(open('mast.xml'), 'mast-xml')
```

**Comment by peterjc** [comment]
Yes, you're right - @mdehoon said he was OK with replacing the text parser with the XML parser, https://github.com/biopython/biopython/issues/1988#issuecomment-483476369

I've hardly used the MAST output, so have no personal experience to guide me here.

**Comment by mdehoon** [comment]
I would keep the XML parser only. Parsing plain-text output is not a good idea to begin with, and we should not encourage it.

**Comment by peterjc** [comment]
OK, but this needs a ``NEWS.rst`` entry, and perhaps even something in the ``DEPRECATED.rst`` file too?

**Comment by victorlin** [comment]
Should this wait until there is an updated XML parser for MEME as well, since it is part of the same package?

**Comment by peterjc** [comment]
I think we could merge XML for MAST only, and then add XML for MEME later.

The longer we leave a pull request, the more likely to get merge conflicts (there is one now already). Are you happy with doing a``git rebase origin/master`` or a merge to resolve that @victorlin, or should we?

**Comment by victorlin** [comment]
@peterjc I did a merge in d9b8fc8. Is there somewhere I should look for other merge conflicts?

If you're referencing the `master` branch on my fork, I attempted some rebase/merges yesterday and messed things up a bit. This `xml-parser-mast` branch can be auto merged with `biopython/master` though. I was thinking of re-forking after this pull request.

**Comment by peterjc** [comment]
Github says there is no merge conflict anymore :)

**Comment by peterjc** [comment]
I suggest we do a squash-and-merge (since the rebase is non-trivial), suggested commit comment:

```
Closes issue #1980

Replaced the old text MAST output parser which was written for:

MAST version 3.0 (Release date: 2004/08/18 09:07:01)

Instead the new parser expects MAST XML output.

Test cases updated using http://meme-suite.org/meme-software/5.0.5/meme-5.0.5.tar.gz
```

Then AFTER than, @victorlin can try deleting and re-forking his repository as the simplest way to sort out his master branch - although there other ways to achieve that.

And, we can update the ``NEWS.rst`` file too.

**Comment by victorlin** [comment]
Suggested entry for `NEWS.rst`:

`Bio.motifs.mast` has been updated to parse XML output files from MAST over the plain-text output file. The goal of this change is to parse a more structured data source with minimal loss of functionality upon future MAST releases. Class structure remains the same plus an additional attribute `Record.strand_handling` required for diagram parsing.

Suggested entry for `DEPRECATED.rst` (under section Bio.Motif ?):

`Bio.motifs.mast` plain-text parsing deprecated in favor of XML parsing as of release 1.74. Also affects `Bio.motifs.read` and `Bio.motifs.parse` for the `mast` format.

How do these sound?

**Comment by peterjc** [comment]
Those sound good. Do you want to add them to this branch (without changing anything else like trying another rebase)?

**Comment by victorlin** [comment]
Done.

**Comment by peterjc** [comment]
OK to squash-and-merge @mdehoon? Suggested commit message: https://github.com/biopython/biopython/pull/2082#issuecomment-497366995

**Comment by mdehoon** [comment]
@peterjc  OK

**Comment by peterjc** [comment]
Thank you both 👍

**Pull request merged**
