### PR TITLE
Splitting Tests\test_PDB.py

### PR DESCRIPTION
**Pull request by Gasta88**
I've moved tests for `Bio.StructureAlignment`, `Bio.Superimposer` and `Bio.Polypetide` from `Testsztest_PDB.py` into three separated files.

### CODE REVIEW

**Comment by peterjc** [comment]
Assuming the tests pass, this looks good to me.

@etal / @JoaoRodrigues / @lennax is this OK with you?

**Comment by Gasta88** [comment]
I'm also working on taking out the test for `Bio.PDB.Vector`, but the testing for the `m2rotaxis` method is not working anymore. I need to dig deeper into that.

**Comment by peterjc** [comment]
TravisCI has flagged a minor white space issue in the style checks:

```
$ flake8 Tests/
Tests/test_PDB_Superimposer.py:22:1: W293 blank line contains whitespace
```

**Comment by peterjc** [comment]
Thank you 👍

**Comment by peterjc** [comment]
I just noticed an oversight - I should not have merged this as it was because you dual licensed the new files without listing copyright holders (fortunately just you I think) and explicitly checking we have their agreement on record - which I have now done:

66b77655e7a8b710a6cf98560cbf5ae06f4c9fcc d375c8c846abe4816a03c30edec4ead9e70563a6 7a587d8d1a335a5afdcba7820ef275d2561faa34

Also there are still ``PPBuilder`` and ``CaPPBuilder`` tests in ``test_PDB.py`` which could (subject to the dual license check) be moved into the new ``test_PDB_Polypetide.py`` file.

**Pull request merged**
