### PR TITLE
Parse REMARK 99 lines from PDB-style Astral files

### PR DESCRIPTION
**Pull request by mikepm35**
This pull request addresses issue #2052 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by jgreener64** [comment]
Looks like a nice addition to me.

I think the test file could just have the header present to reduce the file size?

Also, you could update this sentence in the docs:
> The available keys are name, head, deposition_date, release_date, structure_method, resolution, structure_reference (which maps to a list of references), journal_reference, author, and compound (which maps to a dictionary with various information about the crystallized compound).

**Comment by peterjc** [comment]
Thanks Joe, very useful. I agree with your points.

Note also there are now merge conflicts - @mikepm35 if you are not confident to deal with that, just focus on making the improvements Joe suggested, and one of us can handle the merge. Thank you.

**Comment by mikepm35** [comment]
Thanks for the feedback.  I did do another pull/merge as well as stripped the extra lines from the test file and updated the docs.  Note that I saw that same line in the FAQ doc files, so I updated them as well.

**Comment by peterjc** [comment]
Looks good - do you want to add yourself to the ``NEWS.rst`` and ``CONTRIB.rst`` listings?

**Comment by mikepm35** [comment]
Thanks, yes, I just updated those as well.

**Comment by peterjc** [comment]
A lot of the changes are removing trailing white space (generally a good thing), especially in the documentation.

All the changes in ``Doc/biopdb_faq.lyx `` made me take a closer look, and log issue #2094. Did you use the graphical tool Lyx, or just edit both ``Doc/biopdb_faq.lyx `` and ``Doc/biopdb_faq.tex`` directly?

**Comment by mikepm35** [comment]
I did use Lyx initially, but then made a wording change directly in the file via Atom.  When I re-opened it in Lyx I didn't see the white space issue, but I do see it now.  I can re-do those changes in the documentation to correct it.

**Comment by mikepm35** [comment]
FWIW I found the culprit.  Atom has a default package called "whitespace" which removes all trailing characters.  Furthermore, the Git diff views don't show the trailing whitespace differences, so the changes look like line moves (although I still should have caught it).  I reverted the previous change and made the appropriate updates.

**Comment by mikepm35** [comment]
Awesome, thanks for all the help getting this in!

**Comment by peterjc** [comment]
Rebasing for the merge conflict, squashing a few of the commits together, ...

**Comment by peterjc** [comment]
And another minor conflict to fix...

**Pull request merged**
