### PR TITLE
Adding parameter to return print_that output instead of printing it

### PR DESCRIPTION
**Pull request by sbassi**
This change allows to return the output of print_that instead of sending to stdout. This is usefull when you need this output for a template system.

### CODE REVIEW

**Comment by peterjc** [comment]
I don't understand the use-case here versus just doing ```print(example.print_that(...))``` - could you explain what you meant about a template system in this context?

Rather than a new boolean argument, would an optional handle make more sense (e.g. ``sys.stdout`` or ``sys.stderr`` or a text mode file to write to)? (This might be irrelevant but I don't yet understand your use case.)

**Comment by sbassi** [comment]
With template system I refer to jinja2 and similar.
To render the template I need to pass a dictionary with all values to render, but example.print_that() returns None (instead of returning something, it prints to stdout), so I can't grab the output of example.print_that().
In order to make the print_that() method to return something instead of printing it out, I added a new parameter. With the default value so the user can keep using is as it was before and have the same result.

**Comment by peterjc** [comment]
OK - I see what you mean. Frankly I am not keen on methods which directly print, rather than the more flexible option of returning a string.

How about we introduce a new method like ``.format(...)`` (or similar name) returning the string? And then define ``.print_that(...)`` to just do ``print(self.format(...))``, and ideally deprecate ``.print_that(...)`` as well?

Its a bit more hassle, but leaves us with a cleaner API (although separately I'd like to retire the entire restriction module in favour of a re-write, see eg #268).

**Comment by sbassi** [comment]
I agree, that is the way to go. Will work on that.

**Comment by sbassi** [comment]
I called the new method .format_output() since format() was taken in that namespace.

**Comment by sbassi** [comment]
@peterjc The code is ready for review

**Comment by peterjc** [comment]
While ``Bio/Restriction/Restriction.py`` looks great, ``Bio/Restriction/PrintFormat.py`` needs updating to the new API style. Perhaps you forgot to commit changes to that file?

**Comment by sbassi** [comment]
I thought it was not need because print_that inside PrintFormat is mean to be called from print_that in Restriction. But will modify it anyway.

**Comment by peterjc** [comment]
Probably almost no one would be using that method, but it would be consistent to do both. Thanks.

**Comment by peterjc** [comment]
Looks good, thank you - finally two administrative questions:

Are you happy to dual licence your Biopython contributions (including re-licensing your past contributions) under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS`` file for the next release (you are already listed in the ``CONTRIB`` file)?

**Comment by sbassi** [comment]
Sorry I didn't answer. My answer is yes for both questions.

**Comment by peterjc** [comment]
Thank you 👍

**Pull request merged**
