### PR TITLE
Add MAF support to AlignIO

### PR DESCRIPTION
**Pull request by adamnovak**
This would close #5, which has been open for a couple of years.

I've taken the MAF support that @polyatail wrote and merged it against the current mainline Biopython. All the relevant unit tests pass.

Is there anything blocking the merge of this code? I really need MAF support, and I'm sure others would like to have it too.

### CODE REVIEW

**Comment by endrebak** [comment]
Would love for this to be added.

**Comment by adamnovak** [comment]
@bow @peterjc I have (finally) finished polishing up the issues you mentioned, and I've merged in all the latest master changes.

Is there anything else I need to do to get this merged?

**Comment by peterjc** [comment]
@bow do you want to to review this, and merge if happy?

**Comment by mscook** [comment]
Please review & merge this. We still use the branch provided by @polyatail (Biopython 1.59+ I think). This would go wonders to make our entire pipeline pip installable.

**Comment by peterjc** [comment]
@mscook Given you're using the old branch, can you retest with this branch to confirm it works as you expect? i.e. No incompatibilities between their SQLite index files.

Do you have any concerns about the (lack of) metadata in the SQLite index files (e.g. no index versioning, a limitation of the original SeqIO index creation which was my own fault).

**Comment by bow** [comment]
@peterjc Yes :). Last time I checked, I think it looks ok and it seems good for merging. I am taking a look again and testing locally now.

**Comment by blaiseli** [comment]
I fused the code from this pull request and my parallel work from pull request #503. Result is pull request #504, and last update of it passed the Travis test. Is there something more I could do to help MAF parser integration into the main branch of Biopython?

**Comment by peterjc** [comment]
@adamnovak I've pulled out your ``test_Cluster.py`` lambda fix directly to the master as:

https://github.com/biopython/biopython/commit/2a3735a591414cf33ece90a412f3524cb14e13c2

I have acknowledged you by name as discussed on #504 (which I am still working on):

https://github.com/biopython/biopython/commit/f57d964ed2fe4957f8acb646aa2e9707f3056a51

**Comment by peterjc** [comment]
Closing in favour of a fresh pull request https://github.com/biopython/biopython/pull/1055 using a rebased version of this.

**Pull request closed without merging**
