### PR TITLE
Added retmax value to Entrez Tutorial for error test_chapter_entrez_line_00202.

### PR DESCRIPTION
**Pull request by svalqui**
This pull request addresses issue #2725 

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

This address the first issue test_chapter_entrez_line_00202., by extending the number of items of the list, the ID is included.

### CODE REVIEW

**Comment by peterjc** [comment]
Assuming Markus was right, and they list the newest entries first, at some point the test would need updating again once enough new results are added.

We could narrow the search to reduce the chances? How about using ``biopython[title]`` instead which currently only has two hits? This also shows how the NCBI do field searching.

**Comment by peterjc** [comment]
Also, could you update the ``print(record["IdList"])`` output a few lines later?

**Comment by svalqui** [comment]
Yes, Markus is right the list comes with the newest entries first; Yes, it would need to be updated when more articles include Biopython in the title. Updated, Thank you.

**Comment by peterjc** [comment]
Lovely, thank you.

**Pull request merged**
