### PR TITLE
Enhance alphabet checking in Codonalign

### LINKED ISSUE #1151: Alphabet error "alignment should be a *PROTEIN* alignment" with MultipleSeqAlignment of Proteins
Basically my aim is to use `.get_dn_ds_matrix` on a group sequences. I parsed with SeqIO `(stored in "sequence" list)` and translated my sequences  `(stored in "protein" list)`. While I was following [this tutorial](https://github.com/biopython/biopython/blob/master/Doc/doc.rst) I managed to get my dnds matrix on an ungapped sequence. 

However when the sequence is gapped, although I specify `alphabet=Gapped(IUPAC.IUPACUnambiguousDNA())` in SeqIO, and I successfully translate the proteins with the alphabet `Gapped(ExtendedIUPACProtein()`, when I try to build the alignment:

`aln = MultipleSeqAlignment(protein)`
`codon_aln = codonalign.build(aln, sequence)`

I get the error:

`File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/__init__.py", line 83, in build`    
`TypeError: Alphabet Error!
The input alignment should be a *PROTEIN* alignment`

I'm not sure exactly why it would work on ungapped sequences and not on gapped sequences. 

Could it be something wrong with my code or is it a bug?

Specs:
biopython==1.68
Python =2.7.12
OS = MacOS

### PR DESCRIPTION
**Pull request by peterjc**
Intended to fix #1151, could you look at this @zruan please?

Hopefully @universvm's example can be turned into a test case.

### CODE REVIEW

**Comment by universvm** [comment]
If you don't mind the imports at the beginning, here is the code which includes the sequences
[Archive.zip](https://github.com/biopython/biopython/files/921987/Archive.zip)
I checked and it produces the matrix output.

**Comment by peterjc** [comment]
@universvm What's the code which uses these alignments?

**Comment by peterjc** [comment]
From @universvm's example I could see how to modify one of the existing tests to use a fancy protein alphabet and reproduce the error. Thank you Leo!

**Comment by universvm** [comment]
I'm glad my code was useful! Let me know if there's anything else I can do!

**Comment by peterjc** [comment]
Thanks @universvm - if you can test the fix and report back, that would be great (see #1151).

**Pull request merged**
