### PR TITLE
Define a default sample_id in AbiIO

### PR DESCRIPTION
**Pull request by bow**
This pull request addresses issue #1741. A little surprising (but not completely unexpected), the issue is caused by an ABI file without any sample IDs present. This PR simply defines a default `sample_id` value so that the variable will always be defined and ready for use in creating the `SeqRecord` object.

There are still other values (e.g. PBAS2 for the sequence and PCON2 for the qualities) that we assume always exist (and thus will raise a similar `UnboundLocalError` if not present). But if files without these tags do exist, I would like to see what they look like first before trying to generalize here. I think it is much less likely for an ABI file to exist without these tags, as the sequence and its quality is the essential information that should be present in the file.

Of course the file may be malformed and the tags may be missing then. But then we should raise the appropriate error, instead of still returning an object (like we do here).

Anyway, comments welcome as usual. If there are no objections, I will merge this no sooner than 26/7 8 AM CEST.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Spaces in the ``SeqRecord`` object's `.id`` are bad idea for interconversion to other formats, so I don't like this default value, but ``"<unknown id>"`` is the class' default so using it here is reasonable.

Do you have a real world test case we can include for this fix?

**Comment by bow** [comment]
Hmm..indeed it is not preferable. I don't mind using `""`, though I was trying to follow what other SeqIO parsers are doing with  `<unknown id>`.

In any case, I have to ask for @ananswam for permission to use the test case he sent me. Could you let us know whether we can add this to our test suite, to prevent regressions in the future?

**Comment by bow** [comment]
@ananswam Thank you!
@peterjc The PR should be updated with test case soon :).

**Comment by peterjc** [comment]
Looks good - feel free to merge this, and to add update the names in NEWS.rst 👍

**Pull request merged**
