### PR TITLE
add fasta-nowrap to SeqIO.write API

### PR DESCRIPTION
**Pull request by Zsailer**
This pull request addresses issue #666. pinging @peterjc for review. 

It extends the `SeqIO.write` API to allow writing to fasta format without line wrapping by adding a `fasta-nowrap` option to the format list. 

To implement this, I subclassed `FastaWriter` to `FastaNoWrapWriter` and set `wrap=None` in super. Not sure if this is the best way to do this. I'm happy to change it.

This doesn't update the Docs. I wanted to make sure the logic works before changing the docs. 

**Contributing stuff**

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ AND the _BSD 3-Clause License_.

I am happy to be thanked by name in the ``NEWS.rst`` and
``CONTRIB.rst`` files.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

### CODE REVIEW

**Comment by Zsailer** [comment]
Oops, should have ran tests before submitting. Sorry. 

Looks like the tests are written such that `SeqIO.parse` must be symmetric to `SeqIO.write`. That means the parsing formats must also have a "fasta-nowrap" option. Should I just use the standard fasta parser as a place holder to start?

**Comment by peterjc** [comment]
The place holder makes sense - up until now all the output formats have had a parser, so the tests reflect that. You could instead try adding a special case to the tests?

**Comment by peterjc** [comment]
I think to fix the test, you'd need to update this line

https://github.com/biopython/biopython/blob/biopython-170/Tests/test_SeqIO.py#L433

```python
    elif format == "fasta":
```

to:

```python
    elif format in ["fasta", "fasta-nowrap"]:
```

**Comment by Zsailer** [comment]
That helped fix some of the test. 

I'm breaking some new tests. Looks like I need to add a bunch of "expected output" lines to `output.test_SeqIO`.

**Comment by Zsailer** [comment]
Ok, all tests are passing now.

**Comment by peterjc** [comment]
I hope you spotted ``run_test.py -g test_SeqIO.py`` (see the testing chapter in the tutorial), but anyway - you got there :)

Would you like to add yourself to the ``NEWS.rst`` and ``CONTRIB.rst`` files too (sorted alphabetically)?

**Comment by Zsailer** [comment]
Oh wow, I totally missed that. :man_facepalming: 

Thanks for the review! I've added myself to `NEWS.rst` and `CONTRIB.rst`. If you need anything else from me, let me know. :)

**Comment by peterjc** [comment]
(The TravisCI Python 2.7 test failed in the KD Tree code, looks like a stochastic failure and I have re-run that)

**Comment by Zsailer** [comment]
Thanks @peterjc. Looks like the tests passed this time!

**Comment by peterjc** [comment]
See https://github.com/biopython/biopython/issues/666#issuecomment-350701713 where perhaps ``fasta-2line`` would be better than ``fasta-nowrap`` (important for parsing).

**Comment by peterjc** [comment]
(Hang on, I've had a rebase glitch while adding the parser on top of your branch...)

**Comment by peterjc** [comment]
I had to do a ``git rebase`` and ``git push --force`` to sort out my initial glitch which pulled some unrelated commits onto this pull request.

Anyway, how does this look @Zsailer?

There is scope for also implementing SeqIO indexing for the new FASTA variant as well.

**Comment by peterjc** [comment]
Updated again since master branch now enforces ``pydocstyle`` check D301:

```
$ flake8 Bio/SeqIO/FastaIO.py
Bio/SeqIO/FastaIO.py:76:1: D301 Use r""" if any backslashes in a docstring
```

**Comment by Zsailer** [comment]
@peterjc, this looks good! Thanks for pushing this forward!

**Comment by peterjc** [comment]
Great, thanks. Once the tests have passed on this, I'll apply it.

(The stricter docstring checking is fairly recent, it will make life harder for a few of the already open pull requests)

**Comment by peterjc** [comment]
@bow Does this look good to you? We could add more on the tests side, and perhaps implement direct indexing of two-line-per-record FASTA as well - but this seems a useful unit of work now.

**Comment by bow** [comment]
@peterjc this looks good ~ and @Zsailer thanks for the PR! My only small question is about the writer: is there a reason it is called `FastaNoWrap...` while the iterator is `FastaTwoLine..` and the proposed format name is `fasta-2line`?

**Comment by peterjc** [comment]
Good catch on the write class name - I agree with you. I'll fix that before merging this.

**Pull request merged**
