### PR TITLE
Add strand, start, end properties to SeqFeature

### PR DESCRIPTION
**Pull request by moshi4**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

___

This PR adds strand, start, end properties (read only) to the SeqFeature class.

In the BioPython v1.82 update, the strand property of SeqFeature was removed and the change from `feature.strand` to `feature.location.strand` is required (#4503). I think that `feature.strand` was a relatively commonly used property by users, so the impact of this breaking change seems a bit large. Therefore, I think it is better to keep the strand property of SeqFeature for backward compatibility. I also think that usability would be improved if the start and end properties were added to SeqFeature as well.

### CODE REVIEW

**Review by mdehoon — COMMENTED** [review]
I am -1 on this. Using `feature.location.strand` instead of `feature.strand` is a trivial change. Having these shorthands means maintaining two docstrings and two sets of tests for each function. Also, you'd have to deal with the case where `location` is `None`.

**Comment by peterjc** [comment]
On re-reading #4503 we had explicitly deprecated strand etc as arguments to the ``SeqFeature`` initialization, but technically the properties of the same name were _not_ officially deprecated. In hindsight I would have kept them for Biopython 1.82, but perhaps deprecated them.

I am therefore sympathetic to restoring ``.strand`` (and rarely used ``.ref`` and ``.ref_db``) proxies, perhaps as read only properties, but suggest immediately deprecating them.

However, like @mdehoon, I would oppose adding new aliases for ``.start`` and ``.end`` now.

**Comment by moshi4** [comment]
Thank you for your review comments. I'm satisfied with the content of your review and will close this PR.

I appreciate the development and maintenance of BioPython by the community.

**Comment by ialbert** [comment]
> I am -1 on this. Using `feature.location.strand` instead of `feature.strand` is a trivial change. 

This statement makes no sense whatsoever! 

It is not a trivial change for the many people that download existing code that relies on biopython. Thousands of lines of code using Biopython exist in the wild. You just rendered these non-runnable because the change to fix them is "trivial" to you.  But you are a BioPython developer ... who knows  what hey have removed ... It shows a tremendous disconnect from the audience you intend to help.

"Oh it is an easy fix, all you need is to edit a single line of code in a single location ...  "

**Comment by mdehoon** [comment]
@ialbert   Euhm ... what do you suggest to do instead then? Biopython contains lots of ancient code, some dating back to the previous century, that was well-intended at the time but turned out to be problematic later. We cannot keep carrying that around forever. So at some point, that code will be removed, and existing scripts will break. If it is essential to be able to run an existing script, you can always use an earlier Biopython release.

Since the earliest releases of Biopython, we have moved from Python1 to Python2 to Python3. Now that is a non-trivial change. Changing one line of code is not.

You are right that we should have included a deprecation warning. We usually do, but for some reason missed to do it this time. But with a deprecation warning, the code will still be removed, just two releases later, and scripts will break at that point.

**Comment by ialbert** [comment]
I don't get it, 

if the "trivial" fix is to rename `feature.strand` to `feature.location.strand` then why couldn't you keep `feature.strand` as an alias ... basically forever? If that means keeping all the existing code in working condition? Why is that not worth it? What is about it so unbearable? 

Creating that alias is a far more trivial fix than saying everyone else has to trivially fix their code.

In the new documentation keep using the new format, but I really don't get it why a rename is so important to be worth making all this existing code obsolete.

**Comment by mdehoon** [comment]
@ialbert  See my earlier comment in this thread.

**Comment by peterjc** [comment]
Please consider any discussion on #4563.

**Pull request closed without merging**
