### PR TITLE
Setup TravisCI build via matrix

### PR DESCRIPTION
**Pull request by peterjc**
This replaces lots of complicated if statement logic with per-build target environment variables.

I think this is much clearer, but would like a second opinion before applying this to the master.

### CODE REVIEW

**Comment by cbrueffer** [comment]
I like it. What about the PY3 variable though, does the matrix code take care of that automagically from the configured python version?

**Comment by peterjc** [comment]
TravisCI will ensure than "python" and "pip" match the version of Python being tested, including python3, pypy and pypy3.

After the change, there is no ``$PY3`` variable - that was just part of our if-based system.

**Comment by cbrueffer** [comment]
Cool, please commit :-)

**Comment by peterjc** [comment]
Done. Thank you for your comments @cbrueffer

**Pull request merged**
