### PR TITLE
updated Bio.Phylo for python3

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request updates Exceptions in Bio.Phylo for python3.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
The travis failure was on the s390x CPU, since marked as an allowed fail.

**Comment by peterjc** [comment]
This will need black applied (I could see one issue by eye) - are you happy doing that, or should I?

**Comment by mdehoon** [comment]
@peterjc 
I have made one more change (replacing trim_str by a one-liner).

I'd be happy if you apply the changes for black before merging.

**Comment by peterjc** [comment]
OK, will do.

**Comment by peterjc** [comment]
Rebased with black applied, tests should all be fine...

**Comment by mdehoon** [comment]
@etal  Does this look OK to you?

**Comment by mdehoon** [comment]
Can we assume silent approval from @etal ?

**Comment by peterjc** [comment]
The utility function versus a repeated simple code snippet is a style judgement he might query, but otherwise this seems clear cut. I think if he has no comment overnight, we might as well merge this tomorrow.

**Comment by etal** [comment]
Yep, these all look fine, sorry for the lag. Did black convert `hasattr` to try / except AttributeError automatically?

**Comment by mdehoon** [comment]
@etal 

Thanks,
> Did black convert hasattr to try / except AttributeError automatically?

No it doesn't.

**Pull request merged**
