### PR TITLE
Enable mypy disallow_incomplete_defs setting.

### PR DESCRIPTION
**Pull request by peterjc**
This raises the bar for adding future annotations...

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

@speleo3 and/or @mr-c does making this stricter seem wise, and do the changes here look sane?

[We have some inconsistency in how the SeqIO handles are annotated, something for later]

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by speleo3** [comment]
I haven't used `disallow_incomplete_defs` yet. Feels pretty strict, but I guess we can give it a try.

**Comment by speleo3** [comment]
Regarding SeqIO handles: I like to propose some cleanup of `_IOSource` argument handling. Some could use `File.as_handle` for example. I already started some of that while working on the `mypy` branch and I'd be happy to make a pull request.

**Comment by peterjc** [comment]
Sure, a cleanup of the type annotation of the handle arguments sounds good.

If you mean making more things agnostic about handle vs filename as string vs filename as path object, well maybe. The SeqIO design was the internal format-specific parsers would all expect a plain handle only - while the high level functions would be flexible. Also, we're quite likely to want to rework this to allow bytes handles in more places (which I hope could make the FASTA and FASTQ parsers faster).

**Comment by speleo3** [comment]
> If you mean making more things agnostic about handle vs filename as string vs filename as path object, well maybe.

I don't think that I made it more agnostic, just more consistent and with added type checks. But please give it a critical review :-) https://github.com/biopython/biopython/pull/4410

**Review by mdehoon — APPROVED** [review]

**Pull request merged**
