### PR TITLE
Add lookahead statement to regex patterns to catch overlapping cut sites

### PR DESCRIPTION
**Pull request by biologyguy**
Without this, any additional cut sites are consumed by re.finditer() if
 they are partially contained in another cut site, meaning they get
 missed.

## Previous behaviour (wrapped in a seqbuddy call):
```
>>> seqbuddy test.fa --find_restriction_sites SphI

# ### Restriction Sites (indexed at cut-site) ### #
Seq1
SphI	13
# ############################################### #

LOCUS       Seq1                     131 bp    DNA              UNK 01-JAN-1980
DEFINITION  Seq1.
ACCESSION   Seq1
VERSION     Seq1
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
FEATURES             Location/Qualifiers
     SphI            8..21
ORIGIN
        1 catgcacgca tgcatgcacg caggcaaggg actcttcaaa aagaaacagg aaaaaacttt
       61 gcaagattga gaagggattg atagccaaac tgagcgcttc cctttactac aatacaaagt
      121 aaaaattttt g
//
```

## New behaviour:
```
>>> seqbuddy test.fa --find_restriction_sites SphI

# ### Restriction Sites (indexed at cut-site) ### #
Seq1
SphI	13, 17
# ############################################### #

LOCUS       Seq1                     131 bp    DNA              UNK 01-JAN-1980
DEFINITION  Seq1.
ACCESSION   Seq1
VERSION     Seq1
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
FEATURES             Location/Qualifiers
     SphI            8..21
     SphI            12..25
ORIGIN
        1 catgcacgca tgcatgcacg caggcaaggg actcttcaaa aagaaacagg aaaaaacttt
       61 gcaagattga gaagggattg atagccaaac tgagcgcttc cctttactac aatacaaagt
      121 aaaaattttt g
//
```

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ AND the _BSD 3-Clause License_.

I am happy to be thanked by name in the ``NEWS.rst`` and
``CONTRIB.rst`` files.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks Steve - your pull request looks pretty well explained.

On the technical side, as per the header comments in ``Bio/Restriction/Restriction_Dictionary.py``,

```python
# This file is automatically generated - do not edit it by hand! Instead,
# use the tool Scripts/Restriction/ranacompiler.py which in turn uses
# Bio/Restriction/_Update/RestrictionCompiler.py
```

That said, assuming your regular expression change is consistent updating the compiler script shouldn't be too hard. Maybe you did this, but just forgot to check it in?

I'd like to ask @MarkusPiotrowski to review the functional changes.

Note I would ask for at least one functional test to be added before accepting this change.

**Comment by biologyguy** [comment]
Nope, didn't see that header message at all! I've updated ranacompiler.py.
Also, just fyi, rebase_update.py complained at me. I switched the download method to Popen("wget") and it worked fine, so I didn't dig further.
Here's the traceback in case it matters (failed with Python 2.7 too).

```
>>> python rebase_update.py


 Please wait, trying to connect to Rebase

copying ftp://ftp.neb.com/pub/rebase/emboss_e.710
to /Users/bondsr/Documents/Work/GitHub_repos/biopython/Scripts/Restriction/emboss_e.710
copying ftp://ftp.neb.com/pub/rebase/emboss_s.710
to /Users/bondsr/Documents/Work/GitHub_repos/biopython/Scripts/Restriction/emboss_s.710
Traceback (most recent call last):
  File "/Users/bondsr/anaconda/lib/python3.6/urllib/request.py", line 2056, in open_ftp
    (fp, retrlen) = self.ftpcache[key].retrfile(file, type)
  File "/Users/bondsr/anaconda/lib/python3.6/urllib/request.py", line 2406, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/Users/bondsr/anaconda/lib/python3.6/ftplib.py", line 359, in ntransfercmd
    host, port = self.makepasv()
  File "/Users/bondsr/anaconda/lib/python3.6/ftplib.py", line 337, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/Users/bondsr/anaconda/lib/python3.6/ftplib.py", line 845, in parse227
    raise error_reply(resp)
ftplib.error_reply: 200 Switching to Binary mode.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rebase_update.py", line 127, in <module>
    Getfiles.getfiles()
  File "rebase_update.py", line 67, in getfiles
    self.retrieve(file, filename)
  File "/Users/bondsr/anaconda/lib/python3.6/urllib/request.py", line 1791, in retrieve
    fp = self.open(url, data)
  File "/Users/bondsr/anaconda/lib/python3.6/urllib/request.py", line 1757, in open
    return getattr(self, name)(url)
  File "/Users/bondsr/anaconda/lib/python3.6/urllib/request.py", line 2066, in open_ftp
    raise URLError('ftp error %r' % exp).with_traceback(sys.exc_info()[2])
  File "/Users/bondsr/anaconda/lib/python3.6/urllib/request.py", line 2056, in open_ftp
    (fp, retrlen) = self.ftpcache[key].retrfile(file, type)
  File "/Users/bondsr/anaconda/lib/python3.6/urllib/request.py", line 2406, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/Users/bondsr/anaconda/lib/python3.6/ftplib.py", line 359, in ntransfercmd
    host, port = self.makepasv()
  File "/Users/bondsr/anaconda/lib/python3.6/ftplib.py", line 337, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/Users/bondsr/anaconda/lib/python3.6/ftplib.py", line 845, in parse227
    raise error_reply(resp)
urllib.error.URLError: <urlopen error ftp error error_reply('200 Switching to Binary mode.',)>
```

**Comment by peterjc** [comment]
I wonder why all the ``freq`` entries have changed from floating point numbers to integers in this update? Did you run the compiler on Python 2 or 3 (in case that explains it), or might it be traced to the raw data files (since you'd updated them locally)?

**Comment by biologyguy** [comment]
Shoot, ya. I was still in a py2 env when I managed to get the rebase script to work. Not paying attention, sorry.
Travis seems to be timing out on the Python 2.7 tests now, though. I'm not sure what I could have done to cause this. The tests are passing on my local machine :(

**Comment by peterjc** [comment]
I've asked TravisCI to re-run the Python 2.7 test just in case.

I guess I could try the update here with the latest REBASE files, perhaps that is where the ``.0`` vanished?

**Comment by biologyguy** [comment]
I've amended the commit, so the .0 is back in.

**Comment by biologyguy** [comment]
Huzzah! Travis was just being crotchety :D

**Comment by peterjc** [comment]
I think that's all I've got for review - over to @MarkusPiotrowski as *de facto* module owner for the functional changes.

**Comment by biologyguy** [comment]
As always, thanks for all your help Peter.

**Comment by MarkusPiotrowski** [comment]
Hi Steve @biologyguy 

I first had a look at the ```rebase_update.py``` problem.  It looks that this is a known Python bug introduced recently and which is still open (https://bugs.python.org/issue27973). Possibly I put a ```print``` statement into ```rebase_update.py```, explaining the situation and suggesting a manual download of the emboss files.

Regarding your PR: At first glance, it looks fine. I'm not a ```re``` expert, so please let me do some tests. I wonder if the lookahead is also the solution to another problem with combined searches that I tried to solve by doing two different searches (see https://github.com/biopython/biopython/commit/1f66b2f43a81f48c8af72bf03c33c20aada3ca86#diff-5cf2f301686a13ba5b681e16361c7fd2 , line 932)

**Comment by biologyguy** [comment]
Hi Markus @MarkusPiotrowski,
Thanks for having a look.
Regarding your thoughts on the NonPalindromic class, I think you are correct. The following _seems_ to work once the lookahead is included. I haven't tested it thoroughly though.

```python
    @classmethod
    def _search(cls):
        """Return a list of cutting sites of the enzyme in the sequence (PRIVATE).

        For internal use only.

        Implement the search method for non palindromic enzymes.
        """
        iterator = cls.dna.finditer(cls.compsite.pattern, cls.size)
        cls.results = []
        modif = cls._modify
        revmodif = cls._rev_modify
        s = str(cls)
        cls.on_minus = []

        for start, group in iterator:
            if group(s):
                cls.results += [r for r in modif(start)]
        s += '_as'
        for start, group in iterator:
            if group(s):
                cls.results += [r for r in revmodif(start)]

        if cls.results:
            cls.results.sort()
            cls._drop()
        return cls.results
```

**Comment by MarkusPiotrowski** [comment]
@peterjc 
Looks fine to me. I cherry-picked the commits and made some additional small changes. It's here: https://github.com/MarkusPiotrowski/biopython/tree/Restriction. Do I have commit rights?

**Comment by peterjc** [comment]
Closed in favour of #1439, thank you both for working on this 👍

**Pull request closed without merging**
