### PR TITLE
Ability to specify codon table for dn_ds matrix calculation.

### PR DESCRIPTION
**Pull request by alexjironkin**
Currently only default_codon_table can be used with get_dn_ds_matrix. Extended to expose this option to the end user.

### CODE REVIEW

**Comment by peterjc** [comment]
Does this look sensible @zruan ?

Could you add a test for the new method @alexjironkin ? See file ``Tests/test_codonalign.py``

**Comment by alexjironkin** [comment]
It's not a new method, I just exposed ```codon_table``` to be passed to ```get_dn_ds_matrix``` method that already existed.

**Comment by peterjc** [comment]
Sorry, typo: I meant the new argument (and associated new functionality).

**Comment by alexjironkin** [comment]
Ah no problem ... Although looking at the test code, there is no test for ```get_dn_ds_matrix``` at all.

**Comment by zruan** [comment]
Thank you @alexjironkin. Yes, I think the changes make sense. One more thing I noticed is that we also need to pass the `codon_table` option to the `get_dn_ds_tree` method, as it directly calls `get_dn_ds_matrix`. As to the test code, it's better to do it in `TestCodonAlignment` class.

**Comment by alexjironkin** [comment]
I've already added the ```codon_table``` option to the ```get_dn_ds_tree``` in the same commit.

**Comment by zruan** [comment]
Sorry, my bad. You do edit the `get_dn_ds_tree` as well.

**Comment by peterjc** [comment]
Can one of you write a test for ``get_dn_ds_matrix``?

**Comment by peterjc** [comment]
I didn't chase this and its waited nearly a year. I'd really prefer this have a test before merging it...

Alex, are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by peterjc** [comment]
Closed via #1178 - including Alex's work.

@alexjironkin Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by peterjc** [comment]
@alexjironkin Are you happy to dual licence your contributions under both the Biopython License Agreement AND the BSD 3-Clause License? See #898.

Also, are you happy to be thanked by name in the NEWS.rst and CONTRIB.rst files?

**Pull request closed without merging**
