### PR TITLE
Comply with flake8-comprehensions upgrade

### PR DESCRIPTION
**Pull request by chris-rands**
The upgrade of flake8-comprehensions (in particular see the changes for version 3.1.0) includes some new checks:
https://github.com/adamchainz/flake8-comprehensions/blob/master/HISTORY.rst

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Hmm,

```
$ flake8
./Bio/Restriction/Restriction.py:1550:45: E231 missing whitespace after ':'
./Bio/Restriction/Restriction.py:1551:45: E231 missing whitespace after ':'
./Scripts/Restriction/ranacompiler.py:892:49: E231 missing whitespace after ':'
```

All three are in ``lambda`` expressions - not sure why they were not being reported before, but worth fixing now.

**Comment by chris-rands** [comment]
Thanks Peter, i fixed those failures, I am confused about this one though, looking at the code, might be a false positive?

```
./Tests/test_GraphicsChromosome.py:312:29: C416 Unnecessary list comprehension - rewrite using list().
```

I also meant to say, this is the cause of the Travis failure in #2341

**Comment by peterjc** [comment]
It looks legitimate to me, the tuple is expanded with an additional entry:

```python
                features = [(start, end, strand, label, color)
                            for (start, end, strand, label) in features]
```

https://github.com/biopython/biopython/blob/biopython-175/Tests/test_GraphicsChromosome.py#L312

I don't see any ``flake8`` complaint about this line via TravisCI though...

**Comment by chris-rands** [comment]
The build no longer fails with Travis because i added `# noqa: C416` too the end of this line [here](https://github.com/biopython/biopython/pull/2342/commits/5129c1f4159f45ccf8c9458b72dbd74d14963208)

I'm now convinced this is an issue with the flake8-comprhensions plugin, I can reproduce this like:

```
$ cat tmp.py 
a = 0
x = [(1, 2, 3)]
x = [(b, c, d, a) for b, c, d in [(1, 2, 3)]]
$ flake8 --isolated --select C4 tmp.py 
tmp.py:3:6: C416 Unnecessary list comprehension - rewrite using list().
```

I can raise an issue on their github repo but for this

**Comment by peterjc** [comment]
Good work.

**Pull request merged**
