### PR TITLE
Update paml run docstrings

### PR DESCRIPTION
**Pull request by RonaCostello**
This pull request addresses issue #1708

Hey, this is my first contribution to BioPython (and my first open source contribution ever!!), thanks for labelling this as a good first issue. I've updated and added various paml docstrings.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@brandoninvergo does this look good to you too?

AppVeyor seems to have got stuck uploading the coverage, but after running the tests. I'll re-run that now...

**Comment by brandoninvergo** [comment]
Generally looks good, and thanks to @RonaCostello for taking on the task!

A couple of minor comments:

* For `baseml.run`, there is a typo: "Checks tree attribute is specified..." should be "Checks that the tree attribute is specified..."

* There is a mix of tenses: there are some cases of present declarative ("Checks that the tree attribute") and some imperative ("If parse is True then read and return the result.").  I think it should be one or the other and I think the usual recommendation for docstrings of functions is the imperative.  So, "Check that the tree attribute is specified and exists, and then run baseml.", etc. This affects `_paml.run` and `baseml.run`. @peterjc, do you agree?

**Comment by RonaCostello** [comment]
I have corrected the spelling mistake and updated the docstrings to imperative tense. I can push them if that is what is wanted 👍

**Comment by peterjc** [comment]
Yes, try to use imperative tense - especially for the one line summary. We try to enforce this via the flake8 pydocstyle plugin check ``D401: First line should be imperative`` but its heuristics do not catch everything.

**Comment by peterjc** [comment]
AppVeyor got stuck in the 4th build target, but it looks unrelated - so merging anyway.

Thank you Rona 👍

**Pull request merged**
