### PR TITLE
Rate limit calls to NCBIWWW.qblast function

### PR DESCRIPTION
**Pull request by Amrithasuresh**
This pull request addresses issue #1715

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

*Edit - I removed the spaces to make the checkboxes pretty /Peter*

### CODE REVIEW

**Comment by peterjc** [comment]
This looks good, although since ``qblast`` is a public function (unlike ``_open`` in TogoWS and Entrez), perhaps we should make the attribute name ``._private`` here to indicate it is not part of the intended public API? Does that make sense?

**Comment by Amrithasuresh** [comment]
@peterjc Thank you for the help. If called outside the module it should not be accessible. Does that mean like below.

```
    while True:
        current = time.time()
        wait = qblast._previous + delay - current
        if wait > 0:
            time.sleep(wait)
            qblast._previous = current + wait
        else:
            qblast._previous = current

qblast._previous = 0
```

**Comment by peterjc** [comment]
That looks right, replacing all ``qblast.previous`` with ``qblast._previous``

**Comment by Amrithasuresh** [comment]
@peterjc If this is issue is right and fixed. Please suggest me issues I can work on.

**Comment by peterjc** [comment]
Merged, thank you.

**Pull request merged**
