### PR TITLE
Fix some typos in the Entrez docs

### PR DESCRIPTION
**Pull request by ExplodingCabbage**
This pull request addresses issue #...

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ ] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

*Nope, haven't linted locally, but these are purely spelling error fixes in comments.*

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Changes look good (the automated tests should catch things like invalid reStructuredText or other style issues with doctests).

I take it you don't want to be acknowledged by name for this contribution (but hopefully you will make others in the future)?

**Comment by ExplodingCabbage** [comment]
Indeed, @peterjc. I'd feel silly adding myself to the contributors list for this. :)

**Comment by peterjc** [comment]
(AppVeyor is currently broken, see #2157)

**Comment by peterjc** [comment]
Applied, thank you!

**Pull request merged**
