### PR TITLE
adding docstring to __init__ functions

### PR DESCRIPTION
**Pull request by azneto**
Adding the docstring 'Initialize the class.' to every def __init__ lacking docstring

This pull request addresses issue #1203

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ AND the _BSD 3-Clause License_.

I am not happy to be thanked by name in the ``NEWS.rst`` and
``CONTRIB.rst`` files.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

### CODE REVIEW

**Comment by peterjc** [comment]
I do hope you automated that because otherwise it was a lot of manual effort. But this is good, it should mean we can remove one of the flake8 ignore settings, *D107 Missing docstring in ``__init__``*, which is nice.

Please try updating ``Bio/.flake8`` to remove D107 from the ignore list (and TravisCI should then retest with the now stricter settings).

**Comment by azneto** [comment]
Yes, I wrote a shell script to do it. Let's try the integration after removing D107 from the ignore list.

**Comment by peterjc** [comment]
The automated testing passed with the new stricter flake8 settings - good job, merged, thank you.

**Comment by azneto** [comment]
👍

**Pull request merged**
