### PR TITLE
Coerce atom serial number to an integer for PDBIO

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
This pull request addresses issue #2913.

I added a check to PDBIO to fail if it cannot convert the serial number to a number. Also changed the mmCIF parser to read the serial number from the files and add it to the Atom object as they build the structure. This should make `preserve_atom_numbering` work for mmCIF files as well, and prevent ambiguous errors when trying to write PDB files with non-numerical serials.

A few things need to be done still. I'm a bit tied up this week but will finish this as soon as possible. If anyone else wants to take a stab at the following issues, go ahead!

- [x] Merge latest changes from master
- [x] Style checking
- [x] Write unit tests

---

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ ] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
A couple of hiccups, but this PR should improve test coverage for PDBIO and add the tests to check for the fix for #2913

**Comment by JoaoRodrigues** [comment]
Not sure why it tagged so many people.. and shows so many files changed... let me check that, don't worry about this for now.

**Comment by JoaoRodrigues** [comment]
Some of the internal coordinates tests are failing because of a change to a test file. I missed that when I grepped the tests for that file. Will fix it later..

**Comment by JoaoRodrigues** [comment]
Instead of changing the IC code at several spots, I added a try/except block in the mmCIF parser to try and coerce the serial number to integer. If it fails, the parser still returns a structure but it issues a few warnings that hopefully will be clear if other errors happen downstream with other packages.

**Comment by peterjc** [comment]
Looks good to me - do you want another structural person to look at it, or just go ahead and rebase-and-merge?

**Comment by JoaoRodrigues** [comment]
I think it's OK to go on and merge. It's a fairly simple change and it should not change any behavior in existing code.

**Comment by peterjc** [comment]
Thank you

**Pull request merged**
