### PR TITLE
Fix long-standing issues with copying/operating on DisorderedAtoms.

### LINKED ISSUE #455: PDB Entity.copy() mangles disordered atoms.
Disordered atoms dont inherit `disordered_get_list()` when a parent entity is copied. Eg:

```
>>> pdbl = Bio.PDB.PDBList(server='http://www.rcsb.org/pdb/files')
>>> pdbParser = Bio.PDB.PDBParser()
>>> struct_4LGR = pdbParser.get_structure('4LGR', pdbl.retrieve_pdb_file('4LGR'))
Downloading PDB structure '4LGR'...
>>> Bio.PDB.PPBuilder().build_peptides(struct_4LGR)
[<Polypeptide start=5 end=33>, <Polypeptide start=36 end=259>, <Polypeptide start=2 end=123>]
>>> Bio.PDB.PPBuilder().build_peptides(struct_4LGR.copy())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Polypeptide.py", line 357, in build_peptides
    and is_connected(prev_res, next_res):
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Polypeptide.py", line 417, in _is_connected
    nlist=n.disordered_get_list()
AttributeError: 'Atom' object has no attribute 'disordered_get_list'
```

### LINKED ISSUE #3213: Atom object has no attribute atom.disordered_get_list when saving PDB file
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
3.8.5 (default, Aug  5 2020, 08:36:46) 
[GCC 7.3.0]
CPython
Linux-5.4.0-42-generic-x86_64-with-glibc2.10
1.77

### Expected behaviour

`PDBIO.save()` function should save a `Chain` object normally.

### Actual behaviour
The function failed on calling `atom.disordered_get_list()` on some proteins. For example, `pdb/ah/pdb1ah7.ent.gz`, which was directly downloaded from RCSB PDB. 

```bash
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    io.save('test.pdb')
  File "/home/minys/.conda/envs/bio/lib/python3.8/site-packages/Bio/PDB/PDBIO.py", line 339, in save
    for atom in residue.get_unpacked_list():
  File "/home/minys/.conda/envs/bio/lib/python3.8/site-packages/Bio/PDB/Residue.py", line 88, in get_unpacked_list
    undisordered_atom_list += atom.disordered_get_list()
AttributeError: 'Atom' object has no attribute 'disordered_get_list'
```

### Steps to reproduce
To run this piece of code, please download `pdb1ah7.ent.gz` in advance, for simplicity, here PDBList is not used. The task is to save a protein chain into an individual file.

This issue may be related to #455 , which seems not fixed yet.

```python
from Bio.PDB import PDBIO, PDBParser
import gzip

pdb_file = '/data/pdb/ah/pdb1ah7.ent.gz'
pdbparser = PDBParser()
target = pdbparser.get_structure('id', gzip.open(pdb_file, 'rt'))[0]['A']
io = PDBIO()
io.set_structure(target)
io.save('test.pdb')
```

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #455, closes #2134, and closes #3213. See discussions in those issues for details. In a nutshell, there were several issues with propagating methods (e.g. transform) from Entity-level to all children in a DisorderedAtom. Likewise, there were several issues with copying DisorderedAtoms and keeping all children. The two issues were linked, thus the single PR which:
- Adds a transform method to DisorderedAtom to propagate the call to all children.
- Adds a copy method to DisorderedEntityWrapper to properly copy all children.
- Changes assignment/generation of full_id on Atoms when copying detached parents (single chains).
- Adds a new test file based on each of those issues. The tests all fail (for different reasons) in the current master but pass with this PR.

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
PS. Sorry to tag you on so many issues in the last few days @peterjc - I missed the hackathon earlier this month.... :)

**Comment by jgreener64** [comment]
I am not entirely familiar with the code relating to disordered entities, but from what I see this looks good.

**Comment by JoaoRodrigues** [comment]
Thanks!

**Comment by iriziotis** [comment]
Hi @JoaoRodrigues. It seems that I still stumble upon a problem when trying to transform copies of disordered atoms. They just stay intact unfortunately. It seems that changing `child.copy()` to `copy(child)` in `Entity.copy` fixes the thing, but I'm not sure whether this could cause other problems. Have you tested this case?
Thank you!!

**Comment by JoaoRodrigues** [comment]
Hi @iriziotis, argh! Can you give us a small self-contained example to debug?

**Comment by iriziotis** [comment]
Hi again @JoaoRodrigues! My case is bizarre by principle, but here it is (script and example structure attached): This happens when I build a new SMCRA structure and insert copies of residues from another structure. After transformation, If I go and call `.get_list()` on all residues of the new structure, the disordered atoms are not copies, but plain references to the original structure. However, `.get_unpacked_list()` shows copies of all atoms. If instead I insert references to the new structure rather than copies, then everything is fine. PDBIO will not catch this bug as it uses the `.get_unpacked_list()` method. Check my attached script and example structure. Apologies for the confusing description. 
[biopython_disorder_bug.zip](https://github.com/biopython/biopython/files/6162955/biopython_disorder_bug.zip)

**Comment by JoaoRodrigues** [comment]
No apologies necessary. Thank you for the description and for the code and the sample files. I'll have a look this weeknd when I have the chance!

**Comment by iriziotis** [comment]
Hello @JoaoRodrigues, do we have any news on that? I still cannot figure out what is happening. Currently I just override the bug with something like this:
`                   
                    res_copy = res.copy()
                    res_copy.child_list = []
                    res_copy.child_dict = {}
                    for atom in res.get_unpacked_list():
                        if atom.get_altloc() in (' ', 'A'):
                            res_copy.add(atom.copy())
`

**Comment by JoaoRodrigues** [comment]
Sorry, haven't had the time to look into it ... would you mind sticking with the workaround a little longer?

**Comment by iriziotis** [comment]
Hello @JoaoRodrigues, do we have any news on this? I could not figure out a solution so I currently override it with something like this:
```                   
res_copy = res.copy()
res_copy.child_list = []
res_copy.child_dict = {}
       for atom in res.get_unpacked_list():
             if atom.get_altloc() in (' ', 'A'):
                    res_copy.add(atom.copy())
```

**Comment by iriziotis** [comment]
Hi @JoaoRodrigues. I just realised that this bug also seems to convert DisorderedAtom objects into Atom objects, leading to various errors, e.g. when trying to calculate a center of mass (it tries to call `disordered_get_list()` in an Atom object which should be a DisorderedAtom instead. It seems that the problem lies somewhere deep in the `copy()` methods, but I haven't found the culprit yet.

**Comment by iriziotis** [comment]
@JoaoRodrigues managed to fix it at last. Implemented an explicit `copy()` method in `DisorderedAtom` that seems to tackle away all the problems. Will make a pull request and you may test it afterwards.

**Pull request merged**
