### PR TITLE
 Improved parsing of GN in the SwissProt parser, take 2

### PR DESCRIPTION
**Pull request by mdehoon**
Small change to parsing of GN in the SwissProt parser.
Now creates a dictionary for the gene name tokens.

Based on PR  #234

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
Old SwissProt test files were replaced by their current version as follows:
```
sp001 -> Q13454.txt
sp002 -> P60904.txt
sp003 -> P62258.txt
sp005 -> P68308.txt
sp006 -> P39896.txt
sp007 -> O95832.txt
sp008 -> P04439.txt
sp009 -> O23729.txt
sp010 -> Q13639.txt
sp011 -> P16235.txt
```

**Comment by peterjc** [comment]
I had generally thought it wise to keep old format test cases present (in part to ensure our parsers can cope with both old and new variants of a format), but over time older versions become less and less relevant. That will depend on the format of course, and how many third-party implementations there were.

Can the updated "swiss" parser still can read the old files?

**Comment by mdehoon** [comment]
> Can the updated "swiss" parser still can read the old files?

It cannot. The old files are ancient. Some of the old test files are from the previous century. SwissProt changed to the current format some time during the first Bush administration.

**Comment by peterjc** [comment]
That's justifiable, but ought to be flagged in the NEWS file. Otherwise looks good.

**Review by peterjc — APPROVED** [review]
Does Josha's original patch merit being named as a contributor (if they so desire)?

**Pull request merged**
