### PR TITLE
Molar extinction coefficient

### PR DESCRIPTION
**Pull request by pyahmed**
Would be nice to have calculation of the molar extinction coefficient. Changes are trivial :-)

Returns two values:
- assuming Cys-residues are reduced (no contribution to molar extinction coefficient)
- assuming Cys-Cys-bonds/pairs (Cystine), this obviously requires even number of residues

### CODE REVIEW

**Comment by pyahmed** [comment]
Added test to test_Protparam.py

**Comment by peterjc** [comment]
@sbassi Could you look this over please?

**Comment by pyahmed** [comment]
Small error with sequences that had 0 cysteines, is fixed now.

**Comment by pyahmed** [comment]
Removed print-statement - now it should be good :-)

**Comment by peterjc** [comment]
Unfortunately this comment https://github.com/biopython/biopython/commit/314bf7d2dc7fad538f32e94d41a3ee896b243494#commitcomment-11327805 isn't showing up on this pull request, but the same code is here too.

@Eddie1802 is worried about the ``if num_aa['C']%2 != 0:`` if-else-block and suggests an alternative ``mec_cystines = mec_reduced + (num_aa['C']//2)*125 `` which can be tested against the ExPASy protparam tool (http://web.expasy.org/protparam/)

**Comment by pyahmed** [comment]
Was indeed wrong - should be fixed and working for all cases now.

**Comment by pyahmed** [comment]
Anything else required to get this accepted? Let me know :-)

**Comment by peterjc** [comment]
Sorry, this looks good to go - but I'd lost track of the pull request. There will be some minor style changes to meet our now stricter PEP8 checks (adding some spaces around the operators), but I'm happy to tackle that.

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by pyahmed** [comment]
Yes I'm fine with dual license. If you could use Yasar L. Ahmed (real name) as contributor name in the two files, that would be awesome. 

Thanks!

**Comment by peterjc** [comment]
Great - rebased and applied to master, see commit leading up to https://github.com/peterjc/biopython/commit/c74e8056e172180c5a49b3afc36ea14e81592668 - thank you!

**Comment by peterjc** [comment]
@pyahmed Hello again Yasar. Are you happy to dual licence your contributions under both the Biopython License Agreement AND the BSD 3-Clause License? See #898. Thank you.

**Comment by pyahmed** [comment]
I'm fine with dual licensing under Biopython License Agreement AND the BSD 3-Clause License.

**Comment by peterjc** [comment]
Thank you!

**Pull request closed without merging**
