### PR TITLE
Fixed a table parsing bug.

### LINKED ISSUE #582: Genepop parsing error
Currently, when using the example stated in the [wiki](http://biopython.org/wiki/PopGen_Genepop) for controlling Genpop, at least one of the example fails:

`loci_map = ctrl.test_hw_pop(1, "excess")`

The error is the following:

``` python
Traceback (most recent call last):
  File "BioGenepop.py", line 50, in <module>
    get_exp_obs_het(filehandle, argv[2])
  File "BioGenepop.py", line 34, in get_exp_obs_het
    loci_map = filehandle.test_hw_pop(pop, "excess")
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/EasyController.py", line 45, in test_hw_pop
    return next(hw_res)
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/Controller.py", line 164, in __next__
    return self.func(self)
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/Controller.py", line 266, in hw_func
    return _hw_func(self.stream, False)
  File "/usr/lib/python3.4/site-packages/Bio/PopGen/GenePop/Controller.py", line 130, in _hw_func
    locus, p, se, fis_wc, fis_rh, steps = entry[:-1]
ValueError: need more than 2 values to unpack
```

This is due to a problem in the table parsing, which has a wrong value.
I have patched the issue and will submit a pull request shortly.

### PR DESCRIPTION
**Pull request by StuntsPT**
Fixes #582 .

### CODE REVIEW

**Comment by StuntsPT** [comment]
@peterjc @tiagoantao 
So... It's been a while. Ping, just in case it was forgotten. =-)

**Comment by peterjc** [comment]
@tiagoantao can you look at this small pull request? Even if you only have time to review it, I can do the merge.

**Comment by peterjc** [comment]
@tiagoantao does this little change make sense? Are you happy for it to be accepted as is, or does it need a test?

**Comment by peterjc** [comment]
Sorry to nag @tiagoantao, but is it OK to merge this small PR?

And if so, @StuntsPT:

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

And are you happy to be thanked by name in the ``NEWS`` and ``CONTRIB`` files?

**Comment by StuntsPT** [comment]
@peterjc 
Yes, I am OK with dual licensing. Should I also comment on #898 ?
And yes, I'm also happy to have my name on `NEWS` and `CONTRIB` files. But are you sure such a small patch warrants this?

**Comment by peterjc** [comment]
That's great - I'll update #898 when we merge this.

Regarding acknowledgement, this is a small but real change - but if you prefer we can leave your name off until one day you make a larger contribution. If you need a suggestion, how about adding that wiki example test case to the Biopython unit tests? ;)

**Comment by StuntsPT** [comment]
@peterjc Deal!
Also, NCBI should have a 'real' solution for #926 soon.
Adding those 2 contributions will make me feel worthy of being acknowledged.

**Comment by peterjc** [comment]
@tiagoantao If you don't object I propose to merge this before the next release.

@StuntsPT if you could add something to the unit tests to confirm this fix, that would be even better.

**Comment by StuntsPT** [comment]
@peterjc I'll be on that today, it was already too late yesterday to implement unit testing. =-)

**Comment by StuntsPT** [comment]
I seem to be having some problem, since all the PopGen tests are failing here... Is this expected?
Here is an example:

```python
python Tests/test_PopGen_GenePop.py

test_allele_genotype_frequencies (__main__.AppTest)
Test genepop execution on basic allele and genotype frequencies. ... ERROR
test_calc_diversities_fis_with_identity (__main__.AppTest)
Test calculations of diversities ... ... ERROR
test_estimate_nm (__main__.AppTest)
Test Nm estimation. ... ERROR
test_fst_all (__main__.AppTest)
Test genepop execution on all fst. ... ERROR
test_haploidy (__main__.AppTest)
Test haploidy. ... ERROR

======================================================================
ERROR: test_allele_genotype_frequencies (__main__.AppTest)
Test genepop execution on basic allele and genotype frequencies.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests/test_PopGen_GenePop.py", line 38, in test_allele_genotype_frequencies
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 553, in calc_allele_genotype_freqs
    self._run_genepop(["INF"], [5, 1], fname)
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 246, in _run_genepop
    self.controller()  # checks error level is zero
  File "/usr/lib/python3.6/site-packages/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 255 from 'Genepop MenuOptions=5.1 Mode=Batch InputFile=/home/francisco/Programming/github/biopython/PopGen/big.gen', message 'Unable to open file genepop.txt'

======================================================================
ERROR: test_calc_diversities_fis_with_identity (__main__.AppTest)
Test calculations of diversities ...
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests/test_PopGen_GenePop.py", line 56, in test_calc_diversities_fis_with_identity
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 703, in calc_diversities_fis_with_identity
    return self._calc_diversities_fis(fname, ".DIV")
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 669, in _calc_diversities_fis
    self._run_genepop([ext], [5, 2], fname)
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 246, in _run_genepop
    self.controller()  # checks error level is zero
  File "/usr/lib/python3.6/site-packages/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 255 from 'Genepop MenuOptions=5.2 Mode=Batch InputFile=/tmp/tmp1giye7ew/PopGen/big.gen', message 'Unable to open file genepop.txt'

======================================================================
ERROR: test_estimate_nm (__main__.AppTest)
Test Nm estimation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests/test_PopGen_GenePop.py", line 68, in test_estimate_nm
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 491, in estimate_nm
    self._run_genepop(["PRI"], [4], fname)
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 246, in _run_genepop
    self.controller()  # checks error level is zero
  File "/usr/lib/python3.6/site-packages/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 255 from 'Genepop MenuOptions=4 Mode=Batch InputFile=/tmp/tmpxbyrw49n/PopGen/big.gen', message 'Unable to open file genepop.txt'

======================================================================
ERROR: test_fst_all (__main__.AppTest)
Test genepop execution on all fst.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests/test_PopGen_GenePop.py", line 76, in test_fst_all
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 727, in calc_fst_all
    self._run_genepop([".FST"], [6, 1], fname)
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 246, in _run_genepop
    self.controller()  # checks error level is zero
  File "/usr/lib/python3.6/site-packages/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 255 from 'Genepop MenuOptions=6.1 Mode=Batch InputFile=/tmp/tmpb1ohvfhn/PopGen/c2line.gen', message 'Unable to open file genepop.txt'

======================================================================
ERROR: test_haploidy (__main__.AppTest)
Test haploidy.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests/test_PopGen_GenePop.py", line 86, in test_haploidy
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 727, in calc_fst_all
    self._run_genepop([".FST"], [6, 1], fname)
  File "/usr/lib/python3.6/site-packages/Bio/PopGen/GenePop/Controller.py", line 246, in _run_genepop
    self.controller()  # checks error level is zero
  File "/usr/lib/python3.6/site-packages/Bio/Application/__init__.py", line 516, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 255 from 'Genepop MenuOptions=6.1 Mode=Batch InputFile=/tmp/tmp6zrluam9/PopGen/haplo.gen', message 'Unable to open file genepop.txt'

----------------------------------------------------------------------
Ran 5 tests in 0.026s

FAILED (errors=5) 
```

**Comment by peterjc** [comment]
Could be you're not in the ``Tests/`` directory which is assumed/expected, and could break all the paths in the command line tests?

**Comment by StuntsPT** [comment]
Yup, that's it. I really have to read the docs on `unittest` again...

**Comment by peterjc** [comment]
In this case its a quirk of the Biopython test, which we've tried to document with a chapter in the Tutorial.

**Comment by StuntsPT** [comment]
Oh. In that case, that's where I'm headed. Thanks!

**Comment by StuntsPT** [comment]
Unit test implemented.
Works on both python3 (3.6 tested) and python2 (2.7 tested).

**Comment by peterjc** [comment]
Lovely. It won't trigger under TravisCI as we don't have the command line tool dependencies installed there. Thank you 👍

**Comment by StuntsPT** [comment]
You''re welcome.
Really glad I could help this project! And also thank you for all the guidance.

**Pull request merged**
