### PR TITLE
Dual license more of Bio.PDB

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses in part issue #898, continuing work on #2212 

See also #2240 (``MMCIFParser.py``) and #2241 (``Entity.py``), and also waiting to hear from @kokonech for the remaining files under ``Bio/PDB/``.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@JoaoRodrigues would you be able to review this?

**Comment by peterjc** [comment]
@jgreener64 do you fancy reviewing this dual-licensing PR, looking at the past PDB contributors?

**Comment by jgreener64** [comment]
Sure, it looks good to me.

**Comment by peterjc** [comment]
Thanks Joe.

**Pull request merged**
