### PR TITLE
Standardizing on import numpy as np

### LINKED ISSUE #4238: Standardize on import numpy as np
I think we should follow the numpy documentation and avoid the plain ``import numpy`` form in favour of ``import numpy as np``.

With the current code base:

```
$ cat *.py */*.py */*/*.py | grep "import numpy" | sort | uniq -c
   1         >>> import numpy
   9     import numpy
   3     import numpy as np
   1     import numpy as np  # type: ignore
  17 import numpy
   1 import numpy  # type: ignore
   8 import numpy as np
   1 import numpy as np  # type: ignore
   1 import numpy.linalg
```

This is a fairly simple change with search-and-replace (e.g. using ``sed`` at the command line), suitable for a first-time contributor so marking as such.

### PR DESCRIPTION
**Pull request by john-science**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #4238

This is a small change, where I converted every `import numpy` statement to `import numpy as np`.

This is, as the ticket suggest, just meant to help the repository converge on a standard. Assuming this change was made correctly, and there were not typos, such a change would be extremely safe and could not affect unit tests or runtime code.

### CODE REVIEW

**Comment by john-science** [comment]
I see the linting failed.  Sorry, I didn't know you guys used `ruff`.  I will fix it.

**Review by mdehoon — APPROVED** [review]

**Review by peterjc — APPROVED** [review]
This looks great, happy to see this merged once the tests have finished.

**Comment by peterjc** [comment]
That's weird - spelling errors from files you edited, fixed in 7ba26eb1a3ee83be125806ffd846272deca49869 but I would have expected those to have been flagged already based on how most pre-commit hooks behave.

Well, the AppVeyor and CircleCI tests passed so I _think_ we're good to merge anyway.

**Comment by peterjc** [comment]
I understand the GitHub actions failure, which is due to recently added misspellings in the codespell tool.

When the pre-commit hooks are run on the pre-commit.ci service, this checks *all* the files. However, due to strict time limits we have to skip the slower hooks, including codespell. That means this didn't flag the two "misspellings" when the spell checker was updated.

On the other hand, we do run all the pre-commit hooks on GitHub Actions, but only on changed files. So again, this didn't flag the two "misspellings" immediately.

This was the first pull request to edit a file containing those words, and thus the first time we saw the failure.

**Pull request merged**
