### PR TITLE
Several PEP8 and PEP257 issues in folder Scripts

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
This pull request is related to issue #2014.
It removes several code-style violations according to PEP-8 and PEP-257 in folder `Scripts`, so that no extra `per-file-ignores` are neccesary for this folder.
I put a whole-file `noqa: flake8` on `nextorf.py` in `xbbtools` for now. It does not seem to be used in `xbbtools` (and is causing numerous style-issues...)

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by MarkusPiotrowski** [comment]
@peterjc Travis-CI stopped with a failed download. Can you restart the tests?

**Comment by peterjc** [comment]
Looks like the PhyML server was having trouble, causing TravisCI failures.

**Comment by peterjc** [comment]
I recall ``nextorf.py`` being a pain style wise. This seems pragmatic.

There are a few edits where you've line wrapped - probably unneeded (and will be reverted if we adopt black and its 88 limit). But harmless enough.

**Comment by MarkusPiotrowski** [comment]
So can I merge this?

**Comment by peterjc** [comment]
Sorry, yes, go ahead.

**Pull request merged**
