### PR TITLE
Fix _assign_element to deal with 4 characters atom with last number.

### LINKED ISSUE #4644: Incorrect element assignment for 4-character atom names.
### Setup

I am reporting a problem with Biopython 1.83, Python 3.11.7, and Linux-6.1.64-09049-g010fe86d9eae-x86_64-with-glibc2.36 as follows:

When running `_assign_element`, elements are not correctly assigned for atoms with 4 characters long names such as HNZ1 and HNE2 in the lysine residue. 

I fixed the code and want to propose it as a PR.

### Expected behaviour

"H" is assigned for atoms with 4 characters long names such as HNZ1 and HNE2.

### Actual behaviour

"X" is assigned for atoms with 4 characters long names such as HNZ1 and HNE2.

### Steps to reproduce

To reproduce, construct `Atom` instance without designating elements for atoms.
(`_assign_element` is automatically run.)

### PR DESCRIPTION
**Pull request by eunos-1128**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #4644

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
Thanks for catching, reporting, and providing a fix for the issue - home run!

Could I trouble you to add a unit test that covers this type of case so that we can track it in the future and prevent regressions? You can modify one of the existing PDB files in the test suite for that, no need to add a new one (or just make a synthetic example).

**Comment by eunos-1128** [comment]
Of course, I'll add a unit test.

**Comment by JoaoRodrigues** [comment]
Hi @eunos-1128, any chance you can add that test? Thanks!

**Comment by eunos-1128** [comment]
Sorry for the delay in responding.

I am busy with another project right now, so I will send out another PR when it is ready.

Until then, this issue is temporarily closed.

**Pull request closed without merging**
