### PR TITLE
Switch to non-UTF8 locale (the ASCII only C locale) inside test

### PR DESCRIPTION
**Pull request by BioGeek**
This pull request addresses issue #1402 and is a continuation of pull request #1429 

It adds switching to a non-UTF8 locale (the ASCII only C locale) inside `test_efetch_gds_utf8()`

The code was inspired by [`test_locale()` ](https://github.com/python/cpython/blob/7e2a54cdd977078b40b82182e46b201f8163f659/Lib/test/test_format.py#L420) in the Python standard library.

----

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ AND the _BSD 3-Clause License_.

I *am* happy to be thanked by name in the ``NEWS.rst`` and
``CONTRIB.rst`` files.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

### CODE REVIEW

**Comment by peterjc** [comment]
The changes look good, but the git commit history is confused - and GitHub says there are merge conflicts which prevents a simple merge via the web interface.

Are you happy to rebase this to our master branch yourself, or should I deal with merging this fix at the command line?

**Comment by BioGeek** [comment]
I'm still getting up to speed with `git` and  I've had a hard time just to get this pushed (see [my StackOverflow question](https://stackoverflow.com/questions/47017608/you-are-not-currently-on-a-branch-error-when-trying-to-sync-fork-with-upstream) for details), so if you could merge this fix that would be great.

In the mean time I'll read up on how to do a proper rebase. Thanks!

**Comment by peterjc** [comment]
OK, what I did locally, first get my local master branch up to date with the official one,

```
git fetch origin
git checkout master
git merge --ff-only origin/master
```

Download your patch from github as a single commit:

```
curl -O https://github.com/biopython/biopython/commit/eed2f74972277dff67d3add59e00342f12097dcc.patch
```

Make a new branch and apply the patch,

```
git checkout -b encoding_test
git am eed2f74972277dff67d3add59e00342f12097dcc.patch 
git push peterjc encoding_test
```

(This is similar to how Linus and the Linux team deal with patches without using GitHub, the ``git am`` command is normally used with patches shared by email.)

Now I made a new pull request on GitHub using this commit (which is still under your authorship), see #1436.

Note that until recently I could have just applied your patch directly to the master branch, and since I have commit rights, pushed that to the official Biopython master branch. However, recently we changed to require all changes are made via pull requests which ensures they are fully tested.

**Comment by BioGeek** [comment]
Thanks for the detailed step-by-step on how you solved the merge, very educational!

**Comment by peterjc** [comment]
I hoped it would be interesting, although of course not directly relevant to your ``git rebase`` issue.

Someone else made the same point on your StackOverflow question, but ideally treat the ``master`` branch as read-only, and for any new pull request start by updating your local copy of the ``master`` branch and then make a new branch for the pull request.

**Pull request closed without merging**
