### PR TITLE
Don't raise StopIteration from generators; return does this explicitl…

### LINKED ISSUE #967: Update use of StopIteration for PEP479
I'm using `biopython v1.68` in `anaconda 3.5.1` and am using a structure to read through a fastq file like so:

```
handle = gzip.open(path, "rt")
for record in SeqIO.parse(handle, "fastq"):
    do_stuff()
handle.close()
```

I keep getting this error and can't find anything about it in the source. Does anyone know what is going on here? Thanks!

> /Bio/SeqIO/QualityIO.py:1031: PendingDeprecationWarning: generator 'FastqGeneralIterator' raised StopIteration
> for title_line, seq_string, quality_string in FastqGeneralIterator(handle):

### PR DESCRIPTION
**Pull request by cbrueffer**
…y; fixes #967

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good - just waiting for AppVeyor to finish, just in case...

**Comment by peterjc** [comment]
Note there are still lots more cases to review

**Comment by bow** [comment]
@cbrueffer indeed this looks ok ~ I do also still notice that we still use the `raise` from other places (e.g. in `Bio/AlignIO/MauveIO.py` and `Bio/AlignIO/PhylipIO.py`).

**Comment by cbrueffer** [comment]
I've had a look at all "raise StopIteration" cases in the codebase; I think the remaining one are needed (I could be missing something).

**Comment by peterjc** [comment]
Thank you

**Comment by cbrueffer** [comment]
Expanding on this, the cases @bow mentioned don't use yield, so I'm not sure whether this change applies there?

**Comment by peterjc** [comment]
Good point. Best run with the ``PendingDeprecationWarning`` visible to find out for sure if Python thinks they need fixing...

**Pull request merged**
