### PR TITLE
Pdbio set structure

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
This pull request addresses issue #2995 and supersedes #3003 

PDBIO should not assume, on set_structure, that if passed a residue that the residue is orphan or that the parent chain id is 'A'.

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
Have to update the `test_PDB.py` file to take into account changes made by #2924

**Comment by JoaoRodrigues** [comment]
@peterjc , if there are no issues on your end, I can go ahead and merge this.

**Comment by peterjc** [comment]
It needs some conflicts resolved, but I have no objection.

**Comment by JoaoRodrigues** [comment]
I'll handle those now and merge then, thanks!

**Comment by JoaoRodrigues** [comment]
No conflicts left it seems - tests passing as well. Merging!

**Pull request merged**
