### PR TITLE
flake8: Enforce E731 (no lambda expressions) on Tests/

### PR DESCRIPTION
**Pull request by peterjc**
Like #2016 and #2017, this pull request is somewhat related to issue #883 / #2014 and the goal of having universal flake8 settings for the entire project.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@MarkusPiotrowski assuming we go ahead with per-folder level settings in a top level ``.flake8`` file as discussed on #2014, do you think this PR is needed?

My opinion was most of the lambda use here was reasonable, my question could be rephrased as: Do we want to strongly discourage using lambdas in future tests?

**Comment by MarkusPiotrowski** [comment]
Actually, I also use lambdas in ```test_pairwise2```. I think tests are somewhat special, where lambdas are useful to quickly setup some conditions that we want to test. So I think it would be OK to ignore E731 for the ```Tests``` folder.

**Comment by peterjc** [comment]
OK, assuming we can ignore F731 with a top level ``.flake8``, I'm happy to close this pull request.

**Comment by peterjc** [comment]
@MarkusPiotrowski given there seems to be a bug with the flake8 per-file-ignores (see #2014 discussion), shall we go ahead and merge this?

I'll just rebase it now to deal with the merge conflict...

**Comment by MarkusPiotrowski** [comment]
OK! Then we need to look at the 28 occurrences of E731 in `Bio`.

**Pull request merged**
