### PR TITLE
moving UndoHandle, second attempt

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request moves UndoHandle from Bio.File to Bio.SearchIO._legacy.ParserSupport.
This is a replacement for #2424 .

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@bow Are you still OK with this? This is the same PR as #2424 latest version.

**Comment by peterjc** [comment]
Hi @bow - this is still with an explicit error, rather than a deprecation warning and old scripts otherwise working as is - but what do you think?

**Comment by mdehoon** [comment]
Can we assume tacit approval from @bow  ? There is still lots of old python2 stuff in Bio.File that needs to be taken out.

**Comment by peterjc** [comment]
I suppose so. If he does disagree, we can always revert or tweak the code - we're not about to do a release just yet after all.

**Pull request merged**
