### PR TITLE
Improve test coverage Tests/test_PopGen_GenePop_nodend.py

### PR DESCRIPTION
**Pull request by Gasta88**
This pull request addresses issue #1288 

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

### CODE REVIEW

**Comment by peterjc** [comment]
Hmm, a Windows problem:

```
======================================================================
ERROR: test_remove_features (test_PopGen_GenePop_nodepend.FileParserTest)
Testing the ability to remove population/loci via class methods.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_PopGen_GenePop_nodepend.py", line 136, in test_remove_features
    rec.remove_loci_by_position([0], ftemp.name)
  File "C:\projects\biopython\Bio\PopGen\GenePop\FileParser.py", line 278, in remove_loci_by_position
    with open(fname, "w") as f:
IOError: [Errno 13] Permission denied: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmpwmljdc'
----------------------------------------------------------------------
Ran 275 tests in 676.172 seconds
```

I may be mis-reading the code but are you keeping the file handle open in the test code, while ``remove_loci_by_position`` attempts to open the same filename for writing? I would expect that to fail on Windows even if it works on Linux/macOS.

**Comment by Gasta88** [comment]
The `NamedTemporaryFile` is created and opened at the same time. 
Windows throws an error when the same file is accessed again from the `FileParser` module. 
If I close it before calling `remove_loci_by_position`, the file gets deleted and the filename captured before will point to nothing.
I need to test this through on my Windows environment.

**Comment by peterjc** [comment]
If you have access to a Windows machine, that would be easiest. Windows imposes different restrictions on simultaneous access to the same filename.

**Comment by peterjc** [comment]
Good news, AppVeyor failed but it looks unrelated:

```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_Tutorial.py", line 256, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 1 Tutorial doctests failed: test_chapter_motifs_line_00028
----------------------------------------------------------------------
```

**Comment by Gasta88** [comment]
Should I push another commit to check again?

**Comment by peterjc** [comment]
Yes, if you are familiar with ``git rebase`` that'd be ideal, otherwise any tiny commit should trigger a fresh test of testing.

**Comment by Gasta88** [comment]
Travis is throwing an error when running `test_KDTree.py`, but on my local branch it compiles OK.

Is this likely to be a mess that I've made with `git rebase`?

**Comment by peterjc** [comment]
The fact that everything passed on TravisCI except Python 2.7 is curious, especially when Python 2.7 passed on AppVeyor.

```
======================================================================
FAIL: test_search (test_KDTree.KDTreeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_KDTree.py", line 206, in test_search
    self.assertTrue(test_search(nr_points, dim, bucket_size, radius))
AssertionError: False is not true
----------------------------------------------------------------------
```

I wonder if this is a random test result that sometimes fails? Can you try Python 2.7 on Linux yourself?

**Comment by Gasta88** [comment]
I tried yesterday and I had no errors, but I realized I've made a mess with `git rebase`.

I'll spend some time to fix it and hopefully refresh this PR.

**Comment by peterjc** [comment]
Thanks.

**Pull request merged**
