### PR TITLE
Removal of PopGen deprecated libraries

### PR DESCRIPTION
**Pull request by tiagoantao**
This removes Async, Simcoal and Fdist. #1139

### CODE REVIEW

**Comment by peterjc** [comment]
Can you update the ``DEPRECATED`` file too please?

I'm glad to see the TravisCI build checks did their job - I've been caught out by removing code and not updating ``setup.py`` in the past, only discovered when trying to prepare a release.

**Comment by peterjc** [comment]
Looks good - just needs an update to say removed in Biopython 1.70 in ``DEPRECATED.rst``, and to add your name to ``NEWS.rst`` for Biopython 1.70.

I'm happy to do those minor things myself and merge this tomorrow, but if you have time tonight that's great too - in which case please go ahead and merge this yourself. Thanks.

**Comment by peterjc** [comment]
Thank you 👍

**Comment by tiagoantao** [comment]
Sorry, just saw this now. Great that you did DEPRECATED.rst and NEWS.rst. Thanks!

**Pull request merged**
