### PR TITLE
SeqIO: support for datetime objects, check for valid dates

### PR DESCRIPTION
**Pull request by Ashafix**
This pull request addresses two TODO lines in InsdcIO.py.
* TODO - allow a Python date object	
* TODO - Check is a valid date (e.g. not 31 Feb)	
---
* The datetime object is just formatted and converted to upper case to match the Genbank format.
* The check is performed by trying to pass the `date` string into `datetime()` and check for `ValueError`.
* Unit tests for all previous cases and the newly added functionality were added.

Should an error be thrown if an invalid date or date format is encountered?
It might be confusing to the user if an ill-formed date is silently converted to another date.

---
I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by Ashafix** [comment]
@peterjc The tests were split into smaller functions and using StringIO instead of tempfile.

Not sure if I understand the codecov report correctly since I think I covered all possible branches in the `_get_date` function.

**Comment by Ashafix** [comment]
Is there anything else I need to do to continue with the pull request?

**Comment by peterjc** [comment]
I was hoping to catch up issue triage at the GCCBOSC CollaborationFest (hackathon) last week, but ran out of time.

This looks good. Do you want to be in the ``NEWS.rst`` file for the next release?

Can you suggest how to clarify the pull request template to encourage people to add themselves?
https://github.com/biopython/biopython/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Ashafix** [comment]
@peterjc Thanks but no need, I'm already in the contributors list.

**Comment by peterjc** [comment]
Merged, thank you.

You are in the ``CONTRIB.rst``, but not (yet) in the latest release listing for ``NEWS.rst``. Let me know if you want to be included there too.

**Pull request merged**
