### PR TITLE
change features packet encoding

### PR DESCRIPTION
**Pull request by chenzhiw**
change encoding ASCII to UTF-8

### CODE REVIEW

**Comment by peterjc** [comment]
Why? Do you have a failing use case which might make a good test case?

**Comment by chenzhiw** [comment]
@peterjc Yeah, test this one [pcDNA3.1(+)](https://www.snapgene.com/local/fetch.php?set=basic_cloning_vectors&plasmid=pcDNA3.1(+)). The product of feature AmpR is β-lactamase. It has a Latin alphabet.

**Comment by mdehoon** [comment]
Perhaps it's better than to change ASCII to UTF-8 everywhere in this module?

**Comment by peterjc** [comment]
It depends on the file format ultimately - but some fields like the sequence really ought to be ASCII.

@gouttegd as the SnapGene parser author would you like to comment?

**Comment by gouttegd** [comment]
The documentation that I have for the SnapGene file format does not _explicitly_ says that XML chunks are encoded in UTF-8. However, it is very clear from the XML spec that, in the absence of a `encoding` attribute in the XML declaration, an UTF-8 encoding must be assumed, and this probably holds true for XML chunks embedded in another file as is the case in SnapGene files.

So I agree that all the `decode("ASCII")` calls that deal with the XML chunks should be changed to `decode("UTF-8")`. That’s three of them, in the `_parse_notes_packet`, `_parse_features_packet`, and `_parse_primers_packet` functions. I can submit a patch for that, unless @chenzhiw want to amend his pull request to change all three calls.

However there’s no need to change the calls that deal with the sequence packet and the cookie packet, since those packets should always contain only ASCII bytes (it would do no harm to decode them as UTF-8 since ASCII is basically a subset of UTF-8, but it’s not necessary).

**Comment by peterjc** [comment]
We now have a donated test case on #3180 from @nicolazilio 

It looks like @chenzhiw didn't reply to the suggestions (GitHub notification emails can easily be overlooked), so could you go ahead with your proposal please @gouttegd ?

**Comment by gouttegd** [comment]
@peterjc Sure, I’ll submit the pull request shortly.

**Comment by peterjc** [comment]
Superseded by #3180, but thank you.

**Pull request closed without merging**
