### PR TITLE
alignment getitem for list

### LINKED ISSUE #4186: pairwise2 deprecation: how to align lists of sequences with the new PairwiseAligner?
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
CPython
macOS-12.6.1-x86_64-i386-64bit
1.80

### Expected behaviour

As the new PairwiseAligner is supposed to cover the functionality of pairwise2, I would expect that it can also align lists of sequences. It would also be nice to customize the gap character like in pairwise2.

### Actual behaviour

When passing two lists to the PairwiseAligner, I get

```python
ValueError: alphabet is None; cannot interpret sequence
```

### Steps to reproduce

```python
from Bio import Align
list1 = ['i', 'love', 'bananas', 'and', 'cheese']
list2 = ['bandanas', 'blind', 'bees']
aligner = Align.PairwiseAligner()
alignments = aligner.align(list1, list2)
```

Would appreciate any direction on this matter. Thanks a lot :)

### PR DESCRIPTION
**Pull request by mdehoon**
Fix `Alignment.__getitem__` for sequences that are lists of objects.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #4186.

### CODE REVIEW

**Comment by trenslow** [comment]
Hi @mdehoon, thanks so much for implementing this feature. I was wondering if you have an ETA on when it might make it into a release? No rush from my side, just for planning purposes :)

**Comment by peterjc** [comment]
We used to aim for every 3 months, the gap between Biopython 1.79 and Biopython 1.80 was hopefully an anomaly. If it hasn't happened by Feb 2023, do feel free to remind us/me ;)

https://mailman.open-bio.org/pipermail/biopython/2022-November/016953.html

**Comment by trenslow** [comment]
Awesome, thanks @peterjc :)

**Comment by trenslow** [comment]
hi @peterjc just checking in to see the status of releasing this change. as far as i can tell from the release notes, it didn't make it into v1.81. just trying to plan my upcoming work :)

**Comment by peterjc** [comment]
This was merged on 5 December 2022 https://github.com/biopython/biopython/commit/81e7659c2228ad6961563af44bef58b8734a3a8e so was part of Biopython 1.81 released in Feb 2023.

I guess Michiel didn't think the change significant enough to mention explicitly in the release notes (``NEWS.rst`` file), but we could add something retrospectively if you like?

**Comment by trenslow** [comment]
ah my apologies, i didn't dig deeper into the commits that went into the 1.81 release. i would say don't worry about the release notes unless someone else starts asking about the specific functionality worked on here :)

**Comment by peterjc** [comment]
Great, thanks.

**Pull request merged**
