### PR TITLE
Add a writer to Bio.Blast

### PR DESCRIPTION
**Pull request by mdehoon**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Which version of BLAST XML are you imitating?

**Comment by mdehoon** [comment]
> Which version of BLAST XML are you imitating?

There is only one version, as specified by the DTD.

**Comment by peterjc** [comment]
There are currently two major versions of NCBI BLAST XML, the original and "version two" from  2015.

Looking at this PR it mentions http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd (version one) rather than e.g. http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput2.dtd (version two).

Our parser in ``Bio.blast`` was updated to handle either (#1839), although the issue to update SearchIO is still open #2031

**Comment by mdehoon** [comment]
Right .. this is the original version.
It looks like there are two "version two" versions: The DTD-based one (http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput2.dtd) and the Schema-based one (https://www.ncbi.nlm.nih.gov/data_specs/schema_alt/NCBI_BlastOutput2.xsd), which is not quite the same.

**Comment by peterjc** [comment]
I would guess the XSD and DTD ought to agree - but anyway, we should clarify this output v1 BLAST XML.

**Pull request merged**
