### PR TITLE
SeqIO bug parsing RepeatMasker embl format library

### PR DESCRIPTION
**Pull request by xzhuo**
Hi there,

I am working with RepeatMasker library in embl format. Some records look like this:

<pre>
ID   TIR43YW1_CE     repeatmasker; DNA;  ???;  1740 BP.
CC   TIR43YW1_CE DNA
XX
DE   RepbaseID: TIR43YW1_CE
XX
KW   DNA/.
XX
CC   consensus - See RepBase for additional annotations.
XX
CC   RepeatMasker Annotations:
CC        Type: DNA
CC        SubType: 
CC        Species: Caenorhabditis_elegans
CC        SearchStages: 
CC        BufferStages:
XX
SQ   Sequence 1740 BP; 595 A; 300 C; 260 G; 585 T; 0 other;
     ctcagacaaa cgcttagtag cttaattaga tttcaaccat attaaacgag atttcaacca   60
     tatttgttta gaaaatccat attggattat atttgctcca tattttatta gaaatccatg   120
     ttagattaga tttcctccat atttcattag aaaacaaatc aaatccaata tggcacgatc   180
     tcatccatat tggattagat ttgtccatgt tagattagat ttgttccgta ttggattaga   240
     aatccatgtt ggattagatt tcctccatat ttcattaaaa aacaaatcta atccaatatg   300
     gtcgaaatct aatccaatat ggcacgctct cagccatatt tgattagatt tcgcccatgt   360
     tagattagaa atctcacgag aaatgggcgt attaaaataa ataaataaat aagaagaaaa   420
     cggaaagtgc aaacgcgtag ggcttaaaat tttttaaatt aaaattgaag acctttaaaa   480
     agttttaaaa taaaattatg atttgaaaat aagaattatc tcctgcaaat aataatctaa   540
     agatgatgtc cgctgactga ctttgacgaa tctccgaaaa gtctccaact ggtaatgttt   600
     ttttcagaaa cacttttttt ttcaaaatcc ggcaagaaat ttcacggcta caactgtgac   660
     aacttcgatg gttacaaaca acgaaataac atattctatt aatttaaatt aactcctaca   720
     aaccattact tttttcggta taattcgtgg aaaaattata tcatttcaca caaatgatac   780
     tagagctctt gctgcgaaaa gcggaaacag tcaataccgt acttttaaag ttttcatgaa   840
     ttttgtattt tacgtctgtt ttgtgccaac ccgcagacca tagttaaata aaattacttt   900
     tcctagcatt tacattttga tacaaaatac tttaattcac acttccagca accaaaaagt   960
     atgatttaac gatttttttt tagaaaaaac tcttttccaa attttctgag actaaaaaaa   1020
     tctttgttct cttctattgg ttagtacgat tggaggctaa gattaacgaa agcggttaac   1080
     aaactttttc aaatgaaaaa ccttgatatc aagccgttca agacttcaaa atacattccc   1140
     tctactcagt tcatctaatt ttccttaact tatcgaagaa acaacgcgcg ccaccaccac   1200
     cagctattta accgaacagt tcatcgaaag ttcatgtgtg cagattggcc gagtcggtaa   1260
     gaacacagtc tttagaatat aacatcctgg atcgattccc cacagtggca actccagaga   1320
     agcgcagtag gggagtttat agagcggcta cagttatcag gcgagacagc cagtgtgtag   1380
     tgtaagatat atgcgagaca tgagatgttt tctcattttc tttatttttt ccacattatt   1440
     ttcgggtaaa acattcttcg aaaaaaaatt attcagaaaa tccgagccaa atttgattag   1500
     attttgtcca tatttgatta gatttgttcc atattggatt agatttcaac catattggat   1560
     tagaattgtt ccatatttga ttagatttgt tccatattgg attagatttc aaccatattt   1620
     gattagaaaa tccatattgg attagaatag gaagcctatt aattatgtcc ccattatatt   1680
     tgctcagttt ctaatcaaat atggttgaaa tctaattaag ctactaagcg tttgtctgag   1740
                                                                         1740
//
</pre>

Note the last sequence line. It causes problem when I parse it using SeqIO: in this case, "1740" would be inserted at the end of the sequence string. 

You can say it is not a bug since the file is "wrong", but we can take care of it fairly easy in Bio.Genebank.Scanner.

### CODE REVIEW

**Comment by peterjc** [comment]
That file does look odd, but you're right, it would be nice if Biopython could cope with it.

Can you add a unit test for this? e.g. add your example file under ``Tests/EMBL/`` and add it to ``Tests/test_EMBL_unittest.py`` making sure the sequence is correct?

Are you happy to be named in the ``NEWS`` and ``CONTRIB`` files?

Also, as per #898 do you agree to licence your contribution under both the "Biopython License Agreement" and the "BSD 3-Clause License"?

**Comment by xzhuo** [comment]
Hi @peterjc ,

Just added a unit test for it. I am new to python and have never written a test before, so please correct me if I get it wrong. 

> Are you happy to be named in the NEWS and CONTRIB files?

> Also, as per #898 do you agree to licence your contribution under both the "Biopython License Agreement" and the "BSD 3-Clause License"?

Yes and yes.

**Comment by peterjc** [comment]
There is a typo in the message (``"Importing embl format error: sequence line with no seuqence but coordinate"``, second use of sequence), but I would suggest something a little different here:

```
    def test_embl_0_line(self):
        """Test SQ line with 0 length sequence"""
        # Biopython 1.67 and older would parse this file with a warning:                                                                                                                     
        # 'Expected sequence length 1740, found 1744 (TIR43YW1_CE).' and                                                                                                                     
        # the coordinates 1740 added to the sequence as four extra letters.                                                                                                                  
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")
            rec = SeqIO.read(path.join('EMBL', 'embl_with_0_line.embl'), 'embl')
            self.assertEqual(len(w), 0,
                             "Unexpected parser warnings: " +
                             "\n".join(str(warn.message) for warn in w))
            self.assertEqual(len(rec), 1740)
```

Note I deliberately check the record length - currently Biopython wrongly gives length 1744 because the four characters ``1740`` are added to the sequence.

Can we thank you as Xiaoyu Zhuo in the ``NEWS`` and ``CONTRIB`` file?

**Comment by xzhuo** [comment]
Thanks Peter! I changed the test based on your suggestion. 

> Can we thank you as Xiaoyu Zhuo in the NEWS and CONTRIB file?

Sure. I appreciate that.

**Comment by peterjc** [comment]
Rebased with trailing white space removed, see 81a2cee65da4198af3021df1d4ef1160e3812dfc 2518ec1ddeec590cc92c54a4bb760c3fe7c0493a a6733d5827d7596e7662f3b4c99750716917b16f and acknowledgement in 881faf7f2e896f9421a92f8dbe1fdcaa501e0093 - thank you!

**Pull request closed without merging**
