### PR TITLE
Standardize class init docstrings

### PR DESCRIPTION
**Pull request by amorehead**
- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #...

### CODE REVIEW

**Comment by peterjc** [comment]
The only commit so far is a minor docstring change, is there more coming? e.g. forgot to do a git push?

**Comment by amorehead** [comment]
Peter,

Nope. That is the only change for now. Thank you for asking!

**Comment by peterjc** [comment]
I'm inclined to reject this as is, or suggest a change to match our typical change:

```
$ cat Bio/*.py Bio/*/*.py Bio/*/*/*.py | grep -c '"""Initialize the class."""'
259
$ cat Bio/*.py Bio/*/*.py Bio/*/*/*.py | grep -c '"""Initialize class."""'
1
$ cat Bio/*.py Bio/*/*.py Bio/*/*/*.py | grep -c '"""Initialize."""'
23
```

i.e. Use "Initialize the class." instead?

**Comment by amorehead** [comment]
@peterjc,

That is a great point. I did not check for other files that were still using other comments for class initialization. I have just pushed a change to my patch-2 branch that includes changing the class initialization comment to """Initialize the class.""" across the entire project.

cat Bio/*.py Bio/*/*.py Bio/*/*/*.py | grep -c '"""Initialize the class."""'
283
cat Bio/*.py Bio/*/*.py Bio/*/*/*.py | grep -c '"""Initialize class."""'                                                                                          
0
cat Bio/*.py Bio/*/*.py Bio/*/*/*.py | grep -c '"""Initialize."""'                                                                                             [1]
0

**Review by mdehoon — APPROVED** [review]

**Review by JoaoRodrigues — APPROVED** [review]

**Comment by peterjc** [comment]
CircleCI seems stuck again, merging anyway as TravisCI passed - thank you!

**Pull request merged**
