### PR TITLE
3934 REBASE uids for Bio.Restriction

### PR DESCRIPTION
**Pull request by jakebeal**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes https://github.com/biopython/biopython/issues/3934 by incorporating database IDs and URIs for Bio.Restriction enzyme listings.

### CODE REVIEW

**Comment by jakebeal** [comment]
Bumping for attention from maintainers - this is still waiting for you to approve a workflow to run.

**Comment by jakebeal** [comment]
So far as I can tell, the failure that is showing up here doesn't have anything to do with the code that I am contributing and is identical to the one currently on the `master` branch: https://github.com/biopython/biopython/actions/runs/2394197316

@peterjc @MarkusPiotrowski : what is your preferred way to proceed in a situation like this?

**Comment by jakebeal** [comment]
Thank you, that's good to know. If somebody is setting up the skip-hack suggested in #3944, then I will wait and incorporate their patch in here. If not, please let me know and I can do a skip-hack myself (I'd prefer not to create a conflict).

**Comment by MarkusPiotrowski** [comment]
@jakebeal Indeed #3944 prevented me from merging this PR last week.

**Pull request merged**
