### PR TITLE
use simple form for chi-square distribution

### PR DESCRIPTION
**Pull request by mdehoon**
In `Bio.codonalign`, we only need the chi-square cumulative distribution for 1 degree of freedom.
In that case, the cumulative distribution reduces to a simple formula.
We don't need the numerical calculation from scipy then.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by mdehoon** [comment]
@zruan Any objections?

**Comment by zruan** [comment]
The numeric value of the new function doesn't seem to match with the old implementation. Do you know why this is the case?

```
>>> from math import sqrt, erfc
>>> from Bio.codonalign import chisq
>>> chisq.chisqprob(2, 1)
0.15729923058256473
>>> erfc(sqrt(2))
0.045500263896358396
```

**Comment by mdehoon** [comment]
> The numeric value of the new function doesn't seem to match with the old implementation. Do you know why this is the case?

Note that I removed the multiplication by 2 in the code. If you put this multiplication back in, the values match:
```python
>>> G = 1
>>> chisq.chisqprob(2*G, 1)
0.15729923058256473
>>> erfc(sqrt(G))
0.15729920705028516
>>> G = 2
>>> chisq.chisqprob(2*G, 1)
0.0455002668537458
>>> erfc(sqrt(G))
0.045500263896358396
>>> G = 3
>>> chisq.chisqprob(2*G, 1)
0.014305879045398128
>>> erfc(sqrt(G))
0.014305878435429643
>>> G = 10
>>> chisq.chisqprob(2*G, 1)
7.744216447794454e-06
>>> erfc(sqrt(G))
7.744216431044074e-06
```

**Comment by zruan** [comment]
I see. Then this looks good to me.

**Comment by mdehoon** [comment]
Thanks!

**Pull request merged**
