### PR TITLE
set molecule type where needed

### PR DESCRIPTION
**Pull request by mdehoon**
This pull request sets the molecule type in `test_SeqIO.py` where needed to let the tests run.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
I think we need to be able to set the molecule type explicitly via the ``Bio.SeqIO`` (and ``Bio.AlignIO``) top level API, similar to how this let the alphabet be specified. This is also probably the easiest transition for people with use cases where they had to supply this extra information.

I'm hoping to play with this during the BCC2020 CoFest which started today.

**Comment by mdehoon** [comment]
@peterjc  I am not sure if it's a good idea. If at all you'd probably want to do it as part of `SeqIO.write`.

**Comment by peterjc** [comment]
I am leaning to still specifying it on input (i.e. in ``SeqIO.parse(...)``, ``SeqIO.read(...)``, and the indexing ones too), to match the historic alphabet arguments. That seems less change for end users?

Doing it on output would also be acceptable, i.e. in ``SeqIO.write(...)`` and ``SeqIO.convert(...)``

**Comment by mdehoon** [comment]
> I am leaning to still specifying it on input (i.e. in SeqIO.parse(...), SeqIO.read(...), and the indexing ones too), to match the historic alphabet arguments. That seems less change for end users?

"less change" is not better in this case. When it comes to alphabets, the more change the better.

The problem with specifying it on input is that it introduces `molecule_type` as a concept in Biopython. But just like alphabets (remember the BEP discussion?), within Biopython the molecule type is not defined. Depending on context it can mean different things. The molecule type is only defined in the input- and output files, where it has a specific meaning.

Ideally, we would draw a border between data files and Biopython, like this:
```
   input file      >       Biopython          >    output file
(alphabet defined) | (alphabet doesn't exist) | (alphabet defined)
```
(using the word "alphabet" here, as it's shorter and essentially the same thing as the molecule type)

But since we want to be able to read in a file and write it out without losing any information, we store the molecule type in the `SeqRecord`, so our situation is more like this:
```
   input file      >       Biopython       >    output file
(alphabet defined) | (alphabet exists but  | (alphabet defined)
                   |  its interpretation   |
                   |    is ambiguous)      |
```
Then, if a user needs to specify the molecule type, it should be done at the right boundary, where its interpretation will be defined. In contrast, if we specify the molecule type at the left boundary, we'd be introducing it just at the point where its interpretation becomes ambiguous.

**Comment by peterjc** [comment]
You make a good argument for adding a molecule type argument to the sequence output functions (rather than the sequence input functions).

**Pull request merged**
