### PR TITLE
Improvements to Entrez tests

### PR DESCRIPTION
**Pull request by jlumpe**
- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

* The tests in `test_Entrez::TestURLConstruction` use `_create_params()`, `_encode_options()`, and `_construct_cgi()`, which ignores any special processing done in the main request functions such as `efetch()`. It also seems somewhat fragile. Changed this to patch `urllib.request.urlopen()` to a mocked version, call the public request function itself, then get the URL (and POST data, if any) from the arguments `urlopen()` is called with.
* URL construction tests also only test the URL using naive string operations, and don't test the full set of query parameters. Changed all of them to parse the url and its query segment and check their full values.
* Removed similar asserts on request URL in `test_Entrez_online` which are redundant and also not within the scope/purpose of the test case.
* Altered the `test_efetch_ids` online test to check for the presence of the requested IDs in the response and not just the request URL.

### CODE REVIEW

**Review by mdehoon — APPROVED** [review]

**Comment by peterjc** [comment]
Addresses in part #2779, I think.

Many of the tests are failing on TravisCI (Linux), apparently Python version dependent? e.g.

```
======================================================================
FAIL: test_construct_cgi_ecitmatch (test_Entrez.TestURLConstruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 140, in test_construct_cgi_ecitmatch
    result_url = get_patched_get_url(patched, self)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 83, in get_patched_get_url
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
======================================================================
FAIL: test_construct_cgi_efetch (test_Entrez.TestURLConstruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 284, in test_construct_cgi_efetch
    result_url = get_patched_get_url(patched, self)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 83, in get_patched_get_url
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
======================================================================
FAIL: test_construct_cgi_einfo (test_Entrez.TestURLConstruction)
Test constructed url for request to Entrez.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 155, in test_construct_cgi_einfo
    result_url = get_patched_get_url(patched, self)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 83, in get_patched_get_url
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
======================================================================
FAIL: test_construct_cgi_elink1 (test_Entrez.TestURLConstruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 205, in test_construct_cgi_elink1
    result_url = get_patched_get_url(patched, self)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 83, in get_patched_get_url
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
======================================================================
FAIL: test_construct_cgi_elink2 (test_Entrez.TestURLConstruction)
Commas: Link from protein to gene.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 232, in test_construct_cgi_elink2
    result_url = get_patched_get_url(patched, self)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 83, in get_patched_get_url
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
======================================================================
FAIL: test_construct_cgi_elink3 (test_Entrez.TestURLConstruction)
Multiple ID entries: Find one-to-one links from protein to gene.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 258, in test_construct_cgi_elink3
    result_url = get_patched_get_url(patched, self)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 83, in get_patched_get_url
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
======================================================================
FAIL: test_construct_cgi_epost1 (test_Entrez.TestURLConstruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 168, in test_construct_cgi_epost1
    result_url, options = get_patched_post_args(patched, self, decode=True)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 105, in get_patched_post_args
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
======================================================================
FAIL: test_construct_cgi_epost2 (test_Entrez.TestURLConstruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 182, in test_construct_cgi_epost2
    result_url, options = get_patched_post_args(patched, self, decode=True)
  File "/home/travis/build/biopython/biopython/Tests/test_Entrez.py", line 105, in get_patched_post_args
    testcase.assertEqual(len(call.args), 1)
AssertionError: 3 != 1
----------------------------------------------------------------------
```

**Comment by jlumpe** [comment]
Fixed the issue, but the "ppc64le" build is still failing for some reason that doesn't look related to any of my changed.

**Comment by peterjc** [comment]
Looks like a minor glitch with the BLAST+ dependency on the ppc64le platform, not relevant here.

**Comment by jlumpe** [comment]
Anything else that needs to be done before this gets merged?

**Comment by MarkusPiotrowski** [comment]
It would have been nice if you had included `mock` also for `test_Entrez_online` (I think this is was @peterjc had in mind when he mentioned this) so that the online test can also run offline if no internet is available (or when the tests are run in offline mode). 
I have done this for `test_NCBI_qblast` (#2779); if the tests are run online it will run online, otherwise it will run offline with a mocked version of `urlopen`, providing result files instead of internet responses. 

Oh, @mdehoon has already merged this. Maybe next time.

**Pull request merged**
