### PR TITLE
MatrixInfo.grant table update.  Fixes issue 308.

### PR DESCRIPTION
**Pull request by darcymason**
This pull request fixes issue #308.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the file ``CONTRIB.rst`` as part of this pull request

### CODE REVIEW

**Comment by peterjc** [comment]
I think this needs a ``NEWS.rst`` file entry as well, something like:

> The "grant" matrix in Bio.SubsMat.MatrixInfo has been replaced as our original values taken from Gerhard Vogt's old webpages at EMBL Heidelberg were discovered to be in error. The new values have been transformed following Vogt's approach, taking the global maximum 215 minus the similarity scores from the original paper Grantham (1974), to give a distance measure.

Does that match your understanding of the issue?

**Comment by darcymason** [comment]
Sounds good.  I'll add and update the PR later today.

**Comment by peterjc** [comment]
Do you want to be in the list of contributors to the release in NEWS.rst, or CONTRIB.rst file?

**Comment by darcymason** [comment]
I already added my name to CONTRIB.rst,  I'll add to NEWS.rst and update the PR.

**Comment by peterjc** [comment]
Merged, thank you very much for working on this!

**Pull request merged**
