### PR TITLE
Fix Bio.Nexus.cnexus import

### PR DESCRIPTION
**Pull request by speleo3**
Fix the `Bio.Nexus.cnexus` import and issue a `BiopythonWarning` if the import fails.

----

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
This seems sensible - although I would be curious what PyPy reports (ought to be in the CI logs), everywhere else I would expect the C code to be available.

**Comment by speleo3** [comment]
Works fine with PyPy.
```
$ pypy3
Python 3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jun 16 2023, 10:41:03)
[PyPy 7.3.12 with GCC 13.1.1 20230429] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import Bio.Nexus.cnexus
>>>> Bio.Nexus.cnexus.scanfile("[Hello World")
'['
```

**Comment by peterjc** [comment]
Great. PyPy has come a long way with C extension support - generally it just works now :)

**Review by peterjc — APPROVED** [review]
Looks good, just needs a trivial merge conflict resolved (possibly by us when merging)

**Pull request merged**
