### PR TITLE
Deploy API docs from Sphinx autodoc HTML using GitHub pages

### PR DESCRIPTION
**Pull request by peterjc**
This pull request addresses issue #906, replacing epydoc with Sphinx and autodoc.

Since #1803 we already build the API documentation with Sphinx and autodoc on TravisCI via the tox ``api`` target.

This adds automated deployment of the HTML output (via a bash script using a deployment key) to the new repository https://github.com/biopython/docs using github pages, to appear online under https://biopython.org/docs/dev/api/ etc (with ``.../dev/`` for the master branch development code, or a version like ``.../1.74/...`` instead for releases).

This URL patterns should leave open the possibility of hosting all the Tutorial here as well, probably easiest to do if if we convert that from LaTeX to RST and stay within Sphinx, see #907.

This requires an SSH deployment key. We add the public key to https://github.com/biopython/docs (multiple keys can be added, see below), and the private key is added to https://travis-ci.org/biopython/biopython/settings (suitably escaped).

The proposed setup uses the TravisCI ``deploy:`` stage https://docs.travis-ci.com/user/job-lifecycle/ (although ``after_success:`` works nicely too), currently restricted to the ``master`` branch only.

Testing on a fork is possible, for example from https://github.com/peterjc/biopython/ to https://github.com/biopython/docs as long as you have the private key (have permission to add a new key to the docs repository). Alternatively we could make it try to push to the owner's fork of the docs repository?

e.g. https://travis-ci.org/peterjc/biopython/jobs/557346277 didn't deploy as ``deploy`` was not the ``master`` branch (nor should the testing of this pull request trigger a deploy), while identical code in https://travis-ci.org/peterjc/biopython/jobs/557346457 on my fork's ``master`` branch did run the deploy script.

The implementation right now is in a bash script ``.github/deploy_docs.sh`` and tiny helper ``.github/ssh_via_deploy_key.sh`` but in principle this private key approach could be added to the tool ``doctr`` instead (see https://github.com/drdoctr/doctr/issues/348 and https://github.com/drdoctr/doctr/pull/349 where I am working on this).

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``flake8`` locally, and
understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
Note: Looking at the recent history on https://github.com/biopython/docs/commits/gh-pages from testing, even with no code changes there are documentation changes, apparently due to cases of objects as default arguments, e.g.

```
get_dn_ds_matrix(self, method='NG86', codon_table=<Bio.Data.CodonTable.NCBICodonTable object at 0x7fb0e534c0f0>)
```

This is from https://biopython.org/docs/dev/api/Bio.codonalign.codonalignment.html#Bio.codonalign.codonalignment.CodonAlignment.get_dn_ds_matrix

We can probably address this with an explicit ``__repr__`` on the underlying objects, but this could be a sign of some subtle bugs (instances of mutable objects as defaults), but are also a side effect of https://github.com/sphinx-doc/sphinx/issues/759

**Comment by peterjc** [comment]
The documentation changes on ``Bio.Restriction`` are more interesting - it looks like the class order is essentially random?

e.g. Search https://biopython.org/docs/dev/api/Bio.Restriction.Restriction.html for ``class Bio.Restriction.Restriction.``

**Comment by peterjc** [comment]
Updated to use the Read-The-Docs theme with our logo and the same dark grey side bar as on https://biopython.org - this to me looks pretty good now: https://biopython.org/docs/dev/api/

**Comment by peterjc** [comment]
Merging ready to try to do the Biopython 1.74 release later today.

**Comment by peterjc** [comment]
Thanks Markus,

As to links, I agree - for Biopython 1.74 we have both, linked to from the main documentation page although that could be prettier:

https://biopython.org/wiki/Documentation

The Biopython 1.74 tutorial ought to have included a link to the new documentation but I only remembered afterwards.

My hope is for Biopython 1.75 we can stop using epydoc, and just use Sphinx for the API docs.

Regarding the source code, I turned that off explicitly. Reason one, it will ballon the ``docs/`` repository if every time we commit a change to the main repository master branch, the dev documentation is updated with the pretty rendering of the source code. Reason two, I'd rather have it link directly to the GitHub page (which ought to be possible via templates).

Styling. There are a number of Sphinx themes, this is currently using the read-the-docs theme. That can be tweaked, or replaced. Also the docstring content itself can be polished (e.g. adopt numpydoc style).

Home link (top of side bar). That can probably be changed, although I am in two minds if it should go to the Sphinx documentation home (as now), or biopython.org - and we don't really need the little house icon and text, given the logo is shown below it with the same link.

Default arguments in signatures. There are some settings in Sphinx, but this has been a long standing issue for several projects. Typically they want something like ``out_function(x, y, colors=our_module.DEFAULT_COLOR_MAP)`` but Sphinx will replace the named constant with the actual value. Using mutable objects as default values is generally a bad idea anyway. Often using ``None`` is a good work around, see e.g. 1afe6a66eb0da5b33ce69b14f22551585495954a from this pull request.

Yes, ``Bio.Restriction.Restriction`` was explicitly disabled in 7c2389952911b0d1cec4f286d7a66f1c5894437a from this pull request - not sure about ``Bio.Restriction.Restriction_dictionary`` right away. If we can fix the stochastic class sort order, I'm open to restoring it - otherwise that balloons the ``docs/`` repository with noise.

**Comment by peterjc** [comment]
Fixed the redundancy of the home icon and text Biopython plus the logo in 958bb577b1f3ccce0e0dd3bf753e0d56ca22fb63

**Comment by peterjc** [comment]
Logged https://github.com/readthedocs/sphinx_rtd_theme/issues/777 for changing the Sphinx RTD theme's logo URL.

**Comment by fkgl** [comment]
Hi,
please, I'm using python 3.8 with Pycharm IDE 2020.1.1 , I'm trying to use snakes but I can't load plugins (snakes.plugins.load("gv", "snakes.nets", "nets")
from nets import *)
if I pass the mouse on the load the message (You need configured Python 2 SDK to render Epydoc docstrings) is displayed.
I don't know if that is the problem or there is another problem
I try to install epydoc but the problem is not resolved ; even I ave run the command pip install biopython -->successful but the problem is not resolved ;
please can someone help me?

**Comment by peterjc** [comment]
@fkgl I think you probable need to look at the snakes project documentation - nothing in your comment seems relevant to Biopython, sorry.

**Comment by fkgl** [comment]
@peterjc  Thank you.

**Pull request merged**
