### PR TITLE
A couple trivial fixes to make some PAML code more Pythonic

### PR DESCRIPTION
**Pull request by brandoninvergo**
This is a trivial pull request, just making a couple things more Pythonic in the PAML code, without any functional change.  Feel free to cherry-pick if you only want the `enumerate` fix.

I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

I have read the ``CONTRIBUTING.rst`` file and understand that AppVeyor and
TravisCI will be used to confirm the Biopython unit tests and ``flake8`` style
checks pass with these changes.

I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

### CODE REVIEW

**Comment by peterjc** [comment]
@brandoninvergo if you can deal with the merge conflict (ideally with a git rebase), I can merge this for you. Otherwise are you happy for one of the Biopython team to do it?

**Comment by brandoninvergo** [comment]
Sorry, somehow I never saw your original message about the merge conflict.  

Looks like I totally screwed this up.

**Comment by peterjc** [comment]
I'm not sure what happened there... but I can probably fix the branch and rescue the commit. Leave it with me (currently triaging emails, will hopefully get to it later during my holiday).

**Comment by peterjc** [comment]
What I did and would normally be fine:

```
git fetch origin
git fetch brandon
git checkout -t brandon/paml-pythonic-fix
git rebase origin/master
# Resolve the conflict:
emacs Bio/Phylo/PAML/yn00.py
git add Bio/Phylo/PAML/yn00.py
git rebase --continue
git log
```

That almost worked, maybe I didn't do the merge resolution perfectly, but gave an unwanted second commit. I fixed that and then:

```
git push brandon paml-pythonic-fix --force
```

GitHub lets me edit your branch because you ticked a permissions box as part of making this pull request (normally I would not be able to edit your repository without collaborator rights).

**Comment by peterjc** [comment]
The cleaned up rebased branch has the one expected commit, and assuming the automated tests pass this looks ready for merging now.

**Comment by peterjc** [comment]
The automated checks did pass, belatedly merging this now - thank you!

**Pull request merged**
