### PR TITLE
Solve Bio.PDB.Vector name shadowing

### PR DESCRIPTION
**Pull request by peterjc**
This solves a long standing point of confusion for users, and warning/error from documentation tools like epydoc and sphinx (cross reference #1388).

Requesting comments from @etal, @lennax & @JoaoRodrigues in particular.

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
👍 for me.

**Comment by peterjc** [comment]
It occurred to me last night that this GitHub search would reveal code this change would break - sadly over 300 hits using the ``"from Bio.PDB.Vector import ...`` pattern.

https://github.com/search?utf8=%E2%9C%93&q=%22from+Bio.PDB.Vector+import%22&type=Code

That includes 106 people importing the class with ``from Bio.PDB.Vector import Vector``

https://github.com/search?utf8=%E2%9C%93&q=%22from+Bio.PDB.Vector+import+Vector%22&type=Code

Conversely, only 18 hits for people importing the class with ``from Bio.PDB import Vector``

https://github.com/search?utf8=%E2%9C%93&q=%22from+Bio.PDB+import+Vector%22&type=Code

I think this rules out the one-hit approach to solving the name shadowing by renaming ``Bio/PDB/Vector.py`` to ``Bio/PDB/vectors.py``. Perhaps doing this but providing ``Bio/PDB/Vector.py`` as a deprecated alias is safer...

**Comment by peterjc** [comment]
@JoaoRodrigues what do you think of including ``Bio/PDB/Vector.py`` as a deprecated stub importing from ``Bio/PDB/vectors.py`` as in the second commit?

**Comment by JoaoRodrigues** [comment]
@peterjc Sounds like a good plan, it will raise a DeprecationWarning right?

**Comment by peterjc** [comment]
Yes, with this change explicit imports from the old ``Vector`` module give a deprecation warning, for example:

```
$ python3 -c "from Bio.PDB.Vector import calc_angle"
/Users/peterjc/lib/python3.4/site-packages/Bio/PDB/Vector.py:36: BiopythonDeprecationWarning: The module Bio.PDB.Vector has been deprecated in favor of new module Bio.PDB.vectors to solve a name collisions with the class Vector. For the class Vector, and vector functions like calc_angle, import from Bio.PDB instead.
  "import from Bio.PDB instead.", BiopythonDeprecationWarning)
```

It would be possible to import directly from the new ``vectors`` module, but only on a new version of Biopython:

```
$ python3 -c "from Bio.PDB.vectors import calc_angle"
```

Therefore in the deprecation warning, ``DEPRECATED.rst`` and docstring I am suggesting using the short form which will work on old and new Biopython:

```
$ python3 -c "from Bio.PDB import calc_angle"
```

**Comment by JoaoRodrigues** [comment]
Sounds good to me.

**Comment by peterjc** [comment]
Thanks @JoaoRodrigues.

Any concerns from @etal, @lennax, etc? Assuming not, I'll merge this next week.

**Comment by peterjc** [comment]
Thanks Lenna 👍

**Comment by peterjc** [comment]
(Rebased due to merge conflict, plus adding another tiny workaround for Sphinx complaining about ``Vector`` being ambiguous.)

**Comment by peterjc** [comment]
Rebasing again - the TravisCI test never ran last time.

**Pull request merged**
