### PR TITLE
test and fix for issue #633

### PR DESCRIPTION
**Pull request by vincentdavis**
test and fix for issue  "_unique_label() eval error" #633 as submitted by @biologyguy in issue comments

### CODE REVIEW

**Comment by peterjc** [comment]
We have an OK from @etal in the discussion on #633.

Also bonus points for getting rid of a use of ``eval(...)`` :+1:

If there was no particular reason for the try/except in the test, I/Eric can just remove it when doing the merge.

**Comment by vincentdavis** [comment]
The reason for the try/except in the test is that I was trying to catch and print the error. I am not sure the proper way to do this in a test. Is it necessary to catch errors with try/except in a test?
Let me know I can update also.

**Comment by biologyguy** [comment]
Hi Vincent,
The error should no longer occur, so like Peter said, there's no reason to try and catch it. That's what the test suite is there to do. If, however, you want to catch an expected exception in the future, you can use assertRaises() from unittest.
Thanks for picking up this issue, btw, the bug was causing me some headache :)
-Steve

**Comment by peterjc** [comment]
Squashed into commit https://github.com/biopython/biopython/commit/4a644df02bd4e4ec731d625b706f894040f60481 with minor cleanup (removed the try/except, removed unwanted file ``Tests/temp.del``, checked ``SeqIO.write(...)`` returned four).

Thank you Vincent.

**Pull request closed without merging**
